#pragma once
#ifndef SEAQT_QTCORE_GEN_QABSTRACTITEMMODEL_H
#define SEAQT_QTCORE_GEN_QABSTRACTITEMMODEL_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt/libseaqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemModel;
class QAbstractListModel;
class QAbstractTableModel;
class QChildEvent;
class QDataStream;
class QEvent;
class QMetaMethod;
class QMetaObject;
class QMimeData;
class QModelIndex;
class QObject;
class QPersistentModelIndex;
class QSize;
class QTimerEvent;
class QVariant;
#else
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractListModel QAbstractListModel;
typedef struct QAbstractTableModel QAbstractTableModel;
typedef struct QChildEvent QChildEvent;
typedef struct QDataStream QDataStream;
typedef struct QEvent QEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QModelIndex QModelIndex;
typedef struct QObject QObject;
typedef struct QPersistentModelIndex QPersistentModelIndex;
typedef struct QSize QSize;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
#endif

QModelIndex* QModelIndex_new();
QModelIndex* QModelIndex_new2(QModelIndex* param1);
int QModelIndex_row(const QModelIndex* self);
int QModelIndex_column(const QModelIndex* self);
uintptr_t QModelIndex_internalId(const QModelIndex* self);
void* QModelIndex_internalPointer(const QModelIndex* self);
QModelIndex* QModelIndex_parent(const QModelIndex* self);
QModelIndex* QModelIndex_sibling(const QModelIndex* self, int row, int column);
QModelIndex* QModelIndex_siblingAtColumn(const QModelIndex* self, int column);
QModelIndex* QModelIndex_siblingAtRow(const QModelIndex* self, int row);
QModelIndex* QModelIndex_child(const QModelIndex* self, int row, int column);
QVariant* QModelIndex_data(const QModelIndex* self);
int QModelIndex_flags(const QModelIndex* self);
QAbstractItemModel* QModelIndex_model(const QModelIndex* self);
bool QModelIndex_isValid(const QModelIndex* self);
bool QModelIndex_operatorEqual(const QModelIndex* self, QModelIndex* other);
bool QModelIndex_operatorNotEqual(const QModelIndex* self, QModelIndex* other);
bool QModelIndex_operatorLesser(const QModelIndex* self, QModelIndex* other);
QVariant* QModelIndex_data1(const QModelIndex* self, int role);
void QModelIndex_delete(QModelIndex* self);

QPersistentModelIndex* QPersistentModelIndex_new();
QPersistentModelIndex* QPersistentModelIndex_new2(QModelIndex* index);
QPersistentModelIndex* QPersistentModelIndex_new3(QPersistentModelIndex* other);
bool QPersistentModelIndex_operatorLesser(const QPersistentModelIndex* self, QPersistentModelIndex* other);
bool QPersistentModelIndex_operatorEqual(const QPersistentModelIndex* self, QPersistentModelIndex* other);
bool QPersistentModelIndex_operatorNotEqual(const QPersistentModelIndex* self, QPersistentModelIndex* other);
void QPersistentModelIndex_operatorAssign(QPersistentModelIndex* self, QPersistentModelIndex* other);
void QPersistentModelIndex_swap(QPersistentModelIndex* self, QPersistentModelIndex* other);
bool QPersistentModelIndex_operatorEqualWithOther(const QPersistentModelIndex* self, QModelIndex* other);
bool QPersistentModelIndex_operatorNotEqualWithOther(const QPersistentModelIndex* self, QModelIndex* other);
void QPersistentModelIndex_operatorAssignWithOther(QPersistentModelIndex* self, QModelIndex* other);
QModelIndex* QPersistentModelIndex_ToConstQModelIndexBitwiseAnd(const QPersistentModelIndex* self);
int QPersistentModelIndex_row(const QPersistentModelIndex* self);
int QPersistentModelIndex_column(const QPersistentModelIndex* self);
void* QPersistentModelIndex_internalPointer(const QPersistentModelIndex* self);
uintptr_t QPersistentModelIndex_internalId(const QPersistentModelIndex* self);
QModelIndex* QPersistentModelIndex_parent(const QPersistentModelIndex* self);
QModelIndex* QPersistentModelIndex_sibling(const QPersistentModelIndex* self, int row, int column);
QModelIndex* QPersistentModelIndex_child(const QPersistentModelIndex* self, int row, int column);
QVariant* QPersistentModelIndex_data(const QPersistentModelIndex* self);
int QPersistentModelIndex_flags(const QPersistentModelIndex* self);
QAbstractItemModel* QPersistentModelIndex_model(const QPersistentModelIndex* self);
bool QPersistentModelIndex_isValid(const QPersistentModelIndex* self);
QVariant* QPersistentModelIndex_data1(const QPersistentModelIndex* self, int role);
void QPersistentModelIndex_delete(QPersistentModelIndex* self);

struct QAbstractItemModel_VTable {
	void (*destructor)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self);
	QMetaObject* (*metaObject)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self);
	void* (*metacast)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, const char* param1);
	int (*metacall)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, int param1, int param2, void** param3);
	QModelIndex* (*index)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, int row, int column, QModelIndex* parent);
	QModelIndex* (*parent)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, QModelIndex* child);
	QModelIndex* (*sibling)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, int row, int column, QModelIndex* idx);
	int (*rowCount)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, QModelIndex* parent);
	int (*columnCount)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, QModelIndex* parent);
	bool (*hasChildren)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, QModelIndex* parent);
	QVariant* (*data)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, QModelIndex* index, int role);
	bool (*setData)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QModelIndex* index, QVariant* value, int role);
	QVariant* (*headerData)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, int section, int orientation, int role);
	bool (*setHeaderData)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, int section, int orientation, QVariant* value, int role);
	struct miqt_map /* of int to QVariant* */  (*itemData)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, QModelIndex* index);
	bool (*setItemData)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QModelIndex* index, struct miqt_map /* of int to QVariant* */  roles);
	struct miqt_array /* of struct miqt_string */  (*mimeTypes)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self);
	QMimeData* (*mimeData)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, struct miqt_array /* of QModelIndex* */  indexes);
	bool (*canDropMimeData)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
	bool (*dropMimeData)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
	int (*supportedDropActions)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self);
	int (*supportedDragActions)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self);
	bool (*insertRows)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, int row, int count, QModelIndex* parent);
	bool (*insertColumns)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, int column, int count, QModelIndex* parent);
	bool (*removeRows)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, int row, int count, QModelIndex* parent);
	bool (*removeColumns)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, int column, int count, QModelIndex* parent);
	bool (*moveRows)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QModelIndex* sourceParent, int sourceRow, int count, QModelIndex* destinationParent, int destinationChild);
	bool (*moveColumns)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QModelIndex* sourceParent, int sourceColumn, int count, QModelIndex* destinationParent, int destinationChild);
	void (*fetchMore)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QModelIndex* parent);
	bool (*canFetchMore)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, QModelIndex* parent);
	int (*flags)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, QModelIndex* index);
	void (*sort)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, int column, int order);
	QModelIndex* (*buddy)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, QModelIndex* index);
	struct miqt_array /* of QModelIndex* */  (*match)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, QModelIndex* start, int role, QVariant* value, int hits, int flags);
	QSize* (*span)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self, QModelIndex* index);
	struct miqt_map /* of int to struct miqt_string */  (*roleNames)(struct QAbstractItemModel_VTable* vtbl, const QAbstractItemModel* self);
	bool (*submit)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self);
	void (*revert)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self);
	bool (*event)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QEvent* event);
	bool (*eventFilter)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QObject* watched, QEvent* event);
	void (*timerEvent)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QTimerEvent* event);
	void (*childEvent)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QChildEvent* event);
	void (*customEvent)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QEvent* event);
	void (*connectNotify)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QAbstractItemModel_VTable* vtbl, QAbstractItemModel* self, QMetaMethod* signal);
};
QAbstractItemModel* QAbstractItemModel_new(struct QAbstractItemModel_VTable* vtbl);
QAbstractItemModel* QAbstractItemModel_new2(struct QAbstractItemModel_VTable* vtbl, QObject* parent);
void QAbstractItemModel_virtbase(QAbstractItemModel* src, QObject** outptr_QObject);
QMetaObject* QAbstractItemModel_metaObject(const QAbstractItemModel* self);
void* QAbstractItemModel_metacast(QAbstractItemModel* self, const char* param1);
int QAbstractItemModel_metacall(QAbstractItemModel* self, int param1, int param2, void** param3);
struct miqt_string QAbstractItemModel_tr(const char* s);
struct miqt_string QAbstractItemModel_trUtf8(const char* s);
bool QAbstractItemModel_hasIndex(const QAbstractItemModel* self, int row, int column);
QModelIndex* QAbstractItemModel_index(const QAbstractItemModel* self, int row, int column, QModelIndex* parent);
QModelIndex* QAbstractItemModel_parent(const QAbstractItemModel* self, QModelIndex* child);
QModelIndex* QAbstractItemModel_sibling(const QAbstractItemModel* self, int row, int column, QModelIndex* idx);
int QAbstractItemModel_rowCount(const QAbstractItemModel* self, QModelIndex* parent);
int QAbstractItemModel_columnCount(const QAbstractItemModel* self, QModelIndex* parent);
bool QAbstractItemModel_hasChildren(const QAbstractItemModel* self, QModelIndex* parent);
QVariant* QAbstractItemModel_data(const QAbstractItemModel* self, QModelIndex* index, int role);
bool QAbstractItemModel_setData(QAbstractItemModel* self, QModelIndex* index, QVariant* value, int role);
QVariant* QAbstractItemModel_headerData(const QAbstractItemModel* self, int section, int orientation, int role);
bool QAbstractItemModel_setHeaderData(QAbstractItemModel* self, int section, int orientation, QVariant* value, int role);
struct miqt_map /* of int to QVariant* */  QAbstractItemModel_itemData(const QAbstractItemModel* self, QModelIndex* index);
bool QAbstractItemModel_setItemData(QAbstractItemModel* self, QModelIndex* index, struct miqt_map /* of int to QVariant* */  roles);
struct miqt_array /* of struct miqt_string */  QAbstractItemModel_mimeTypes(const QAbstractItemModel* self);
QMimeData* QAbstractItemModel_mimeData(const QAbstractItemModel* self, struct miqt_array /* of QModelIndex* */  indexes);
bool QAbstractItemModel_canDropMimeData(const QAbstractItemModel* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
bool QAbstractItemModel_dropMimeData(QAbstractItemModel* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
int QAbstractItemModel_supportedDropActions(const QAbstractItemModel* self);
int QAbstractItemModel_supportedDragActions(const QAbstractItemModel* self);
bool QAbstractItemModel_insertRows(QAbstractItemModel* self, int row, int count, QModelIndex* parent);
bool QAbstractItemModel_insertColumns(QAbstractItemModel* self, int column, int count, QModelIndex* parent);
bool QAbstractItemModel_removeRows(QAbstractItemModel* self, int row, int count, QModelIndex* parent);
bool QAbstractItemModel_removeColumns(QAbstractItemModel* self, int column, int count, QModelIndex* parent);
bool QAbstractItemModel_moveRows(QAbstractItemModel* self, QModelIndex* sourceParent, int sourceRow, int count, QModelIndex* destinationParent, int destinationChild);
bool QAbstractItemModel_moveColumns(QAbstractItemModel* self, QModelIndex* sourceParent, int sourceColumn, int count, QModelIndex* destinationParent, int destinationChild);
bool QAbstractItemModel_insertRow(QAbstractItemModel* self, int row);
bool QAbstractItemModel_insertColumn(QAbstractItemModel* self, int column);
bool QAbstractItemModel_removeRow(QAbstractItemModel* self, int row);
bool QAbstractItemModel_removeColumn(QAbstractItemModel* self, int column);
bool QAbstractItemModel_moveRow(QAbstractItemModel* self, QModelIndex* sourceParent, int sourceRow, QModelIndex* destinationParent, int destinationChild);
bool QAbstractItemModel_moveColumn(QAbstractItemModel* self, QModelIndex* sourceParent, int sourceColumn, QModelIndex* destinationParent, int destinationChild);
void QAbstractItemModel_fetchMore(QAbstractItemModel* self, QModelIndex* parent);
bool QAbstractItemModel_canFetchMore(const QAbstractItemModel* self, QModelIndex* parent);
int QAbstractItemModel_flags(const QAbstractItemModel* self, QModelIndex* index);
void QAbstractItemModel_sort(QAbstractItemModel* self, int column, int order);
QModelIndex* QAbstractItemModel_buddy(const QAbstractItemModel* self, QModelIndex* index);
struct miqt_array /* of QModelIndex* */  QAbstractItemModel_match(const QAbstractItemModel* self, QModelIndex* start, int role, QVariant* value, int hits, int flags);
QSize* QAbstractItemModel_span(const QAbstractItemModel* self, QModelIndex* index);
struct miqt_map /* of int to struct miqt_string */  QAbstractItemModel_roleNames(const QAbstractItemModel* self);
bool QAbstractItemModel_checkIndex(const QAbstractItemModel* self, QModelIndex* index);
void QAbstractItemModel_dataChanged(QAbstractItemModel* self, QModelIndex* topLeft, QModelIndex* bottomRight);
void QAbstractItemModel_connect_dataChanged(QAbstractItemModel* self, intptr_t slot, void (*callback)(intptr_t, QModelIndex*, QModelIndex*), void (*release)(intptr_t));
void QAbstractItemModel_headerDataChanged(QAbstractItemModel* self, int orientation, int first, int last);
void QAbstractItemModel_connect_headerDataChanged(QAbstractItemModel* self, intptr_t slot, void (*callback)(intptr_t, int, int, int), void (*release)(intptr_t));
void QAbstractItemModel_layoutChanged(QAbstractItemModel* self);
void QAbstractItemModel_connect_layoutChanged(QAbstractItemModel* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QAbstractItemModel_layoutAboutToBeChanged(QAbstractItemModel* self);
void QAbstractItemModel_connect_layoutAboutToBeChanged(QAbstractItemModel* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
bool QAbstractItemModel_submit(QAbstractItemModel* self);
void QAbstractItemModel_revert(QAbstractItemModel* self);
struct miqt_string QAbstractItemModel_tr2(const char* s, const char* c);
struct miqt_string QAbstractItemModel_tr3(const char* s, const char* c, int n);
struct miqt_string QAbstractItemModel_trUtf82(const char* s, const char* c);
struct miqt_string QAbstractItemModel_trUtf83(const char* s, const char* c, int n);
bool QAbstractItemModel_hasIndex3(const QAbstractItemModel* self, int row, int column, QModelIndex* parent);
bool QAbstractItemModel_insertRow2(QAbstractItemModel* self, int row, QModelIndex* parent);
bool QAbstractItemModel_insertColumn2(QAbstractItemModel* self, int column, QModelIndex* parent);
bool QAbstractItemModel_removeRow2(QAbstractItemModel* self, int row, QModelIndex* parent);
bool QAbstractItemModel_removeColumn2(QAbstractItemModel* self, int column, QModelIndex* parent);
bool QAbstractItemModel_checkIndex2(const QAbstractItemModel* self, QModelIndex* index, int options);
void QAbstractItemModel_dataChanged3(QAbstractItemModel* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct miqt_array /* of int */  roles);
void QAbstractItemModel_connect_dataChanged3(QAbstractItemModel* self, intptr_t slot, void (*callback)(intptr_t, QModelIndex*, QModelIndex*, struct miqt_array /* of int */ ), void (*release)(intptr_t));
void QAbstractItemModel_layoutChanged1(QAbstractItemModel* self, struct miqt_array /* of QPersistentModelIndex* */  parents);
void QAbstractItemModel_connect_layoutChanged1(QAbstractItemModel* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_array /* of QPersistentModelIndex* */ ), void (*release)(intptr_t));
void QAbstractItemModel_layoutChanged2(QAbstractItemModel* self, struct miqt_array /* of QPersistentModelIndex* */  parents, int hint);
void QAbstractItemModel_connect_layoutChanged2(QAbstractItemModel* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_array /* of QPersistentModelIndex* */ , int), void (*release)(intptr_t));
void QAbstractItemModel_layoutAboutToBeChanged1(QAbstractItemModel* self, struct miqt_array /* of QPersistentModelIndex* */  parents);
void QAbstractItemModel_connect_layoutAboutToBeChanged1(QAbstractItemModel* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_array /* of QPersistentModelIndex* */ ), void (*release)(intptr_t));
void QAbstractItemModel_layoutAboutToBeChanged2(QAbstractItemModel* self, struct miqt_array /* of QPersistentModelIndex* */  parents, int hint);
void QAbstractItemModel_connect_layoutAboutToBeChanged2(QAbstractItemModel* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_array /* of QPersistentModelIndex* */ , int), void (*release)(intptr_t));
QMetaObject* QAbstractItemModel_virtualbase_metaObject(const void* self);
void* QAbstractItemModel_virtualbase_metacast(void* self, const char* param1);
int QAbstractItemModel_virtualbase_metacall(void* self, int param1, int param2, void** param3);
QModelIndex* QAbstractItemModel_virtualbase_index(const void* self, int row, int column, QModelIndex* parent);
QModelIndex* QAbstractItemModel_virtualbase_parent(const void* self, QModelIndex* child);
QModelIndex* QAbstractItemModel_virtualbase_sibling(const void* self, int row, int column, QModelIndex* idx);
int QAbstractItemModel_virtualbase_rowCount(const void* self, QModelIndex* parent);
int QAbstractItemModel_virtualbase_columnCount(const void* self, QModelIndex* parent);
bool QAbstractItemModel_virtualbase_hasChildren(const void* self, QModelIndex* parent);
QVariant* QAbstractItemModel_virtualbase_data(const void* self, QModelIndex* index, int role);
bool QAbstractItemModel_virtualbase_setData(void* self, QModelIndex* index, QVariant* value, int role);
QVariant* QAbstractItemModel_virtualbase_headerData(const void* self, int section, int orientation, int role);
bool QAbstractItemModel_virtualbase_setHeaderData(void* self, int section, int orientation, QVariant* value, int role);
struct miqt_map /* of int to QVariant* */  QAbstractItemModel_virtualbase_itemData(const void* self, QModelIndex* index);
bool QAbstractItemModel_virtualbase_setItemData(void* self, QModelIndex* index, struct miqt_map /* of int to QVariant* */  roles);
struct miqt_array /* of struct miqt_string */  QAbstractItemModel_virtualbase_mimeTypes(const void* self);
QMimeData* QAbstractItemModel_virtualbase_mimeData(const void* self, struct miqt_array /* of QModelIndex* */  indexes);
bool QAbstractItemModel_virtualbase_canDropMimeData(const void* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
bool QAbstractItemModel_virtualbase_dropMimeData(void* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
int QAbstractItemModel_virtualbase_supportedDropActions(const void* self);
int QAbstractItemModel_virtualbase_supportedDragActions(const void* self);
bool QAbstractItemModel_virtualbase_insertRows(void* self, int row, int count, QModelIndex* parent);
bool QAbstractItemModel_virtualbase_insertColumns(void* self, int column, int count, QModelIndex* parent);
bool QAbstractItemModel_virtualbase_removeRows(void* self, int row, int count, QModelIndex* parent);
bool QAbstractItemModel_virtualbase_removeColumns(void* self, int column, int count, QModelIndex* parent);
bool QAbstractItemModel_virtualbase_moveRows(void* self, QModelIndex* sourceParent, int sourceRow, int count, QModelIndex* destinationParent, int destinationChild);
bool QAbstractItemModel_virtualbase_moveColumns(void* self, QModelIndex* sourceParent, int sourceColumn, int count, QModelIndex* destinationParent, int destinationChild);
void QAbstractItemModel_virtualbase_fetchMore(void* self, QModelIndex* parent);
bool QAbstractItemModel_virtualbase_canFetchMore(const void* self, QModelIndex* parent);
int QAbstractItemModel_virtualbase_flags(const void* self, QModelIndex* index);
void QAbstractItemModel_virtualbase_sort(void* self, int column, int order);
QModelIndex* QAbstractItemModel_virtualbase_buddy(const void* self, QModelIndex* index);
struct miqt_array /* of QModelIndex* */  QAbstractItemModel_virtualbase_match(const void* self, QModelIndex* start, int role, QVariant* value, int hits, int flags);
QSize* QAbstractItemModel_virtualbase_span(const void* self, QModelIndex* index);
struct miqt_map /* of int to struct miqt_string */  QAbstractItemModel_virtualbase_roleNames(const void* self);
bool QAbstractItemModel_virtualbase_submit(void* self);
void QAbstractItemModel_virtualbase_revert(void* self);
bool QAbstractItemModel_virtualbase_event(void* self, QEvent* event);
bool QAbstractItemModel_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
void QAbstractItemModel_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QAbstractItemModel_virtualbase_childEvent(void* self, QChildEvent* event);
void QAbstractItemModel_virtualbase_customEvent(void* self, QEvent* event);
void QAbstractItemModel_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QAbstractItemModel_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
void QAbstractItemModel_protectedbase_resetInternalData(bool* _dynamic_cast_ok, void* self);
QModelIndex* QAbstractItemModel_protectedbase_createIndex(bool* _dynamic_cast_ok, const void* self, int row, int column);
QModelIndex* QAbstractItemModel_protectedbase_createIndex2(bool* _dynamic_cast_ok, const void* self, int row, int column, uintptr_t id);
void QAbstractItemModel_protectedbase_encodeData(bool* _dynamic_cast_ok, const void* self, struct miqt_array /* of QModelIndex* */  indexes, QDataStream* stream);
bool QAbstractItemModel_protectedbase_decodeData(bool* _dynamic_cast_ok, void* self, int row, int column, QModelIndex* parent, QDataStream* stream);
void QAbstractItemModel_protectedbase_beginInsertRows(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QAbstractItemModel_protectedbase_endInsertRows(bool* _dynamic_cast_ok, void* self);
void QAbstractItemModel_protectedbase_beginRemoveRows(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QAbstractItemModel_protectedbase_endRemoveRows(bool* _dynamic_cast_ok, void* self);
bool QAbstractItemModel_protectedbase_beginMoveRows(bool* _dynamic_cast_ok, void* self, QModelIndex* sourceParent, int sourceFirst, int sourceLast, QModelIndex* destinationParent, int destinationRow);
void QAbstractItemModel_protectedbase_endMoveRows(bool* _dynamic_cast_ok, void* self);
void QAbstractItemModel_protectedbase_beginInsertColumns(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QAbstractItemModel_protectedbase_endInsertColumns(bool* _dynamic_cast_ok, void* self);
void QAbstractItemModel_protectedbase_beginRemoveColumns(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QAbstractItemModel_protectedbase_endRemoveColumns(bool* _dynamic_cast_ok, void* self);
bool QAbstractItemModel_protectedbase_beginMoveColumns(bool* _dynamic_cast_ok, void* self, QModelIndex* sourceParent, int sourceFirst, int sourceLast, QModelIndex* destinationParent, int destinationColumn);
void QAbstractItemModel_protectedbase_endMoveColumns(bool* _dynamic_cast_ok, void* self);
void QAbstractItemModel_protectedbase_beginResetModel(bool* _dynamic_cast_ok, void* self);
void QAbstractItemModel_protectedbase_endResetModel(bool* _dynamic_cast_ok, void* self);
void QAbstractItemModel_protectedbase_changePersistentIndex(bool* _dynamic_cast_ok, void* self, QModelIndex* from, QModelIndex* to);
void QAbstractItemModel_protectedbase_changePersistentIndexList(bool* _dynamic_cast_ok, void* self, struct miqt_array /* of QModelIndex* */  from, struct miqt_array /* of QModelIndex* */  to);
struct miqt_array /* of QModelIndex* */  QAbstractItemModel_protectedbase_persistentIndexList(bool* _dynamic_cast_ok, const void* self);
QModelIndex* QAbstractItemModel_protectedbase_createIndex3(bool* _dynamic_cast_ok, const void* self, int row, int column, void* data);
QObject* QAbstractItemModel_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QAbstractItemModel_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QAbstractItemModel_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QAbstractItemModel_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
const QMetaObject* QAbstractItemModel_staticMetaObject();
void QAbstractItemModel_delete(QAbstractItemModel* self);

struct QAbstractTableModel_VTable {
	void (*destructor)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self);
	QMetaObject* (*metaObject)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self);
	void* (*metacast)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, const char* param1);
	int (*metacall)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, int param1, int param2, void** param3);
	QModelIndex* (*index)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, int row, int column, QModelIndex* parent);
	QModelIndex* (*sibling)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, int row, int column, QModelIndex* idx);
	bool (*dropMimeData)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
	int (*flags)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, QModelIndex* index);
	int (*rowCount)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, QModelIndex* parent);
	int (*columnCount)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, QModelIndex* parent);
	QVariant* (*data)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, QModelIndex* index, int role);
	bool (*setData)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QModelIndex* index, QVariant* value, int role);
	QVariant* (*headerData)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, int section, int orientation, int role);
	bool (*setHeaderData)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, int section, int orientation, QVariant* value, int role);
	struct miqt_map /* of int to QVariant* */  (*itemData)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, QModelIndex* index);
	bool (*setItemData)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QModelIndex* index, struct miqt_map /* of int to QVariant* */  roles);
	struct miqt_array /* of struct miqt_string */  (*mimeTypes)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self);
	QMimeData* (*mimeData)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, struct miqt_array /* of QModelIndex* */  indexes);
	bool (*canDropMimeData)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
	int (*supportedDropActions)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self);
	int (*supportedDragActions)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self);
	bool (*insertRows)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, int row, int count, QModelIndex* parent);
	bool (*insertColumns)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, int column, int count, QModelIndex* parent);
	bool (*removeRows)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, int row, int count, QModelIndex* parent);
	bool (*removeColumns)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, int column, int count, QModelIndex* parent);
	bool (*moveRows)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QModelIndex* sourceParent, int sourceRow, int count, QModelIndex* destinationParent, int destinationChild);
	bool (*moveColumns)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QModelIndex* sourceParent, int sourceColumn, int count, QModelIndex* destinationParent, int destinationChild);
	void (*fetchMore)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QModelIndex* parent);
	bool (*canFetchMore)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, QModelIndex* parent);
	void (*sort)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, int column, int order);
	QModelIndex* (*buddy)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, QModelIndex* index);
	struct miqt_array /* of QModelIndex* */  (*match)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, QModelIndex* start, int role, QVariant* value, int hits, int flags);
	QSize* (*span)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self, QModelIndex* index);
	struct miqt_map /* of int to struct miqt_string */  (*roleNames)(struct QAbstractTableModel_VTable* vtbl, const QAbstractTableModel* self);
	bool (*submit)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self);
	void (*revert)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self);
	bool (*event)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QEvent* event);
	bool (*eventFilter)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QObject* watched, QEvent* event);
	void (*timerEvent)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QTimerEvent* event);
	void (*childEvent)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QChildEvent* event);
	void (*customEvent)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QEvent* event);
	void (*connectNotify)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QAbstractTableModel_VTable* vtbl, QAbstractTableModel* self, QMetaMethod* signal);
};
QAbstractTableModel* QAbstractTableModel_new(struct QAbstractTableModel_VTable* vtbl);
QAbstractTableModel* QAbstractTableModel_new2(struct QAbstractTableModel_VTable* vtbl, QObject* parent);
void QAbstractTableModel_virtbase(QAbstractTableModel* src, QAbstractItemModel** outptr_QAbstractItemModel);
QMetaObject* QAbstractTableModel_metaObject(const QAbstractTableModel* self);
void* QAbstractTableModel_metacast(QAbstractTableModel* self, const char* param1);
int QAbstractTableModel_metacall(QAbstractTableModel* self, int param1, int param2, void** param3);
struct miqt_string QAbstractTableModel_tr(const char* s);
struct miqt_string QAbstractTableModel_trUtf8(const char* s);
QModelIndex* QAbstractTableModel_index(const QAbstractTableModel* self, int row, int column, QModelIndex* parent);
QModelIndex* QAbstractTableModel_sibling(const QAbstractTableModel* self, int row, int column, QModelIndex* idx);
bool QAbstractTableModel_dropMimeData(QAbstractTableModel* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
int QAbstractTableModel_flags(const QAbstractTableModel* self, QModelIndex* index);
struct miqt_string QAbstractTableModel_tr2(const char* s, const char* c);
struct miqt_string QAbstractTableModel_tr3(const char* s, const char* c, int n);
struct miqt_string QAbstractTableModel_trUtf82(const char* s, const char* c);
struct miqt_string QAbstractTableModel_trUtf83(const char* s, const char* c, int n);
QMetaObject* QAbstractTableModel_virtualbase_metaObject(const void* self);
void* QAbstractTableModel_virtualbase_metacast(void* self, const char* param1);
int QAbstractTableModel_virtualbase_metacall(void* self, int param1, int param2, void** param3);
QModelIndex* QAbstractTableModel_virtualbase_index(const void* self, int row, int column, QModelIndex* parent);
QModelIndex* QAbstractTableModel_virtualbase_sibling(const void* self, int row, int column, QModelIndex* idx);
bool QAbstractTableModel_virtualbase_dropMimeData(void* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
int QAbstractTableModel_virtualbase_flags(const void* self, QModelIndex* index);
int QAbstractTableModel_virtualbase_rowCount(const void* self, QModelIndex* parent);
int QAbstractTableModel_virtualbase_columnCount(const void* self, QModelIndex* parent);
QVariant* QAbstractTableModel_virtualbase_data(const void* self, QModelIndex* index, int role);
bool QAbstractTableModel_virtualbase_setData(void* self, QModelIndex* index, QVariant* value, int role);
QVariant* QAbstractTableModel_virtualbase_headerData(const void* self, int section, int orientation, int role);
bool QAbstractTableModel_virtualbase_setHeaderData(void* self, int section, int orientation, QVariant* value, int role);
struct miqt_map /* of int to QVariant* */  QAbstractTableModel_virtualbase_itemData(const void* self, QModelIndex* index);
bool QAbstractTableModel_virtualbase_setItemData(void* self, QModelIndex* index, struct miqt_map /* of int to QVariant* */  roles);
struct miqt_array /* of struct miqt_string */  QAbstractTableModel_virtualbase_mimeTypes(const void* self);
QMimeData* QAbstractTableModel_virtualbase_mimeData(const void* self, struct miqt_array /* of QModelIndex* */  indexes);
bool QAbstractTableModel_virtualbase_canDropMimeData(const void* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
int QAbstractTableModel_virtualbase_supportedDropActions(const void* self);
int QAbstractTableModel_virtualbase_supportedDragActions(const void* self);
bool QAbstractTableModel_virtualbase_insertRows(void* self, int row, int count, QModelIndex* parent);
bool QAbstractTableModel_virtualbase_insertColumns(void* self, int column, int count, QModelIndex* parent);
bool QAbstractTableModel_virtualbase_removeRows(void* self, int row, int count, QModelIndex* parent);
bool QAbstractTableModel_virtualbase_removeColumns(void* self, int column, int count, QModelIndex* parent);
bool QAbstractTableModel_virtualbase_moveRows(void* self, QModelIndex* sourceParent, int sourceRow, int count, QModelIndex* destinationParent, int destinationChild);
bool QAbstractTableModel_virtualbase_moveColumns(void* self, QModelIndex* sourceParent, int sourceColumn, int count, QModelIndex* destinationParent, int destinationChild);
void QAbstractTableModel_virtualbase_fetchMore(void* self, QModelIndex* parent);
bool QAbstractTableModel_virtualbase_canFetchMore(const void* self, QModelIndex* parent);
void QAbstractTableModel_virtualbase_sort(void* self, int column, int order);
QModelIndex* QAbstractTableModel_virtualbase_buddy(const void* self, QModelIndex* index);
struct miqt_array /* of QModelIndex* */  QAbstractTableModel_virtualbase_match(const void* self, QModelIndex* start, int role, QVariant* value, int hits, int flags);
QSize* QAbstractTableModel_virtualbase_span(const void* self, QModelIndex* index);
struct miqt_map /* of int to struct miqt_string */  QAbstractTableModel_virtualbase_roleNames(const void* self);
bool QAbstractTableModel_virtualbase_submit(void* self);
void QAbstractTableModel_virtualbase_revert(void* self);
bool QAbstractTableModel_virtualbase_event(void* self, QEvent* event);
bool QAbstractTableModel_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
void QAbstractTableModel_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QAbstractTableModel_virtualbase_childEvent(void* self, QChildEvent* event);
void QAbstractTableModel_virtualbase_customEvent(void* self, QEvent* event);
void QAbstractTableModel_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QAbstractTableModel_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
void QAbstractTableModel_protectedbase_resetInternalData(bool* _dynamic_cast_ok, void* self);
QModelIndex* QAbstractTableModel_protectedbase_createIndex(bool* _dynamic_cast_ok, const void* self, int row, int column);
void QAbstractTableModel_protectedbase_encodeData(bool* _dynamic_cast_ok, const void* self, struct miqt_array /* of QModelIndex* */  indexes, QDataStream* stream);
bool QAbstractTableModel_protectedbase_decodeData(bool* _dynamic_cast_ok, void* self, int row, int column, QModelIndex* parent, QDataStream* stream);
void QAbstractTableModel_protectedbase_beginInsertRows(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QAbstractTableModel_protectedbase_endInsertRows(bool* _dynamic_cast_ok, void* self);
void QAbstractTableModel_protectedbase_beginRemoveRows(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QAbstractTableModel_protectedbase_endRemoveRows(bool* _dynamic_cast_ok, void* self);
bool QAbstractTableModel_protectedbase_beginMoveRows(bool* _dynamic_cast_ok, void* self, QModelIndex* sourceParent, int sourceFirst, int sourceLast, QModelIndex* destinationParent, int destinationRow);
void QAbstractTableModel_protectedbase_endMoveRows(bool* _dynamic_cast_ok, void* self);
void QAbstractTableModel_protectedbase_beginInsertColumns(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QAbstractTableModel_protectedbase_endInsertColumns(bool* _dynamic_cast_ok, void* self);
void QAbstractTableModel_protectedbase_beginRemoveColumns(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QAbstractTableModel_protectedbase_endRemoveColumns(bool* _dynamic_cast_ok, void* self);
bool QAbstractTableModel_protectedbase_beginMoveColumns(bool* _dynamic_cast_ok, void* self, QModelIndex* sourceParent, int sourceFirst, int sourceLast, QModelIndex* destinationParent, int destinationColumn);
void QAbstractTableModel_protectedbase_endMoveColumns(bool* _dynamic_cast_ok, void* self);
void QAbstractTableModel_protectedbase_beginResetModel(bool* _dynamic_cast_ok, void* self);
void QAbstractTableModel_protectedbase_endResetModel(bool* _dynamic_cast_ok, void* self);
void QAbstractTableModel_protectedbase_changePersistentIndex(bool* _dynamic_cast_ok, void* self, QModelIndex* from, QModelIndex* to);
void QAbstractTableModel_protectedbase_changePersistentIndexList(bool* _dynamic_cast_ok, void* self, struct miqt_array /* of QModelIndex* */  from, struct miqt_array /* of QModelIndex* */  to);
struct miqt_array /* of QModelIndex* */  QAbstractTableModel_protectedbase_persistentIndexList(bool* _dynamic_cast_ok, const void* self);
QObject* QAbstractTableModel_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QAbstractTableModel_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QAbstractTableModel_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QAbstractTableModel_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
const QMetaObject* QAbstractTableModel_staticMetaObject();
void QAbstractTableModel_delete(QAbstractTableModel* self);

struct QAbstractListModel_VTable {
	void (*destructor)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self);
	QMetaObject* (*metaObject)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self);
	void* (*metacast)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, const char* param1);
	int (*metacall)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, int param1, int param2, void** param3);
	QModelIndex* (*index)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, int row, int column, QModelIndex* parent);
	QModelIndex* (*sibling)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, int row, int column, QModelIndex* idx);
	bool (*dropMimeData)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
	int (*flags)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, QModelIndex* index);
	int (*rowCount)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, QModelIndex* parent);
	QVariant* (*data)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, QModelIndex* index, int role);
	bool (*setData)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QModelIndex* index, QVariant* value, int role);
	QVariant* (*headerData)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, int section, int orientation, int role);
	bool (*setHeaderData)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, int section, int orientation, QVariant* value, int role);
	struct miqt_map /* of int to QVariant* */  (*itemData)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, QModelIndex* index);
	bool (*setItemData)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QModelIndex* index, struct miqt_map /* of int to QVariant* */  roles);
	struct miqt_array /* of struct miqt_string */  (*mimeTypes)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self);
	QMimeData* (*mimeData)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, struct miqt_array /* of QModelIndex* */  indexes);
	bool (*canDropMimeData)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
	int (*supportedDropActions)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self);
	int (*supportedDragActions)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self);
	bool (*insertRows)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, int row, int count, QModelIndex* parent);
	bool (*insertColumns)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, int column, int count, QModelIndex* parent);
	bool (*removeRows)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, int row, int count, QModelIndex* parent);
	bool (*removeColumns)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, int column, int count, QModelIndex* parent);
	bool (*moveRows)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QModelIndex* sourceParent, int sourceRow, int count, QModelIndex* destinationParent, int destinationChild);
	bool (*moveColumns)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QModelIndex* sourceParent, int sourceColumn, int count, QModelIndex* destinationParent, int destinationChild);
	void (*fetchMore)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QModelIndex* parent);
	bool (*canFetchMore)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, QModelIndex* parent);
	void (*sort)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, int column, int order);
	QModelIndex* (*buddy)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, QModelIndex* index);
	struct miqt_array /* of QModelIndex* */  (*match)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, QModelIndex* start, int role, QVariant* value, int hits, int flags);
	QSize* (*span)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self, QModelIndex* index);
	struct miqt_map /* of int to struct miqt_string */  (*roleNames)(struct QAbstractListModel_VTable* vtbl, const QAbstractListModel* self);
	bool (*submit)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self);
	void (*revert)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self);
	bool (*event)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QEvent* event);
	bool (*eventFilter)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QObject* watched, QEvent* event);
	void (*timerEvent)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QTimerEvent* event);
	void (*childEvent)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QChildEvent* event);
	void (*customEvent)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QEvent* event);
	void (*connectNotify)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QAbstractListModel_VTable* vtbl, QAbstractListModel* self, QMetaMethod* signal);
};
QAbstractListModel* QAbstractListModel_new(struct QAbstractListModel_VTable* vtbl);
QAbstractListModel* QAbstractListModel_new2(struct QAbstractListModel_VTable* vtbl, QObject* parent);
void QAbstractListModel_virtbase(QAbstractListModel* src, QAbstractItemModel** outptr_QAbstractItemModel);
QMetaObject* QAbstractListModel_metaObject(const QAbstractListModel* self);
void* QAbstractListModel_metacast(QAbstractListModel* self, const char* param1);
int QAbstractListModel_metacall(QAbstractListModel* self, int param1, int param2, void** param3);
struct miqt_string QAbstractListModel_tr(const char* s);
struct miqt_string QAbstractListModel_trUtf8(const char* s);
QModelIndex* QAbstractListModel_index(const QAbstractListModel* self, int row, int column, QModelIndex* parent);
QModelIndex* QAbstractListModel_sibling(const QAbstractListModel* self, int row, int column, QModelIndex* idx);
bool QAbstractListModel_dropMimeData(QAbstractListModel* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
int QAbstractListModel_flags(const QAbstractListModel* self, QModelIndex* index);
struct miqt_string QAbstractListModel_tr2(const char* s, const char* c);
struct miqt_string QAbstractListModel_tr3(const char* s, const char* c, int n);
struct miqt_string QAbstractListModel_trUtf82(const char* s, const char* c);
struct miqt_string QAbstractListModel_trUtf83(const char* s, const char* c, int n);
QMetaObject* QAbstractListModel_virtualbase_metaObject(const void* self);
void* QAbstractListModel_virtualbase_metacast(void* self, const char* param1);
int QAbstractListModel_virtualbase_metacall(void* self, int param1, int param2, void** param3);
QModelIndex* QAbstractListModel_virtualbase_index(const void* self, int row, int column, QModelIndex* parent);
QModelIndex* QAbstractListModel_virtualbase_sibling(const void* self, int row, int column, QModelIndex* idx);
bool QAbstractListModel_virtualbase_dropMimeData(void* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
int QAbstractListModel_virtualbase_flags(const void* self, QModelIndex* index);
int QAbstractListModel_virtualbase_rowCount(const void* self, QModelIndex* parent);
QVariant* QAbstractListModel_virtualbase_data(const void* self, QModelIndex* index, int role);
bool QAbstractListModel_virtualbase_setData(void* self, QModelIndex* index, QVariant* value, int role);
QVariant* QAbstractListModel_virtualbase_headerData(const void* self, int section, int orientation, int role);
bool QAbstractListModel_virtualbase_setHeaderData(void* self, int section, int orientation, QVariant* value, int role);
struct miqt_map /* of int to QVariant* */  QAbstractListModel_virtualbase_itemData(const void* self, QModelIndex* index);
bool QAbstractListModel_virtualbase_setItemData(void* self, QModelIndex* index, struct miqt_map /* of int to QVariant* */  roles);
struct miqt_array /* of struct miqt_string */  QAbstractListModel_virtualbase_mimeTypes(const void* self);
QMimeData* QAbstractListModel_virtualbase_mimeData(const void* self, struct miqt_array /* of QModelIndex* */  indexes);
bool QAbstractListModel_virtualbase_canDropMimeData(const void* self, QMimeData* data, int action, int row, int column, QModelIndex* parent);
int QAbstractListModel_virtualbase_supportedDropActions(const void* self);
int QAbstractListModel_virtualbase_supportedDragActions(const void* self);
bool QAbstractListModel_virtualbase_insertRows(void* self, int row, int count, QModelIndex* parent);
bool QAbstractListModel_virtualbase_insertColumns(void* self, int column, int count, QModelIndex* parent);
bool QAbstractListModel_virtualbase_removeRows(void* self, int row, int count, QModelIndex* parent);
bool QAbstractListModel_virtualbase_removeColumns(void* self, int column, int count, QModelIndex* parent);
bool QAbstractListModel_virtualbase_moveRows(void* self, QModelIndex* sourceParent, int sourceRow, int count, QModelIndex* destinationParent, int destinationChild);
bool QAbstractListModel_virtualbase_moveColumns(void* self, QModelIndex* sourceParent, int sourceColumn, int count, QModelIndex* destinationParent, int destinationChild);
void QAbstractListModel_virtualbase_fetchMore(void* self, QModelIndex* parent);
bool QAbstractListModel_virtualbase_canFetchMore(const void* self, QModelIndex* parent);
void QAbstractListModel_virtualbase_sort(void* self, int column, int order);
QModelIndex* QAbstractListModel_virtualbase_buddy(const void* self, QModelIndex* index);
struct miqt_array /* of QModelIndex* */  QAbstractListModel_virtualbase_match(const void* self, QModelIndex* start, int role, QVariant* value, int hits, int flags);
QSize* QAbstractListModel_virtualbase_span(const void* self, QModelIndex* index);
struct miqt_map /* of int to struct miqt_string */  QAbstractListModel_virtualbase_roleNames(const void* self);
bool QAbstractListModel_virtualbase_submit(void* self);
void QAbstractListModel_virtualbase_revert(void* self);
bool QAbstractListModel_virtualbase_event(void* self, QEvent* event);
bool QAbstractListModel_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
void QAbstractListModel_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QAbstractListModel_virtualbase_childEvent(void* self, QChildEvent* event);
void QAbstractListModel_virtualbase_customEvent(void* self, QEvent* event);
void QAbstractListModel_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QAbstractListModel_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
void QAbstractListModel_protectedbase_resetInternalData(bool* _dynamic_cast_ok, void* self);
QModelIndex* QAbstractListModel_protectedbase_createIndex(bool* _dynamic_cast_ok, const void* self, int row, int column);
void QAbstractListModel_protectedbase_encodeData(bool* _dynamic_cast_ok, const void* self, struct miqt_array /* of QModelIndex* */  indexes, QDataStream* stream);
bool QAbstractListModel_protectedbase_decodeData(bool* _dynamic_cast_ok, void* self, int row, int column, QModelIndex* parent, QDataStream* stream);
void QAbstractListModel_protectedbase_beginInsertRows(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QAbstractListModel_protectedbase_endInsertRows(bool* _dynamic_cast_ok, void* self);
void QAbstractListModel_protectedbase_beginRemoveRows(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QAbstractListModel_protectedbase_endRemoveRows(bool* _dynamic_cast_ok, void* self);
bool QAbstractListModel_protectedbase_beginMoveRows(bool* _dynamic_cast_ok, void* self, QModelIndex* sourceParent, int sourceFirst, int sourceLast, QModelIndex* destinationParent, int destinationRow);
void QAbstractListModel_protectedbase_endMoveRows(bool* _dynamic_cast_ok, void* self);
void QAbstractListModel_protectedbase_beginInsertColumns(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QAbstractListModel_protectedbase_endInsertColumns(bool* _dynamic_cast_ok, void* self);
void QAbstractListModel_protectedbase_beginRemoveColumns(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QAbstractListModel_protectedbase_endRemoveColumns(bool* _dynamic_cast_ok, void* self);
bool QAbstractListModel_protectedbase_beginMoveColumns(bool* _dynamic_cast_ok, void* self, QModelIndex* sourceParent, int sourceFirst, int sourceLast, QModelIndex* destinationParent, int destinationColumn);
void QAbstractListModel_protectedbase_endMoveColumns(bool* _dynamic_cast_ok, void* self);
void QAbstractListModel_protectedbase_beginResetModel(bool* _dynamic_cast_ok, void* self);
void QAbstractListModel_protectedbase_endResetModel(bool* _dynamic_cast_ok, void* self);
void QAbstractListModel_protectedbase_changePersistentIndex(bool* _dynamic_cast_ok, void* self, QModelIndex* from, QModelIndex* to);
void QAbstractListModel_protectedbase_changePersistentIndexList(bool* _dynamic_cast_ok, void* self, struct miqt_array /* of QModelIndex* */  from, struct miqt_array /* of QModelIndex* */  to);
struct miqt_array /* of QModelIndex* */  QAbstractListModel_protectedbase_persistentIndexList(bool* _dynamic_cast_ok, const void* self);
QObject* QAbstractListModel_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QAbstractListModel_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QAbstractListModel_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QAbstractListModel_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
const QMetaObject* QAbstractListModel_staticMetaObject();
void QAbstractListModel_delete(QAbstractListModel* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
