#pragma once
#ifndef SEAQT_QTWEBKITWIDGETS_GEN_QGRAPHICSWEBVIEW_H
#define SEAQT_QTWEBKITWIDGETS_GEN_QGRAPHICSWEBVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt/libseaqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAction;
class QChildEvent;
class QCloseEvent;
class QEvent;
class QFocusEvent;
class QGraphicsItem;
class QGraphicsLayoutItem;
class QGraphicsObject;
class QGraphicsSceneContextMenuEvent;
class QGraphicsSceneDragDropEvent;
class QGraphicsSceneHoverEvent;
class QGraphicsSceneMouseEvent;
class QGraphicsSceneMoveEvent;
class QGraphicsSceneResizeEvent;
class QGraphicsSceneWheelEvent;
class QGraphicsWebView;
class QGraphicsWidget;
class QHideEvent;
class QIcon;
class QInputMethodEvent;
class QKeyEvent;
class QMetaMethod;
class QMetaObject;
class QNetworkRequest;
class QObject;
class QPainter;
class QPainterPath;
class QPointF;
class QRectF;
class QShowEvent;
class QSizeF;
class QStyleOption;
class QStyleOptionGraphicsItem;
class QTimerEvent;
class QUrl;
class QVariant;
class QWebHistory;
class QWebPage;
class QWebSettings;
class QWidget;
#else
typedef struct QAction QAction;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QGraphicsItem QGraphicsItem;
typedef struct QGraphicsLayoutItem QGraphicsLayoutItem;
typedef struct QGraphicsObject QGraphicsObject;
typedef struct QGraphicsSceneContextMenuEvent QGraphicsSceneContextMenuEvent;
typedef struct QGraphicsSceneDragDropEvent QGraphicsSceneDragDropEvent;
typedef struct QGraphicsSceneHoverEvent QGraphicsSceneHoverEvent;
typedef struct QGraphicsSceneMouseEvent QGraphicsSceneMouseEvent;
typedef struct QGraphicsSceneMoveEvent QGraphicsSceneMoveEvent;
typedef struct QGraphicsSceneResizeEvent QGraphicsSceneResizeEvent;
typedef struct QGraphicsSceneWheelEvent QGraphicsSceneWheelEvent;
typedef struct QGraphicsWebView QGraphicsWebView;
typedef struct QGraphicsWidget QGraphicsWidget;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QNetworkRequest QNetworkRequest;
typedef struct QObject QObject;
typedef struct QPainter QPainter;
typedef struct QPainterPath QPainterPath;
typedef struct QPointF QPointF;
typedef struct QRectF QRectF;
typedef struct QShowEvent QShowEvent;
typedef struct QSizeF QSizeF;
typedef struct QStyleOption QStyleOption;
typedef struct QStyleOptionGraphicsItem QStyleOptionGraphicsItem;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWebHistory QWebHistory;
typedef struct QWebPage QWebPage;
typedef struct QWebSettings QWebSettings;
typedef struct QWidget QWidget;
#endif

struct QGraphicsWebView_VTable {
	void (*destructor)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self);
	QMetaObject* (*metaObject)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self);
	void* (*metacast)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, const char* param1);
	int (*metacall)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, int param1, int param2, void** param3);
	void (*setGeometry)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QRectF* rect);
	void (*updateGeometry)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self);
	void (*paint)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QPainter* param1, QStyleOptionGraphicsItem* options, QWidget* widget);
	QVariant* (*itemChange)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, int change, QVariant* value);
	bool (*event)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QEvent* param1);
	QSizeF* (*sizeHint)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self, int which, QSizeF* constraint);
	QVariant* (*inputMethodQuery)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self, int query);
	void (*mousePressEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneMouseEvent* param1);
	void (*mouseDoubleClickEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneMouseEvent* param1);
	void (*mouseReleaseEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneMouseEvent* param1);
	void (*mouseMoveEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneMouseEvent* param1);
	void (*hoverMoveEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneHoverEvent* param1);
	void (*hoverLeaveEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneHoverEvent* param1);
	void (*wheelEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneWheelEvent* param1);
	void (*keyPressEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QKeyEvent* param1);
	void (*keyReleaseEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QKeyEvent* param1);
	void (*contextMenuEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneContextMenuEvent* param1);
	void (*dragEnterEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneDragDropEvent* param1);
	void (*dragLeaveEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneDragDropEvent* param1);
	void (*dragMoveEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneDragDropEvent* param1);
	void (*dropEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneDragDropEvent* param1);
	void (*focusInEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QFocusEvent* param1);
	void (*focusOutEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QFocusEvent* param1);
	void (*inputMethodEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QInputMethodEvent* param1);
	bool (*focusNextPrevChild)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, bool next);
	bool (*sceneEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QEvent* param1);
	void (*getContentsMargins)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self, double* left, double* top, double* right, double* bottom);
	int (*type)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self);
	void (*paintWindowFrame)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
	QRectF* (*boundingRect)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self);
	QPainterPath* (*shape)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self);
	void (*initStyleOption)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self, QStyleOption* option);
	QVariant* (*propertyChange)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, struct miqt_string propertyName, QVariant* value);
	bool (*windowFrameEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QEvent* e);
	int (*windowFrameSectionAt)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self, QPointF* pos);
	void (*changeEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QEvent* event);
	void (*closeEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QCloseEvent* event);
	void (*hideEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QHideEvent* event);
	void (*moveEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneMoveEvent* event);
	void (*polishEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self);
	void (*resizeEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneResizeEvent* event);
	void (*showEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QShowEvent* event);
	void (*grabMouseEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QEvent* event);
	void (*ungrabMouseEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QEvent* event);
	void (*grabKeyboardEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QEvent* event);
	void (*ungrabKeyboardEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QEvent* event);
	bool (*eventFilter)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QObject* watched, QEvent* event);
	void (*timerEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QTimerEvent* event);
	void (*childEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QChildEvent* event);
	void (*customEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QEvent* event);
	void (*connectNotify)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QMetaMethod* signal);
	void (*advance)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, int phase);
	bool (*contains)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self, QPointF* point);
	bool (*collidesWithItem)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self, QGraphicsItem* other, int mode);
	bool (*collidesWithPath)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self, QPainterPath* path, int mode);
	bool (*isObscuredBy)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self, QGraphicsItem* item);
	QPainterPath* (*opaqueArea)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self);
	bool (*sceneEventFilter)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsItem* watched, QEvent* event);
	void (*hoverEnterEvent)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, QGraphicsSceneHoverEvent* event);
	bool (*supportsExtension)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self, int extension);
	void (*setExtension)(struct QGraphicsWebView_VTable* vtbl, QGraphicsWebView* self, int extension, QVariant* variant);
	QVariant* (*extension)(struct QGraphicsWebView_VTable* vtbl, const QGraphicsWebView* self, QVariant* variant);
};
QGraphicsWebView* QGraphicsWebView_new(struct QGraphicsWebView_VTable* vtbl);
QGraphicsWebView* QGraphicsWebView_new2(struct QGraphicsWebView_VTable* vtbl, QGraphicsItem* parent);
void QGraphicsWebView_virtbase(QGraphicsWebView* src, QGraphicsWidget** outptr_QGraphicsWidget);
QMetaObject* QGraphicsWebView_metaObject(const QGraphicsWebView* self);
void* QGraphicsWebView_metacast(QGraphicsWebView* self, const char* param1);
int QGraphicsWebView_metacall(QGraphicsWebView* self, int param1, int param2, void** param3);
struct miqt_string QGraphicsWebView_tr(const char* s);
struct miqt_string QGraphicsWebView_trUtf8(const char* s);
QWebPage* QGraphicsWebView_page(const QGraphicsWebView* self);
void QGraphicsWebView_setPage(QGraphicsWebView* self, QWebPage* page);
QUrl* QGraphicsWebView_url(const QGraphicsWebView* self);
void QGraphicsWebView_setUrl(QGraphicsWebView* self, QUrl* url);
struct miqt_string QGraphicsWebView_title(const QGraphicsWebView* self);
QIcon* QGraphicsWebView_icon(const QGraphicsWebView* self);
double QGraphicsWebView_zoomFactor(const QGraphicsWebView* self);
void QGraphicsWebView_setZoomFactor(QGraphicsWebView* self, double zoomFactor);
bool QGraphicsWebView_isModified(const QGraphicsWebView* self);
void QGraphicsWebView_load(QGraphicsWebView* self, QUrl* url);
void QGraphicsWebView_loadWithRequest(QGraphicsWebView* self, QNetworkRequest* request);
void QGraphicsWebView_setHtml(QGraphicsWebView* self, struct miqt_string html);
void QGraphicsWebView_setContent(QGraphicsWebView* self, struct miqt_string data);
QWebHistory* QGraphicsWebView_history(const QGraphicsWebView* self);
QWebSettings* QGraphicsWebView_settings(const QGraphicsWebView* self);
QAction* QGraphicsWebView_pageAction(const QGraphicsWebView* self, int action);
void QGraphicsWebView_triggerPageAction(QGraphicsWebView* self, int action);
bool QGraphicsWebView_findText(QGraphicsWebView* self, struct miqt_string subString);
bool QGraphicsWebView_resizesToContents(const QGraphicsWebView* self);
void QGraphicsWebView_setResizesToContents(QGraphicsWebView* self, bool enabled);
bool QGraphicsWebView_isTiledBackingStoreFrozen(const QGraphicsWebView* self);
void QGraphicsWebView_setTiledBackingStoreFrozen(QGraphicsWebView* self, bool frozen);
void QGraphicsWebView_setGeometry(QGraphicsWebView* self, QRectF* rect);
void QGraphicsWebView_updateGeometry(QGraphicsWebView* self);
void QGraphicsWebView_paint(QGraphicsWebView* self, QPainter* param1, QStyleOptionGraphicsItem* options, QWidget* widget);
QVariant* QGraphicsWebView_itemChange(QGraphicsWebView* self, int change, QVariant* value);
bool QGraphicsWebView_event(QGraphicsWebView* self, QEvent* param1);
QSizeF* QGraphicsWebView_sizeHint(const QGraphicsWebView* self, int which, QSizeF* constraint);
QVariant* QGraphicsWebView_inputMethodQuery(const QGraphicsWebView* self, int query);
int QGraphicsWebView_renderHints(const QGraphicsWebView* self);
void QGraphicsWebView_setRenderHints(QGraphicsWebView* self, int renderHints);
void QGraphicsWebView_setRenderHint(QGraphicsWebView* self, int param1);
void QGraphicsWebView_stop(QGraphicsWebView* self);
void QGraphicsWebView_back(QGraphicsWebView* self);
void QGraphicsWebView_forward(QGraphicsWebView* self);
void QGraphicsWebView_reload(QGraphicsWebView* self);
void QGraphicsWebView_loadStarted(QGraphicsWebView* self);
void QGraphicsWebView_connect_loadStarted(QGraphicsWebView* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QGraphicsWebView_loadFinished(QGraphicsWebView* self, bool param1);
void QGraphicsWebView_connect_loadFinished(QGraphicsWebView* self, intptr_t slot, void (*callback)(intptr_t, bool), void (*release)(intptr_t));
void QGraphicsWebView_loadProgress(QGraphicsWebView* self, int progress);
void QGraphicsWebView_connect_loadProgress(QGraphicsWebView* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QGraphicsWebView_urlChanged(QGraphicsWebView* self, QUrl* param1);
void QGraphicsWebView_connect_urlChanged(QGraphicsWebView* self, intptr_t slot, void (*callback)(intptr_t, QUrl*), void (*release)(intptr_t));
void QGraphicsWebView_titleChanged(QGraphicsWebView* self, struct miqt_string param1);
void QGraphicsWebView_connect_titleChanged(QGraphicsWebView* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_string), void (*release)(intptr_t));
void QGraphicsWebView_iconChanged(QGraphicsWebView* self);
void QGraphicsWebView_connect_iconChanged(QGraphicsWebView* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QGraphicsWebView_statusBarMessage(QGraphicsWebView* self, struct miqt_string message);
void QGraphicsWebView_connect_statusBarMessage(QGraphicsWebView* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_string), void (*release)(intptr_t));
void QGraphicsWebView_linkClicked(QGraphicsWebView* self, QUrl* param1);
void QGraphicsWebView_connect_linkClicked(QGraphicsWebView* self, intptr_t slot, void (*callback)(intptr_t, QUrl*), void (*release)(intptr_t));
void QGraphicsWebView_mousePressEvent(QGraphicsWebView* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_mouseDoubleClickEvent(QGraphicsWebView* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_mouseReleaseEvent(QGraphicsWebView* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_mouseMoveEvent(QGraphicsWebView* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_hoverMoveEvent(QGraphicsWebView* self, QGraphicsSceneHoverEvent* param1);
void QGraphicsWebView_hoverLeaveEvent(QGraphicsWebView* self, QGraphicsSceneHoverEvent* param1);
void QGraphicsWebView_wheelEvent(QGraphicsWebView* self, QGraphicsSceneWheelEvent* param1);
void QGraphicsWebView_keyPressEvent(QGraphicsWebView* self, QKeyEvent* param1);
void QGraphicsWebView_keyReleaseEvent(QGraphicsWebView* self, QKeyEvent* param1);
void QGraphicsWebView_contextMenuEvent(QGraphicsWebView* self, QGraphicsSceneContextMenuEvent* param1);
void QGraphicsWebView_dragEnterEvent(QGraphicsWebView* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_dragLeaveEvent(QGraphicsWebView* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_dragMoveEvent(QGraphicsWebView* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_dropEvent(QGraphicsWebView* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_focusInEvent(QGraphicsWebView* self, QFocusEvent* param1);
void QGraphicsWebView_focusOutEvent(QGraphicsWebView* self, QFocusEvent* param1);
void QGraphicsWebView_inputMethodEvent(QGraphicsWebView* self, QInputMethodEvent* param1);
bool QGraphicsWebView_focusNextPrevChild(QGraphicsWebView* self, bool next);
bool QGraphicsWebView_sceneEvent(QGraphicsWebView* self, QEvent* param1);
struct miqt_string QGraphicsWebView_tr2(const char* s, const char* c);
struct miqt_string QGraphicsWebView_tr3(const char* s, const char* c, int n);
struct miqt_string QGraphicsWebView_trUtf82(const char* s, const char* c);
struct miqt_string QGraphicsWebView_trUtf83(const char* s, const char* c, int n);
void QGraphicsWebView_load2(QGraphicsWebView* self, QNetworkRequest* request, int operation);
void QGraphicsWebView_load3(QGraphicsWebView* self, QNetworkRequest* request, int operation, struct miqt_string body);
void QGraphicsWebView_setHtml2(QGraphicsWebView* self, struct miqt_string html, QUrl* baseUrl);
void QGraphicsWebView_setContent2(QGraphicsWebView* self, struct miqt_string data, struct miqt_string mimeType);
void QGraphicsWebView_setContent3(QGraphicsWebView* self, struct miqt_string data, struct miqt_string mimeType, QUrl* baseUrl);
void QGraphicsWebView_triggerPageAction2(QGraphicsWebView* self, int action, bool checked);
bool QGraphicsWebView_findText2(QGraphicsWebView* self, struct miqt_string subString, int options);
void QGraphicsWebView_setRenderHint2(QGraphicsWebView* self, int param1, bool enabled);
QMetaObject* QGraphicsWebView_virtualbase_metaObject(const void* self);
void* QGraphicsWebView_virtualbase_metacast(void* self, const char* param1);
int QGraphicsWebView_virtualbase_metacall(void* self, int param1, int param2, void** param3);
void QGraphicsWebView_virtualbase_setGeometry(void* self, QRectF* rect);
void QGraphicsWebView_virtualbase_updateGeometry(void* self);
void QGraphicsWebView_virtualbase_paint(void* self, QPainter* param1, QStyleOptionGraphicsItem* options, QWidget* widget);
QVariant* QGraphicsWebView_virtualbase_itemChange(void* self, int change, QVariant* value);
bool QGraphicsWebView_virtualbase_event(void* self, QEvent* param1);
QSizeF* QGraphicsWebView_virtualbase_sizeHint(const void* self, int which, QSizeF* constraint);
QVariant* QGraphicsWebView_virtualbase_inputMethodQuery(const void* self, int query);
void QGraphicsWebView_virtualbase_mousePressEvent(void* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_virtualbase_mouseDoubleClickEvent(void* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_virtualbase_mouseReleaseEvent(void* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_virtualbase_mouseMoveEvent(void* self, QGraphicsSceneMouseEvent* param1);
void QGraphicsWebView_virtualbase_hoverMoveEvent(void* self, QGraphicsSceneHoverEvent* param1);
void QGraphicsWebView_virtualbase_hoverLeaveEvent(void* self, QGraphicsSceneHoverEvent* param1);
void QGraphicsWebView_virtualbase_wheelEvent(void* self, QGraphicsSceneWheelEvent* param1);
void QGraphicsWebView_virtualbase_keyPressEvent(void* self, QKeyEvent* param1);
void QGraphicsWebView_virtualbase_keyReleaseEvent(void* self, QKeyEvent* param1);
void QGraphicsWebView_virtualbase_contextMenuEvent(void* self, QGraphicsSceneContextMenuEvent* param1);
void QGraphicsWebView_virtualbase_dragEnterEvent(void* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_virtualbase_dragLeaveEvent(void* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_virtualbase_dragMoveEvent(void* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_virtualbase_dropEvent(void* self, QGraphicsSceneDragDropEvent* param1);
void QGraphicsWebView_virtualbase_focusInEvent(void* self, QFocusEvent* param1);
void QGraphicsWebView_virtualbase_focusOutEvent(void* self, QFocusEvent* param1);
void QGraphicsWebView_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* param1);
bool QGraphicsWebView_virtualbase_focusNextPrevChild(void* self, bool next);
bool QGraphicsWebView_virtualbase_sceneEvent(void* self, QEvent* param1);
void QGraphicsWebView_virtualbase_getContentsMargins(const void* self, double* left, double* top, double* right, double* bottom);
int QGraphicsWebView_virtualbase_type(const void* self);
void QGraphicsWebView_virtualbase_paintWindowFrame(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
QRectF* QGraphicsWebView_virtualbase_boundingRect(const void* self);
QPainterPath* QGraphicsWebView_virtualbase_shape(const void* self);
void QGraphicsWebView_virtualbase_initStyleOption(const void* self, QStyleOption* option);
QVariant* QGraphicsWebView_virtualbase_propertyChange(void* self, struct miqt_string propertyName, QVariant* value);
bool QGraphicsWebView_virtualbase_windowFrameEvent(void* self, QEvent* e);
int QGraphicsWebView_virtualbase_windowFrameSectionAt(const void* self, QPointF* pos);
void QGraphicsWebView_virtualbase_changeEvent(void* self, QEvent* event);
void QGraphicsWebView_virtualbase_closeEvent(void* self, QCloseEvent* event);
void QGraphicsWebView_virtualbase_hideEvent(void* self, QHideEvent* event);
void QGraphicsWebView_virtualbase_moveEvent(void* self, QGraphicsSceneMoveEvent* event);
void QGraphicsWebView_virtualbase_polishEvent(void* self);
void QGraphicsWebView_virtualbase_resizeEvent(void* self, QGraphicsSceneResizeEvent* event);
void QGraphicsWebView_virtualbase_showEvent(void* self, QShowEvent* event);
void QGraphicsWebView_virtualbase_grabMouseEvent(void* self, QEvent* event);
void QGraphicsWebView_virtualbase_ungrabMouseEvent(void* self, QEvent* event);
void QGraphicsWebView_virtualbase_grabKeyboardEvent(void* self, QEvent* event);
void QGraphicsWebView_virtualbase_ungrabKeyboardEvent(void* self, QEvent* event);
bool QGraphicsWebView_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
void QGraphicsWebView_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QGraphicsWebView_virtualbase_childEvent(void* self, QChildEvent* event);
void QGraphicsWebView_virtualbase_customEvent(void* self, QEvent* event);
void QGraphicsWebView_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QGraphicsWebView_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
void QGraphicsWebView_virtualbase_advance(void* self, int phase);
bool QGraphicsWebView_virtualbase_contains(const void* self, QPointF* point);
bool QGraphicsWebView_virtualbase_collidesWithItem(const void* self, QGraphicsItem* other, int mode);
bool QGraphicsWebView_virtualbase_collidesWithPath(const void* self, QPainterPath* path, int mode);
bool QGraphicsWebView_virtualbase_isObscuredBy(const void* self, QGraphicsItem* item);
QPainterPath* QGraphicsWebView_virtualbase_opaqueArea(const void* self);
bool QGraphicsWebView_virtualbase_sceneEventFilter(void* self, QGraphicsItem* watched, QEvent* event);
void QGraphicsWebView_virtualbase_hoverEnterEvent(void* self, QGraphicsSceneHoverEvent* event);
bool QGraphicsWebView_virtualbase_supportsExtension(const void* self, int extension);
void QGraphicsWebView_virtualbase_setExtension(void* self, int extension, QVariant* variant);
QVariant* QGraphicsWebView_virtualbase_extension(const void* self, QVariant* variant);
void QGraphicsWebView_protectedbase_updateMicroFocus(bool* _dynamic_cast_ok, void* self);
QObject* QGraphicsWebView_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QGraphicsWebView_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QGraphicsWebView_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QGraphicsWebView_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
void QGraphicsWebView_protectedbase_addToIndex(bool* _dynamic_cast_ok, void* self);
void QGraphicsWebView_protectedbase_removeFromIndex(bool* _dynamic_cast_ok, void* self);
void QGraphicsWebView_protectedbase_prepareGeometryChange(bool* _dynamic_cast_ok, void* self);
void QGraphicsWebView_protectedbase_setGraphicsItem(bool* _dynamic_cast_ok, void* self, QGraphicsItem* item);
void QGraphicsWebView_protectedbase_setOwnedByLayout(bool* _dynamic_cast_ok, void* self, bool ownedByLayout);
const QMetaObject* QGraphicsWebView_staticMetaObject();
void QGraphicsWebView_delete(QGraphicsWebView* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
