#pragma once
#ifndef SEAQT_QTWEBKITWIDGETS_GEN_QWEBVIEW_H
#define SEAQT_QTWEBKITWIDGETS_GEN_QWEBVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt/libseaqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAction;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QHideEvent;
class QIcon;
class QInputMethodEvent;
class QKeyEvent;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QNetworkRequest;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QPrinter;
class QResizeEvent;
class QShowEvent;
class QSize;
class QTabletEvent;
class QTimerEvent;
class QUrl;
class QVariant;
class QWebHistory;
class QWebPage;
class QWebSettings;
class QWebView;
class QWheelEvent;
class QWidget;
#else
typedef struct QAction QAction;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QNetworkRequest QNetworkRequest;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QPrinter QPrinter;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWebHistory QWebHistory;
typedef struct QWebPage QWebPage;
typedef struct QWebSettings QWebSettings;
typedef struct QWebView QWebView;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

struct QWebView_VTable {
	void (*destructor)(struct QWebView_VTable* vtbl, QWebView* self);
	QMetaObject* (*metaObject)(struct QWebView_VTable* vtbl, const QWebView* self);
	void* (*metacast)(struct QWebView_VTable* vtbl, QWebView* self, const char* param1);
	int (*metacall)(struct QWebView_VTable* vtbl, QWebView* self, int param1, int param2, void** param3);
	QVariant* (*inputMethodQuery)(struct QWebView_VTable* vtbl, const QWebView* self, int property);
	QSize* (*sizeHint)(struct QWebView_VTable* vtbl, const QWebView* self);
	bool (*event)(struct QWebView_VTable* vtbl, QWebView* self, QEvent* param1);
	void (*resizeEvent)(struct QWebView_VTable* vtbl, QWebView* self, QResizeEvent* param1);
	void (*paintEvent)(struct QWebView_VTable* vtbl, QWebView* self, QPaintEvent* param1);
	QWebView* (*createWindow)(struct QWebView_VTable* vtbl, QWebView* self, int type);
	void (*changeEvent)(struct QWebView_VTable* vtbl, QWebView* self, QEvent* param1);
	void (*mouseMoveEvent)(struct QWebView_VTable* vtbl, QWebView* self, QMouseEvent* param1);
	void (*mousePressEvent)(struct QWebView_VTable* vtbl, QWebView* self, QMouseEvent* param1);
	void (*mouseDoubleClickEvent)(struct QWebView_VTable* vtbl, QWebView* self, QMouseEvent* param1);
	void (*mouseReleaseEvent)(struct QWebView_VTable* vtbl, QWebView* self, QMouseEvent* param1);
	void (*contextMenuEvent)(struct QWebView_VTable* vtbl, QWebView* self, QContextMenuEvent* param1);
	void (*wheelEvent)(struct QWebView_VTable* vtbl, QWebView* self, QWheelEvent* param1);
	void (*keyPressEvent)(struct QWebView_VTable* vtbl, QWebView* self, QKeyEvent* param1);
	void (*keyReleaseEvent)(struct QWebView_VTable* vtbl, QWebView* self, QKeyEvent* param1);
	void (*dragEnterEvent)(struct QWebView_VTable* vtbl, QWebView* self, QDragEnterEvent* param1);
	void (*dragLeaveEvent)(struct QWebView_VTable* vtbl, QWebView* self, QDragLeaveEvent* param1);
	void (*dragMoveEvent)(struct QWebView_VTable* vtbl, QWebView* self, QDragMoveEvent* param1);
	void (*dropEvent)(struct QWebView_VTable* vtbl, QWebView* self, QDropEvent* param1);
	void (*focusInEvent)(struct QWebView_VTable* vtbl, QWebView* self, QFocusEvent* param1);
	void (*focusOutEvent)(struct QWebView_VTable* vtbl, QWebView* self, QFocusEvent* param1);
	void (*inputMethodEvent)(struct QWebView_VTable* vtbl, QWebView* self, QInputMethodEvent* param1);
	bool (*focusNextPrevChild)(struct QWebView_VTable* vtbl, QWebView* self, bool next);
	int (*devType)(struct QWebView_VTable* vtbl, const QWebView* self);
	void (*setVisible)(struct QWebView_VTable* vtbl, QWebView* self, bool visible);
	QSize* (*minimumSizeHint)(struct QWebView_VTable* vtbl, const QWebView* self);
	int (*heightForWidth)(struct QWebView_VTable* vtbl, const QWebView* self, int param1);
	bool (*hasHeightForWidth)(struct QWebView_VTable* vtbl, const QWebView* self);
	QPaintEngine* (*paintEngine)(struct QWebView_VTable* vtbl, const QWebView* self);
	void (*enterEvent)(struct QWebView_VTable* vtbl, QWebView* self, QEvent* event);
	void (*leaveEvent)(struct QWebView_VTable* vtbl, QWebView* self, QEvent* event);
	void (*moveEvent)(struct QWebView_VTable* vtbl, QWebView* self, QMoveEvent* event);
	void (*closeEvent)(struct QWebView_VTable* vtbl, QWebView* self, QCloseEvent* event);
	void (*tabletEvent)(struct QWebView_VTable* vtbl, QWebView* self, QTabletEvent* event);
	void (*actionEvent)(struct QWebView_VTable* vtbl, QWebView* self, QActionEvent* event);
	void (*showEvent)(struct QWebView_VTable* vtbl, QWebView* self, QShowEvent* event);
	void (*hideEvent)(struct QWebView_VTable* vtbl, QWebView* self, QHideEvent* event);
	bool (*nativeEvent)(struct QWebView_VTable* vtbl, QWebView* self, struct miqt_string eventType, void* message, long* result);
	int (*metric)(struct QWebView_VTable* vtbl, const QWebView* self, int param1);
	void (*initPainter)(struct QWebView_VTable* vtbl, const QWebView* self, QPainter* painter);
	QPaintDevice* (*redirected)(struct QWebView_VTable* vtbl, const QWebView* self, QPoint* offset);
	QPainter* (*sharedPainter)(struct QWebView_VTable* vtbl, const QWebView* self);
	bool (*eventFilter)(struct QWebView_VTable* vtbl, QWebView* self, QObject* watched, QEvent* event);
	void (*timerEvent)(struct QWebView_VTable* vtbl, QWebView* self, QTimerEvent* event);
	void (*childEvent)(struct QWebView_VTable* vtbl, QWebView* self, QChildEvent* event);
	void (*customEvent)(struct QWebView_VTable* vtbl, QWebView* self, QEvent* event);
	void (*connectNotify)(struct QWebView_VTable* vtbl, QWebView* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QWebView_VTable* vtbl, QWebView* self, QMetaMethod* signal);
};
QWebView* QWebView_new(struct QWebView_VTable* vtbl, QWidget* parent);
QWebView* QWebView_new2(struct QWebView_VTable* vtbl);
void QWebView_virtbase(QWebView* src, QWidget** outptr_QWidget);
QMetaObject* QWebView_metaObject(const QWebView* self);
void* QWebView_metacast(QWebView* self, const char* param1);
int QWebView_metacall(QWebView* self, int param1, int param2, void** param3);
struct miqt_string QWebView_tr(const char* s);
struct miqt_string QWebView_trUtf8(const char* s);
QWebPage* QWebView_page(const QWebView* self);
void QWebView_setPage(QWebView* self, QWebPage* page);
void QWebView_load(QWebView* self, QUrl* url);
void QWebView_loadWithRequest(QWebView* self, QNetworkRequest* request);
void QWebView_setHtml(QWebView* self, struct miqt_string html);
void QWebView_setContent(QWebView* self, struct miqt_string data);
QWebHistory* QWebView_history(const QWebView* self);
QWebSettings* QWebView_settings(const QWebView* self);
struct miqt_string QWebView_title(const QWebView* self);
void QWebView_setUrl(QWebView* self, QUrl* url);
QUrl* QWebView_url(const QWebView* self);
QIcon* QWebView_icon(const QWebView* self);
bool QWebView_hasSelection(const QWebView* self);
struct miqt_string QWebView_selectedText(const QWebView* self);
struct miqt_string QWebView_selectedHtml(const QWebView* self);
QAction* QWebView_pageAction(const QWebView* self, int action);
void QWebView_triggerPageAction(QWebView* self, int action);
bool QWebView_isModified(const QWebView* self);
QVariant* QWebView_inputMethodQuery(const QWebView* self, int property);
QSize* QWebView_sizeHint(const QWebView* self);
double QWebView_zoomFactor(const QWebView* self);
void QWebView_setZoomFactor(QWebView* self, double factor);
void QWebView_setTextSizeMultiplier(QWebView* self, double factor);
double QWebView_textSizeMultiplier(const QWebView* self);
int QWebView_renderHints(const QWebView* self);
void QWebView_setRenderHints(QWebView* self, int hints);
void QWebView_setRenderHint(QWebView* self, int hint);
bool QWebView_findText(QWebView* self, struct miqt_string subString);
bool QWebView_event(QWebView* self, QEvent* param1);
void QWebView_stop(QWebView* self);
void QWebView_back(QWebView* self);
void QWebView_forward(QWebView* self);
void QWebView_reload(QWebView* self);
void QWebView_print(const QWebView* self, QPrinter* param1);
void QWebView_loadStarted(QWebView* self);
void QWebView_connect_loadStarted(QWebView* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QWebView_loadProgress(QWebView* self, int progress);
void QWebView_connect_loadProgress(QWebView* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QWebView_loadFinished(QWebView* self, bool param1);
void QWebView_connect_loadFinished(QWebView* self, intptr_t slot, void (*callback)(intptr_t, bool), void (*release)(intptr_t));
void QWebView_titleChanged(QWebView* self, struct miqt_string title);
void QWebView_connect_titleChanged(QWebView* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_string), void (*release)(intptr_t));
void QWebView_statusBarMessage(QWebView* self, struct miqt_string text);
void QWebView_connect_statusBarMessage(QWebView* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_string), void (*release)(intptr_t));
void QWebView_linkClicked(QWebView* self, QUrl* param1);
void QWebView_connect_linkClicked(QWebView* self, intptr_t slot, void (*callback)(intptr_t, QUrl*), void (*release)(intptr_t));
void QWebView_selectionChanged(QWebView* self);
void QWebView_connect_selectionChanged(QWebView* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QWebView_iconChanged(QWebView* self);
void QWebView_connect_iconChanged(QWebView* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QWebView_urlChanged(QWebView* self, QUrl* param1);
void QWebView_connect_urlChanged(QWebView* self, intptr_t slot, void (*callback)(intptr_t, QUrl*), void (*release)(intptr_t));
void QWebView_resizeEvent(QWebView* self, QResizeEvent* param1);
void QWebView_paintEvent(QWebView* self, QPaintEvent* param1);
QWebView* QWebView_createWindow(QWebView* self, int type);
void QWebView_changeEvent(QWebView* self, QEvent* param1);
void QWebView_mouseMoveEvent(QWebView* self, QMouseEvent* param1);
void QWebView_mousePressEvent(QWebView* self, QMouseEvent* param1);
void QWebView_mouseDoubleClickEvent(QWebView* self, QMouseEvent* param1);
void QWebView_mouseReleaseEvent(QWebView* self, QMouseEvent* param1);
void QWebView_contextMenuEvent(QWebView* self, QContextMenuEvent* param1);
void QWebView_wheelEvent(QWebView* self, QWheelEvent* param1);
void QWebView_keyPressEvent(QWebView* self, QKeyEvent* param1);
void QWebView_keyReleaseEvent(QWebView* self, QKeyEvent* param1);
void QWebView_dragEnterEvent(QWebView* self, QDragEnterEvent* param1);
void QWebView_dragLeaveEvent(QWebView* self, QDragLeaveEvent* param1);
void QWebView_dragMoveEvent(QWebView* self, QDragMoveEvent* param1);
void QWebView_dropEvent(QWebView* self, QDropEvent* param1);
void QWebView_focusInEvent(QWebView* self, QFocusEvent* param1);
void QWebView_focusOutEvent(QWebView* self, QFocusEvent* param1);
void QWebView_inputMethodEvent(QWebView* self, QInputMethodEvent* param1);
bool QWebView_focusNextPrevChild(QWebView* self, bool next);
struct miqt_string QWebView_tr2(const char* s, const char* c);
struct miqt_string QWebView_tr3(const char* s, const char* c, int n);
struct miqt_string QWebView_trUtf82(const char* s, const char* c);
struct miqt_string QWebView_trUtf83(const char* s, const char* c, int n);
void QWebView_load2(QWebView* self, QNetworkRequest* request, int operation);
void QWebView_load3(QWebView* self, QNetworkRequest* request, int operation, struct miqt_string body);
void QWebView_setHtml2(QWebView* self, struct miqt_string html, QUrl* baseUrl);
void QWebView_setContent2(QWebView* self, struct miqt_string data, struct miqt_string mimeType);
void QWebView_setContent3(QWebView* self, struct miqt_string data, struct miqt_string mimeType, QUrl* baseUrl);
void QWebView_triggerPageAction2(QWebView* self, int action, bool checked);
void QWebView_setRenderHint2(QWebView* self, int hint, bool enabled);
bool QWebView_findText2(QWebView* self, struct miqt_string subString, int options);
QMetaObject* QWebView_virtualbase_metaObject(const void* self);
void* QWebView_virtualbase_metacast(void* self, const char* param1);
int QWebView_virtualbase_metacall(void* self, int param1, int param2, void** param3);
QVariant* QWebView_virtualbase_inputMethodQuery(const void* self, int property);
QSize* QWebView_virtualbase_sizeHint(const void* self);
bool QWebView_virtualbase_event(void* self, QEvent* param1);
void QWebView_virtualbase_resizeEvent(void* self, QResizeEvent* param1);
void QWebView_virtualbase_paintEvent(void* self, QPaintEvent* param1);
QWebView* QWebView_virtualbase_createWindow(void* self, int type);
void QWebView_virtualbase_changeEvent(void* self, QEvent* param1);
void QWebView_virtualbase_mouseMoveEvent(void* self, QMouseEvent* param1);
void QWebView_virtualbase_mousePressEvent(void* self, QMouseEvent* param1);
void QWebView_virtualbase_mouseDoubleClickEvent(void* self, QMouseEvent* param1);
void QWebView_virtualbase_mouseReleaseEvent(void* self, QMouseEvent* param1);
void QWebView_virtualbase_contextMenuEvent(void* self, QContextMenuEvent* param1);
void QWebView_virtualbase_wheelEvent(void* self, QWheelEvent* param1);
void QWebView_virtualbase_keyPressEvent(void* self, QKeyEvent* param1);
void QWebView_virtualbase_keyReleaseEvent(void* self, QKeyEvent* param1);
void QWebView_virtualbase_dragEnterEvent(void* self, QDragEnterEvent* param1);
void QWebView_virtualbase_dragLeaveEvent(void* self, QDragLeaveEvent* param1);
void QWebView_virtualbase_dragMoveEvent(void* self, QDragMoveEvent* param1);
void QWebView_virtualbase_dropEvent(void* self, QDropEvent* param1);
void QWebView_virtualbase_focusInEvent(void* self, QFocusEvent* param1);
void QWebView_virtualbase_focusOutEvent(void* self, QFocusEvent* param1);
void QWebView_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* param1);
bool QWebView_virtualbase_focusNextPrevChild(void* self, bool next);
int QWebView_virtualbase_devType(const void* self);
void QWebView_virtualbase_setVisible(void* self, bool visible);
QSize* QWebView_virtualbase_minimumSizeHint(const void* self);
int QWebView_virtualbase_heightForWidth(const void* self, int param1);
bool QWebView_virtualbase_hasHeightForWidth(const void* self);
QPaintEngine* QWebView_virtualbase_paintEngine(const void* self);
void QWebView_virtualbase_enterEvent(void* self, QEvent* event);
void QWebView_virtualbase_leaveEvent(void* self, QEvent* event);
void QWebView_virtualbase_moveEvent(void* self, QMoveEvent* event);
void QWebView_virtualbase_closeEvent(void* self, QCloseEvent* event);
void QWebView_virtualbase_tabletEvent(void* self, QTabletEvent* event);
void QWebView_virtualbase_actionEvent(void* self, QActionEvent* event);
void QWebView_virtualbase_showEvent(void* self, QShowEvent* event);
void QWebView_virtualbase_hideEvent(void* self, QHideEvent* event);
bool QWebView_virtualbase_nativeEvent(void* self, struct miqt_string eventType, void* message, long* result);
int QWebView_virtualbase_metric(const void* self, int param1);
void QWebView_virtualbase_initPainter(const void* self, QPainter* painter);
QPaintDevice* QWebView_virtualbase_redirected(const void* self, QPoint* offset);
QPainter* QWebView_virtualbase_sharedPainter(const void* self);
bool QWebView_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
void QWebView_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QWebView_virtualbase_childEvent(void* self, QChildEvent* event);
void QWebView_virtualbase_customEvent(void* self, QEvent* event);
void QWebView_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QWebView_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
void QWebView_protectedbase_updateMicroFocus(void* self);
void QWebView_protectedbase_create(void* self);
void QWebView_protectedbase_destroy(void* self);
bool QWebView_protectedbase_focusNextChild(void* self);
bool QWebView_protectedbase_focusPreviousChild(void* self);
QObject* QWebView_protectedbase_sender(const void* self);
int QWebView_protectedbase_senderSignalIndex(const void* self);
int QWebView_protectedbase_receivers(const void* self, const char* signal);
bool QWebView_protectedbase_isSignalConnected(const void* self, QMetaMethod* signal);
const QMetaObject* QWebView_staticMetaObject();
void QWebView_delete(QWebView* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
