#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QFILEDIALOG_H
#define SEAQT_QTWIDGETS_GEN_QFILEDIALOG_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt/libseaqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemDelegate;
class QAbstractProxyModel;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDialog;
class QDir;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFileDialog;
class QFileIconProvider;
class QFocusEvent;
class QHideEvent;
class QInputMethodEvent;
class QKeyEvent;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QResizeEvent;
class QShowEvent;
class QSize;
class QTabletEvent;
class QTimerEvent;
class QUrl;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractProxyModel QAbstractProxyModel;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDir QDir;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFileDialog QFileDialog;
typedef struct QFileIconProvider QFileIconProvider;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

struct QFileDialog_VTable {
	void (*destructor)(struct QFileDialog_VTable* vtbl, QFileDialog* self);
	QMetaObject* (*metaObject)(struct QFileDialog_VTable* vtbl, const QFileDialog* self);
	void* (*metacast)(struct QFileDialog_VTable* vtbl, QFileDialog* self, const char* param1);
	int (*metacall)(struct QFileDialog_VTable* vtbl, QFileDialog* self, int param1, int param2, void** param3);
	void (*setVisible)(struct QFileDialog_VTable* vtbl, QFileDialog* self, bool visible);
	void (*done)(struct QFileDialog_VTable* vtbl, QFileDialog* self, int result);
	void (*accept)(struct QFileDialog_VTable* vtbl, QFileDialog* self);
	void (*changeEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QEvent* e);
	QSize* (*sizeHint)(struct QFileDialog_VTable* vtbl, const QFileDialog* self);
	QSize* (*minimumSizeHint)(struct QFileDialog_VTable* vtbl, const QFileDialog* self);
	void (*open)(struct QFileDialog_VTable* vtbl, QFileDialog* self);
	int (*exec)(struct QFileDialog_VTable* vtbl, QFileDialog* self);
	void (*reject)(struct QFileDialog_VTable* vtbl, QFileDialog* self);
	void (*keyPressEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QKeyEvent* param1);
	void (*closeEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QCloseEvent* param1);
	void (*showEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QShowEvent* param1);
	void (*resizeEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QResizeEvent* param1);
	void (*contextMenuEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QContextMenuEvent* param1);
	bool (*eventFilter)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QObject* param1, QEvent* param2);
	int (*devType)(struct QFileDialog_VTable* vtbl, const QFileDialog* self);
	int (*heightForWidth)(struct QFileDialog_VTable* vtbl, const QFileDialog* self, int param1);
	bool (*hasHeightForWidth)(struct QFileDialog_VTable* vtbl, const QFileDialog* self);
	QPaintEngine* (*paintEngine)(struct QFileDialog_VTable* vtbl, const QFileDialog* self);
	bool (*event)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QEvent* event);
	void (*mousePressEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QMouseEvent* event);
	void (*mouseDoubleClickEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QMouseEvent* event);
	void (*mouseMoveEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QMouseEvent* event);
	void (*wheelEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QWheelEvent* event);
	void (*keyReleaseEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QKeyEvent* event);
	void (*focusInEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QFocusEvent* event);
	void (*focusOutEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QFocusEvent* event);
	void (*enterEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QEvent* event);
	void (*leaveEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QEvent* event);
	void (*paintEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QPaintEvent* event);
	void (*moveEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QMoveEvent* event);
	void (*tabletEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QTabletEvent* event);
	void (*actionEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QActionEvent* event);
	void (*dragEnterEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QDragEnterEvent* event);
	void (*dragMoveEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QDragMoveEvent* event);
	void (*dragLeaveEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QDragLeaveEvent* event);
	void (*dropEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QDropEvent* event);
	void (*hideEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QHideEvent* event);
	bool (*nativeEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, struct miqt_string eventType, void* message, long* result);
	int (*metric)(struct QFileDialog_VTable* vtbl, const QFileDialog* self, int param1);
	void (*initPainter)(struct QFileDialog_VTable* vtbl, const QFileDialog* self, QPainter* painter);
	QPaintDevice* (*redirected)(struct QFileDialog_VTable* vtbl, const QFileDialog* self, QPoint* offset);
	QPainter* (*sharedPainter)(struct QFileDialog_VTable* vtbl, const QFileDialog* self);
	void (*inputMethodEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QInputMethodEvent* param1);
	QVariant* (*inputMethodQuery)(struct QFileDialog_VTable* vtbl, const QFileDialog* self, int param1);
	bool (*focusNextPrevChild)(struct QFileDialog_VTable* vtbl, QFileDialog* self, bool next);
	void (*timerEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QTimerEvent* event);
	void (*childEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QChildEvent* event);
	void (*customEvent)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QEvent* event);
	void (*connectNotify)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QFileDialog_VTable* vtbl, QFileDialog* self, QMetaMethod* signal);
};
QFileDialog* QFileDialog_new(struct QFileDialog_VTable* vtbl, QWidget* parent);
QFileDialog* QFileDialog_new2(struct QFileDialog_VTable* vtbl, QWidget* parent, int f);
QFileDialog* QFileDialog_new3(struct QFileDialog_VTable* vtbl);
QFileDialog* QFileDialog_new4(struct QFileDialog_VTable* vtbl, QWidget* parent, struct miqt_string caption);
QFileDialog* QFileDialog_new5(struct QFileDialog_VTable* vtbl, QWidget* parent, struct miqt_string caption, struct miqt_string directory);
QFileDialog* QFileDialog_new6(struct QFileDialog_VTable* vtbl, QWidget* parent, struct miqt_string caption, struct miqt_string directory, struct miqt_string filter);
void QFileDialog_virtbase(QFileDialog* src, QDialog** outptr_QDialog);
QMetaObject* QFileDialog_metaObject(const QFileDialog* self);
void* QFileDialog_metacast(QFileDialog* self, const char* param1);
int QFileDialog_metacall(QFileDialog* self, int param1, int param2, void** param3);
struct miqt_string QFileDialog_tr(const char* s);
struct miqt_string QFileDialog_trUtf8(const char* s);
void QFileDialog_setDirectory(QFileDialog* self, struct miqt_string directory);
void QFileDialog_setDirectoryWithDirectory(QFileDialog* self, QDir* directory);
QDir* QFileDialog_directory(const QFileDialog* self);
void QFileDialog_setDirectoryUrl(QFileDialog* self, QUrl* directory);
QUrl* QFileDialog_directoryUrl(const QFileDialog* self);
void QFileDialog_selectFile(QFileDialog* self, struct miqt_string filename);
struct miqt_array /* of struct miqt_string */  QFileDialog_selectedFiles(const QFileDialog* self);
void QFileDialog_selectUrl(QFileDialog* self, QUrl* url);
struct miqt_array /* of QUrl* */  QFileDialog_selectedUrls(const QFileDialog* self);
void QFileDialog_setNameFilterDetailsVisible(QFileDialog* self, bool enabled);
bool QFileDialog_isNameFilterDetailsVisible(const QFileDialog* self);
void QFileDialog_setNameFilter(QFileDialog* self, struct miqt_string filter);
void QFileDialog_setNameFilters(QFileDialog* self, struct miqt_array /* of struct miqt_string */  filters);
struct miqt_array /* of struct miqt_string */  QFileDialog_nameFilters(const QFileDialog* self);
void QFileDialog_selectNameFilter(QFileDialog* self, struct miqt_string filter);
struct miqt_string QFileDialog_selectedMimeTypeFilter(const QFileDialog* self);
struct miqt_string QFileDialog_selectedNameFilter(const QFileDialog* self);
void QFileDialog_setMimeTypeFilters(QFileDialog* self, struct miqt_array /* of struct miqt_string */  filters);
struct miqt_array /* of struct miqt_string */  QFileDialog_mimeTypeFilters(const QFileDialog* self);
void QFileDialog_selectMimeTypeFilter(QFileDialog* self, struct miqt_string filter);
int QFileDialog_filter(const QFileDialog* self);
void QFileDialog_setFilter(QFileDialog* self, int filters);
void QFileDialog_setViewMode(QFileDialog* self, int mode);
int QFileDialog_viewMode(const QFileDialog* self);
void QFileDialog_setFileMode(QFileDialog* self, int mode);
int QFileDialog_fileMode(const QFileDialog* self);
void QFileDialog_setAcceptMode(QFileDialog* self, int mode);
int QFileDialog_acceptMode(const QFileDialog* self);
void QFileDialog_setReadOnly(QFileDialog* self, bool enabled);
bool QFileDialog_isReadOnly(const QFileDialog* self);
void QFileDialog_setResolveSymlinks(QFileDialog* self, bool enabled);
bool QFileDialog_resolveSymlinks(const QFileDialog* self);
void QFileDialog_setSidebarUrls(QFileDialog* self, struct miqt_array /* of QUrl* */  urls);
struct miqt_array /* of QUrl* */  QFileDialog_sidebarUrls(const QFileDialog* self);
struct miqt_string QFileDialog_saveState(const QFileDialog* self);
bool QFileDialog_restoreState(QFileDialog* self, struct miqt_string state);
void QFileDialog_setConfirmOverwrite(QFileDialog* self, bool enabled);
bool QFileDialog_confirmOverwrite(const QFileDialog* self);
void QFileDialog_setDefaultSuffix(QFileDialog* self, struct miqt_string suffix);
struct miqt_string QFileDialog_defaultSuffix(const QFileDialog* self);
void QFileDialog_setHistory(QFileDialog* self, struct miqt_array /* of struct miqt_string */  paths);
struct miqt_array /* of struct miqt_string */  QFileDialog_history(const QFileDialog* self);
void QFileDialog_setItemDelegate(QFileDialog* self, QAbstractItemDelegate* delegate);
QAbstractItemDelegate* QFileDialog_itemDelegate(const QFileDialog* self);
void QFileDialog_setIconProvider(QFileDialog* self, QFileIconProvider* provider);
QFileIconProvider* QFileDialog_iconProvider(const QFileDialog* self);
void QFileDialog_setLabelText(QFileDialog* self, int label, struct miqt_string text);
struct miqt_string QFileDialog_labelText(const QFileDialog* self, int label);
void QFileDialog_setSupportedSchemes(QFileDialog* self, struct miqt_array /* of struct miqt_string */  schemes);
struct miqt_array /* of struct miqt_string */  QFileDialog_supportedSchemes(const QFileDialog* self);
void QFileDialog_setProxyModel(QFileDialog* self, QAbstractProxyModel* model);
QAbstractProxyModel* QFileDialog_proxyModel(const QFileDialog* self);
void QFileDialog_setOption(QFileDialog* self, int option);
bool QFileDialog_testOption(const QFileDialog* self, int option);
void QFileDialog_setOptions(QFileDialog* self, int options);
int QFileDialog_options(const QFileDialog* self);
void QFileDialog_setVisible(QFileDialog* self, bool visible);
void QFileDialog_fileSelected(QFileDialog* self, struct miqt_string file);
void QFileDialog_connect_fileSelected(QFileDialog* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_string), void (*release)(intptr_t));
void QFileDialog_filesSelected(QFileDialog* self, struct miqt_array /* of struct miqt_string */  files);
void QFileDialog_connect_filesSelected(QFileDialog* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_array /* of struct miqt_string */ ), void (*release)(intptr_t));
void QFileDialog_currentChanged(QFileDialog* self, struct miqt_string path);
void QFileDialog_connect_currentChanged(QFileDialog* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_string), void (*release)(intptr_t));
void QFileDialog_directoryEntered(QFileDialog* self, struct miqt_string directory);
void QFileDialog_connect_directoryEntered(QFileDialog* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_string), void (*release)(intptr_t));
void QFileDialog_urlSelected(QFileDialog* self, QUrl* url);
void QFileDialog_connect_urlSelected(QFileDialog* self, intptr_t slot, void (*callback)(intptr_t, QUrl*), void (*release)(intptr_t));
void QFileDialog_urlsSelected(QFileDialog* self, struct miqt_array /* of QUrl* */  urls);
void QFileDialog_connect_urlsSelected(QFileDialog* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_array /* of QUrl* */ ), void (*release)(intptr_t));
void QFileDialog_currentUrlChanged(QFileDialog* self, QUrl* url);
void QFileDialog_connect_currentUrlChanged(QFileDialog* self, intptr_t slot, void (*callback)(intptr_t, QUrl*), void (*release)(intptr_t));
void QFileDialog_directoryUrlEntered(QFileDialog* self, QUrl* directory);
void QFileDialog_connect_directoryUrlEntered(QFileDialog* self, intptr_t slot, void (*callback)(intptr_t, QUrl*), void (*release)(intptr_t));
void QFileDialog_filterSelected(QFileDialog* self, struct miqt_string filter);
void QFileDialog_connect_filterSelected(QFileDialog* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_string), void (*release)(intptr_t));
struct miqt_string QFileDialog_getOpenFileName();
QUrl* QFileDialog_getOpenFileUrl();
struct miqt_string QFileDialog_getSaveFileName();
QUrl* QFileDialog_getSaveFileUrl();
struct miqt_string QFileDialog_getExistingDirectory();
QUrl* QFileDialog_getExistingDirectoryUrl();
struct miqt_array /* of struct miqt_string */  QFileDialog_getOpenFileNames();
struct miqt_array /* of QUrl* */  QFileDialog_getOpenFileUrls();
void QFileDialog_saveFileContent(struct miqt_string fileContent, struct miqt_string fileNameHint);
void QFileDialog_done(QFileDialog* self, int result);
void QFileDialog_accept(QFileDialog* self);
void QFileDialog_changeEvent(QFileDialog* self, QEvent* e);
struct miqt_string QFileDialog_tr2(const char* s, const char* c);
struct miqt_string QFileDialog_tr3(const char* s, const char* c, int n);
struct miqt_string QFileDialog_trUtf82(const char* s, const char* c);
struct miqt_string QFileDialog_trUtf83(const char* s, const char* c, int n);
void QFileDialog_setOption2(QFileDialog* self, int option, bool on);
struct miqt_string QFileDialog_getOpenFileName1(QWidget* parent);
struct miqt_string QFileDialog_getOpenFileName2(QWidget* parent, struct miqt_string caption);
struct miqt_string QFileDialog_getOpenFileName3(QWidget* parent, struct miqt_string caption, struct miqt_string dir);
struct miqt_string QFileDialog_getOpenFileName4(QWidget* parent, struct miqt_string caption, struct miqt_string dir, struct miqt_string filter);
QUrl* QFileDialog_getOpenFileUrl1(QWidget* parent);
QUrl* QFileDialog_getOpenFileUrl2(QWidget* parent, struct miqt_string caption);
QUrl* QFileDialog_getOpenFileUrl3(QWidget* parent, struct miqt_string caption, QUrl* dir);
QUrl* QFileDialog_getOpenFileUrl4(QWidget* parent, struct miqt_string caption, QUrl* dir, struct miqt_string filter);
struct miqt_string QFileDialog_getSaveFileName1(QWidget* parent);
struct miqt_string QFileDialog_getSaveFileName2(QWidget* parent, struct miqt_string caption);
struct miqt_string QFileDialog_getSaveFileName3(QWidget* parent, struct miqt_string caption, struct miqt_string dir);
struct miqt_string QFileDialog_getSaveFileName4(QWidget* parent, struct miqt_string caption, struct miqt_string dir, struct miqt_string filter);
QUrl* QFileDialog_getSaveFileUrl1(QWidget* parent);
QUrl* QFileDialog_getSaveFileUrl2(QWidget* parent, struct miqt_string caption);
QUrl* QFileDialog_getSaveFileUrl3(QWidget* parent, struct miqt_string caption, QUrl* dir);
QUrl* QFileDialog_getSaveFileUrl4(QWidget* parent, struct miqt_string caption, QUrl* dir, struct miqt_string filter);
struct miqt_string QFileDialog_getExistingDirectory1(QWidget* parent);
struct miqt_string QFileDialog_getExistingDirectory2(QWidget* parent, struct miqt_string caption);
struct miqt_string QFileDialog_getExistingDirectory3(QWidget* parent, struct miqt_string caption, struct miqt_string dir);
struct miqt_string QFileDialog_getExistingDirectory4(QWidget* parent, struct miqt_string caption, struct miqt_string dir, int options);
QUrl* QFileDialog_getExistingDirectoryUrl1(QWidget* parent);
QUrl* QFileDialog_getExistingDirectoryUrl2(QWidget* parent, struct miqt_string caption);
QUrl* QFileDialog_getExistingDirectoryUrl3(QWidget* parent, struct miqt_string caption, QUrl* dir);
QUrl* QFileDialog_getExistingDirectoryUrl4(QWidget* parent, struct miqt_string caption, QUrl* dir, int options);
QUrl* QFileDialog_getExistingDirectoryUrl5(QWidget* parent, struct miqt_string caption, QUrl* dir, int options, struct miqt_array /* of struct miqt_string */  supportedSchemes);
struct miqt_array /* of struct miqt_string */  QFileDialog_getOpenFileNames1(QWidget* parent);
struct miqt_array /* of struct miqt_string */  QFileDialog_getOpenFileNames2(QWidget* parent, struct miqt_string caption);
struct miqt_array /* of struct miqt_string */  QFileDialog_getOpenFileNames3(QWidget* parent, struct miqt_string caption, struct miqt_string dir);
struct miqt_array /* of struct miqt_string */  QFileDialog_getOpenFileNames4(QWidget* parent, struct miqt_string caption, struct miqt_string dir, struct miqt_string filter);
struct miqt_array /* of QUrl* */  QFileDialog_getOpenFileUrls1(QWidget* parent);
struct miqt_array /* of QUrl* */  QFileDialog_getOpenFileUrls2(QWidget* parent, struct miqt_string caption);
struct miqt_array /* of QUrl* */  QFileDialog_getOpenFileUrls3(QWidget* parent, struct miqt_string caption, QUrl* dir);
struct miqt_array /* of QUrl* */  QFileDialog_getOpenFileUrls4(QWidget* parent, struct miqt_string caption, QUrl* dir, struct miqt_string filter);
QMetaObject* QFileDialog_virtualbase_metaObject(const void* self);
void* QFileDialog_virtualbase_metacast(void* self, const char* param1);
int QFileDialog_virtualbase_metacall(void* self, int param1, int param2, void** param3);
void QFileDialog_virtualbase_setVisible(void* self, bool visible);
void QFileDialog_virtualbase_done(void* self, int result);
void QFileDialog_virtualbase_accept(void* self);
void QFileDialog_virtualbase_changeEvent(void* self, QEvent* e);
QSize* QFileDialog_virtualbase_sizeHint(const void* self);
QSize* QFileDialog_virtualbase_minimumSizeHint(const void* self);
void QFileDialog_virtualbase_open(void* self);
int QFileDialog_virtualbase_exec(void* self);
void QFileDialog_virtualbase_reject(void* self);
void QFileDialog_virtualbase_keyPressEvent(void* self, QKeyEvent* param1);
void QFileDialog_virtualbase_closeEvent(void* self, QCloseEvent* param1);
void QFileDialog_virtualbase_showEvent(void* self, QShowEvent* param1);
void QFileDialog_virtualbase_resizeEvent(void* self, QResizeEvent* param1);
void QFileDialog_virtualbase_contextMenuEvent(void* self, QContextMenuEvent* param1);
bool QFileDialog_virtualbase_eventFilter(void* self, QObject* param1, QEvent* param2);
int QFileDialog_virtualbase_devType(const void* self);
int QFileDialog_virtualbase_heightForWidth(const void* self, int param1);
bool QFileDialog_virtualbase_hasHeightForWidth(const void* self);
QPaintEngine* QFileDialog_virtualbase_paintEngine(const void* self);
bool QFileDialog_virtualbase_event(void* self, QEvent* event);
void QFileDialog_virtualbase_mousePressEvent(void* self, QMouseEvent* event);
void QFileDialog_virtualbase_mouseReleaseEvent(void* self, QMouseEvent* event);
void QFileDialog_virtualbase_mouseDoubleClickEvent(void* self, QMouseEvent* event);
void QFileDialog_virtualbase_mouseMoveEvent(void* self, QMouseEvent* event);
void QFileDialog_virtualbase_wheelEvent(void* self, QWheelEvent* event);
void QFileDialog_virtualbase_keyReleaseEvent(void* self, QKeyEvent* event);
void QFileDialog_virtualbase_focusInEvent(void* self, QFocusEvent* event);
void QFileDialog_virtualbase_focusOutEvent(void* self, QFocusEvent* event);
void QFileDialog_virtualbase_enterEvent(void* self, QEvent* event);
void QFileDialog_virtualbase_leaveEvent(void* self, QEvent* event);
void QFileDialog_virtualbase_paintEvent(void* self, QPaintEvent* event);
void QFileDialog_virtualbase_moveEvent(void* self, QMoveEvent* event);
void QFileDialog_virtualbase_tabletEvent(void* self, QTabletEvent* event);
void QFileDialog_virtualbase_actionEvent(void* self, QActionEvent* event);
void QFileDialog_virtualbase_dragEnterEvent(void* self, QDragEnterEvent* event);
void QFileDialog_virtualbase_dragMoveEvent(void* self, QDragMoveEvent* event);
void QFileDialog_virtualbase_dragLeaveEvent(void* self, QDragLeaveEvent* event);
void QFileDialog_virtualbase_dropEvent(void* self, QDropEvent* event);
void QFileDialog_virtualbase_hideEvent(void* self, QHideEvent* event);
bool QFileDialog_virtualbase_nativeEvent(void* self, struct miqt_string eventType, void* message, long* result);
int QFileDialog_virtualbase_metric(const void* self, int param1);
void QFileDialog_virtualbase_initPainter(const void* self, QPainter* painter);
QPaintDevice* QFileDialog_virtualbase_redirected(const void* self, QPoint* offset);
QPainter* QFileDialog_virtualbase_sharedPainter(const void* self);
void QFileDialog_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* param1);
QVariant* QFileDialog_virtualbase_inputMethodQuery(const void* self, int param1);
bool QFileDialog_virtualbase_focusNextPrevChild(void* self, bool next);
void QFileDialog_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QFileDialog_virtualbase_childEvent(void* self, QChildEvent* event);
void QFileDialog_virtualbase_customEvent(void* self, QEvent* event);
void QFileDialog_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QFileDialog_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
void QFileDialog_protectedbase_adjustPosition(void* self, QWidget* param1);
void QFileDialog_protectedbase_updateMicroFocus(void* self);
void QFileDialog_protectedbase_create(void* self);
void QFileDialog_protectedbase_destroy(void* self);
bool QFileDialog_protectedbase_focusNextChild(void* self);
bool QFileDialog_protectedbase_focusPreviousChild(void* self);
QObject* QFileDialog_protectedbase_sender(const void* self);
int QFileDialog_protectedbase_senderSignalIndex(const void* self);
int QFileDialog_protectedbase_receivers(const void* self, const char* signal);
bool QFileDialog_protectedbase_isSignalConnected(const void* self, QMetaMethod* signal);
const QMetaObject* QFileDialog_staticMetaObject();
void QFileDialog_delete(QFileDialog* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
