#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QGRAPHICSWIDGET_H
#define SEAQT_QTWIDGETS_GEN_QGRAPHICSWIDGET_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt/libseaqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAction;
class QChildEvent;
class QCloseEvent;
class QEvent;
class QFocusEvent;
class QFont;
class QGraphicsItem;
class QGraphicsLayout;
class QGraphicsLayoutItem;
class QGraphicsObject;
class QGraphicsSceneContextMenuEvent;
class QGraphicsSceneDragDropEvent;
class QGraphicsSceneHoverEvent;
class QGraphicsSceneMouseEvent;
class QGraphicsSceneMoveEvent;
class QGraphicsSceneResizeEvent;
class QGraphicsSceneWheelEvent;
class QGraphicsWidget;
class QHideEvent;
class QInputMethodEvent;
class QKeyEvent;
class QKeySequence;
class QMarginsF;
class QMetaMethod;
class QMetaObject;
class QObject;
class QPainter;
class QPainterPath;
class QPalette;
class QPointF;
class QRectF;
class QShowEvent;
class QSizeF;
class QStyle;
class QStyleOption;
class QStyleOptionGraphicsItem;
class QTimerEvent;
class QVariant;
class QWidget;
#else
typedef struct QAction QAction;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QGraphicsItem QGraphicsItem;
typedef struct QGraphicsLayout QGraphicsLayout;
typedef struct QGraphicsLayoutItem QGraphicsLayoutItem;
typedef struct QGraphicsObject QGraphicsObject;
typedef struct QGraphicsSceneContextMenuEvent QGraphicsSceneContextMenuEvent;
typedef struct QGraphicsSceneDragDropEvent QGraphicsSceneDragDropEvent;
typedef struct QGraphicsSceneHoverEvent QGraphicsSceneHoverEvent;
typedef struct QGraphicsSceneMouseEvent QGraphicsSceneMouseEvent;
typedef struct QGraphicsSceneMoveEvent QGraphicsSceneMoveEvent;
typedef struct QGraphicsSceneResizeEvent QGraphicsSceneResizeEvent;
typedef struct QGraphicsSceneWheelEvent QGraphicsSceneWheelEvent;
typedef struct QGraphicsWidget QGraphicsWidget;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QKeySequence QKeySequence;
typedef struct QMarginsF QMarginsF;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QObject QObject;
typedef struct QPainter QPainter;
typedef struct QPainterPath QPainterPath;
typedef struct QPalette QPalette;
typedef struct QPointF QPointF;
typedef struct QRectF QRectF;
typedef struct QShowEvent QShowEvent;
typedef struct QSizeF QSizeF;
typedef struct QStyle QStyle;
typedef struct QStyleOption QStyleOption;
typedef struct QStyleOptionGraphicsItem QStyleOptionGraphicsItem;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWidget QWidget;
#endif

struct QGraphicsWidget_VTable {
	void (*destructor)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self);
	QMetaObject* (*metaObject)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self);
	void* (*metacast)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, const char* param1);
	int (*metacall)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, int param1, int param2, void** param3);
	void (*setGeometry)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QRectF* rect);
	void (*getContentsMargins)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self, double* left, double* top, double* right, double* bottom);
	int (*type)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self);
	void (*paint)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
	void (*paintWindowFrame)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
	QRectF* (*boundingRect)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self);
	QPainterPath* (*shape)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self);
	void (*initStyleOption)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self, QStyleOption* option);
	QSizeF* (*sizeHint)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self, int which, QSizeF* constraint);
	void (*updateGeometry)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self);
	QVariant* (*itemChange)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, int change, QVariant* value);
	QVariant* (*propertyChange)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, struct miqt_string propertyName, QVariant* value);
	bool (*sceneEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QEvent* event);
	bool (*windowFrameEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QEvent* e);
	int (*windowFrameSectionAt)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self, QPointF* pos);
	bool (*event)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QEvent* event);
	void (*changeEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QEvent* event);
	void (*closeEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QCloseEvent* event);
	void (*focusInEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QFocusEvent* event);
	bool (*focusNextPrevChild)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, bool next);
	void (*focusOutEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QFocusEvent* event);
	void (*hideEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QHideEvent* event);
	void (*moveEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneMoveEvent* event);
	void (*polishEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self);
	void (*resizeEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneResizeEvent* event);
	void (*showEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QShowEvent* event);
	void (*hoverMoveEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneHoverEvent* event);
	void (*hoverLeaveEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneHoverEvent* event);
	void (*grabMouseEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QEvent* event);
	void (*ungrabMouseEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QEvent* event);
	void (*grabKeyboardEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QEvent* event);
	void (*ungrabKeyboardEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QEvent* event);
	bool (*eventFilter)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QObject* watched, QEvent* event);
	void (*timerEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QTimerEvent* event);
	void (*childEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QChildEvent* event);
	void (*customEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QEvent* event);
	void (*connectNotify)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QMetaMethod* signal);
	void (*advance)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, int phase);
	bool (*contains)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self, QPointF* point);
	bool (*collidesWithItem)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self, QGraphicsItem* other, int mode);
	bool (*collidesWithPath)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self, QPainterPath* path, int mode);
	bool (*isObscuredBy)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self, QGraphicsItem* item);
	QPainterPath* (*opaqueArea)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self);
	bool (*sceneEventFilter)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsItem* watched, QEvent* event);
	void (*contextMenuEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneContextMenuEvent* event);
	void (*dragEnterEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneDragDropEvent* event);
	void (*dragLeaveEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneDragDropEvent* event);
	void (*dragMoveEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneDragDropEvent* event);
	void (*dropEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneDragDropEvent* event);
	void (*hoverEnterEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneHoverEvent* event);
	void (*keyPressEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QKeyEvent* event);
	void (*keyReleaseEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QKeyEvent* event);
	void (*mousePressEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneMouseEvent* event);
	void (*mouseMoveEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneMouseEvent* event);
	void (*mouseReleaseEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneMouseEvent* event);
	void (*mouseDoubleClickEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneMouseEvent* event);
	void (*wheelEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QGraphicsSceneWheelEvent* event);
	void (*inputMethodEvent)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, QInputMethodEvent* event);
	QVariant* (*inputMethodQuery)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self, int query);
	bool (*supportsExtension)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self, int extension);
	void (*setExtension)(struct QGraphicsWidget_VTable* vtbl, QGraphicsWidget* self, int extension, QVariant* variant);
	QVariant* (*extension)(struct QGraphicsWidget_VTable* vtbl, const QGraphicsWidget* self, QVariant* variant);
};
QGraphicsWidget* QGraphicsWidget_new(struct QGraphicsWidget_VTable* vtbl);
QGraphicsWidget* QGraphicsWidget_new2(struct QGraphicsWidget_VTable* vtbl, QGraphicsItem* parent);
QGraphicsWidget* QGraphicsWidget_new3(struct QGraphicsWidget_VTable* vtbl, QGraphicsItem* parent, int wFlags);
void QGraphicsWidget_virtbase(QGraphicsWidget* src, QGraphicsObject** outptr_QGraphicsObject, QGraphicsLayoutItem** outptr_QGraphicsLayoutItem);
QMetaObject* QGraphicsWidget_metaObject(const QGraphicsWidget* self);
void* QGraphicsWidget_metacast(QGraphicsWidget* self, const char* param1);
int QGraphicsWidget_metacall(QGraphicsWidget* self, int param1, int param2, void** param3);
struct miqt_string QGraphicsWidget_tr(const char* s);
struct miqt_string QGraphicsWidget_trUtf8(const char* s);
QGraphicsLayout* QGraphicsWidget_layout(const QGraphicsWidget* self);
void QGraphicsWidget_setLayout(QGraphicsWidget* self, QGraphicsLayout* layout);
void QGraphicsWidget_adjustSize(QGraphicsWidget* self);
int QGraphicsWidget_layoutDirection(const QGraphicsWidget* self);
void QGraphicsWidget_setLayoutDirection(QGraphicsWidget* self, int direction);
void QGraphicsWidget_unsetLayoutDirection(QGraphicsWidget* self);
QStyle* QGraphicsWidget_style(const QGraphicsWidget* self);
void QGraphicsWidget_setStyle(QGraphicsWidget* self, QStyle* style);
QFont* QGraphicsWidget_font(const QGraphicsWidget* self);
void QGraphicsWidget_setFont(QGraphicsWidget* self, QFont* font);
QPalette* QGraphicsWidget_palette(const QGraphicsWidget* self);
void QGraphicsWidget_setPalette(QGraphicsWidget* self, QPalette* palette);
bool QGraphicsWidget_autoFillBackground(const QGraphicsWidget* self);
void QGraphicsWidget_setAutoFillBackground(QGraphicsWidget* self, bool enabled);
void QGraphicsWidget_resize(QGraphicsWidget* self, QSizeF* size);
void QGraphicsWidget_resize2(QGraphicsWidget* self, double w, double h);
QSizeF* QGraphicsWidget_size(const QGraphicsWidget* self);
void QGraphicsWidget_setGeometry(QGraphicsWidget* self, QRectF* rect);
void QGraphicsWidget_setGeometry2(QGraphicsWidget* self, double x, double y, double w, double h);
QRectF* QGraphicsWidget_rect(const QGraphicsWidget* self);
void QGraphicsWidget_setContentsMargins(QGraphicsWidget* self, double left, double top, double right, double bottom);
void QGraphicsWidget_setContentsMarginsWithMargins(QGraphicsWidget* self, QMarginsF* margins);
void QGraphicsWidget_getContentsMargins(const QGraphicsWidget* self, double* left, double* top, double* right, double* bottom);
void QGraphicsWidget_setWindowFrameMargins(QGraphicsWidget* self, double left, double top, double right, double bottom);
void QGraphicsWidget_setWindowFrameMarginsWithMargins(QGraphicsWidget* self, QMarginsF* margins);
void QGraphicsWidget_getWindowFrameMargins(const QGraphicsWidget* self, double* left, double* top, double* right, double* bottom);
void QGraphicsWidget_unsetWindowFrameMargins(QGraphicsWidget* self);
QRectF* QGraphicsWidget_windowFrameGeometry(const QGraphicsWidget* self);
QRectF* QGraphicsWidget_windowFrameRect(const QGraphicsWidget* self);
int QGraphicsWidget_windowFlags(const QGraphicsWidget* self);
int QGraphicsWidget_windowType(const QGraphicsWidget* self);
void QGraphicsWidget_setWindowFlags(QGraphicsWidget* self, int wFlags);
bool QGraphicsWidget_isActiveWindow(const QGraphicsWidget* self);
void QGraphicsWidget_setWindowTitle(QGraphicsWidget* self, struct miqt_string title);
struct miqt_string QGraphicsWidget_windowTitle(const QGraphicsWidget* self);
int QGraphicsWidget_focusPolicy(const QGraphicsWidget* self);
void QGraphicsWidget_setFocusPolicy(QGraphicsWidget* self, int policy);
void QGraphicsWidget_setTabOrder(QGraphicsWidget* first, QGraphicsWidget* second);
QGraphicsWidget* QGraphicsWidget_focusWidget(const QGraphicsWidget* self);
int QGraphicsWidget_grabShortcut(QGraphicsWidget* self, QKeySequence* sequence);
void QGraphicsWidget_releaseShortcut(QGraphicsWidget* self, int id);
void QGraphicsWidget_setShortcutEnabled(QGraphicsWidget* self, int id);
void QGraphicsWidget_setShortcutAutoRepeat(QGraphicsWidget* self, int id);
void QGraphicsWidget_addAction(QGraphicsWidget* self, QAction* action);
void QGraphicsWidget_addActions(QGraphicsWidget* self, struct miqt_array /* of QAction* */  actions);
void QGraphicsWidget_insertActions(QGraphicsWidget* self, QAction* before, struct miqt_array /* of QAction* */  actions);
void QGraphicsWidget_insertAction(QGraphicsWidget* self, QAction* before, QAction* action);
void QGraphicsWidget_removeAction(QGraphicsWidget* self, QAction* action);
struct miqt_array /* of QAction* */  QGraphicsWidget_actions(const QGraphicsWidget* self);
void QGraphicsWidget_setAttribute(QGraphicsWidget* self, int attribute);
bool QGraphicsWidget_testAttribute(const QGraphicsWidget* self, int attribute);
int QGraphicsWidget_type(const QGraphicsWidget* self);
void QGraphicsWidget_paint(QGraphicsWidget* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsWidget_paintWindowFrame(QGraphicsWidget* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
QRectF* QGraphicsWidget_boundingRect(const QGraphicsWidget* self);
QPainterPath* QGraphicsWidget_shape(const QGraphicsWidget* self);
void QGraphicsWidget_geometryChanged(QGraphicsWidget* self);
void QGraphicsWidget_connect_geometryChanged(QGraphicsWidget* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QGraphicsWidget_layoutChanged(QGraphicsWidget* self);
void QGraphicsWidget_connect_layoutChanged(QGraphicsWidget* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
bool QGraphicsWidget_close(QGraphicsWidget* self);
void QGraphicsWidget_initStyleOption(const QGraphicsWidget* self, QStyleOption* option);
QSizeF* QGraphicsWidget_sizeHint(const QGraphicsWidget* self, int which, QSizeF* constraint);
void QGraphicsWidget_updateGeometry(QGraphicsWidget* self);
QVariant* QGraphicsWidget_itemChange(QGraphicsWidget* self, int change, QVariant* value);
QVariant* QGraphicsWidget_propertyChange(QGraphicsWidget* self, struct miqt_string propertyName, QVariant* value);
bool QGraphicsWidget_sceneEvent(QGraphicsWidget* self, QEvent* event);
bool QGraphicsWidget_windowFrameEvent(QGraphicsWidget* self, QEvent* e);
int QGraphicsWidget_windowFrameSectionAt(const QGraphicsWidget* self, QPointF* pos);
bool QGraphicsWidget_event(QGraphicsWidget* self, QEvent* event);
void QGraphicsWidget_changeEvent(QGraphicsWidget* self, QEvent* event);
void QGraphicsWidget_closeEvent(QGraphicsWidget* self, QCloseEvent* event);
void QGraphicsWidget_focusInEvent(QGraphicsWidget* self, QFocusEvent* event);
bool QGraphicsWidget_focusNextPrevChild(QGraphicsWidget* self, bool next);
void QGraphicsWidget_focusOutEvent(QGraphicsWidget* self, QFocusEvent* event);
void QGraphicsWidget_hideEvent(QGraphicsWidget* self, QHideEvent* event);
void QGraphicsWidget_moveEvent(QGraphicsWidget* self, QGraphicsSceneMoveEvent* event);
void QGraphicsWidget_polishEvent(QGraphicsWidget* self);
void QGraphicsWidget_resizeEvent(QGraphicsWidget* self, QGraphicsSceneResizeEvent* event);
void QGraphicsWidget_showEvent(QGraphicsWidget* self, QShowEvent* event);
void QGraphicsWidget_hoverMoveEvent(QGraphicsWidget* self, QGraphicsSceneHoverEvent* event);
void QGraphicsWidget_hoverLeaveEvent(QGraphicsWidget* self, QGraphicsSceneHoverEvent* event);
void QGraphicsWidget_grabMouseEvent(QGraphicsWidget* self, QEvent* event);
void QGraphicsWidget_ungrabMouseEvent(QGraphicsWidget* self, QEvent* event);
void QGraphicsWidget_grabKeyboardEvent(QGraphicsWidget* self, QEvent* event);
void QGraphicsWidget_ungrabKeyboardEvent(QGraphicsWidget* self, QEvent* event);
struct miqt_string QGraphicsWidget_tr2(const char* s, const char* c);
struct miqt_string QGraphicsWidget_tr3(const char* s, const char* c, int n);
struct miqt_string QGraphicsWidget_trUtf82(const char* s, const char* c);
struct miqt_string QGraphicsWidget_trUtf83(const char* s, const char* c, int n);
int QGraphicsWidget_grabShortcut2(QGraphicsWidget* self, QKeySequence* sequence, int context);
void QGraphicsWidget_setShortcutEnabled2(QGraphicsWidget* self, int id, bool enabled);
void QGraphicsWidget_setShortcutAutoRepeat2(QGraphicsWidget* self, int id, bool enabled);
void QGraphicsWidget_setAttribute2(QGraphicsWidget* self, int attribute, bool on);
QMetaObject* QGraphicsWidget_virtualbase_metaObject(const void* self);
void* QGraphicsWidget_virtualbase_metacast(void* self, const char* param1);
int QGraphicsWidget_virtualbase_metacall(void* self, int param1, int param2, void** param3);
void QGraphicsWidget_virtualbase_setGeometry(void* self, QRectF* rect);
void QGraphicsWidget_virtualbase_getContentsMargins(const void* self, double* left, double* top, double* right, double* bottom);
int QGraphicsWidget_virtualbase_type(const void* self);
void QGraphicsWidget_virtualbase_paint(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsWidget_virtualbase_paintWindowFrame(void* self, QPainter* painter, QStyleOptionGraphicsItem* option, QWidget* widget);
QRectF* QGraphicsWidget_virtualbase_boundingRect(const void* self);
QPainterPath* QGraphicsWidget_virtualbase_shape(const void* self);
void QGraphicsWidget_virtualbase_initStyleOption(const void* self, QStyleOption* option);
QSizeF* QGraphicsWidget_virtualbase_sizeHint(const void* self, int which, QSizeF* constraint);
void QGraphicsWidget_virtualbase_updateGeometry(void* self);
QVariant* QGraphicsWidget_virtualbase_itemChange(void* self, int change, QVariant* value);
QVariant* QGraphicsWidget_virtualbase_propertyChange(void* self, struct miqt_string propertyName, QVariant* value);
bool QGraphicsWidget_virtualbase_sceneEvent(void* self, QEvent* event);
bool QGraphicsWidget_virtualbase_windowFrameEvent(void* self, QEvent* e);
int QGraphicsWidget_virtualbase_windowFrameSectionAt(const void* self, QPointF* pos);
bool QGraphicsWidget_virtualbase_event(void* self, QEvent* event);
void QGraphicsWidget_virtualbase_changeEvent(void* self, QEvent* event);
void QGraphicsWidget_virtualbase_closeEvent(void* self, QCloseEvent* event);
void QGraphicsWidget_virtualbase_focusInEvent(void* self, QFocusEvent* event);
bool QGraphicsWidget_virtualbase_focusNextPrevChild(void* self, bool next);
void QGraphicsWidget_virtualbase_focusOutEvent(void* self, QFocusEvent* event);
void QGraphicsWidget_virtualbase_hideEvent(void* self, QHideEvent* event);
void QGraphicsWidget_virtualbase_moveEvent(void* self, QGraphicsSceneMoveEvent* event);
void QGraphicsWidget_virtualbase_polishEvent(void* self);
void QGraphicsWidget_virtualbase_resizeEvent(void* self, QGraphicsSceneResizeEvent* event);
void QGraphicsWidget_virtualbase_showEvent(void* self, QShowEvent* event);
void QGraphicsWidget_virtualbase_hoverMoveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsWidget_virtualbase_hoverLeaveEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsWidget_virtualbase_grabMouseEvent(void* self, QEvent* event);
void QGraphicsWidget_virtualbase_ungrabMouseEvent(void* self, QEvent* event);
void QGraphicsWidget_virtualbase_grabKeyboardEvent(void* self, QEvent* event);
void QGraphicsWidget_virtualbase_ungrabKeyboardEvent(void* self, QEvent* event);
bool QGraphicsWidget_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
void QGraphicsWidget_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QGraphicsWidget_virtualbase_childEvent(void* self, QChildEvent* event);
void QGraphicsWidget_virtualbase_customEvent(void* self, QEvent* event);
void QGraphicsWidget_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QGraphicsWidget_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
void QGraphicsWidget_virtualbase_advance(void* self, int phase);
bool QGraphicsWidget_virtualbase_contains(const void* self, QPointF* point);
bool QGraphicsWidget_virtualbase_collidesWithItem(const void* self, QGraphicsItem* other, int mode);
bool QGraphicsWidget_virtualbase_collidesWithPath(const void* self, QPainterPath* path, int mode);
bool QGraphicsWidget_virtualbase_isObscuredBy(const void* self, QGraphicsItem* item);
QPainterPath* QGraphicsWidget_virtualbase_opaqueArea(const void* self);
bool QGraphicsWidget_virtualbase_sceneEventFilter(void* self, QGraphicsItem* watched, QEvent* event);
void QGraphicsWidget_virtualbase_contextMenuEvent(void* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsWidget_virtualbase_dragEnterEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsWidget_virtualbase_dragLeaveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsWidget_virtualbase_dragMoveEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsWidget_virtualbase_dropEvent(void* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsWidget_virtualbase_hoverEnterEvent(void* self, QGraphicsSceneHoverEvent* event);
void QGraphicsWidget_virtualbase_keyPressEvent(void* self, QKeyEvent* event);
void QGraphicsWidget_virtualbase_keyReleaseEvent(void* self, QKeyEvent* event);
void QGraphicsWidget_virtualbase_mousePressEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsWidget_virtualbase_mouseMoveEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsWidget_virtualbase_mouseReleaseEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsWidget_virtualbase_mouseDoubleClickEvent(void* self, QGraphicsSceneMouseEvent* event);
void QGraphicsWidget_virtualbase_wheelEvent(void* self, QGraphicsSceneWheelEvent* event);
void QGraphicsWidget_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* event);
QVariant* QGraphicsWidget_virtualbase_inputMethodQuery(const void* self, int query);
bool QGraphicsWidget_virtualbase_supportsExtension(const void* self, int extension);
void QGraphicsWidget_virtualbase_setExtension(void* self, int extension, QVariant* variant);
QVariant* QGraphicsWidget_virtualbase_extension(const void* self, QVariant* variant);
void QGraphicsWidget_protectedbase_updateMicroFocus(bool* _dynamic_cast_ok, void* self);
QObject* QGraphicsWidget_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QGraphicsWidget_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QGraphicsWidget_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QGraphicsWidget_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
void QGraphicsWidget_protectedbase_addToIndex(bool* _dynamic_cast_ok, void* self);
void QGraphicsWidget_protectedbase_removeFromIndex(bool* _dynamic_cast_ok, void* self);
void QGraphicsWidget_protectedbase_prepareGeometryChange(bool* _dynamic_cast_ok, void* self);
void QGraphicsWidget_protectedbase_setGraphicsItem(bool* _dynamic_cast_ok, void* self, QGraphicsItem* item);
void QGraphicsWidget_protectedbase_setOwnedByLayout(bool* _dynamic_cast_ok, void* self, bool ownedByLayout);
const QMetaObject* QGraphicsWidget_staticMetaObject();
void QGraphicsWidget_delete(QGraphicsWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
