#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QPLAINTEXTEDIT_H
#define SEAQT_QTWIDGETS_GEN_QPLAINTEXTEDIT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt-runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractScrollArea;
class QAbstractTextDocumentLayout;
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QAbstractTextDocumentLayout__PaintContext)
typedef QAbstractTextDocumentLayout::PaintContext QAbstractTextDocumentLayout__PaintContext;
#else
class QAbstractTextDocumentLayout__PaintContext;
#endif
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEnterEvent;
class QEvent;
class QFocusEvent;
class QFrame;
class QHideEvent;
class QInputMethodEvent;
class QKeyEvent;
class QMargins;
class QMenu;
class QMetaMethod;
class QMetaObject;
class QMimeData;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPagedPaintDevice;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPlainTextDocumentLayout;
class QPlainTextEdit;
class QPoint;
class QPointF;
class QRect;
class QRectF;
class QRegularExpression;
class QResizeEvent;
class QShowEvent;
class QSize;
class QSizeF;
class QStyleOptionFrame;
class QTabletEvent;
class QTextBlock;
class QTextCharFormat;
class QTextCursor;
class QTextDocument;
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QTextEdit__ExtraSelection)
typedef QTextEdit::ExtraSelection QTextEdit__ExtraSelection;
#else
class QTextEdit__ExtraSelection;
#endif
class QTextFormat;
class QTextFrame;
class QTextInlineObject;
class QTimerEvent;
class QUrl;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QAbstractTextDocumentLayout QAbstractTextDocumentLayout;
typedef struct QAbstractTextDocumentLayout__PaintContext QAbstractTextDocumentLayout__PaintContext;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMenu QMenu;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPagedPaintDevice QPagedPaintDevice;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPlainTextDocumentLayout QPlainTextDocumentLayout;
typedef struct QPlainTextEdit QPlainTextEdit;
typedef struct QPoint QPoint;
typedef struct QPointF QPointF;
typedef struct QRect QRect;
typedef struct QRectF QRectF;
typedef struct QRegularExpression QRegularExpression;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QSizeF QSizeF;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTextBlock QTextBlock;
typedef struct QTextCharFormat QTextCharFormat;
typedef struct QTextCursor QTextCursor;
typedef struct QTextDocument QTextDocument;
typedef struct QTextEdit__ExtraSelection QTextEdit__ExtraSelection;
typedef struct QTextFormat QTextFormat;
typedef struct QTextFrame QTextFrame;
typedef struct QTextInlineObject QTextInlineObject;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

typedef struct VirtualQPlainTextEdit VirtualQPlainTextEdit;
typedef struct QPlainTextEdit_VTable{
	void (*destructor)(VirtualQPlainTextEdit* self);
	QMetaObject* (*metaObject)(const VirtualQPlainTextEdit* self);
	void* (*metacast)(VirtualQPlainTextEdit* self, const char* param1);
	int (*metacall)(VirtualQPlainTextEdit* self, int param1, int param2, void** param3);
	QVariant* (*loadResource)(VirtualQPlainTextEdit* self, int type, QUrl* name);
	QVariant* (*inputMethodQuery_property)(const VirtualQPlainTextEdit* self, int property);
	bool (*event)(VirtualQPlainTextEdit* self, QEvent* e);
	void (*timerEvent)(VirtualQPlainTextEdit* self, QTimerEvent* e);
	void (*keyPressEvent)(VirtualQPlainTextEdit* self, QKeyEvent* e);
	void (*keyReleaseEvent)(VirtualQPlainTextEdit* self, QKeyEvent* e);
	void (*resizeEvent)(VirtualQPlainTextEdit* self, QResizeEvent* e);
	void (*paintEvent)(VirtualQPlainTextEdit* self, QPaintEvent* e);
	void (*mousePressEvent)(VirtualQPlainTextEdit* self, QMouseEvent* e);
	void (*mouseMoveEvent)(VirtualQPlainTextEdit* self, QMouseEvent* e);
	void (*mouseReleaseEvent)(VirtualQPlainTextEdit* self, QMouseEvent* e);
	void (*mouseDoubleClickEvent)(VirtualQPlainTextEdit* self, QMouseEvent* e);
	bool (*focusNextPrevChild)(VirtualQPlainTextEdit* self, bool next);
	void (*contextMenuEvent)(VirtualQPlainTextEdit* self, QContextMenuEvent* e);
	void (*dragEnterEvent)(VirtualQPlainTextEdit* self, QDragEnterEvent* e);
	void (*dragLeaveEvent)(VirtualQPlainTextEdit* self, QDragLeaveEvent* e);
	void (*dragMoveEvent)(VirtualQPlainTextEdit* self, QDragMoveEvent* e);
	void (*dropEvent)(VirtualQPlainTextEdit* self, QDropEvent* e);
	void (*focusInEvent)(VirtualQPlainTextEdit* self, QFocusEvent* e);
	void (*focusOutEvent)(VirtualQPlainTextEdit* self, QFocusEvent* e);
	void (*showEvent)(VirtualQPlainTextEdit* self, QShowEvent* param1);
	void (*changeEvent)(VirtualQPlainTextEdit* self, QEvent* e);
	void (*wheelEvent)(VirtualQPlainTextEdit* self, QWheelEvent* e);
	QMimeData* (*createMimeDataFromSelection)(const VirtualQPlainTextEdit* self);
	bool (*canInsertFromMimeData)(const VirtualQPlainTextEdit* self, QMimeData* source);
	void (*insertFromMimeData)(VirtualQPlainTextEdit* self, QMimeData* source);
	void (*inputMethodEvent)(VirtualQPlainTextEdit* self, QInputMethodEvent* param1);
	void (*scrollContentsBy)(VirtualQPlainTextEdit* self, int dx, int dy);
	void (*doSetTextCursor)(VirtualQPlainTextEdit* self, QTextCursor* cursor);
	QSize* (*minimumSizeHint)(const VirtualQPlainTextEdit* self);
	QSize* (*sizeHint)(const VirtualQPlainTextEdit* self);
	void (*setupViewport)(VirtualQPlainTextEdit* self, QWidget* viewport);
	bool (*eventFilter)(VirtualQPlainTextEdit* self, QObject* param1, QEvent* param2);
	bool (*viewportEvent)(VirtualQPlainTextEdit* self, QEvent* param1);
	QSize* (*viewportSizeHint)(const VirtualQPlainTextEdit* self);
	void (*initStyleOption)(const VirtualQPlainTextEdit* self, QStyleOptionFrame* option);
	int (*devType)(const VirtualQPlainTextEdit* self);
	void (*setVisible)(VirtualQPlainTextEdit* self, bool visible);
	int (*heightForWidth)(const VirtualQPlainTextEdit* self, int param1);
	bool (*hasHeightForWidth)(const VirtualQPlainTextEdit* self);
	QPaintEngine* (*paintEngine)(const VirtualQPlainTextEdit* self);
	void (*enterEvent)(VirtualQPlainTextEdit* self, QEnterEvent* event);
	void (*leaveEvent)(VirtualQPlainTextEdit* self, QEvent* event);
	void (*moveEvent)(VirtualQPlainTextEdit* self, QMoveEvent* event);
	void (*closeEvent)(VirtualQPlainTextEdit* self, QCloseEvent* event);
	void (*tabletEvent)(VirtualQPlainTextEdit* self, QTabletEvent* event);
	void (*actionEvent)(VirtualQPlainTextEdit* self, QActionEvent* event);
	void (*hideEvent)(VirtualQPlainTextEdit* self, QHideEvent* event);
	bool (*nativeEvent)(VirtualQPlainTextEdit* self, struct seaqt_string eventType, void* message, intptr_t* result);
	int (*metric)(const VirtualQPlainTextEdit* self, int param1);
	void (*initPainter)(const VirtualQPlainTextEdit* self, QPainter* painter);
	QPaintDevice* (*redirected)(const VirtualQPlainTextEdit* self, QPoint* offset);
	QPainter* (*sharedPainter)(const VirtualQPlainTextEdit* self);
	void (*childEvent)(VirtualQPlainTextEdit* self, QChildEvent* event);
	void (*customEvent)(VirtualQPlainTextEdit* self, QEvent* event);
	void (*connectNotify)(VirtualQPlainTextEdit* self, QMetaMethod* signal);
	void (*disconnectNotify)(VirtualQPlainTextEdit* self, QMetaMethod* signal);
}QPlainTextEdit_VTable;

void* QPlainTextEdit_vdata(VirtualQPlainTextEdit* self);
VirtualQPlainTextEdit* vdata_QPlainTextEdit(void* vdata);

VirtualQPlainTextEdit* QPlainTextEdit_new_parent(const QPlainTextEdit_VTable* vtbl, size_t vdata, QWidget* parent);
VirtualQPlainTextEdit* QPlainTextEdit_new(const QPlainTextEdit_VTable* vtbl, size_t vdata);
VirtualQPlainTextEdit* QPlainTextEdit_new_text(const QPlainTextEdit_VTable* vtbl, size_t vdata, struct seaqt_string text);
VirtualQPlainTextEdit* QPlainTextEdit_new_text_parent(const QPlainTextEdit_VTable* vtbl, size_t vdata, struct seaqt_string text, QWidget* parent);

void QPlainTextEdit_virtbase(QPlainTextEdit* src, QAbstractScrollArea** outptr_QAbstractScrollArea);
QMetaObject* QPlainTextEdit_metaObject(const QPlainTextEdit* self);
void* QPlainTextEdit_metacast(QPlainTextEdit* self, const char* param1);
int QPlainTextEdit_metacall(QPlainTextEdit* self, int param1, int param2, void** param3);
struct seaqt_string QPlainTextEdit_tr_s(const char* s);
void QPlainTextEdit_setDocument(QPlainTextEdit* self, QTextDocument* document);
QTextDocument* QPlainTextEdit_document(const QPlainTextEdit* self);
void QPlainTextEdit_setPlaceholderText(QPlainTextEdit* self, struct seaqt_string placeholderText);
struct seaqt_string QPlainTextEdit_placeholderText(const QPlainTextEdit* self);
void QPlainTextEdit_setTextCursor(QPlainTextEdit* self, QTextCursor* cursor);
QTextCursor* QPlainTextEdit_textCursor(const QPlainTextEdit* self);
bool QPlainTextEdit_isReadOnly(const QPlainTextEdit* self);
void QPlainTextEdit_setReadOnly(QPlainTextEdit* self, bool ro);
void QPlainTextEdit_setTextInteractionFlags(QPlainTextEdit* self, int flags);
int QPlainTextEdit_textInteractionFlags(const QPlainTextEdit* self);
void QPlainTextEdit_mergeCurrentCharFormat(QPlainTextEdit* self, QTextCharFormat* modifier);
void QPlainTextEdit_setCurrentCharFormat(QPlainTextEdit* self, QTextCharFormat* format);
QTextCharFormat* QPlainTextEdit_currentCharFormat(const QPlainTextEdit* self);
bool QPlainTextEdit_tabChangesFocus(const QPlainTextEdit* self);
void QPlainTextEdit_setTabChangesFocus(QPlainTextEdit* self, bool b);
void QPlainTextEdit_setDocumentTitle(QPlainTextEdit* self, struct seaqt_string title);
struct seaqt_string QPlainTextEdit_documentTitle(const QPlainTextEdit* self);
bool QPlainTextEdit_isUndoRedoEnabled(const QPlainTextEdit* self);
void QPlainTextEdit_setUndoRedoEnabled(QPlainTextEdit* self, bool enable);
void QPlainTextEdit_setMaximumBlockCount(QPlainTextEdit* self, int maximum);
int QPlainTextEdit_maximumBlockCount(const QPlainTextEdit* self);
int QPlainTextEdit_lineWrapMode(const QPlainTextEdit* self);
void QPlainTextEdit_setLineWrapMode(QPlainTextEdit* self, int mode);
int QPlainTextEdit_wordWrapMode(const QPlainTextEdit* self);
void QPlainTextEdit_setWordWrapMode(QPlainTextEdit* self, int policy);
void QPlainTextEdit_setBackgroundVisible(QPlainTextEdit* self, bool visible);
bool QPlainTextEdit_backgroundVisible(const QPlainTextEdit* self);
void QPlainTextEdit_setCenterOnScroll(QPlainTextEdit* self, bool enabled);
bool QPlainTextEdit_centerOnScroll(const QPlainTextEdit* self);
bool QPlainTextEdit_find_QString(QPlainTextEdit* self, struct seaqt_string exp);
bool QPlainTextEdit_find_QRegularExpression(QPlainTextEdit* self, QRegularExpression* exp);
struct seaqt_string QPlainTextEdit_toPlainText(const QPlainTextEdit* self);
void QPlainTextEdit_ensureCursorVisible(QPlainTextEdit* self);
QVariant* QPlainTextEdit_loadResource(QPlainTextEdit* self, int type, QUrl* name);
QMenu* QPlainTextEdit_createStandardContextMenu(QPlainTextEdit* self);
QMenu* QPlainTextEdit_createStandardContextMenu_position(QPlainTextEdit* self, QPoint* position);
QTextCursor* QPlainTextEdit_cursorForPosition(const QPlainTextEdit* self, QPoint* pos);
QRect* QPlainTextEdit_cursorRect_cursor(const QPlainTextEdit* self, QTextCursor* cursor);
QRect* QPlainTextEdit_cursorRect(const QPlainTextEdit* self);
struct seaqt_string QPlainTextEdit_anchorAt(const QPlainTextEdit* self, QPoint* pos);
bool QPlainTextEdit_overwriteMode(const QPlainTextEdit* self);
void QPlainTextEdit_setOverwriteMode(QPlainTextEdit* self, bool overwrite);
double QPlainTextEdit_tabStopDistance(const QPlainTextEdit* self);
void QPlainTextEdit_setTabStopDistance(QPlainTextEdit* self, double distance);
int QPlainTextEdit_cursorWidth(const QPlainTextEdit* self);
void QPlainTextEdit_setCursorWidth(QPlainTextEdit* self, int width);
void QPlainTextEdit_setExtraSelections(QPlainTextEdit* self, struct seaqt_array /* of QTextEdit__ExtraSelection* */  selections);
struct seaqt_array /* of QTextEdit__ExtraSelection* */  QPlainTextEdit_extraSelections(const QPlainTextEdit* self);
void QPlainTextEdit_moveCursor_operation(QPlainTextEdit* self, int operation);
bool QPlainTextEdit_canPaste(const QPlainTextEdit* self);
void QPlainTextEdit_print(const QPlainTextEdit* self, QPagedPaintDevice* printer);
int QPlainTextEdit_blockCount(const QPlainTextEdit* self);
QVariant* QPlainTextEdit_inputMethodQuery_property(const QPlainTextEdit* self, int property);
QVariant* QPlainTextEdit_inputMethodQuery_query_argument(const QPlainTextEdit* self, int query, QVariant* argument);
void QPlainTextEdit_setPlainText(QPlainTextEdit* self, struct seaqt_string text);
void QPlainTextEdit_cut(QPlainTextEdit* self);
void QPlainTextEdit_copy(QPlainTextEdit* self);
void QPlainTextEdit_paste(QPlainTextEdit* self);
void QPlainTextEdit_undo(QPlainTextEdit* self);
void QPlainTextEdit_redo(QPlainTextEdit* self);
void QPlainTextEdit_clear(QPlainTextEdit* self);
void QPlainTextEdit_selectAll(QPlainTextEdit* self);
void QPlainTextEdit_insertPlainText(QPlainTextEdit* self, struct seaqt_string text);
void QPlainTextEdit_appendPlainText(QPlainTextEdit* self, struct seaqt_string text);
void QPlainTextEdit_appendHtml(QPlainTextEdit* self, struct seaqt_string html);
void QPlainTextEdit_centerCursor(QPlainTextEdit* self);
void QPlainTextEdit_zoomIn(QPlainTextEdit* self);
void QPlainTextEdit_zoomOut(QPlainTextEdit* self);
void QPlainTextEdit_textChanged(QPlainTextEdit* self);
void QPlainTextEdit_connect_textChanged(QPlainTextEdit* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QPlainTextEdit_undoAvailable(QPlainTextEdit* self, bool b);
void QPlainTextEdit_connect_undoAvailable(QPlainTextEdit* self, intptr_t slot, void (*callback)(intptr_t, bool), void (*release)(intptr_t));
void QPlainTextEdit_redoAvailable(QPlainTextEdit* self, bool b);
void QPlainTextEdit_connect_redoAvailable(QPlainTextEdit* self, intptr_t slot, void (*callback)(intptr_t, bool), void (*release)(intptr_t));
void QPlainTextEdit_copyAvailable(QPlainTextEdit* self, bool b);
void QPlainTextEdit_connect_copyAvailable(QPlainTextEdit* self, intptr_t slot, void (*callback)(intptr_t, bool), void (*release)(intptr_t));
void QPlainTextEdit_selectionChanged(QPlainTextEdit* self);
void QPlainTextEdit_connect_selectionChanged(QPlainTextEdit* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QPlainTextEdit_cursorPositionChanged(QPlainTextEdit* self);
void QPlainTextEdit_connect_cursorPositionChanged(QPlainTextEdit* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QPlainTextEdit_updateRequest(QPlainTextEdit* self, QRect* rect, int dy);
void QPlainTextEdit_connect_updateRequest(QPlainTextEdit* self, intptr_t slot, void (*callback)(intptr_t, QRect*, int), void (*release)(intptr_t));
void QPlainTextEdit_blockCountChanged(QPlainTextEdit* self, int newBlockCount);
void QPlainTextEdit_connect_blockCountChanged(QPlainTextEdit* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QPlainTextEdit_modificationChanged(QPlainTextEdit* self, bool param1);
void QPlainTextEdit_connect_modificationChanged(QPlainTextEdit* self, intptr_t slot, void (*callback)(intptr_t, bool), void (*release)(intptr_t));
bool QPlainTextEdit_event(QPlainTextEdit* self, QEvent* e);
void QPlainTextEdit_timerEvent(QPlainTextEdit* self, QTimerEvent* e);
void QPlainTextEdit_keyPressEvent(QPlainTextEdit* self, QKeyEvent* e);
void QPlainTextEdit_keyReleaseEvent(QPlainTextEdit* self, QKeyEvent* e);
void QPlainTextEdit_resizeEvent(QPlainTextEdit* self, QResizeEvent* e);
void QPlainTextEdit_paintEvent(QPlainTextEdit* self, QPaintEvent* e);
void QPlainTextEdit_mousePressEvent(QPlainTextEdit* self, QMouseEvent* e);
void QPlainTextEdit_mouseMoveEvent(QPlainTextEdit* self, QMouseEvent* e);
void QPlainTextEdit_mouseReleaseEvent(QPlainTextEdit* self, QMouseEvent* e);
void QPlainTextEdit_mouseDoubleClickEvent(QPlainTextEdit* self, QMouseEvent* e);
bool QPlainTextEdit_focusNextPrevChild(QPlainTextEdit* self, bool next);
void QPlainTextEdit_contextMenuEvent(QPlainTextEdit* self, QContextMenuEvent* e);
void QPlainTextEdit_dragEnterEvent(QPlainTextEdit* self, QDragEnterEvent* e);
void QPlainTextEdit_dragLeaveEvent(QPlainTextEdit* self, QDragLeaveEvent* e);
void QPlainTextEdit_dragMoveEvent(QPlainTextEdit* self, QDragMoveEvent* e);
void QPlainTextEdit_dropEvent(QPlainTextEdit* self, QDropEvent* e);
void QPlainTextEdit_focusInEvent(QPlainTextEdit* self, QFocusEvent* e);
void QPlainTextEdit_focusOutEvent(QPlainTextEdit* self, QFocusEvent* e);
void QPlainTextEdit_showEvent(QPlainTextEdit* self, QShowEvent* param1);
void QPlainTextEdit_changeEvent(QPlainTextEdit* self, QEvent* e);
void QPlainTextEdit_wheelEvent(QPlainTextEdit* self, QWheelEvent* e);
QMimeData* QPlainTextEdit_createMimeDataFromSelection(const QPlainTextEdit* self);
bool QPlainTextEdit_canInsertFromMimeData(const QPlainTextEdit* self, QMimeData* source);
void QPlainTextEdit_insertFromMimeData(QPlainTextEdit* self, QMimeData* source);
void QPlainTextEdit_inputMethodEvent(QPlainTextEdit* self, QInputMethodEvent* param1);
void QPlainTextEdit_scrollContentsBy(QPlainTextEdit* self, int dx, int dy);
void QPlainTextEdit_doSetTextCursor(QPlainTextEdit* self, QTextCursor* cursor);
struct seaqt_string QPlainTextEdit_tr_s_c(const char* s, const char* c);
struct seaqt_string QPlainTextEdit_tr_s_c_n(const char* s, const char* c, int n);
bool QPlainTextEdit_find_QString_QTextDocument_FindFlags(QPlainTextEdit* self, struct seaqt_string exp, int options);
bool QPlainTextEdit_find_QRegularExpression_QTextDocument_FindFlags(QPlainTextEdit* self, QRegularExpression* exp, int options);
void QPlainTextEdit_moveCursor_operation_mode(QPlainTextEdit* self, int operation, int mode);
void QPlainTextEdit_zoomIn_range(QPlainTextEdit* self, int range);
void QPlainTextEdit_zoomOut_range(QPlainTextEdit* self, int range);

QMetaObject* QPlainTextEdit_virtualbase_metaObject(const VirtualQPlainTextEdit* self);
void* QPlainTextEdit_virtualbase_metacast(VirtualQPlainTextEdit* self, const char* param1);
int QPlainTextEdit_virtualbase_metacall(VirtualQPlainTextEdit* self, int param1, int param2, void** param3);
QVariant* QPlainTextEdit_virtualbase_loadResource(VirtualQPlainTextEdit* self, int type, QUrl* name);
QVariant* QPlainTextEdit_virtualbase_inputMethodQuery_property(const VirtualQPlainTextEdit* self, int property);
bool QPlainTextEdit_virtualbase_event(VirtualQPlainTextEdit* self, QEvent* e);
void QPlainTextEdit_virtualbase_timerEvent(VirtualQPlainTextEdit* self, QTimerEvent* e);
void QPlainTextEdit_virtualbase_keyPressEvent(VirtualQPlainTextEdit* self, QKeyEvent* e);
void QPlainTextEdit_virtualbase_keyReleaseEvent(VirtualQPlainTextEdit* self, QKeyEvent* e);
void QPlainTextEdit_virtualbase_resizeEvent(VirtualQPlainTextEdit* self, QResizeEvent* e);
void QPlainTextEdit_virtualbase_paintEvent(VirtualQPlainTextEdit* self, QPaintEvent* e);
void QPlainTextEdit_virtualbase_mousePressEvent(VirtualQPlainTextEdit* self, QMouseEvent* e);
void QPlainTextEdit_virtualbase_mouseMoveEvent(VirtualQPlainTextEdit* self, QMouseEvent* e);
void QPlainTextEdit_virtualbase_mouseReleaseEvent(VirtualQPlainTextEdit* self, QMouseEvent* e);
void QPlainTextEdit_virtualbase_mouseDoubleClickEvent(VirtualQPlainTextEdit* self, QMouseEvent* e);
bool QPlainTextEdit_virtualbase_focusNextPrevChild(VirtualQPlainTextEdit* self, bool next);
void QPlainTextEdit_virtualbase_contextMenuEvent(VirtualQPlainTextEdit* self, QContextMenuEvent* e);
void QPlainTextEdit_virtualbase_dragEnterEvent(VirtualQPlainTextEdit* self, QDragEnterEvent* e);
void QPlainTextEdit_virtualbase_dragLeaveEvent(VirtualQPlainTextEdit* self, QDragLeaveEvent* e);
void QPlainTextEdit_virtualbase_dragMoveEvent(VirtualQPlainTextEdit* self, QDragMoveEvent* e);
void QPlainTextEdit_virtualbase_dropEvent(VirtualQPlainTextEdit* self, QDropEvent* e);
void QPlainTextEdit_virtualbase_focusInEvent(VirtualQPlainTextEdit* self, QFocusEvent* e);
void QPlainTextEdit_virtualbase_focusOutEvent(VirtualQPlainTextEdit* self, QFocusEvent* e);
void QPlainTextEdit_virtualbase_showEvent(VirtualQPlainTextEdit* self, QShowEvent* param1);
void QPlainTextEdit_virtualbase_changeEvent(VirtualQPlainTextEdit* self, QEvent* e);
void QPlainTextEdit_virtualbase_wheelEvent(VirtualQPlainTextEdit* self, QWheelEvent* e);
QMimeData* QPlainTextEdit_virtualbase_createMimeDataFromSelection(const VirtualQPlainTextEdit* self);
bool QPlainTextEdit_virtualbase_canInsertFromMimeData(const VirtualQPlainTextEdit* self, QMimeData* source);
void QPlainTextEdit_virtualbase_insertFromMimeData(VirtualQPlainTextEdit* self, QMimeData* source);
void QPlainTextEdit_virtualbase_inputMethodEvent(VirtualQPlainTextEdit* self, QInputMethodEvent* param1);
void QPlainTextEdit_virtualbase_scrollContentsBy(VirtualQPlainTextEdit* self, int dx, int dy);
void QPlainTextEdit_virtualbase_doSetTextCursor(VirtualQPlainTextEdit* self, QTextCursor* cursor);
QSize* QPlainTextEdit_virtualbase_minimumSizeHint(const VirtualQPlainTextEdit* self);
QSize* QPlainTextEdit_virtualbase_sizeHint(const VirtualQPlainTextEdit* self);
void QPlainTextEdit_virtualbase_setupViewport(VirtualQPlainTextEdit* self, QWidget* viewport);
bool QPlainTextEdit_virtualbase_eventFilter(VirtualQPlainTextEdit* self, QObject* param1, QEvent* param2);
bool QPlainTextEdit_virtualbase_viewportEvent(VirtualQPlainTextEdit* self, QEvent* param1);
QSize* QPlainTextEdit_virtualbase_viewportSizeHint(const VirtualQPlainTextEdit* self);
void QPlainTextEdit_virtualbase_initStyleOption(const VirtualQPlainTextEdit* self, QStyleOptionFrame* option);
int QPlainTextEdit_virtualbase_devType(const VirtualQPlainTextEdit* self);
void QPlainTextEdit_virtualbase_setVisible(VirtualQPlainTextEdit* self, bool visible);
int QPlainTextEdit_virtualbase_heightForWidth(const VirtualQPlainTextEdit* self, int param1);
bool QPlainTextEdit_virtualbase_hasHeightForWidth(const VirtualQPlainTextEdit* self);
QPaintEngine* QPlainTextEdit_virtualbase_paintEngine(const VirtualQPlainTextEdit* self);
void QPlainTextEdit_virtualbase_enterEvent(VirtualQPlainTextEdit* self, QEnterEvent* event);
void QPlainTextEdit_virtualbase_leaveEvent(VirtualQPlainTextEdit* self, QEvent* event);
void QPlainTextEdit_virtualbase_moveEvent(VirtualQPlainTextEdit* self, QMoveEvent* event);
void QPlainTextEdit_virtualbase_closeEvent(VirtualQPlainTextEdit* self, QCloseEvent* event);
void QPlainTextEdit_virtualbase_tabletEvent(VirtualQPlainTextEdit* self, QTabletEvent* event);
void QPlainTextEdit_virtualbase_actionEvent(VirtualQPlainTextEdit* self, QActionEvent* event);
void QPlainTextEdit_virtualbase_hideEvent(VirtualQPlainTextEdit* self, QHideEvent* event);
bool QPlainTextEdit_virtualbase_nativeEvent(VirtualQPlainTextEdit* self, struct seaqt_string eventType, void* message, intptr_t* result);
int QPlainTextEdit_virtualbase_metric(const VirtualQPlainTextEdit* self, int param1);
void QPlainTextEdit_virtualbase_initPainter(const VirtualQPlainTextEdit* self, QPainter* painter);
QPaintDevice* QPlainTextEdit_virtualbase_redirected(const VirtualQPlainTextEdit* self, QPoint* offset);
QPainter* QPlainTextEdit_virtualbase_sharedPainter(const VirtualQPlainTextEdit* self);
void QPlainTextEdit_virtualbase_childEvent(VirtualQPlainTextEdit* self, QChildEvent* event);
void QPlainTextEdit_virtualbase_customEvent(VirtualQPlainTextEdit* self, QEvent* event);
void QPlainTextEdit_virtualbase_connectNotify(VirtualQPlainTextEdit* self, QMetaMethod* signal);
void QPlainTextEdit_virtualbase_disconnectNotify(VirtualQPlainTextEdit* self, QMetaMethod* signal);

QTextBlock* QPlainTextEdit_protectedbase_firstVisibleBlock(const VirtualQPlainTextEdit* self);
QPointF* QPlainTextEdit_protectedbase_contentOffset(const VirtualQPlainTextEdit* self);
QRectF* QPlainTextEdit_protectedbase_blockBoundingRect(const VirtualQPlainTextEdit* self, QTextBlock* block);
QRectF* QPlainTextEdit_protectedbase_blockBoundingGeometry(const VirtualQPlainTextEdit* self, QTextBlock* block);
QAbstractTextDocumentLayout__PaintContext* QPlainTextEdit_protectedbase_getPaintContext(const VirtualQPlainTextEdit* self);
void QPlainTextEdit_protectedbase_zoomInF(VirtualQPlainTextEdit* self, float range);
void QPlainTextEdit_protectedbase_setViewportMargins_left_top_right_bottom(VirtualQPlainTextEdit* self, int left, int top, int right, int bottom);
QMargins* QPlainTextEdit_protectedbase_viewportMargins(const VirtualQPlainTextEdit* self);
void QPlainTextEdit_protectedbase_drawFrame(VirtualQPlainTextEdit* self, QPainter* param1);
void QPlainTextEdit_protectedbase_updateMicroFocus(VirtualQPlainTextEdit* self);
void QPlainTextEdit_protectedbase_create(VirtualQPlainTextEdit* self);
void QPlainTextEdit_protectedbase_destroy(VirtualQPlainTextEdit* self);
bool QPlainTextEdit_protectedbase_focusNextChild(VirtualQPlainTextEdit* self);
bool QPlainTextEdit_protectedbase_focusPreviousChild(VirtualQPlainTextEdit* self);
QObject* QPlainTextEdit_protectedbase_sender(const VirtualQPlainTextEdit* self);
int QPlainTextEdit_protectedbase_senderSignalIndex(const VirtualQPlainTextEdit* self);
int QPlainTextEdit_protectedbase_receivers(const VirtualQPlainTextEdit* self, const char* signal);
bool QPlainTextEdit_protectedbase_isSignalConnected(const VirtualQPlainTextEdit* self, QMetaMethod* signal);

const QMetaObject* QPlainTextEdit_staticMetaObject();
void QPlainTextEdit_delete(QPlainTextEdit* self);

typedef struct VirtualQPlainTextDocumentLayout VirtualQPlainTextDocumentLayout;
typedef struct QPlainTextDocumentLayout_VTable{
	void (*destructor)(VirtualQPlainTextDocumentLayout* self);
	QMetaObject* (*metaObject)(const VirtualQPlainTextDocumentLayout* self);
	void* (*metacast)(VirtualQPlainTextDocumentLayout* self, const char* param1);
	int (*metacall)(VirtualQPlainTextDocumentLayout* self, int param1, int param2, void** param3);
	void (*draw)(VirtualQPlainTextDocumentLayout* self, QPainter* param1, QAbstractTextDocumentLayout__PaintContext* param2);
	int (*hitTest)(const VirtualQPlainTextDocumentLayout* self, QPointF* param1, int param2);
	int (*pageCount)(const VirtualQPlainTextDocumentLayout* self);
	QSizeF* (*documentSize)(const VirtualQPlainTextDocumentLayout* self);
	QRectF* (*frameBoundingRect)(const VirtualQPlainTextDocumentLayout* self, QTextFrame* param1);
	QRectF* (*blockBoundingRect)(const VirtualQPlainTextDocumentLayout* self, QTextBlock* block);
	void (*documentChanged)(VirtualQPlainTextDocumentLayout* self, int from, int param2, int charsAdded);
	void (*resizeInlineObject)(VirtualQPlainTextDocumentLayout* self, QTextInlineObject* item, int posInDocument, QTextFormat* format);
	void (*positionInlineObject)(VirtualQPlainTextDocumentLayout* self, QTextInlineObject* item, int posInDocument, QTextFormat* format);
	void (*drawInlineObject)(VirtualQPlainTextDocumentLayout* self, QPainter* painter, QRectF* rect, QTextInlineObject* object, int posInDocument, QTextFormat* format);
	bool (*event)(VirtualQPlainTextDocumentLayout* self, QEvent* event);
	bool (*eventFilter)(VirtualQPlainTextDocumentLayout* self, QObject* watched, QEvent* event);
	void (*timerEvent)(VirtualQPlainTextDocumentLayout* self, QTimerEvent* event);
	void (*childEvent)(VirtualQPlainTextDocumentLayout* self, QChildEvent* event);
	void (*customEvent)(VirtualQPlainTextDocumentLayout* self, QEvent* event);
	void (*connectNotify)(VirtualQPlainTextDocumentLayout* self, QMetaMethod* signal);
	void (*disconnectNotify)(VirtualQPlainTextDocumentLayout* self, QMetaMethod* signal);
}QPlainTextDocumentLayout_VTable;

void* QPlainTextDocumentLayout_vdata(VirtualQPlainTextDocumentLayout* self);
VirtualQPlainTextDocumentLayout* vdata_QPlainTextDocumentLayout(void* vdata);

VirtualQPlainTextDocumentLayout* QPlainTextDocumentLayout_new(const QPlainTextDocumentLayout_VTable* vtbl, size_t vdata, QTextDocument* document);

void QPlainTextDocumentLayout_virtbase(QPlainTextDocumentLayout* src, QAbstractTextDocumentLayout** outptr_QAbstractTextDocumentLayout);
QMetaObject* QPlainTextDocumentLayout_metaObject(const QPlainTextDocumentLayout* self);
void* QPlainTextDocumentLayout_metacast(QPlainTextDocumentLayout* self, const char* param1);
int QPlainTextDocumentLayout_metacall(QPlainTextDocumentLayout* self, int param1, int param2, void** param3);
struct seaqt_string QPlainTextDocumentLayout_tr_s(const char* s);
void QPlainTextDocumentLayout_draw(QPlainTextDocumentLayout* self, QPainter* param1, QAbstractTextDocumentLayout__PaintContext* param2);
int QPlainTextDocumentLayout_hitTest(const QPlainTextDocumentLayout* self, QPointF* param1, int param2);
int QPlainTextDocumentLayout_pageCount(const QPlainTextDocumentLayout* self);
QSizeF* QPlainTextDocumentLayout_documentSize(const QPlainTextDocumentLayout* self);
QRectF* QPlainTextDocumentLayout_frameBoundingRect(const QPlainTextDocumentLayout* self, QTextFrame* param1);
QRectF* QPlainTextDocumentLayout_blockBoundingRect(const QPlainTextDocumentLayout* self, QTextBlock* block);
void QPlainTextDocumentLayout_ensureBlockLayout(const QPlainTextDocumentLayout* self, QTextBlock* block);
void QPlainTextDocumentLayout_setCursorWidth(QPlainTextDocumentLayout* self, int width);
int QPlainTextDocumentLayout_cursorWidth(const QPlainTextDocumentLayout* self);
void QPlainTextDocumentLayout_requestUpdate(QPlainTextDocumentLayout* self);
void QPlainTextDocumentLayout_documentChanged(QPlainTextDocumentLayout* self, int from, int param2, int charsAdded);
struct seaqt_string QPlainTextDocumentLayout_tr_s_c(const char* s, const char* c);
struct seaqt_string QPlainTextDocumentLayout_tr_s_c_n(const char* s, const char* c, int n);

QMetaObject* QPlainTextDocumentLayout_virtualbase_metaObject(const VirtualQPlainTextDocumentLayout* self);
void* QPlainTextDocumentLayout_virtualbase_metacast(VirtualQPlainTextDocumentLayout* self, const char* param1);
int QPlainTextDocumentLayout_virtualbase_metacall(VirtualQPlainTextDocumentLayout* self, int param1, int param2, void** param3);
void QPlainTextDocumentLayout_virtualbase_draw(VirtualQPlainTextDocumentLayout* self, QPainter* param1, QAbstractTextDocumentLayout__PaintContext* param2);
int QPlainTextDocumentLayout_virtualbase_hitTest(const VirtualQPlainTextDocumentLayout* self, QPointF* param1, int param2);
int QPlainTextDocumentLayout_virtualbase_pageCount(const VirtualQPlainTextDocumentLayout* self);
QSizeF* QPlainTextDocumentLayout_virtualbase_documentSize(const VirtualQPlainTextDocumentLayout* self);
QRectF* QPlainTextDocumentLayout_virtualbase_frameBoundingRect(const VirtualQPlainTextDocumentLayout* self, QTextFrame* param1);
QRectF* QPlainTextDocumentLayout_virtualbase_blockBoundingRect(const VirtualQPlainTextDocumentLayout* self, QTextBlock* block);
void QPlainTextDocumentLayout_virtualbase_documentChanged(VirtualQPlainTextDocumentLayout* self, int from, int param2, int charsAdded);
void QPlainTextDocumentLayout_virtualbase_resizeInlineObject(VirtualQPlainTextDocumentLayout* self, QTextInlineObject* item, int posInDocument, QTextFormat* format);
void QPlainTextDocumentLayout_virtualbase_positionInlineObject(VirtualQPlainTextDocumentLayout* self, QTextInlineObject* item, int posInDocument, QTextFormat* format);
void QPlainTextDocumentLayout_virtualbase_drawInlineObject(VirtualQPlainTextDocumentLayout* self, QPainter* painter, QRectF* rect, QTextInlineObject* object, int posInDocument, QTextFormat* format);
bool QPlainTextDocumentLayout_virtualbase_event(VirtualQPlainTextDocumentLayout* self, QEvent* event);
bool QPlainTextDocumentLayout_virtualbase_eventFilter(VirtualQPlainTextDocumentLayout* self, QObject* watched, QEvent* event);
void QPlainTextDocumentLayout_virtualbase_timerEvent(VirtualQPlainTextDocumentLayout* self, QTimerEvent* event);
void QPlainTextDocumentLayout_virtualbase_childEvent(VirtualQPlainTextDocumentLayout* self, QChildEvent* event);
void QPlainTextDocumentLayout_virtualbase_customEvent(VirtualQPlainTextDocumentLayout* self, QEvent* event);
void QPlainTextDocumentLayout_virtualbase_connectNotify(VirtualQPlainTextDocumentLayout* self, QMetaMethod* signal);
void QPlainTextDocumentLayout_virtualbase_disconnectNotify(VirtualQPlainTextDocumentLayout* self, QMetaMethod* signal);

int QPlainTextDocumentLayout_protectedbase_formatIndex(VirtualQPlainTextDocumentLayout* self, int pos);
QTextCharFormat* QPlainTextDocumentLayout_protectedbase_format(VirtualQPlainTextDocumentLayout* self, int pos);
QObject* QPlainTextDocumentLayout_protectedbase_sender(const VirtualQPlainTextDocumentLayout* self);
int QPlainTextDocumentLayout_protectedbase_senderSignalIndex(const VirtualQPlainTextDocumentLayout* self);
int QPlainTextDocumentLayout_protectedbase_receivers(const VirtualQPlainTextDocumentLayout* self, const char* signal);
bool QPlainTextDocumentLayout_protectedbase_isSignalConnected(const VirtualQPlainTextDocumentLayout* self, QMetaMethod* signal);

const QMetaObject* QPlainTextDocumentLayout_staticMetaObject();
void QPlainTextDocumentLayout_delete(QPlainTextDocumentLayout* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
