#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QSPINBOX_H
#define SEAQT_QTWIDGETS_GEN_QSPINBOX_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt/libseaqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractSpinBox;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDoubleSpinBox;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEnterEvent;
class QEvent;
class QFocusEvent;
class QHideEvent;
class QInputMethodEvent;
class QKeyEvent;
class QLineEdit;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QResizeEvent;
class QShowEvent;
class QSize;
class QSpinBox;
class QStyleOptionSpinBox;
class QTabletEvent;
class QTimerEvent;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractSpinBox QAbstractSpinBox;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDoubleSpinBox QDoubleSpinBox;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QLineEdit QLineEdit;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QSpinBox QSpinBox;
typedef struct QStyleOptionSpinBox QStyleOptionSpinBox;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

struct QSpinBox_VTable {
	void (*destructor)(struct QSpinBox_VTable* vtbl, QSpinBox* self);
	QMetaObject* (*metaObject)(struct QSpinBox_VTable* vtbl, const QSpinBox* self);
	void* (*metacast)(struct QSpinBox_VTable* vtbl, QSpinBox* self, const char* param1);
	int (*metacall)(struct QSpinBox_VTable* vtbl, QSpinBox* self, int param1, int param2, void** param3);
	bool (*event)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QEvent* event);
	int (*validate)(struct QSpinBox_VTable* vtbl, const QSpinBox* self, struct miqt_string input, int* pos);
	int (*valueFromText)(struct QSpinBox_VTable* vtbl, const QSpinBox* self, struct miqt_string text);
	struct miqt_string (*textFromValue)(struct QSpinBox_VTable* vtbl, const QSpinBox* self, int val);
	void (*fixup)(struct QSpinBox_VTable* vtbl, const QSpinBox* self, struct miqt_string str);
	QSize* (*sizeHint)(struct QSpinBox_VTable* vtbl, const QSpinBox* self);
	QSize* (*minimumSizeHint)(struct QSpinBox_VTable* vtbl, const QSpinBox* self);
	QVariant* (*inputMethodQuery)(struct QSpinBox_VTable* vtbl, const QSpinBox* self, int param1);
	void (*stepBy)(struct QSpinBox_VTable* vtbl, QSpinBox* self, int steps);
	void (*clear)(struct QSpinBox_VTable* vtbl, QSpinBox* self);
	void (*resizeEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QResizeEvent* event);
	void (*keyPressEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QKeyEvent* event);
	void (*keyReleaseEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QKeyEvent* event);
	void (*wheelEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QWheelEvent* event);
	void (*focusInEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QFocusEvent* event);
	void (*focusOutEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QFocusEvent* event);
	void (*contextMenuEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QContextMenuEvent* event);
	void (*changeEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QEvent* event);
	void (*closeEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QCloseEvent* event);
	void (*hideEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QHideEvent* event);
	void (*mousePressEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QMouseEvent* event);
	void (*mouseMoveEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QMouseEvent* event);
	void (*timerEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QTimerEvent* event);
	void (*paintEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QPaintEvent* event);
	void (*showEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QShowEvent* event);
	void (*initStyleOption)(struct QSpinBox_VTable* vtbl, const QSpinBox* self, QStyleOptionSpinBox* option);
	int (*stepEnabled)(struct QSpinBox_VTable* vtbl, const QSpinBox* self);
	int (*devType)(struct QSpinBox_VTable* vtbl, const QSpinBox* self);
	void (*setVisible)(struct QSpinBox_VTable* vtbl, QSpinBox* self, bool visible);
	int (*heightForWidth)(struct QSpinBox_VTable* vtbl, const QSpinBox* self, int param1);
	bool (*hasHeightForWidth)(struct QSpinBox_VTable* vtbl, const QSpinBox* self);
	QPaintEngine* (*paintEngine)(struct QSpinBox_VTable* vtbl, const QSpinBox* self);
	void (*mouseDoubleClickEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QMouseEvent* event);
	void (*enterEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QEnterEvent* event);
	void (*leaveEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QEvent* event);
	void (*moveEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QMoveEvent* event);
	void (*tabletEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QTabletEvent* event);
	void (*actionEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QActionEvent* event);
	void (*dragEnterEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QDragEnterEvent* event);
	void (*dragMoveEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QDragMoveEvent* event);
	void (*dragLeaveEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QDragLeaveEvent* event);
	void (*dropEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QDropEvent* event);
	bool (*nativeEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, struct miqt_string eventType, void* message, intptr_t* result);
	int (*metric)(struct QSpinBox_VTable* vtbl, const QSpinBox* self, int param1);
	void (*initPainter)(struct QSpinBox_VTable* vtbl, const QSpinBox* self, QPainter* painter);
	QPaintDevice* (*redirected)(struct QSpinBox_VTable* vtbl, const QSpinBox* self, QPoint* offset);
	QPainter* (*sharedPainter)(struct QSpinBox_VTable* vtbl, const QSpinBox* self);
	void (*inputMethodEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QInputMethodEvent* param1);
	bool (*focusNextPrevChild)(struct QSpinBox_VTable* vtbl, QSpinBox* self, bool next);
	bool (*eventFilter)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QObject* watched, QEvent* event);
	void (*childEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QChildEvent* event);
	void (*customEvent)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QEvent* event);
	void (*connectNotify)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QSpinBox_VTable* vtbl, QSpinBox* self, QMetaMethod* signal);
};
QSpinBox* QSpinBox_new(struct QSpinBox_VTable* vtbl, QWidget* parent);
QSpinBox* QSpinBox_new2(struct QSpinBox_VTable* vtbl);
void QSpinBox_virtbase(QSpinBox* src, QAbstractSpinBox** outptr_QAbstractSpinBox);
QMetaObject* QSpinBox_metaObject(const QSpinBox* self);
void* QSpinBox_metacast(QSpinBox* self, const char* param1);
int QSpinBox_metacall(QSpinBox* self, int param1, int param2, void** param3);
struct miqt_string QSpinBox_tr(const char* s);
int QSpinBox_value(const QSpinBox* self);
struct miqt_string QSpinBox_prefix(const QSpinBox* self);
void QSpinBox_setPrefix(QSpinBox* self, struct miqt_string prefix);
struct miqt_string QSpinBox_suffix(const QSpinBox* self);
void QSpinBox_setSuffix(QSpinBox* self, struct miqt_string suffix);
struct miqt_string QSpinBox_cleanText(const QSpinBox* self);
int QSpinBox_singleStep(const QSpinBox* self);
void QSpinBox_setSingleStep(QSpinBox* self, int val);
int QSpinBox_minimum(const QSpinBox* self);
void QSpinBox_setMinimum(QSpinBox* self, int min);
int QSpinBox_maximum(const QSpinBox* self);
void QSpinBox_setMaximum(QSpinBox* self, int max);
void QSpinBox_setRange(QSpinBox* self, int min, int max);
int QSpinBox_stepType(const QSpinBox* self);
void QSpinBox_setStepType(QSpinBox* self, int stepType);
int QSpinBox_displayIntegerBase(const QSpinBox* self);
void QSpinBox_setDisplayIntegerBase(QSpinBox* self, int base);
bool QSpinBox_event(QSpinBox* self, QEvent* event);
int QSpinBox_validate(const QSpinBox* self, struct miqt_string input, int* pos);
int QSpinBox_valueFromText(const QSpinBox* self, struct miqt_string text);
struct miqt_string QSpinBox_textFromValue(const QSpinBox* self, int val);
void QSpinBox_fixup(const QSpinBox* self, struct miqt_string str);
void QSpinBox_setValue(QSpinBox* self, int val);
void QSpinBox_valueChanged(QSpinBox* self, int param1);
void QSpinBox_connect_valueChanged(QSpinBox* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QSpinBox_textChanged(QSpinBox* self, struct miqt_string param1);
void QSpinBox_connect_textChanged(QSpinBox* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_string), void (*release)(intptr_t));
struct miqt_string QSpinBox_tr2(const char* s, const char* c);
struct miqt_string QSpinBox_tr3(const char* s, const char* c, int n);
QMetaObject* QSpinBox_virtualbase_metaObject(const void* self);
void* QSpinBox_virtualbase_metacast(void* self, const char* param1);
int QSpinBox_virtualbase_metacall(void* self, int param1, int param2, void** param3);
bool QSpinBox_virtualbase_event(void* self, QEvent* event);
int QSpinBox_virtualbase_validate(const void* self, struct miqt_string input, int* pos);
int QSpinBox_virtualbase_valueFromText(const void* self, struct miqt_string text);
struct miqt_string QSpinBox_virtualbase_textFromValue(const void* self, int val);
void QSpinBox_virtualbase_fixup(const void* self, struct miqt_string str);
QSize* QSpinBox_virtualbase_sizeHint(const void* self);
QSize* QSpinBox_virtualbase_minimumSizeHint(const void* self);
QVariant* QSpinBox_virtualbase_inputMethodQuery(const void* self, int param1);
void QSpinBox_virtualbase_stepBy(void* self, int steps);
void QSpinBox_virtualbase_clear(void* self);
void QSpinBox_virtualbase_resizeEvent(void* self, QResizeEvent* event);
void QSpinBox_virtualbase_keyPressEvent(void* self, QKeyEvent* event);
void QSpinBox_virtualbase_keyReleaseEvent(void* self, QKeyEvent* event);
void QSpinBox_virtualbase_wheelEvent(void* self, QWheelEvent* event);
void QSpinBox_virtualbase_focusInEvent(void* self, QFocusEvent* event);
void QSpinBox_virtualbase_focusOutEvent(void* self, QFocusEvent* event);
void QSpinBox_virtualbase_contextMenuEvent(void* self, QContextMenuEvent* event);
void QSpinBox_virtualbase_changeEvent(void* self, QEvent* event);
void QSpinBox_virtualbase_closeEvent(void* self, QCloseEvent* event);
void QSpinBox_virtualbase_hideEvent(void* self, QHideEvent* event);
void QSpinBox_virtualbase_mousePressEvent(void* self, QMouseEvent* event);
void QSpinBox_virtualbase_mouseReleaseEvent(void* self, QMouseEvent* event);
void QSpinBox_virtualbase_mouseMoveEvent(void* self, QMouseEvent* event);
void QSpinBox_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QSpinBox_virtualbase_paintEvent(void* self, QPaintEvent* event);
void QSpinBox_virtualbase_showEvent(void* self, QShowEvent* event);
void QSpinBox_virtualbase_initStyleOption(const void* self, QStyleOptionSpinBox* option);
int QSpinBox_virtualbase_stepEnabled(const void* self);
int QSpinBox_virtualbase_devType(const void* self);
void QSpinBox_virtualbase_setVisible(void* self, bool visible);
int QSpinBox_virtualbase_heightForWidth(const void* self, int param1);
bool QSpinBox_virtualbase_hasHeightForWidth(const void* self);
QPaintEngine* QSpinBox_virtualbase_paintEngine(const void* self);
void QSpinBox_virtualbase_mouseDoubleClickEvent(void* self, QMouseEvent* event);
void QSpinBox_virtualbase_enterEvent(void* self, QEnterEvent* event);
void QSpinBox_virtualbase_leaveEvent(void* self, QEvent* event);
void QSpinBox_virtualbase_moveEvent(void* self, QMoveEvent* event);
void QSpinBox_virtualbase_tabletEvent(void* self, QTabletEvent* event);
void QSpinBox_virtualbase_actionEvent(void* self, QActionEvent* event);
void QSpinBox_virtualbase_dragEnterEvent(void* self, QDragEnterEvent* event);
void QSpinBox_virtualbase_dragMoveEvent(void* self, QDragMoveEvent* event);
void QSpinBox_virtualbase_dragLeaveEvent(void* self, QDragLeaveEvent* event);
void QSpinBox_virtualbase_dropEvent(void* self, QDropEvent* event);
bool QSpinBox_virtualbase_nativeEvent(void* self, struct miqt_string eventType, void* message, intptr_t* result);
int QSpinBox_virtualbase_metric(const void* self, int param1);
void QSpinBox_virtualbase_initPainter(const void* self, QPainter* painter);
QPaintDevice* QSpinBox_virtualbase_redirected(const void* self, QPoint* offset);
QPainter* QSpinBox_virtualbase_sharedPainter(const void* self);
void QSpinBox_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* param1);
bool QSpinBox_virtualbase_focusNextPrevChild(void* self, bool next);
bool QSpinBox_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
void QSpinBox_virtualbase_childEvent(void* self, QChildEvent* event);
void QSpinBox_virtualbase_customEvent(void* self, QEvent* event);
void QSpinBox_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QSpinBox_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
QLineEdit* QSpinBox_protectedbase_lineEdit(bool* _dynamic_cast_ok, const void* self);
void QSpinBox_protectedbase_setLineEdit(bool* _dynamic_cast_ok, void* self, QLineEdit* edit);
void QSpinBox_protectedbase_updateMicroFocus(bool* _dynamic_cast_ok, void* self);
void QSpinBox_protectedbase_create(bool* _dynamic_cast_ok, void* self);
void QSpinBox_protectedbase_destroy(bool* _dynamic_cast_ok, void* self);
bool QSpinBox_protectedbase_focusNextChild(bool* _dynamic_cast_ok, void* self);
bool QSpinBox_protectedbase_focusPreviousChild(bool* _dynamic_cast_ok, void* self);
QObject* QSpinBox_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QSpinBox_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QSpinBox_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QSpinBox_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
const QMetaObject* QSpinBox_staticMetaObject();
void QSpinBox_delete(QSpinBox* self);

struct QDoubleSpinBox_VTable {
	void (*destructor)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self);
	QMetaObject* (*metaObject)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self);
	void* (*metacast)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, const char* param1);
	int (*metacall)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, int param1, int param2, void** param3);
	int (*validate)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self, struct miqt_string input, int* pos);
	double (*valueFromText)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self, struct miqt_string text);
	struct miqt_string (*textFromValue)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self, double val);
	void (*fixup)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self, struct miqt_string str);
	QSize* (*sizeHint)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self);
	QSize* (*minimumSizeHint)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self);
	bool (*event)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QEvent* event);
	QVariant* (*inputMethodQuery)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self, int param1);
	void (*stepBy)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, int steps);
	void (*clear)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self);
	void (*resizeEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QResizeEvent* event);
	void (*keyPressEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QKeyEvent* event);
	void (*keyReleaseEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QKeyEvent* event);
	void (*wheelEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QWheelEvent* event);
	void (*focusInEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QFocusEvent* event);
	void (*focusOutEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QFocusEvent* event);
	void (*contextMenuEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QContextMenuEvent* event);
	void (*changeEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QEvent* event);
	void (*closeEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QCloseEvent* event);
	void (*hideEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QHideEvent* event);
	void (*mousePressEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QMouseEvent* event);
	void (*mouseMoveEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QMouseEvent* event);
	void (*timerEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QTimerEvent* event);
	void (*paintEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QPaintEvent* event);
	void (*showEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QShowEvent* event);
	void (*initStyleOption)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self, QStyleOptionSpinBox* option);
	int (*stepEnabled)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self);
	int (*devType)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self);
	void (*setVisible)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, bool visible);
	int (*heightForWidth)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self, int param1);
	bool (*hasHeightForWidth)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self);
	QPaintEngine* (*paintEngine)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self);
	void (*mouseDoubleClickEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QMouseEvent* event);
	void (*enterEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QEnterEvent* event);
	void (*leaveEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QEvent* event);
	void (*moveEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QMoveEvent* event);
	void (*tabletEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QTabletEvent* event);
	void (*actionEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QActionEvent* event);
	void (*dragEnterEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QDragEnterEvent* event);
	void (*dragMoveEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QDragMoveEvent* event);
	void (*dragLeaveEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QDragLeaveEvent* event);
	void (*dropEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QDropEvent* event);
	bool (*nativeEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, struct miqt_string eventType, void* message, intptr_t* result);
	int (*metric)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self, int param1);
	void (*initPainter)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self, QPainter* painter);
	QPaintDevice* (*redirected)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self, QPoint* offset);
	QPainter* (*sharedPainter)(struct QDoubleSpinBox_VTable* vtbl, const QDoubleSpinBox* self);
	void (*inputMethodEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QInputMethodEvent* param1);
	bool (*focusNextPrevChild)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, bool next);
	bool (*eventFilter)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QObject* watched, QEvent* event);
	void (*childEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QChildEvent* event);
	void (*customEvent)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QEvent* event);
	void (*connectNotify)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QDoubleSpinBox_VTable* vtbl, QDoubleSpinBox* self, QMetaMethod* signal);
};
QDoubleSpinBox* QDoubleSpinBox_new(struct QDoubleSpinBox_VTable* vtbl, QWidget* parent);
QDoubleSpinBox* QDoubleSpinBox_new2(struct QDoubleSpinBox_VTable* vtbl);
void QDoubleSpinBox_virtbase(QDoubleSpinBox* src, QAbstractSpinBox** outptr_QAbstractSpinBox);
QMetaObject* QDoubleSpinBox_metaObject(const QDoubleSpinBox* self);
void* QDoubleSpinBox_metacast(QDoubleSpinBox* self, const char* param1);
int QDoubleSpinBox_metacall(QDoubleSpinBox* self, int param1, int param2, void** param3);
struct miqt_string QDoubleSpinBox_tr(const char* s);
double QDoubleSpinBox_value(const QDoubleSpinBox* self);
struct miqt_string QDoubleSpinBox_prefix(const QDoubleSpinBox* self);
void QDoubleSpinBox_setPrefix(QDoubleSpinBox* self, struct miqt_string prefix);
struct miqt_string QDoubleSpinBox_suffix(const QDoubleSpinBox* self);
void QDoubleSpinBox_setSuffix(QDoubleSpinBox* self, struct miqt_string suffix);
struct miqt_string QDoubleSpinBox_cleanText(const QDoubleSpinBox* self);
double QDoubleSpinBox_singleStep(const QDoubleSpinBox* self);
void QDoubleSpinBox_setSingleStep(QDoubleSpinBox* self, double val);
double QDoubleSpinBox_minimum(const QDoubleSpinBox* self);
void QDoubleSpinBox_setMinimum(QDoubleSpinBox* self, double min);
double QDoubleSpinBox_maximum(const QDoubleSpinBox* self);
void QDoubleSpinBox_setMaximum(QDoubleSpinBox* self, double max);
void QDoubleSpinBox_setRange(QDoubleSpinBox* self, double min, double max);
int QDoubleSpinBox_stepType(const QDoubleSpinBox* self);
void QDoubleSpinBox_setStepType(QDoubleSpinBox* self, int stepType);
int QDoubleSpinBox_decimals(const QDoubleSpinBox* self);
void QDoubleSpinBox_setDecimals(QDoubleSpinBox* self, int prec);
int QDoubleSpinBox_validate(const QDoubleSpinBox* self, struct miqt_string input, int* pos);
double QDoubleSpinBox_valueFromText(const QDoubleSpinBox* self, struct miqt_string text);
struct miqt_string QDoubleSpinBox_textFromValue(const QDoubleSpinBox* self, double val);
void QDoubleSpinBox_fixup(const QDoubleSpinBox* self, struct miqt_string str);
void QDoubleSpinBox_setValue(QDoubleSpinBox* self, double val);
void QDoubleSpinBox_valueChanged(QDoubleSpinBox* self, double param1);
void QDoubleSpinBox_connect_valueChanged(QDoubleSpinBox* self, intptr_t slot, void (*callback)(intptr_t, double), void (*release)(intptr_t));
void QDoubleSpinBox_textChanged(QDoubleSpinBox* self, struct miqt_string param1);
void QDoubleSpinBox_connect_textChanged(QDoubleSpinBox* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_string), void (*release)(intptr_t));
struct miqt_string QDoubleSpinBox_tr2(const char* s, const char* c);
struct miqt_string QDoubleSpinBox_tr3(const char* s, const char* c, int n);
QMetaObject* QDoubleSpinBox_virtualbase_metaObject(const void* self);
void* QDoubleSpinBox_virtualbase_metacast(void* self, const char* param1);
int QDoubleSpinBox_virtualbase_metacall(void* self, int param1, int param2, void** param3);
int QDoubleSpinBox_virtualbase_validate(const void* self, struct miqt_string input, int* pos);
double QDoubleSpinBox_virtualbase_valueFromText(const void* self, struct miqt_string text);
struct miqt_string QDoubleSpinBox_virtualbase_textFromValue(const void* self, double val);
void QDoubleSpinBox_virtualbase_fixup(const void* self, struct miqt_string str);
QSize* QDoubleSpinBox_virtualbase_sizeHint(const void* self);
QSize* QDoubleSpinBox_virtualbase_minimumSizeHint(const void* self);
bool QDoubleSpinBox_virtualbase_event(void* self, QEvent* event);
QVariant* QDoubleSpinBox_virtualbase_inputMethodQuery(const void* self, int param1);
void QDoubleSpinBox_virtualbase_stepBy(void* self, int steps);
void QDoubleSpinBox_virtualbase_clear(void* self);
void QDoubleSpinBox_virtualbase_resizeEvent(void* self, QResizeEvent* event);
void QDoubleSpinBox_virtualbase_keyPressEvent(void* self, QKeyEvent* event);
void QDoubleSpinBox_virtualbase_keyReleaseEvent(void* self, QKeyEvent* event);
void QDoubleSpinBox_virtualbase_wheelEvent(void* self, QWheelEvent* event);
void QDoubleSpinBox_virtualbase_focusInEvent(void* self, QFocusEvent* event);
void QDoubleSpinBox_virtualbase_focusOutEvent(void* self, QFocusEvent* event);
void QDoubleSpinBox_virtualbase_contextMenuEvent(void* self, QContextMenuEvent* event);
void QDoubleSpinBox_virtualbase_changeEvent(void* self, QEvent* event);
void QDoubleSpinBox_virtualbase_closeEvent(void* self, QCloseEvent* event);
void QDoubleSpinBox_virtualbase_hideEvent(void* self, QHideEvent* event);
void QDoubleSpinBox_virtualbase_mousePressEvent(void* self, QMouseEvent* event);
void QDoubleSpinBox_virtualbase_mouseReleaseEvent(void* self, QMouseEvent* event);
void QDoubleSpinBox_virtualbase_mouseMoveEvent(void* self, QMouseEvent* event);
void QDoubleSpinBox_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QDoubleSpinBox_virtualbase_paintEvent(void* self, QPaintEvent* event);
void QDoubleSpinBox_virtualbase_showEvent(void* self, QShowEvent* event);
void QDoubleSpinBox_virtualbase_initStyleOption(const void* self, QStyleOptionSpinBox* option);
int QDoubleSpinBox_virtualbase_stepEnabled(const void* self);
int QDoubleSpinBox_virtualbase_devType(const void* self);
void QDoubleSpinBox_virtualbase_setVisible(void* self, bool visible);
int QDoubleSpinBox_virtualbase_heightForWidth(const void* self, int param1);
bool QDoubleSpinBox_virtualbase_hasHeightForWidth(const void* self);
QPaintEngine* QDoubleSpinBox_virtualbase_paintEngine(const void* self);
void QDoubleSpinBox_virtualbase_mouseDoubleClickEvent(void* self, QMouseEvent* event);
void QDoubleSpinBox_virtualbase_enterEvent(void* self, QEnterEvent* event);
void QDoubleSpinBox_virtualbase_leaveEvent(void* self, QEvent* event);
void QDoubleSpinBox_virtualbase_moveEvent(void* self, QMoveEvent* event);
void QDoubleSpinBox_virtualbase_tabletEvent(void* self, QTabletEvent* event);
void QDoubleSpinBox_virtualbase_actionEvent(void* self, QActionEvent* event);
void QDoubleSpinBox_virtualbase_dragEnterEvent(void* self, QDragEnterEvent* event);
void QDoubleSpinBox_virtualbase_dragMoveEvent(void* self, QDragMoveEvent* event);
void QDoubleSpinBox_virtualbase_dragLeaveEvent(void* self, QDragLeaveEvent* event);
void QDoubleSpinBox_virtualbase_dropEvent(void* self, QDropEvent* event);
bool QDoubleSpinBox_virtualbase_nativeEvent(void* self, struct miqt_string eventType, void* message, intptr_t* result);
int QDoubleSpinBox_virtualbase_metric(const void* self, int param1);
void QDoubleSpinBox_virtualbase_initPainter(const void* self, QPainter* painter);
QPaintDevice* QDoubleSpinBox_virtualbase_redirected(const void* self, QPoint* offset);
QPainter* QDoubleSpinBox_virtualbase_sharedPainter(const void* self);
void QDoubleSpinBox_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* param1);
bool QDoubleSpinBox_virtualbase_focusNextPrevChild(void* self, bool next);
bool QDoubleSpinBox_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
void QDoubleSpinBox_virtualbase_childEvent(void* self, QChildEvent* event);
void QDoubleSpinBox_virtualbase_customEvent(void* self, QEvent* event);
void QDoubleSpinBox_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QDoubleSpinBox_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
QLineEdit* QDoubleSpinBox_protectedbase_lineEdit(bool* _dynamic_cast_ok, const void* self);
void QDoubleSpinBox_protectedbase_setLineEdit(bool* _dynamic_cast_ok, void* self, QLineEdit* edit);
void QDoubleSpinBox_protectedbase_updateMicroFocus(bool* _dynamic_cast_ok, void* self);
void QDoubleSpinBox_protectedbase_create(bool* _dynamic_cast_ok, void* self);
void QDoubleSpinBox_protectedbase_destroy(bool* _dynamic_cast_ok, void* self);
bool QDoubleSpinBox_protectedbase_focusNextChild(bool* _dynamic_cast_ok, void* self);
bool QDoubleSpinBox_protectedbase_focusPreviousChild(bool* _dynamic_cast_ok, void* self);
QObject* QDoubleSpinBox_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QDoubleSpinBox_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QDoubleSpinBox_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QDoubleSpinBox_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
const QMetaObject* QDoubleSpinBox_staticMetaObject();
void QDoubleSpinBox_delete(QDoubleSpinBox* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
