#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QTABLEVIEW_H
#define SEAQT_QTWIDGETS_GEN_QTABLEVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt-runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemModel;
class QAbstractItemView;
class QAbstractScrollArea;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QFrame;
class QHeaderView;
class QHideEvent;
class QInputMethodEvent;
class QItemSelection;
class QItemSelectionModel;
class QKeyEvent;
class QMargins;
class QMetaMethod;
class QMetaObject;
class QModelIndex;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QRect;
class QRegion;
class QResizeEvent;
class QShowEvent;
class QSize;
class QStyleOptionFrame;
class QStyleOptionViewItem;
class QTableView;
class QTabletEvent;
class QTimerEvent;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHeaderView QHeaderView;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTableView QTableView;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

typedef struct VirtualQTableView VirtualQTableView;
typedef struct QTableView_VTable{
	void (*destructor)(VirtualQTableView* self);
	QMetaObject* (*metaObject)(const VirtualQTableView* self);
	void* (*metacast)(VirtualQTableView* self, const char* param1);
	int (*metacall)(VirtualQTableView* self, int param1, int param2, void** param3);
	void (*setModel)(VirtualQTableView* self, QAbstractItemModel* model);
	void (*setRootIndex)(VirtualQTableView* self, QModelIndex* index);
	void (*setSelectionModel)(VirtualQTableView* self, QItemSelectionModel* selectionModel);
	void (*doItemsLayout)(VirtualQTableView* self);
	QRect* (*visualRect)(const VirtualQTableView* self, QModelIndex* index);
	void (*scrollTo)(VirtualQTableView* self, QModelIndex* index, int hint);
	QModelIndex* (*indexAt)(const VirtualQTableView* self, QPoint* p);
	void (*scrollContentsBy)(VirtualQTableView* self, int dx, int dy);
	QStyleOptionViewItem* (*viewOptions)(const VirtualQTableView* self);
	void (*paintEvent)(VirtualQTableView* self, QPaintEvent* e);
	void (*timerEvent)(VirtualQTableView* self, QTimerEvent* event);
	int (*horizontalOffset)(const VirtualQTableView* self);
	int (*verticalOffset)(const VirtualQTableView* self);
	QModelIndex* (*moveCursor)(VirtualQTableView* self, int cursorAction, int modifiers);
	void (*setSelection)(VirtualQTableView* self, QRect* rect, int command);
	QRegion* (*visualRegionForSelection)(const VirtualQTableView* self, QItemSelection* selection);
	struct seaqt_array /* of QModelIndex* */  (*selectedIndexes)(const VirtualQTableView* self);
	void (*updateGeometries)(VirtualQTableView* self);
	QSize* (*viewportSizeHint)(const VirtualQTableView* self);
	int (*sizeHintForRow)(const VirtualQTableView* self, int row);
	int (*sizeHintForColumn)(const VirtualQTableView* self, int column);
	void (*verticalScrollbarAction)(VirtualQTableView* self, int action);
	void (*horizontalScrollbarAction)(VirtualQTableView* self, int action);
	bool (*isIndexHidden)(const VirtualQTableView* self, QModelIndex* index);
	void (*selectionChanged)(VirtualQTableView* self, QItemSelection* selected, QItemSelection* deselected);
	void (*currentChanged)(VirtualQTableView* self, QModelIndex* current, QModelIndex* previous);
	void (*keyboardSearch)(VirtualQTableView* self, struct seaqt_string search);
	QVariant* (*inputMethodQuery)(const VirtualQTableView* self, int query);
	void (*reset)(VirtualQTableView* self);
	void (*selectAll)(VirtualQTableView* self);
	void (*dataChanged)(VirtualQTableView* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct seaqt_array /* of int */  roles);
	void (*rowsInserted)(VirtualQTableView* self, QModelIndex* parent, int start, int end);
	void (*rowsAboutToBeRemoved)(VirtualQTableView* self, QModelIndex* parent, int start, int end);
	void (*updateEditorData)(VirtualQTableView* self);
	void (*updateEditorGeometries)(VirtualQTableView* self);
	void (*verticalScrollbarValueChanged)(VirtualQTableView* self, int value);
	void (*horizontalScrollbarValueChanged)(VirtualQTableView* self, int value);
	void (*closeEditor)(VirtualQTableView* self, QWidget* editor, int hint);
	void (*commitData)(VirtualQTableView* self, QWidget* editor);
	void (*editorDestroyed)(VirtualQTableView* self, QObject* editor);
	bool (*edit2)(VirtualQTableView* self, QModelIndex* index, int trigger, QEvent* event);
	int (*selectionCommand)(const VirtualQTableView* self, QModelIndex* index, QEvent* event);
	void (*startDrag)(VirtualQTableView* self, int supportedActions);
	bool (*focusNextPrevChild)(VirtualQTableView* self, bool next);
	bool (*event)(VirtualQTableView* self, QEvent* event);
	bool (*viewportEvent)(VirtualQTableView* self, QEvent* event);
	void (*mousePressEvent)(VirtualQTableView* self, QMouseEvent* event);
	void (*mouseMoveEvent)(VirtualQTableView* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(VirtualQTableView* self, QMouseEvent* event);
	void (*mouseDoubleClickEvent)(VirtualQTableView* self, QMouseEvent* event);
	void (*dragEnterEvent)(VirtualQTableView* self, QDragEnterEvent* event);
	void (*dragMoveEvent)(VirtualQTableView* self, QDragMoveEvent* event);
	void (*dragLeaveEvent)(VirtualQTableView* self, QDragLeaveEvent* event);
	void (*dropEvent)(VirtualQTableView* self, QDropEvent* event);
	void (*focusInEvent)(VirtualQTableView* self, QFocusEvent* event);
	void (*focusOutEvent)(VirtualQTableView* self, QFocusEvent* event);
	void (*keyPressEvent)(VirtualQTableView* self, QKeyEvent* event);
	void (*resizeEvent)(VirtualQTableView* self, QResizeEvent* event);
	void (*inputMethodEvent)(VirtualQTableView* self, QInputMethodEvent* event);
	bool (*eventFilter)(VirtualQTableView* self, QObject* object, QEvent* event);
	QSize* (*minimumSizeHint)(const VirtualQTableView* self);
	QSize* (*sizeHint)(const VirtualQTableView* self);
	void (*setupViewport)(VirtualQTableView* self, QWidget* viewport);
	void (*wheelEvent)(VirtualQTableView* self, QWheelEvent* param1);
	void (*contextMenuEvent)(VirtualQTableView* self, QContextMenuEvent* param1);
	void (*changeEvent)(VirtualQTableView* self, QEvent* param1);
	int (*devType)(const VirtualQTableView* self);
	void (*setVisible)(VirtualQTableView* self, bool visible);
	int (*heightForWidth)(const VirtualQTableView* self, int param1);
	bool (*hasHeightForWidth)(const VirtualQTableView* self);
	QPaintEngine* (*paintEngine)(const VirtualQTableView* self);
	void (*keyReleaseEvent)(VirtualQTableView* self, QKeyEvent* event);
	void (*enterEvent)(VirtualQTableView* self, QEvent* event);
	void (*leaveEvent)(VirtualQTableView* self, QEvent* event);
	void (*moveEvent)(VirtualQTableView* self, QMoveEvent* event);
	void (*closeEvent)(VirtualQTableView* self, QCloseEvent* event);
	void (*tabletEvent)(VirtualQTableView* self, QTabletEvent* event);
	void (*actionEvent)(VirtualQTableView* self, QActionEvent* event);
	void (*showEvent)(VirtualQTableView* self, QShowEvent* event);
	void (*hideEvent)(VirtualQTableView* self, QHideEvent* event);
	bool (*nativeEvent)(VirtualQTableView* self, struct seaqt_string eventType, void* message, long* result);
	int (*metric)(const VirtualQTableView* self, int param1);
	void (*initPainter)(const VirtualQTableView* self, QPainter* painter);
	QPaintDevice* (*redirected)(const VirtualQTableView* self, QPoint* offset);
	QPainter* (*sharedPainter)(const VirtualQTableView* self);
	void (*childEvent)(VirtualQTableView* self, QChildEvent* event);
	void (*customEvent)(VirtualQTableView* self, QEvent* event);
	void (*connectNotify)(VirtualQTableView* self, QMetaMethod* signal);
	void (*disconnectNotify)(VirtualQTableView* self, QMetaMethod* signal);
}QTableView_VTable;

void* QTableView_vdata(VirtualQTableView* self);
VirtualQTableView* vdata_QTableView(void* vdata);

VirtualQTableView* QTableView_new(const QTableView_VTable* vtbl, size_t vdata, QWidget* parent);
VirtualQTableView* QTableView_new2(const QTableView_VTable* vtbl, size_t vdata);

void QTableView_virtbase(QTableView* src, QAbstractItemView** outptr_QAbstractItemView);
QMetaObject* QTableView_metaObject(const QTableView* self);
void* QTableView_metacast(QTableView* self, const char* param1);
int QTableView_metacall(QTableView* self, int param1, int param2, void** param3);
struct seaqt_string QTableView_tr(const char* s);
struct seaqt_string QTableView_trUtf8(const char* s);
void QTableView_setModel(QTableView* self, QAbstractItemModel* model);
void QTableView_setRootIndex(QTableView* self, QModelIndex* index);
void QTableView_setSelectionModel(QTableView* self, QItemSelectionModel* selectionModel);
void QTableView_doItemsLayout(QTableView* self);
QHeaderView* QTableView_horizontalHeader(const QTableView* self);
QHeaderView* QTableView_verticalHeader(const QTableView* self);
void QTableView_setHorizontalHeader(QTableView* self, QHeaderView* header);
void QTableView_setVerticalHeader(QTableView* self, QHeaderView* header);
int QTableView_rowViewportPosition(const QTableView* self, int row);
int QTableView_rowAt(const QTableView* self, int y);
void QTableView_setRowHeight(QTableView* self, int row, int height);
int QTableView_rowHeight(const QTableView* self, int row);
int QTableView_columnViewportPosition(const QTableView* self, int column);
int QTableView_columnAt(const QTableView* self, int x);
void QTableView_setColumnWidth(QTableView* self, int column, int width);
int QTableView_columnWidth(const QTableView* self, int column);
bool QTableView_isRowHidden(const QTableView* self, int row);
void QTableView_setRowHidden(QTableView* self, int row, bool hide);
bool QTableView_isColumnHidden(const QTableView* self, int column);
void QTableView_setColumnHidden(QTableView* self, int column, bool hide);
void QTableView_setSortingEnabled(QTableView* self, bool enable);
bool QTableView_isSortingEnabled(const QTableView* self);
bool QTableView_showGrid(const QTableView* self);
int QTableView_gridStyle(const QTableView* self);
void QTableView_setGridStyle(QTableView* self, int style);
void QTableView_setWordWrap(QTableView* self, bool on);
bool QTableView_wordWrap(const QTableView* self);
void QTableView_setCornerButtonEnabled(QTableView* self, bool enable);
bool QTableView_isCornerButtonEnabled(const QTableView* self);
QRect* QTableView_visualRect(const QTableView* self, QModelIndex* index);
void QTableView_scrollTo(QTableView* self, QModelIndex* index, int hint);
QModelIndex* QTableView_indexAt(const QTableView* self, QPoint* p);
void QTableView_setSpan(QTableView* self, int row, int column, int rowSpan, int columnSpan);
int QTableView_rowSpan(const QTableView* self, int row, int column);
int QTableView_columnSpan(const QTableView* self, int row, int column);
void QTableView_clearSpans(QTableView* self);
void QTableView_selectRow(QTableView* self, int row);
void QTableView_selectColumn(QTableView* self, int column);
void QTableView_hideRow(QTableView* self, int row);
void QTableView_hideColumn(QTableView* self, int column);
void QTableView_showRow(QTableView* self, int row);
void QTableView_showColumn(QTableView* self, int column);
void QTableView_resizeRowToContents(QTableView* self, int row);
void QTableView_resizeRowsToContents(QTableView* self);
void QTableView_resizeColumnToContents(QTableView* self, int column);
void QTableView_resizeColumnsToContents(QTableView* self);
void QTableView_sortByColumn(QTableView* self, int column);
void QTableView_sortByColumn2(QTableView* self, int column, int order);
void QTableView_setShowGrid(QTableView* self, bool show);
void QTableView_scrollContentsBy(QTableView* self, int dx, int dy);
QStyleOptionViewItem* QTableView_viewOptions(const QTableView* self);
void QTableView_paintEvent(QTableView* self, QPaintEvent* e);
void QTableView_timerEvent(QTableView* self, QTimerEvent* event);
int QTableView_horizontalOffset(const QTableView* self);
int QTableView_verticalOffset(const QTableView* self);
QModelIndex* QTableView_moveCursor(QTableView* self, int cursorAction, int modifiers);
void QTableView_setSelection(QTableView* self, QRect* rect, int command);
QRegion* QTableView_visualRegionForSelection(const QTableView* self, QItemSelection* selection);
struct seaqt_array /* of QModelIndex* */  QTableView_selectedIndexes(const QTableView* self);
void QTableView_updateGeometries(QTableView* self);
QSize* QTableView_viewportSizeHint(const QTableView* self);
int QTableView_sizeHintForRow(const QTableView* self, int row);
int QTableView_sizeHintForColumn(const QTableView* self, int column);
void QTableView_verticalScrollbarAction(QTableView* self, int action);
void QTableView_horizontalScrollbarAction(QTableView* self, int action);
bool QTableView_isIndexHidden(const QTableView* self, QModelIndex* index);
void QTableView_selectionChanged(QTableView* self, QItemSelection* selected, QItemSelection* deselected);
void QTableView_currentChanged(QTableView* self, QModelIndex* current, QModelIndex* previous);
struct seaqt_string QTableView_tr2(const char* s, const char* c);
struct seaqt_string QTableView_tr3(const char* s, const char* c, int n);
struct seaqt_string QTableView_trUtf82(const char* s, const char* c);
struct seaqt_string QTableView_trUtf83(const char* s, const char* c, int n);

QMetaObject* QTableView_virtualbase_metaObject(const VirtualQTableView* self);
void* QTableView_virtualbase_metacast(VirtualQTableView* self, const char* param1);
int QTableView_virtualbase_metacall(VirtualQTableView* self, int param1, int param2, void** param3);
void QTableView_virtualbase_setModel(VirtualQTableView* self, QAbstractItemModel* model);
void QTableView_virtualbase_setRootIndex(VirtualQTableView* self, QModelIndex* index);
void QTableView_virtualbase_setSelectionModel(VirtualQTableView* self, QItemSelectionModel* selectionModel);
void QTableView_virtualbase_doItemsLayout(VirtualQTableView* self);
QRect* QTableView_virtualbase_visualRect(const VirtualQTableView* self, QModelIndex* index);
void QTableView_virtualbase_scrollTo(VirtualQTableView* self, QModelIndex* index, int hint);
QModelIndex* QTableView_virtualbase_indexAt(const VirtualQTableView* self, QPoint* p);
void QTableView_virtualbase_scrollContentsBy(VirtualQTableView* self, int dx, int dy);
QStyleOptionViewItem* QTableView_virtualbase_viewOptions(const VirtualQTableView* self);
void QTableView_virtualbase_paintEvent(VirtualQTableView* self, QPaintEvent* e);
void QTableView_virtualbase_timerEvent(VirtualQTableView* self, QTimerEvent* event);
int QTableView_virtualbase_horizontalOffset(const VirtualQTableView* self);
int QTableView_virtualbase_verticalOffset(const VirtualQTableView* self);
QModelIndex* QTableView_virtualbase_moveCursor(VirtualQTableView* self, int cursorAction, int modifiers);
void QTableView_virtualbase_setSelection(VirtualQTableView* self, QRect* rect, int command);
QRegion* QTableView_virtualbase_visualRegionForSelection(const VirtualQTableView* self, QItemSelection* selection);
struct seaqt_array /* of QModelIndex* */  QTableView_virtualbase_selectedIndexes(const VirtualQTableView* self);
void QTableView_virtualbase_updateGeometries(VirtualQTableView* self);
QSize* QTableView_virtualbase_viewportSizeHint(const VirtualQTableView* self);
int QTableView_virtualbase_sizeHintForRow(const VirtualQTableView* self, int row);
int QTableView_virtualbase_sizeHintForColumn(const VirtualQTableView* self, int column);
void QTableView_virtualbase_verticalScrollbarAction(VirtualQTableView* self, int action);
void QTableView_virtualbase_horizontalScrollbarAction(VirtualQTableView* self, int action);
bool QTableView_virtualbase_isIndexHidden(const VirtualQTableView* self, QModelIndex* index);
void QTableView_virtualbase_selectionChanged(VirtualQTableView* self, QItemSelection* selected, QItemSelection* deselected);
void QTableView_virtualbase_currentChanged(VirtualQTableView* self, QModelIndex* current, QModelIndex* previous);
void QTableView_virtualbase_keyboardSearch(VirtualQTableView* self, struct seaqt_string search);
QVariant* QTableView_virtualbase_inputMethodQuery(const VirtualQTableView* self, int query);
void QTableView_virtualbase_reset(VirtualQTableView* self);
void QTableView_virtualbase_selectAll(VirtualQTableView* self);
void QTableView_virtualbase_dataChanged(VirtualQTableView* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct seaqt_array /* of int */  roles);
void QTableView_virtualbase_rowsInserted(VirtualQTableView* self, QModelIndex* parent, int start, int end);
void QTableView_virtualbase_rowsAboutToBeRemoved(VirtualQTableView* self, QModelIndex* parent, int start, int end);
void QTableView_virtualbase_updateEditorData(VirtualQTableView* self);
void QTableView_virtualbase_updateEditorGeometries(VirtualQTableView* self);
void QTableView_virtualbase_verticalScrollbarValueChanged(VirtualQTableView* self, int value);
void QTableView_virtualbase_horizontalScrollbarValueChanged(VirtualQTableView* self, int value);
void QTableView_virtualbase_closeEditor(VirtualQTableView* self, QWidget* editor, int hint);
void QTableView_virtualbase_commitData(VirtualQTableView* self, QWidget* editor);
void QTableView_virtualbase_editorDestroyed(VirtualQTableView* self, QObject* editor);
bool QTableView_virtualbase_edit2(VirtualQTableView* self, QModelIndex* index, int trigger, QEvent* event);
int QTableView_virtualbase_selectionCommand(const VirtualQTableView* self, QModelIndex* index, QEvent* event);
void QTableView_virtualbase_startDrag(VirtualQTableView* self, int supportedActions);
bool QTableView_virtualbase_focusNextPrevChild(VirtualQTableView* self, bool next);
bool QTableView_virtualbase_event(VirtualQTableView* self, QEvent* event);
bool QTableView_virtualbase_viewportEvent(VirtualQTableView* self, QEvent* event);
void QTableView_virtualbase_mousePressEvent(VirtualQTableView* self, QMouseEvent* event);
void QTableView_virtualbase_mouseMoveEvent(VirtualQTableView* self, QMouseEvent* event);
void QTableView_virtualbase_mouseReleaseEvent(VirtualQTableView* self, QMouseEvent* event);
void QTableView_virtualbase_mouseDoubleClickEvent(VirtualQTableView* self, QMouseEvent* event);
void QTableView_virtualbase_dragEnterEvent(VirtualQTableView* self, QDragEnterEvent* event);
void QTableView_virtualbase_dragMoveEvent(VirtualQTableView* self, QDragMoveEvent* event);
void QTableView_virtualbase_dragLeaveEvent(VirtualQTableView* self, QDragLeaveEvent* event);
void QTableView_virtualbase_dropEvent(VirtualQTableView* self, QDropEvent* event);
void QTableView_virtualbase_focusInEvent(VirtualQTableView* self, QFocusEvent* event);
void QTableView_virtualbase_focusOutEvent(VirtualQTableView* self, QFocusEvent* event);
void QTableView_virtualbase_keyPressEvent(VirtualQTableView* self, QKeyEvent* event);
void QTableView_virtualbase_resizeEvent(VirtualQTableView* self, QResizeEvent* event);
void QTableView_virtualbase_inputMethodEvent(VirtualQTableView* self, QInputMethodEvent* event);
bool QTableView_virtualbase_eventFilter(VirtualQTableView* self, QObject* object, QEvent* event);
QSize* QTableView_virtualbase_minimumSizeHint(const VirtualQTableView* self);
QSize* QTableView_virtualbase_sizeHint(const VirtualQTableView* self);
void QTableView_virtualbase_setupViewport(VirtualQTableView* self, QWidget* viewport);
void QTableView_virtualbase_wheelEvent(VirtualQTableView* self, QWheelEvent* param1);
void QTableView_virtualbase_contextMenuEvent(VirtualQTableView* self, QContextMenuEvent* param1);
void QTableView_virtualbase_changeEvent(VirtualQTableView* self, QEvent* param1);
int QTableView_virtualbase_devType(const VirtualQTableView* self);
void QTableView_virtualbase_setVisible(VirtualQTableView* self, bool visible);
int QTableView_virtualbase_heightForWidth(const VirtualQTableView* self, int param1);
bool QTableView_virtualbase_hasHeightForWidth(const VirtualQTableView* self);
QPaintEngine* QTableView_virtualbase_paintEngine(const VirtualQTableView* self);
void QTableView_virtualbase_keyReleaseEvent(VirtualQTableView* self, QKeyEvent* event);
void QTableView_virtualbase_enterEvent(VirtualQTableView* self, QEvent* event);
void QTableView_virtualbase_leaveEvent(VirtualQTableView* self, QEvent* event);
void QTableView_virtualbase_moveEvent(VirtualQTableView* self, QMoveEvent* event);
void QTableView_virtualbase_closeEvent(VirtualQTableView* self, QCloseEvent* event);
void QTableView_virtualbase_tabletEvent(VirtualQTableView* self, QTabletEvent* event);
void QTableView_virtualbase_actionEvent(VirtualQTableView* self, QActionEvent* event);
void QTableView_virtualbase_showEvent(VirtualQTableView* self, QShowEvent* event);
void QTableView_virtualbase_hideEvent(VirtualQTableView* self, QHideEvent* event);
bool QTableView_virtualbase_nativeEvent(VirtualQTableView* self, struct seaqt_string eventType, void* message, long* result);
int QTableView_virtualbase_metric(const VirtualQTableView* self, int param1);
void QTableView_virtualbase_initPainter(const VirtualQTableView* self, QPainter* painter);
QPaintDevice* QTableView_virtualbase_redirected(const VirtualQTableView* self, QPoint* offset);
QPainter* QTableView_virtualbase_sharedPainter(const VirtualQTableView* self);
void QTableView_virtualbase_childEvent(VirtualQTableView* self, QChildEvent* event);
void QTableView_virtualbase_customEvent(VirtualQTableView* self, QEvent* event);
void QTableView_virtualbase_connectNotify(VirtualQTableView* self, QMetaMethod* signal);
void QTableView_virtualbase_disconnectNotify(VirtualQTableView* self, QMetaMethod* signal);

void QTableView_protectedbase_rowMoved(VirtualQTableView* self, int row, int oldIndex, int newIndex);
void QTableView_protectedbase_columnMoved(VirtualQTableView* self, int column, int oldIndex, int newIndex);
void QTableView_protectedbase_rowResized(VirtualQTableView* self, int row, int oldHeight, int newHeight);
void QTableView_protectedbase_columnResized(VirtualQTableView* self, int column, int oldWidth, int newWidth);
void QTableView_protectedbase_rowCountChanged(VirtualQTableView* self, int oldCount, int newCount);
void QTableView_protectedbase_columnCountChanged(VirtualQTableView* self, int oldCount, int newCount);
void QTableView_protectedbase_setHorizontalStepsPerItem(VirtualQTableView* self, int steps);
int QTableView_protectedbase_horizontalStepsPerItem(const VirtualQTableView* self);
void QTableView_protectedbase_setVerticalStepsPerItem(VirtualQTableView* self, int steps);
int QTableView_protectedbase_verticalStepsPerItem(const VirtualQTableView* self);
int QTableView_protectedbase_state(const VirtualQTableView* self);
void QTableView_protectedbase_setState(VirtualQTableView* self, int state);
void QTableView_protectedbase_scheduleDelayedItemsLayout(VirtualQTableView* self);
void QTableView_protectedbase_executeDelayedItemsLayout(VirtualQTableView* self);
void QTableView_protectedbase_setDirtyRegion(VirtualQTableView* self, QRegion* region);
void QTableView_protectedbase_scrollDirtyRegion(VirtualQTableView* self, int dx, int dy);
QPoint* QTableView_protectedbase_dirtyRegionOffset(const VirtualQTableView* self);
void QTableView_protectedbase_startAutoScroll(VirtualQTableView* self);
void QTableView_protectedbase_stopAutoScroll(VirtualQTableView* self);
void QTableView_protectedbase_doAutoScroll(VirtualQTableView* self);
int QTableView_protectedbase_dropIndicatorPosition(const VirtualQTableView* self);
void QTableView_protectedbase_setViewportMargins(VirtualQTableView* self, int left, int top, int right, int bottom);
QMargins* QTableView_protectedbase_viewportMargins(const VirtualQTableView* self);
void QTableView_protectedbase_drawFrame(VirtualQTableView* self, QPainter* param1);
void QTableView_protectedbase_initStyleOption(const VirtualQTableView* self, QStyleOptionFrame* option);
void QTableView_protectedbase_updateMicroFocus(VirtualQTableView* self);
void QTableView_protectedbase_create(VirtualQTableView* self);
void QTableView_protectedbase_destroy(VirtualQTableView* self);
bool QTableView_protectedbase_focusNextChild(VirtualQTableView* self);
bool QTableView_protectedbase_focusPreviousChild(VirtualQTableView* self);
QObject* QTableView_protectedbase_sender(const VirtualQTableView* self);
int QTableView_protectedbase_senderSignalIndex(const VirtualQTableView* self);
int QTableView_protectedbase_receivers(const VirtualQTableView* self, const char* signal);
bool QTableView_protectedbase_isSignalConnected(const VirtualQTableView* self, QMetaMethod* signal);

const QMetaObject* QTableView_staticMetaObject();
void QTableView_delete(QTableView* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
