#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QWIZARD_H
#define SEAQT_QTWIDGETS_GEN_QWIZARD_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt/libseaqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractButton;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDialog;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QHideEvent;
class QInputMethodEvent;
class QKeyEvent;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPixmap;
class QPoint;
class QResizeEvent;
class QShowEvent;
class QSize;
class QTabletEvent;
class QTimerEvent;
class QVariant;
class QWheelEvent;
class QWidget;
class QWizard;
class QWizardPage;
#else
typedef struct QAbstractButton QAbstractButton;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct QWizard QWizard;
typedef struct QWizardPage QWizardPage;
#endif

struct QWizard_VTable {
	void (*destructor)(struct QWizard_VTable* vtbl, QWizard* self);
	QMetaObject* (*metaObject)(struct QWizard_VTable* vtbl, const QWizard* self);
	void* (*metacast)(struct QWizard_VTable* vtbl, QWizard* self, const char* param1);
	int (*metacall)(struct QWizard_VTable* vtbl, QWizard* self, int param1, int param2, void** param3);
	bool (*validateCurrentPage)(struct QWizard_VTable* vtbl, QWizard* self);
	int (*nextId)(struct QWizard_VTable* vtbl, const QWizard* self);
	void (*setVisible)(struct QWizard_VTable* vtbl, QWizard* self, bool visible);
	QSize* (*sizeHint)(struct QWizard_VTable* vtbl, const QWizard* self);
	bool (*event)(struct QWizard_VTable* vtbl, QWizard* self, QEvent* event);
	void (*resizeEvent)(struct QWizard_VTable* vtbl, QWizard* self, QResizeEvent* event);
	void (*paintEvent)(struct QWizard_VTable* vtbl, QWizard* self, QPaintEvent* event);
	void (*done)(struct QWizard_VTable* vtbl, QWizard* self, int result);
	void (*initializePage)(struct QWizard_VTable* vtbl, QWizard* self, int id);
	void (*cleanupPage)(struct QWizard_VTable* vtbl, QWizard* self, int id);
	QSize* (*minimumSizeHint)(struct QWizard_VTable* vtbl, const QWizard* self);
	void (*open)(struct QWizard_VTable* vtbl, QWizard* self);
	int (*exec)(struct QWizard_VTable* vtbl, QWizard* self);
	void (*accept)(struct QWizard_VTable* vtbl, QWizard* self);
	void (*reject)(struct QWizard_VTable* vtbl, QWizard* self);
	void (*keyPressEvent)(struct QWizard_VTable* vtbl, QWizard* self, QKeyEvent* param1);
	void (*closeEvent)(struct QWizard_VTable* vtbl, QWizard* self, QCloseEvent* param1);
	void (*showEvent)(struct QWizard_VTable* vtbl, QWizard* self, QShowEvent* param1);
	void (*contextMenuEvent)(struct QWizard_VTable* vtbl, QWizard* self, QContextMenuEvent* param1);
	bool (*eventFilter)(struct QWizard_VTable* vtbl, QWizard* self, QObject* param1, QEvent* param2);
	int (*devType)(struct QWizard_VTable* vtbl, const QWizard* self);
	int (*heightForWidth)(struct QWizard_VTable* vtbl, const QWizard* self, int param1);
	bool (*hasHeightForWidth)(struct QWizard_VTable* vtbl, const QWizard* self);
	QPaintEngine* (*paintEngine)(struct QWizard_VTable* vtbl, const QWizard* self);
	void (*mousePressEvent)(struct QWizard_VTable* vtbl, QWizard* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(struct QWizard_VTable* vtbl, QWizard* self, QMouseEvent* event);
	void (*mouseDoubleClickEvent)(struct QWizard_VTable* vtbl, QWizard* self, QMouseEvent* event);
	void (*mouseMoveEvent)(struct QWizard_VTable* vtbl, QWizard* self, QMouseEvent* event);
	void (*wheelEvent)(struct QWizard_VTable* vtbl, QWizard* self, QWheelEvent* event);
	void (*keyReleaseEvent)(struct QWizard_VTable* vtbl, QWizard* self, QKeyEvent* event);
	void (*focusInEvent)(struct QWizard_VTable* vtbl, QWizard* self, QFocusEvent* event);
	void (*focusOutEvent)(struct QWizard_VTable* vtbl, QWizard* self, QFocusEvent* event);
	void (*enterEvent)(struct QWizard_VTable* vtbl, QWizard* self, QEvent* event);
	void (*leaveEvent)(struct QWizard_VTable* vtbl, QWizard* self, QEvent* event);
	void (*moveEvent)(struct QWizard_VTable* vtbl, QWizard* self, QMoveEvent* event);
	void (*tabletEvent)(struct QWizard_VTable* vtbl, QWizard* self, QTabletEvent* event);
	void (*actionEvent)(struct QWizard_VTable* vtbl, QWizard* self, QActionEvent* event);
	void (*dragEnterEvent)(struct QWizard_VTable* vtbl, QWizard* self, QDragEnterEvent* event);
	void (*dragMoveEvent)(struct QWizard_VTable* vtbl, QWizard* self, QDragMoveEvent* event);
	void (*dragLeaveEvent)(struct QWizard_VTable* vtbl, QWizard* self, QDragLeaveEvent* event);
	void (*dropEvent)(struct QWizard_VTable* vtbl, QWizard* self, QDropEvent* event);
	void (*hideEvent)(struct QWizard_VTable* vtbl, QWizard* self, QHideEvent* event);
	bool (*nativeEvent)(struct QWizard_VTable* vtbl, QWizard* self, struct miqt_string eventType, void* message, long* result);
	void (*changeEvent)(struct QWizard_VTable* vtbl, QWizard* self, QEvent* param1);
	int (*metric)(struct QWizard_VTable* vtbl, const QWizard* self, int param1);
	void (*initPainter)(struct QWizard_VTable* vtbl, const QWizard* self, QPainter* painter);
	QPaintDevice* (*redirected)(struct QWizard_VTable* vtbl, const QWizard* self, QPoint* offset);
	QPainter* (*sharedPainter)(struct QWizard_VTable* vtbl, const QWizard* self);
	void (*inputMethodEvent)(struct QWizard_VTable* vtbl, QWizard* self, QInputMethodEvent* param1);
	QVariant* (*inputMethodQuery)(struct QWizard_VTable* vtbl, const QWizard* self, int param1);
	bool (*focusNextPrevChild)(struct QWizard_VTable* vtbl, QWizard* self, bool next);
	void (*timerEvent)(struct QWizard_VTable* vtbl, QWizard* self, QTimerEvent* event);
	void (*childEvent)(struct QWizard_VTable* vtbl, QWizard* self, QChildEvent* event);
	void (*customEvent)(struct QWizard_VTable* vtbl, QWizard* self, QEvent* event);
	void (*connectNotify)(struct QWizard_VTable* vtbl, QWizard* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QWizard_VTable* vtbl, QWizard* self, QMetaMethod* signal);
};
QWizard* QWizard_new(struct QWizard_VTable* vtbl, QWidget* parent);
QWizard* QWizard_new2(struct QWizard_VTable* vtbl);
QWizard* QWizard_new3(struct QWizard_VTable* vtbl, QWidget* parent, int flags);
void QWizard_virtbase(QWizard* src, QDialog** outptr_QDialog);
QMetaObject* QWizard_metaObject(const QWizard* self);
void* QWizard_metacast(QWizard* self, const char* param1);
int QWizard_metacall(QWizard* self, int param1, int param2, void** param3);
struct miqt_string QWizard_tr(const char* s);
struct miqt_string QWizard_trUtf8(const char* s);
int QWizard_addPage(QWizard* self, QWizardPage* page);
void QWizard_setPage(QWizard* self, int id, QWizardPage* page);
void QWizard_removePage(QWizard* self, int id);
QWizardPage* QWizard_page(const QWizard* self, int id);
bool QWizard_hasVisitedPage(const QWizard* self, int id);
struct miqt_array /* of int */  QWizard_visitedPages(const QWizard* self);
struct miqt_array /* of int */  QWizard_visitedIds(const QWizard* self);
struct miqt_array /* of int */  QWizard_pageIds(const QWizard* self);
void QWizard_setStartId(QWizard* self, int id);
int QWizard_startId(const QWizard* self);
QWizardPage* QWizard_currentPage(const QWizard* self);
int QWizard_currentId(const QWizard* self);
bool QWizard_validateCurrentPage(QWizard* self);
int QWizard_nextId(const QWizard* self);
void QWizard_setField(QWizard* self, struct miqt_string name, QVariant* value);
QVariant* QWizard_field(const QWizard* self, struct miqt_string name);
void QWizard_setWizardStyle(QWizard* self, int style);
int QWizard_wizardStyle(const QWizard* self);
void QWizard_setOption(QWizard* self, int option);
bool QWizard_testOption(const QWizard* self, int option);
void QWizard_setOptions(QWizard* self, int options);
int QWizard_options(const QWizard* self);
void QWizard_setButtonText(QWizard* self, int which, struct miqt_string text);
struct miqt_string QWizard_buttonText(const QWizard* self, int which);
void QWizard_setButtonLayout(QWizard* self, struct miqt_array /* of int */  layout);
void QWizard_setButton(QWizard* self, int which, QAbstractButton* button);
QAbstractButton* QWizard_button(const QWizard* self, int which);
void QWizard_setTitleFormat(QWizard* self, int format);
int QWizard_titleFormat(const QWizard* self);
void QWizard_setSubTitleFormat(QWizard* self, int format);
int QWizard_subTitleFormat(const QWizard* self);
void QWizard_setPixmap(QWizard* self, int which, QPixmap* pixmap);
QPixmap* QWizard_pixmap(const QWizard* self, int which);
void QWizard_setSideWidget(QWizard* self, QWidget* widget);
QWidget* QWizard_sideWidget(const QWizard* self);
void QWizard_setDefaultProperty(QWizard* self, const char* className, const char* property, const char* changedSignal);
void QWizard_setVisible(QWizard* self, bool visible);
QSize* QWizard_sizeHint(const QWizard* self);
void QWizard_currentIdChanged(QWizard* self, int id);
void QWizard_connect_currentIdChanged(QWizard* self, intptr_t slot);
void QWizard_helpRequested(QWizard* self);
void QWizard_connect_helpRequested(QWizard* self, intptr_t slot);
void QWizard_customButtonClicked(QWizard* self, int which);
void QWizard_connect_customButtonClicked(QWizard* self, intptr_t slot);
void QWizard_pageAdded(QWizard* self, int id);
void QWizard_connect_pageAdded(QWizard* self, intptr_t slot);
void QWizard_pageRemoved(QWizard* self, int id);
void QWizard_connect_pageRemoved(QWizard* self, intptr_t slot);
void QWizard_back(QWizard* self);
void QWizard_next(QWizard* self);
void QWizard_restart(QWizard* self);
bool QWizard_event(QWizard* self, QEvent* event);
void QWizard_resizeEvent(QWizard* self, QResizeEvent* event);
void QWizard_paintEvent(QWizard* self, QPaintEvent* event);
void QWizard_done(QWizard* self, int result);
void QWizard_initializePage(QWizard* self, int id);
void QWizard_cleanupPage(QWizard* self, int id);
struct miqt_string QWizard_tr2(const char* s, const char* c);
struct miqt_string QWizard_tr3(const char* s, const char* c, int n);
struct miqt_string QWizard_trUtf82(const char* s, const char* c);
struct miqt_string QWizard_trUtf83(const char* s, const char* c, int n);
void QWizard_setOption2(QWizard* self, int option, bool on);
QMetaObject* QWizard_virtualbase_metaObject(const void* self);
void* QWizard_virtualbase_metacast(void* self, const char* param1);
int QWizard_virtualbase_metacall(void* self, int param1, int param2, void** param3);
bool QWizard_virtualbase_validateCurrentPage(void* self);
int QWizard_virtualbase_nextId(const void* self);
void QWizard_virtualbase_setVisible(void* self, bool visible);
QSize* QWizard_virtualbase_sizeHint(const void* self);
bool QWizard_virtualbase_event(void* self, QEvent* event);
void QWizard_virtualbase_resizeEvent(void* self, QResizeEvent* event);
void QWizard_virtualbase_paintEvent(void* self, QPaintEvent* event);
void QWizard_virtualbase_done(void* self, int result);
void QWizard_virtualbase_initializePage(void* self, int id);
void QWizard_virtualbase_cleanupPage(void* self, int id);
QSize* QWizard_virtualbase_minimumSizeHint(const void* self);
void QWizard_virtualbase_open(void* self);
int QWizard_virtualbase_exec(void* self);
void QWizard_virtualbase_accept(void* self);
void QWizard_virtualbase_reject(void* self);
void QWizard_virtualbase_keyPressEvent(void* self, QKeyEvent* param1);
void QWizard_virtualbase_closeEvent(void* self, QCloseEvent* param1);
void QWizard_virtualbase_showEvent(void* self, QShowEvent* param1);
void QWizard_virtualbase_contextMenuEvent(void* self, QContextMenuEvent* param1);
bool QWizard_virtualbase_eventFilter(void* self, QObject* param1, QEvent* param2);
int QWizard_virtualbase_devType(const void* self);
int QWizard_virtualbase_heightForWidth(const void* self, int param1);
bool QWizard_virtualbase_hasHeightForWidth(const void* self);
QPaintEngine* QWizard_virtualbase_paintEngine(const void* self);
void QWizard_virtualbase_mousePressEvent(void* self, QMouseEvent* event);
void QWizard_virtualbase_mouseReleaseEvent(void* self, QMouseEvent* event);
void QWizard_virtualbase_mouseDoubleClickEvent(void* self, QMouseEvent* event);
void QWizard_virtualbase_mouseMoveEvent(void* self, QMouseEvent* event);
void QWizard_virtualbase_wheelEvent(void* self, QWheelEvent* event);
void QWizard_virtualbase_keyReleaseEvent(void* self, QKeyEvent* event);
void QWizard_virtualbase_focusInEvent(void* self, QFocusEvent* event);
void QWizard_virtualbase_focusOutEvent(void* self, QFocusEvent* event);
void QWizard_virtualbase_enterEvent(void* self, QEvent* event);
void QWizard_virtualbase_leaveEvent(void* self, QEvent* event);
void QWizard_virtualbase_moveEvent(void* self, QMoveEvent* event);
void QWizard_virtualbase_tabletEvent(void* self, QTabletEvent* event);
void QWizard_virtualbase_actionEvent(void* self, QActionEvent* event);
void QWizard_virtualbase_dragEnterEvent(void* self, QDragEnterEvent* event);
void QWizard_virtualbase_dragMoveEvent(void* self, QDragMoveEvent* event);
void QWizard_virtualbase_dragLeaveEvent(void* self, QDragLeaveEvent* event);
void QWizard_virtualbase_dropEvent(void* self, QDropEvent* event);
void QWizard_virtualbase_hideEvent(void* self, QHideEvent* event);
bool QWizard_virtualbase_nativeEvent(void* self, struct miqt_string eventType, void* message, long* result);
void QWizard_virtualbase_changeEvent(void* self, QEvent* param1);
int QWizard_virtualbase_metric(const void* self, int param1);
void QWizard_virtualbase_initPainter(const void* self, QPainter* painter);
QPaintDevice* QWizard_virtualbase_redirected(const void* self, QPoint* offset);
QPainter* QWizard_virtualbase_sharedPainter(const void* self);
void QWizard_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* param1);
QVariant* QWizard_virtualbase_inputMethodQuery(const void* self, int param1);
bool QWizard_virtualbase_focusNextPrevChild(void* self, bool next);
void QWizard_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QWizard_virtualbase_childEvent(void* self, QChildEvent* event);
void QWizard_virtualbase_customEvent(void* self, QEvent* event);
void QWizard_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QWizard_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
void QWizard_protectedbase_adjustPosition(bool* _dynamic_cast_ok, void* self, QWidget* param1);
void QWizard_protectedbase_updateMicroFocus(bool* _dynamic_cast_ok, void* self);
void QWizard_protectedbase_create(bool* _dynamic_cast_ok, void* self);
void QWizard_protectedbase_destroy(bool* _dynamic_cast_ok, void* self);
bool QWizard_protectedbase_focusNextChild(bool* _dynamic_cast_ok, void* self);
bool QWizard_protectedbase_focusPreviousChild(bool* _dynamic_cast_ok, void* self);
QObject* QWizard_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QWizard_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QWizard_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QWizard_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
const QMetaObject* QWizard_staticMetaObject();
void QWizard_delete(QWizard* self);

struct QWizardPage_VTable {
	void (*destructor)(struct QWizardPage_VTable* vtbl, QWizardPage* self);
	QMetaObject* (*metaObject)(struct QWizardPage_VTable* vtbl, const QWizardPage* self);
	void* (*metacast)(struct QWizardPage_VTable* vtbl, QWizardPage* self, const char* param1);
	int (*metacall)(struct QWizardPage_VTable* vtbl, QWizardPage* self, int param1, int param2, void** param3);
	void (*initializePage)(struct QWizardPage_VTable* vtbl, QWizardPage* self);
	void (*cleanupPage)(struct QWizardPage_VTable* vtbl, QWizardPage* self);
	bool (*validatePage)(struct QWizardPage_VTable* vtbl, QWizardPage* self);
	bool (*isComplete)(struct QWizardPage_VTable* vtbl, const QWizardPage* self);
	int (*nextId)(struct QWizardPage_VTable* vtbl, const QWizardPage* self);
	int (*devType)(struct QWizardPage_VTable* vtbl, const QWizardPage* self);
	void (*setVisible)(struct QWizardPage_VTable* vtbl, QWizardPage* self, bool visible);
	QSize* (*sizeHint)(struct QWizardPage_VTable* vtbl, const QWizardPage* self);
	QSize* (*minimumSizeHint)(struct QWizardPage_VTable* vtbl, const QWizardPage* self);
	int (*heightForWidth)(struct QWizardPage_VTable* vtbl, const QWizardPage* self, int param1);
	bool (*hasHeightForWidth)(struct QWizardPage_VTable* vtbl, const QWizardPage* self);
	QPaintEngine* (*paintEngine)(struct QWizardPage_VTable* vtbl, const QWizardPage* self);
	bool (*event)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QEvent* event);
	void (*mousePressEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QMouseEvent* event);
	void (*mouseDoubleClickEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QMouseEvent* event);
	void (*mouseMoveEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QMouseEvent* event);
	void (*wheelEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QWheelEvent* event);
	void (*keyPressEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QKeyEvent* event);
	void (*keyReleaseEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QKeyEvent* event);
	void (*focusInEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QFocusEvent* event);
	void (*focusOutEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QFocusEvent* event);
	void (*enterEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QEvent* event);
	void (*leaveEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QEvent* event);
	void (*paintEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QPaintEvent* event);
	void (*moveEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QMoveEvent* event);
	void (*resizeEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QResizeEvent* event);
	void (*closeEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QCloseEvent* event);
	void (*contextMenuEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QContextMenuEvent* event);
	void (*tabletEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QTabletEvent* event);
	void (*actionEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QActionEvent* event);
	void (*dragEnterEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QDragEnterEvent* event);
	void (*dragMoveEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QDragMoveEvent* event);
	void (*dragLeaveEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QDragLeaveEvent* event);
	void (*dropEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QDropEvent* event);
	void (*showEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QShowEvent* event);
	void (*hideEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QHideEvent* event);
	bool (*nativeEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, struct miqt_string eventType, void* message, long* result);
	void (*changeEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QEvent* param1);
	int (*metric)(struct QWizardPage_VTable* vtbl, const QWizardPage* self, int param1);
	void (*initPainter)(struct QWizardPage_VTable* vtbl, const QWizardPage* self, QPainter* painter);
	QPaintDevice* (*redirected)(struct QWizardPage_VTable* vtbl, const QWizardPage* self, QPoint* offset);
	QPainter* (*sharedPainter)(struct QWizardPage_VTable* vtbl, const QWizardPage* self);
	void (*inputMethodEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QInputMethodEvent* param1);
	QVariant* (*inputMethodQuery)(struct QWizardPage_VTable* vtbl, const QWizardPage* self, int param1);
	bool (*focusNextPrevChild)(struct QWizardPage_VTable* vtbl, QWizardPage* self, bool next);
	bool (*eventFilter)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QObject* watched, QEvent* event);
	void (*timerEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QTimerEvent* event);
	void (*childEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QChildEvent* event);
	void (*customEvent)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QEvent* event);
	void (*connectNotify)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QWizardPage_VTable* vtbl, QWizardPage* self, QMetaMethod* signal);
};
QWizardPage* QWizardPage_new(struct QWizardPage_VTable* vtbl, QWidget* parent);
QWizardPage* QWizardPage_new2(struct QWizardPage_VTable* vtbl);
void QWizardPage_virtbase(QWizardPage* src, QWidget** outptr_QWidget);
QMetaObject* QWizardPage_metaObject(const QWizardPage* self);
void* QWizardPage_metacast(QWizardPage* self, const char* param1);
int QWizardPage_metacall(QWizardPage* self, int param1, int param2, void** param3);
struct miqt_string QWizardPage_tr(const char* s);
struct miqt_string QWizardPage_trUtf8(const char* s);
void QWizardPage_setTitle(QWizardPage* self, struct miqt_string title);
struct miqt_string QWizardPage_title(const QWizardPage* self);
void QWizardPage_setSubTitle(QWizardPage* self, struct miqt_string subTitle);
struct miqt_string QWizardPage_subTitle(const QWizardPage* self);
void QWizardPage_setPixmap(QWizardPage* self, int which, QPixmap* pixmap);
QPixmap* QWizardPage_pixmap(const QWizardPage* self, int which);
void QWizardPage_setFinalPage(QWizardPage* self, bool finalPage);
bool QWizardPage_isFinalPage(const QWizardPage* self);
void QWizardPage_setCommitPage(QWizardPage* self, bool commitPage);
bool QWizardPage_isCommitPage(const QWizardPage* self);
void QWizardPage_setButtonText(QWizardPage* self, int which, struct miqt_string text);
struct miqt_string QWizardPage_buttonText(const QWizardPage* self, int which);
void QWizardPage_initializePage(QWizardPage* self);
void QWizardPage_cleanupPage(QWizardPage* self);
bool QWizardPage_validatePage(QWizardPage* self);
bool QWizardPage_isComplete(const QWizardPage* self);
int QWizardPage_nextId(const QWizardPage* self);
void QWizardPage_completeChanged(QWizardPage* self);
void QWizardPage_connect_completeChanged(QWizardPage* self, intptr_t slot);
struct miqt_string QWizardPage_tr2(const char* s, const char* c);
struct miqt_string QWizardPage_tr3(const char* s, const char* c, int n);
struct miqt_string QWizardPage_trUtf82(const char* s, const char* c);
struct miqt_string QWizardPage_trUtf83(const char* s, const char* c, int n);
QMetaObject* QWizardPage_virtualbase_metaObject(const void* self);
void* QWizardPage_virtualbase_metacast(void* self, const char* param1);
int QWizardPage_virtualbase_metacall(void* self, int param1, int param2, void** param3);
void QWizardPage_virtualbase_initializePage(void* self);
void QWizardPage_virtualbase_cleanupPage(void* self);
bool QWizardPage_virtualbase_validatePage(void* self);
bool QWizardPage_virtualbase_isComplete(const void* self);
int QWizardPage_virtualbase_nextId(const void* self);
int QWizardPage_virtualbase_devType(const void* self);
void QWizardPage_virtualbase_setVisible(void* self, bool visible);
QSize* QWizardPage_virtualbase_sizeHint(const void* self);
QSize* QWizardPage_virtualbase_minimumSizeHint(const void* self);
int QWizardPage_virtualbase_heightForWidth(const void* self, int param1);
bool QWizardPage_virtualbase_hasHeightForWidth(const void* self);
QPaintEngine* QWizardPage_virtualbase_paintEngine(const void* self);
bool QWizardPage_virtualbase_event(void* self, QEvent* event);
void QWizardPage_virtualbase_mousePressEvent(void* self, QMouseEvent* event);
void QWizardPage_virtualbase_mouseReleaseEvent(void* self, QMouseEvent* event);
void QWizardPage_virtualbase_mouseDoubleClickEvent(void* self, QMouseEvent* event);
void QWizardPage_virtualbase_mouseMoveEvent(void* self, QMouseEvent* event);
void QWizardPage_virtualbase_wheelEvent(void* self, QWheelEvent* event);
void QWizardPage_virtualbase_keyPressEvent(void* self, QKeyEvent* event);
void QWizardPage_virtualbase_keyReleaseEvent(void* self, QKeyEvent* event);
void QWizardPage_virtualbase_focusInEvent(void* self, QFocusEvent* event);
void QWizardPage_virtualbase_focusOutEvent(void* self, QFocusEvent* event);
void QWizardPage_virtualbase_enterEvent(void* self, QEvent* event);
void QWizardPage_virtualbase_leaveEvent(void* self, QEvent* event);
void QWizardPage_virtualbase_paintEvent(void* self, QPaintEvent* event);
void QWizardPage_virtualbase_moveEvent(void* self, QMoveEvent* event);
void QWizardPage_virtualbase_resizeEvent(void* self, QResizeEvent* event);
void QWizardPage_virtualbase_closeEvent(void* self, QCloseEvent* event);
void QWizardPage_virtualbase_contextMenuEvent(void* self, QContextMenuEvent* event);
void QWizardPage_virtualbase_tabletEvent(void* self, QTabletEvent* event);
void QWizardPage_virtualbase_actionEvent(void* self, QActionEvent* event);
void QWizardPage_virtualbase_dragEnterEvent(void* self, QDragEnterEvent* event);
void QWizardPage_virtualbase_dragMoveEvent(void* self, QDragMoveEvent* event);
void QWizardPage_virtualbase_dragLeaveEvent(void* self, QDragLeaveEvent* event);
void QWizardPage_virtualbase_dropEvent(void* self, QDropEvent* event);
void QWizardPage_virtualbase_showEvent(void* self, QShowEvent* event);
void QWizardPage_virtualbase_hideEvent(void* self, QHideEvent* event);
bool QWizardPage_virtualbase_nativeEvent(void* self, struct miqt_string eventType, void* message, long* result);
void QWizardPage_virtualbase_changeEvent(void* self, QEvent* param1);
int QWizardPage_virtualbase_metric(const void* self, int param1);
void QWizardPage_virtualbase_initPainter(const void* self, QPainter* painter);
QPaintDevice* QWizardPage_virtualbase_redirected(const void* self, QPoint* offset);
QPainter* QWizardPage_virtualbase_sharedPainter(const void* self);
void QWizardPage_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* param1);
QVariant* QWizardPage_virtualbase_inputMethodQuery(const void* self, int param1);
bool QWizardPage_virtualbase_focusNextPrevChild(void* self, bool next);
bool QWizardPage_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
void QWizardPage_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QWizardPage_virtualbase_childEvent(void* self, QChildEvent* event);
void QWizardPage_virtualbase_customEvent(void* self, QEvent* event);
void QWizardPage_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QWizardPage_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
void QWizardPage_protectedbase_setField(bool* _dynamic_cast_ok, void* self, struct miqt_string name, QVariant* value);
QVariant* QWizardPage_protectedbase_field(bool* _dynamic_cast_ok, const void* self, struct miqt_string name);
void QWizardPage_protectedbase_registerField(bool* _dynamic_cast_ok, void* self, struct miqt_string name, QWidget* widget);
QWizard* QWizardPage_protectedbase_wizard(bool* _dynamic_cast_ok, const void* self);
void QWizardPage_protectedbase_registerField3(bool* _dynamic_cast_ok, void* self, struct miqt_string name, QWidget* widget, const char* property);
void QWizardPage_protectedbase_registerField4(bool* _dynamic_cast_ok, void* self, struct miqt_string name, QWidget* widget, const char* property, const char* changedSignal);
void QWizardPage_protectedbase_updateMicroFocus(bool* _dynamic_cast_ok, void* self);
void QWizardPage_protectedbase_create(bool* _dynamic_cast_ok, void* self);
void QWizardPage_protectedbase_destroy(bool* _dynamic_cast_ok, void* self);
bool QWizardPage_protectedbase_focusNextChild(bool* _dynamic_cast_ok, void* self);
bool QWizardPage_protectedbase_focusPreviousChild(bool* _dynamic_cast_ok, void* self);
QObject* QWizardPage_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QWizardPage_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QWizardPage_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QWizardPage_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
const QMetaObject* QWizardPage_staticMetaObject();
void QWizardPage_delete(QWizardPage* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
