#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QTEXTEDIT_H
#define SEAQT_QTWIDGETS_GEN_QTEXTEDIT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt-runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractScrollArea;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QColor;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QFont;
class QFrame;
class QHideEvent;
class QInputMethodEvent;
class QKeyEvent;
class QMargins;
class QMenu;
class QMetaMethod;
class QMetaObject;
class QMimeData;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPagedPaintDevice;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QRect;
class QRegExp;
class QRegularExpression;
class QResizeEvent;
class QShowEvent;
class QSize;
class QStyleOptionFrame;
class QTabletEvent;
class QTextCharFormat;
class QTextCursor;
class QTextDocument;
class QTextEdit;
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QTextEdit__ExtraSelection)
typedef QTextEdit::ExtraSelection QTextEdit__ExtraSelection;
#else
class QTextEdit__ExtraSelection;
#endif
class QTimerEvent;
class QUrl;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QColor QColor;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMenu QMenu;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPagedPaintDevice QPagedPaintDevice;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegExp QRegExp;
typedef struct QRegularExpression QRegularExpression;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTextCharFormat QTextCharFormat;
typedef struct QTextCursor QTextCursor;
typedef struct QTextDocument QTextDocument;
typedef struct QTextEdit QTextEdit;
typedef struct QTextEdit__ExtraSelection QTextEdit__ExtraSelection;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

typedef struct VirtualQTextEdit VirtualQTextEdit;
typedef struct QTextEdit_VTable{
	void (*destructor)(VirtualQTextEdit* self);
	QMetaObject* (*metaObject)(const VirtualQTextEdit* self);
	void* (*metacast)(VirtualQTextEdit* self, const char* param1);
	int (*metacall)(VirtualQTextEdit* self, int param1, int param2, void** param3);
	QVariant* (*loadResource)(VirtualQTextEdit* self, int type, QUrl* name);
	QVariant* (*inputMethodQuery_property)(const VirtualQTextEdit* self, int property);
	bool (*event)(VirtualQTextEdit* self, QEvent* e);
	void (*timerEvent)(VirtualQTextEdit* self, QTimerEvent* e);
	void (*keyPressEvent)(VirtualQTextEdit* self, QKeyEvent* e);
	void (*keyReleaseEvent)(VirtualQTextEdit* self, QKeyEvent* e);
	void (*resizeEvent)(VirtualQTextEdit* self, QResizeEvent* e);
	void (*paintEvent)(VirtualQTextEdit* self, QPaintEvent* e);
	void (*mousePressEvent)(VirtualQTextEdit* self, QMouseEvent* e);
	void (*mouseMoveEvent)(VirtualQTextEdit* self, QMouseEvent* e);
	void (*mouseReleaseEvent)(VirtualQTextEdit* self, QMouseEvent* e);
	void (*mouseDoubleClickEvent)(VirtualQTextEdit* self, QMouseEvent* e);
	bool (*focusNextPrevChild)(VirtualQTextEdit* self, bool next);
	void (*contextMenuEvent)(VirtualQTextEdit* self, QContextMenuEvent* e);
	void (*dragEnterEvent)(VirtualQTextEdit* self, QDragEnterEvent* e);
	void (*dragLeaveEvent)(VirtualQTextEdit* self, QDragLeaveEvent* e);
	void (*dragMoveEvent)(VirtualQTextEdit* self, QDragMoveEvent* e);
	void (*dropEvent)(VirtualQTextEdit* self, QDropEvent* e);
	void (*focusInEvent)(VirtualQTextEdit* self, QFocusEvent* e);
	void (*focusOutEvent)(VirtualQTextEdit* self, QFocusEvent* e);
	void (*showEvent)(VirtualQTextEdit* self, QShowEvent* param1);
	void (*changeEvent)(VirtualQTextEdit* self, QEvent* e);
	void (*wheelEvent)(VirtualQTextEdit* self, QWheelEvent* e);
	QMimeData* (*createMimeDataFromSelection)(const VirtualQTextEdit* self);
	bool (*canInsertFromMimeData)(const VirtualQTextEdit* self, QMimeData* source);
	void (*insertFromMimeData)(VirtualQTextEdit* self, QMimeData* source);
	void (*inputMethodEvent)(VirtualQTextEdit* self, QInputMethodEvent* param1);
	void (*scrollContentsBy)(VirtualQTextEdit* self, int dx, int dy);
	void (*doSetTextCursor)(VirtualQTextEdit* self, QTextCursor* cursor);
	QSize* (*minimumSizeHint)(const VirtualQTextEdit* self);
	QSize* (*sizeHint)(const VirtualQTextEdit* self);
	void (*setupViewport)(VirtualQTextEdit* self, QWidget* viewport);
	bool (*eventFilter)(VirtualQTextEdit* self, QObject* param1, QEvent* param2);
	bool (*viewportEvent)(VirtualQTextEdit* self, QEvent* param1);
	QSize* (*viewportSizeHint)(const VirtualQTextEdit* self);
	int (*devType)(const VirtualQTextEdit* self);
	void (*setVisible)(VirtualQTextEdit* self, bool visible);
	int (*heightForWidth)(const VirtualQTextEdit* self, int param1);
	bool (*hasHeightForWidth)(const VirtualQTextEdit* self);
	QPaintEngine* (*paintEngine)(const VirtualQTextEdit* self);
	void (*enterEvent)(VirtualQTextEdit* self, QEvent* event);
	void (*leaveEvent)(VirtualQTextEdit* self, QEvent* event);
	void (*moveEvent)(VirtualQTextEdit* self, QMoveEvent* event);
	void (*closeEvent)(VirtualQTextEdit* self, QCloseEvent* event);
	void (*tabletEvent)(VirtualQTextEdit* self, QTabletEvent* event);
	void (*actionEvent)(VirtualQTextEdit* self, QActionEvent* event);
	void (*hideEvent)(VirtualQTextEdit* self, QHideEvent* event);
	bool (*nativeEvent)(VirtualQTextEdit* self, struct seaqt_string eventType, void* message, long* result);
	int (*metric)(const VirtualQTextEdit* self, int param1);
	void (*initPainter)(const VirtualQTextEdit* self, QPainter* painter);
	QPaintDevice* (*redirected)(const VirtualQTextEdit* self, QPoint* offset);
	QPainter* (*sharedPainter)(const VirtualQTextEdit* self);
	void (*childEvent)(VirtualQTextEdit* self, QChildEvent* event);
	void (*customEvent)(VirtualQTextEdit* self, QEvent* event);
	void (*connectNotify)(VirtualQTextEdit* self, QMetaMethod* signal);
	void (*disconnectNotify)(VirtualQTextEdit* self, QMetaMethod* signal);
}QTextEdit_VTable;

void* QTextEdit_vdata(VirtualQTextEdit* self);
VirtualQTextEdit* vdata_QTextEdit(void* vdata);

VirtualQTextEdit* QTextEdit_new(const QTextEdit_VTable* vtbl, size_t vdata);
VirtualQTextEdit* QTextEdit_new_text(const QTextEdit_VTable* vtbl, size_t vdata, struct seaqt_string text);
VirtualQTextEdit* QTextEdit_new_parent(const QTextEdit_VTable* vtbl, size_t vdata, QWidget* parent);
VirtualQTextEdit* QTextEdit_new_text_parent(const QTextEdit_VTable* vtbl, size_t vdata, struct seaqt_string text, QWidget* parent);

void QTextEdit_virtbase(QTextEdit* src, QAbstractScrollArea** outptr_QAbstractScrollArea);
QMetaObject* QTextEdit_metaObject(const QTextEdit* self);
void* QTextEdit_metacast(QTextEdit* self, const char* param1);
int QTextEdit_metacall(QTextEdit* self, int param1, int param2, void** param3);
struct seaqt_string QTextEdit_tr_s(const char* s);
struct seaqt_string QTextEdit_trUtf8_s(const char* s);
void QTextEdit_setDocument(QTextEdit* self, QTextDocument* document);
QTextDocument* QTextEdit_document(const QTextEdit* self);
void QTextEdit_setPlaceholderText(QTextEdit* self, struct seaqt_string placeholderText);
struct seaqt_string QTextEdit_placeholderText(const QTextEdit* self);
void QTextEdit_setTextCursor(QTextEdit* self, QTextCursor* cursor);
QTextCursor* QTextEdit_textCursor(const QTextEdit* self);
bool QTextEdit_isReadOnly(const QTextEdit* self);
void QTextEdit_setReadOnly(QTextEdit* self, bool ro);
void QTextEdit_setTextInteractionFlags(QTextEdit* self, int flags);
int QTextEdit_textInteractionFlags(const QTextEdit* self);
double QTextEdit_fontPointSize(const QTextEdit* self);
struct seaqt_string QTextEdit_fontFamily(const QTextEdit* self);
int QTextEdit_fontWeight(const QTextEdit* self);
bool QTextEdit_fontUnderline(const QTextEdit* self);
bool QTextEdit_fontItalic(const QTextEdit* self);
QColor* QTextEdit_textColor(const QTextEdit* self);
QColor* QTextEdit_textBackgroundColor(const QTextEdit* self);
QFont* QTextEdit_currentFont(const QTextEdit* self);
int QTextEdit_alignment(const QTextEdit* self);
void QTextEdit_mergeCurrentCharFormat(QTextEdit* self, QTextCharFormat* modifier);
void QTextEdit_setCurrentCharFormat(QTextEdit* self, QTextCharFormat* format);
QTextCharFormat* QTextEdit_currentCharFormat(const QTextEdit* self);
int QTextEdit_autoFormatting(const QTextEdit* self);
void QTextEdit_setAutoFormatting(QTextEdit* self, int features);
bool QTextEdit_tabChangesFocus(const QTextEdit* self);
void QTextEdit_setTabChangesFocus(QTextEdit* self, bool b);
void QTextEdit_setDocumentTitle(QTextEdit* self, struct seaqt_string title);
struct seaqt_string QTextEdit_documentTitle(const QTextEdit* self);
bool QTextEdit_isUndoRedoEnabled(const QTextEdit* self);
void QTextEdit_setUndoRedoEnabled(QTextEdit* self, bool enable);
int QTextEdit_lineWrapMode(const QTextEdit* self);
void QTextEdit_setLineWrapMode(QTextEdit* self, int mode);
int QTextEdit_lineWrapColumnOrWidth(const QTextEdit* self);
void QTextEdit_setLineWrapColumnOrWidth(QTextEdit* self, int w);
int QTextEdit_wordWrapMode(const QTextEdit* self);
void QTextEdit_setWordWrapMode(QTextEdit* self, int policy);
bool QTextEdit_find_QString(QTextEdit* self, struct seaqt_string exp);
bool QTextEdit_find_QRegExp(QTextEdit* self, QRegExp* exp);
bool QTextEdit_find_QRegularExpression(QTextEdit* self, QRegularExpression* exp);
struct seaqt_string QTextEdit_toPlainText(const QTextEdit* self);
struct seaqt_string QTextEdit_toHtml(const QTextEdit* self);
struct seaqt_string QTextEdit_toMarkdown(const QTextEdit* self);
void QTextEdit_ensureCursorVisible(QTextEdit* self);
QVariant* QTextEdit_loadResource(QTextEdit* self, int type, QUrl* name);
QMenu* QTextEdit_createStandardContextMenu(QTextEdit* self);
QMenu* QTextEdit_createStandardContextMenu_position(QTextEdit* self, QPoint* position);
QTextCursor* QTextEdit_cursorForPosition(const QTextEdit* self, QPoint* pos);
QRect* QTextEdit_cursorRect_cursor(const QTextEdit* self, QTextCursor* cursor);
QRect* QTextEdit_cursorRect(const QTextEdit* self);
struct seaqt_string QTextEdit_anchorAt(const QTextEdit* self, QPoint* pos);
bool QTextEdit_overwriteMode(const QTextEdit* self);
void QTextEdit_setOverwriteMode(QTextEdit* self, bool overwrite);
int QTextEdit_tabStopWidth(const QTextEdit* self);
void QTextEdit_setTabStopWidth(QTextEdit* self, int width);
double QTextEdit_tabStopDistance(const QTextEdit* self);
void QTextEdit_setTabStopDistance(QTextEdit* self, double distance);
int QTextEdit_cursorWidth(const QTextEdit* self);
void QTextEdit_setCursorWidth(QTextEdit* self, int width);
bool QTextEdit_acceptRichText(const QTextEdit* self);
void QTextEdit_setAcceptRichText(QTextEdit* self, bool accept);
void QTextEdit_setExtraSelections(QTextEdit* self, struct seaqt_array /* of QTextEdit__ExtraSelection* */  selections);
struct seaqt_array /* of QTextEdit__ExtraSelection* */  QTextEdit_extraSelections(const QTextEdit* self);
void QTextEdit_moveCursor_operation(QTextEdit* self, int operation);
bool QTextEdit_canPaste(const QTextEdit* self);
void QTextEdit_print(const QTextEdit* self, QPagedPaintDevice* printer);
QVariant* QTextEdit_inputMethodQuery_property(const QTextEdit* self, int property);
QVariant* QTextEdit_inputMethodQuery_query_argument(const QTextEdit* self, int query, QVariant* argument);
void QTextEdit_setFontPointSize(QTextEdit* self, double s);
void QTextEdit_setFontFamily(QTextEdit* self, struct seaqt_string fontFamily);
void QTextEdit_setFontWeight(QTextEdit* self, int w);
void QTextEdit_setFontUnderline(QTextEdit* self, bool b);
void QTextEdit_setFontItalic(QTextEdit* self, bool b);
void QTextEdit_setTextColor(QTextEdit* self, QColor* c);
void QTextEdit_setTextBackgroundColor(QTextEdit* self, QColor* c);
void QTextEdit_setCurrentFont(QTextEdit* self, QFont* f);
void QTextEdit_setAlignment(QTextEdit* self, int a);
void QTextEdit_setPlainText(QTextEdit* self, struct seaqt_string text);
void QTextEdit_setHtml(QTextEdit* self, struct seaqt_string text);
void QTextEdit_setMarkdown(QTextEdit* self, struct seaqt_string markdown);
void QTextEdit_setText(QTextEdit* self, struct seaqt_string text);
void QTextEdit_cut(QTextEdit* self);
void QTextEdit_copy(QTextEdit* self);
void QTextEdit_paste(QTextEdit* self);
void QTextEdit_undo(QTextEdit* self);
void QTextEdit_redo(QTextEdit* self);
void QTextEdit_clear(QTextEdit* self);
void QTextEdit_selectAll(QTextEdit* self);
void QTextEdit_insertPlainText(QTextEdit* self, struct seaqt_string text);
void QTextEdit_insertHtml(QTextEdit* self, struct seaqt_string text);
void QTextEdit_append(QTextEdit* self, struct seaqt_string text);
void QTextEdit_scrollToAnchor(QTextEdit* self, struct seaqt_string name);
void QTextEdit_zoomIn(QTextEdit* self);
void QTextEdit_zoomOut(QTextEdit* self);
void QTextEdit_textChanged(QTextEdit* self);
void QTextEdit_connect_textChanged(QTextEdit* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QTextEdit_undoAvailable(QTextEdit* self, bool b);
void QTextEdit_connect_undoAvailable(QTextEdit* self, intptr_t slot, void (*callback)(intptr_t, bool), void (*release)(intptr_t));
void QTextEdit_redoAvailable(QTextEdit* self, bool b);
void QTextEdit_connect_redoAvailable(QTextEdit* self, intptr_t slot, void (*callback)(intptr_t, bool), void (*release)(intptr_t));
void QTextEdit_currentCharFormatChanged(QTextEdit* self, QTextCharFormat* format);
void QTextEdit_connect_currentCharFormatChanged(QTextEdit* self, intptr_t slot, void (*callback)(intptr_t, QTextCharFormat*), void (*release)(intptr_t));
void QTextEdit_copyAvailable(QTextEdit* self, bool b);
void QTextEdit_connect_copyAvailable(QTextEdit* self, intptr_t slot, void (*callback)(intptr_t, bool), void (*release)(intptr_t));
void QTextEdit_selectionChanged(QTextEdit* self);
void QTextEdit_connect_selectionChanged(QTextEdit* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QTextEdit_cursorPositionChanged(QTextEdit* self);
void QTextEdit_connect_cursorPositionChanged(QTextEdit* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
bool QTextEdit_event(QTextEdit* self, QEvent* e);
void QTextEdit_timerEvent(QTextEdit* self, QTimerEvent* e);
void QTextEdit_keyPressEvent(QTextEdit* self, QKeyEvent* e);
void QTextEdit_keyReleaseEvent(QTextEdit* self, QKeyEvent* e);
void QTextEdit_resizeEvent(QTextEdit* self, QResizeEvent* e);
void QTextEdit_paintEvent(QTextEdit* self, QPaintEvent* e);
void QTextEdit_mousePressEvent(QTextEdit* self, QMouseEvent* e);
void QTextEdit_mouseMoveEvent(QTextEdit* self, QMouseEvent* e);
void QTextEdit_mouseReleaseEvent(QTextEdit* self, QMouseEvent* e);
void QTextEdit_mouseDoubleClickEvent(QTextEdit* self, QMouseEvent* e);
bool QTextEdit_focusNextPrevChild(QTextEdit* self, bool next);
void QTextEdit_contextMenuEvent(QTextEdit* self, QContextMenuEvent* e);
void QTextEdit_dragEnterEvent(QTextEdit* self, QDragEnterEvent* e);
void QTextEdit_dragLeaveEvent(QTextEdit* self, QDragLeaveEvent* e);
void QTextEdit_dragMoveEvent(QTextEdit* self, QDragMoveEvent* e);
void QTextEdit_dropEvent(QTextEdit* self, QDropEvent* e);
void QTextEdit_focusInEvent(QTextEdit* self, QFocusEvent* e);
void QTextEdit_focusOutEvent(QTextEdit* self, QFocusEvent* e);
void QTextEdit_showEvent(QTextEdit* self, QShowEvent* param1);
void QTextEdit_changeEvent(QTextEdit* self, QEvent* e);
void QTextEdit_wheelEvent(QTextEdit* self, QWheelEvent* e);
QMimeData* QTextEdit_createMimeDataFromSelection(const QTextEdit* self);
bool QTextEdit_canInsertFromMimeData(const QTextEdit* self, QMimeData* source);
void QTextEdit_insertFromMimeData(QTextEdit* self, QMimeData* source);
void QTextEdit_inputMethodEvent(QTextEdit* self, QInputMethodEvent* param1);
void QTextEdit_scrollContentsBy(QTextEdit* self, int dx, int dy);
void QTextEdit_doSetTextCursor(QTextEdit* self, QTextCursor* cursor);
struct seaqt_string QTextEdit_tr_s_c(const char* s, const char* c);
struct seaqt_string QTextEdit_tr_s_c_n(const char* s, const char* c, int n);
struct seaqt_string QTextEdit_trUtf8_s_c(const char* s, const char* c);
struct seaqt_string QTextEdit_trUtf8_s_c_n(const char* s, const char* c, int n);
bool QTextEdit_find_QString_QTextDocument_FindFlags(QTextEdit* self, struct seaqt_string exp, int options);
bool QTextEdit_find_QRegExp_QTextDocument_FindFlags(QTextEdit* self, QRegExp* exp, int options);
bool QTextEdit_find_QRegularExpression_QTextDocument_FindFlags(QTextEdit* self, QRegularExpression* exp, int options);
struct seaqt_string QTextEdit_toMarkdown_features(const QTextEdit* self, int features);
void QTextEdit_moveCursor_operation_mode(QTextEdit* self, int operation, int mode);
void QTextEdit_zoomIn_range(QTextEdit* self, int range);
void QTextEdit_zoomOut_range(QTextEdit* self, int range);

QMetaObject* QTextEdit_virtualbase_metaObject(const VirtualQTextEdit* self);
void* QTextEdit_virtualbase_metacast(VirtualQTextEdit* self, const char* param1);
int QTextEdit_virtualbase_metacall(VirtualQTextEdit* self, int param1, int param2, void** param3);
QVariant* QTextEdit_virtualbase_loadResource(VirtualQTextEdit* self, int type, QUrl* name);
QVariant* QTextEdit_virtualbase_inputMethodQuery_property(const VirtualQTextEdit* self, int property);
bool QTextEdit_virtualbase_event(VirtualQTextEdit* self, QEvent* e);
void QTextEdit_virtualbase_timerEvent(VirtualQTextEdit* self, QTimerEvent* e);
void QTextEdit_virtualbase_keyPressEvent(VirtualQTextEdit* self, QKeyEvent* e);
void QTextEdit_virtualbase_keyReleaseEvent(VirtualQTextEdit* self, QKeyEvent* e);
void QTextEdit_virtualbase_resizeEvent(VirtualQTextEdit* self, QResizeEvent* e);
void QTextEdit_virtualbase_paintEvent(VirtualQTextEdit* self, QPaintEvent* e);
void QTextEdit_virtualbase_mousePressEvent(VirtualQTextEdit* self, QMouseEvent* e);
void QTextEdit_virtualbase_mouseMoveEvent(VirtualQTextEdit* self, QMouseEvent* e);
void QTextEdit_virtualbase_mouseReleaseEvent(VirtualQTextEdit* self, QMouseEvent* e);
void QTextEdit_virtualbase_mouseDoubleClickEvent(VirtualQTextEdit* self, QMouseEvent* e);
bool QTextEdit_virtualbase_focusNextPrevChild(VirtualQTextEdit* self, bool next);
void QTextEdit_virtualbase_contextMenuEvent(VirtualQTextEdit* self, QContextMenuEvent* e);
void QTextEdit_virtualbase_dragEnterEvent(VirtualQTextEdit* self, QDragEnterEvent* e);
void QTextEdit_virtualbase_dragLeaveEvent(VirtualQTextEdit* self, QDragLeaveEvent* e);
void QTextEdit_virtualbase_dragMoveEvent(VirtualQTextEdit* self, QDragMoveEvent* e);
void QTextEdit_virtualbase_dropEvent(VirtualQTextEdit* self, QDropEvent* e);
void QTextEdit_virtualbase_focusInEvent(VirtualQTextEdit* self, QFocusEvent* e);
void QTextEdit_virtualbase_focusOutEvent(VirtualQTextEdit* self, QFocusEvent* e);
void QTextEdit_virtualbase_showEvent(VirtualQTextEdit* self, QShowEvent* param1);
void QTextEdit_virtualbase_changeEvent(VirtualQTextEdit* self, QEvent* e);
void QTextEdit_virtualbase_wheelEvent(VirtualQTextEdit* self, QWheelEvent* e);
QMimeData* QTextEdit_virtualbase_createMimeDataFromSelection(const VirtualQTextEdit* self);
bool QTextEdit_virtualbase_canInsertFromMimeData(const VirtualQTextEdit* self, QMimeData* source);
void QTextEdit_virtualbase_insertFromMimeData(VirtualQTextEdit* self, QMimeData* source);
void QTextEdit_virtualbase_inputMethodEvent(VirtualQTextEdit* self, QInputMethodEvent* param1);
void QTextEdit_virtualbase_scrollContentsBy(VirtualQTextEdit* self, int dx, int dy);
void QTextEdit_virtualbase_doSetTextCursor(VirtualQTextEdit* self, QTextCursor* cursor);
QSize* QTextEdit_virtualbase_minimumSizeHint(const VirtualQTextEdit* self);
QSize* QTextEdit_virtualbase_sizeHint(const VirtualQTextEdit* self);
void QTextEdit_virtualbase_setupViewport(VirtualQTextEdit* self, QWidget* viewport);
bool QTextEdit_virtualbase_eventFilter(VirtualQTextEdit* self, QObject* param1, QEvent* param2);
bool QTextEdit_virtualbase_viewportEvent(VirtualQTextEdit* self, QEvent* param1);
QSize* QTextEdit_virtualbase_viewportSizeHint(const VirtualQTextEdit* self);
int QTextEdit_virtualbase_devType(const VirtualQTextEdit* self);
void QTextEdit_virtualbase_setVisible(VirtualQTextEdit* self, bool visible);
int QTextEdit_virtualbase_heightForWidth(const VirtualQTextEdit* self, int param1);
bool QTextEdit_virtualbase_hasHeightForWidth(const VirtualQTextEdit* self);
QPaintEngine* QTextEdit_virtualbase_paintEngine(const VirtualQTextEdit* self);
void QTextEdit_virtualbase_enterEvent(VirtualQTextEdit* self, QEvent* event);
void QTextEdit_virtualbase_leaveEvent(VirtualQTextEdit* self, QEvent* event);
void QTextEdit_virtualbase_moveEvent(VirtualQTextEdit* self, QMoveEvent* event);
void QTextEdit_virtualbase_closeEvent(VirtualQTextEdit* self, QCloseEvent* event);
void QTextEdit_virtualbase_tabletEvent(VirtualQTextEdit* self, QTabletEvent* event);
void QTextEdit_virtualbase_actionEvent(VirtualQTextEdit* self, QActionEvent* event);
void QTextEdit_virtualbase_hideEvent(VirtualQTextEdit* self, QHideEvent* event);
bool QTextEdit_virtualbase_nativeEvent(VirtualQTextEdit* self, struct seaqt_string eventType, void* message, long* result);
int QTextEdit_virtualbase_metric(const VirtualQTextEdit* self, int param1);
void QTextEdit_virtualbase_initPainter(const VirtualQTextEdit* self, QPainter* painter);
QPaintDevice* QTextEdit_virtualbase_redirected(const VirtualQTextEdit* self, QPoint* offset);
QPainter* QTextEdit_virtualbase_sharedPainter(const VirtualQTextEdit* self);
void QTextEdit_virtualbase_childEvent(VirtualQTextEdit* self, QChildEvent* event);
void QTextEdit_virtualbase_customEvent(VirtualQTextEdit* self, QEvent* event);
void QTextEdit_virtualbase_connectNotify(VirtualQTextEdit* self, QMetaMethod* signal);
void QTextEdit_virtualbase_disconnectNotify(VirtualQTextEdit* self, QMetaMethod* signal);

void QTextEdit_protectedbase_zoomInF(VirtualQTextEdit* self, float range);
void QTextEdit_protectedbase_setViewportMargins_left_top_right_bottom(VirtualQTextEdit* self, int left, int top, int right, int bottom);
QMargins* QTextEdit_protectedbase_viewportMargins(const VirtualQTextEdit* self);
void QTextEdit_protectedbase_drawFrame(VirtualQTextEdit* self, QPainter* param1);
void QTextEdit_protectedbase_initStyleOption(const VirtualQTextEdit* self, QStyleOptionFrame* option);
void QTextEdit_protectedbase_updateMicroFocus(VirtualQTextEdit* self);
void QTextEdit_protectedbase_create(VirtualQTextEdit* self);
void QTextEdit_protectedbase_destroy(VirtualQTextEdit* self);
bool QTextEdit_protectedbase_focusNextChild(VirtualQTextEdit* self);
bool QTextEdit_protectedbase_focusPreviousChild(VirtualQTextEdit* self);
QObject* QTextEdit_protectedbase_sender(const VirtualQTextEdit* self);
int QTextEdit_protectedbase_senderSignalIndex(const VirtualQTextEdit* self);
int QTextEdit_protectedbase_receivers(const VirtualQTextEdit* self, const char* signal);
bool QTextEdit_protectedbase_isSignalConnected(const VirtualQTextEdit* self, QMetaMethod* signal);

void QTextEdit_delete(QTextEdit* self);

QTextEdit__ExtraSelection* QTextEdit__ExtraSelection_new(QTextEdit__ExtraSelection* from);

QTextCursor* QTextEdit__ExtraSelection_cursor(const QTextEdit__ExtraSelection* self);
void QTextEdit__ExtraSelection_setCursor(QTextEdit__ExtraSelection* self, QTextCursor* cursor);
QTextCharFormat* QTextEdit__ExtraSelection_format(const QTextEdit__ExtraSelection* self);
void QTextEdit__ExtraSelection_setFormat(QTextEdit__ExtraSelection* self, QTextCharFormat* format);
void QTextEdit__ExtraSelection_operatorAssign(QTextEdit__ExtraSelection* self, QTextEdit__ExtraSelection* from);

void QTextEdit__ExtraSelection_delete(QTextEdit__ExtraSelection* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
