#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QGRAPHICSVIEW_H
#define SEAQT_QTWIDGETS_GEN_QGRAPHICSVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt-runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractScrollArea;
class QActionEvent;
class QBrush;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEnterEvent;
class QEvent;
class QFocusEvent;
class QFrame;
class QGraphicsItem;
class QGraphicsScene;
class QGraphicsView;
class QHideEvent;
class QInputMethodEvent;
class QKeyEvent;
class QMargins;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPainterPath;
class QPoint;
class QPointF;
class QRect;
class QRectF;
class QResizeEvent;
class QShowEvent;
class QSize;
class QStyleOptionFrame;
class QTabletEvent;
class QTimerEvent;
class QTransform;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QBrush QBrush;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QGraphicsItem QGraphicsItem;
typedef struct QGraphicsScene QGraphicsScene;
typedef struct QGraphicsView QGraphicsView;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPainterPath QPainterPath;
typedef struct QPoint QPoint;
typedef struct QPointF QPointF;
typedef struct QRect QRect;
typedef struct QRectF QRectF;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QTransform QTransform;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

typedef struct VirtualQGraphicsView VirtualQGraphicsView;
typedef struct QGraphicsView_VTable{
	void (*destructor)(VirtualQGraphicsView* self);
	QMetaObject* (*metaObject)(const VirtualQGraphicsView* self);
	void* (*metacast)(VirtualQGraphicsView* self, const char* param1);
	int (*metacall)(VirtualQGraphicsView* self, int param1, int param2, void** param3);
	QSize* (*sizeHint)(const VirtualQGraphicsView* self);
	QVariant* (*inputMethodQuery)(const VirtualQGraphicsView* self, int query);
	void (*setupViewport)(VirtualQGraphicsView* self, QWidget* widget);
	bool (*event)(VirtualQGraphicsView* self, QEvent* event);
	bool (*viewportEvent)(VirtualQGraphicsView* self, QEvent* event);
	void (*contextMenuEvent)(VirtualQGraphicsView* self, QContextMenuEvent* event);
	void (*dragEnterEvent)(VirtualQGraphicsView* self, QDragEnterEvent* event);
	void (*dragLeaveEvent)(VirtualQGraphicsView* self, QDragLeaveEvent* event);
	void (*dragMoveEvent)(VirtualQGraphicsView* self, QDragMoveEvent* event);
	void (*dropEvent)(VirtualQGraphicsView* self, QDropEvent* event);
	void (*focusInEvent)(VirtualQGraphicsView* self, QFocusEvent* event);
	bool (*focusNextPrevChild)(VirtualQGraphicsView* self, bool next);
	void (*focusOutEvent)(VirtualQGraphicsView* self, QFocusEvent* event);
	void (*keyPressEvent)(VirtualQGraphicsView* self, QKeyEvent* event);
	void (*keyReleaseEvent)(VirtualQGraphicsView* self, QKeyEvent* event);
	void (*mouseDoubleClickEvent)(VirtualQGraphicsView* self, QMouseEvent* event);
	void (*mousePressEvent)(VirtualQGraphicsView* self, QMouseEvent* event);
	void (*mouseMoveEvent)(VirtualQGraphicsView* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(VirtualQGraphicsView* self, QMouseEvent* event);
	void (*wheelEvent)(VirtualQGraphicsView* self, QWheelEvent* event);
	void (*paintEvent)(VirtualQGraphicsView* self, QPaintEvent* event);
	void (*resizeEvent)(VirtualQGraphicsView* self, QResizeEvent* event);
	void (*scrollContentsBy)(VirtualQGraphicsView* self, int dx, int dy);
	void (*showEvent)(VirtualQGraphicsView* self, QShowEvent* event);
	void (*inputMethodEvent)(VirtualQGraphicsView* self, QInputMethodEvent* event);
	void (*drawBackground)(VirtualQGraphicsView* self, QPainter* painter, QRectF* rect);
	void (*drawForeground)(VirtualQGraphicsView* self, QPainter* painter, QRectF* rect);
	QSize* (*minimumSizeHint)(const VirtualQGraphicsView* self);
	bool (*eventFilter)(VirtualQGraphicsView* self, QObject* param1, QEvent* param2);
	QSize* (*viewportSizeHint)(const VirtualQGraphicsView* self);
	void (*changeEvent)(VirtualQGraphicsView* self, QEvent* param1);
	void (*initStyleOption)(const VirtualQGraphicsView* self, QStyleOptionFrame* option);
	int (*devType)(const VirtualQGraphicsView* self);
	void (*setVisible)(VirtualQGraphicsView* self, bool visible);
	int (*heightForWidth)(const VirtualQGraphicsView* self, int param1);
	bool (*hasHeightForWidth)(const VirtualQGraphicsView* self);
	QPaintEngine* (*paintEngine)(const VirtualQGraphicsView* self);
	void (*enterEvent)(VirtualQGraphicsView* self, QEnterEvent* event);
	void (*leaveEvent)(VirtualQGraphicsView* self, QEvent* event);
	void (*moveEvent)(VirtualQGraphicsView* self, QMoveEvent* event);
	void (*closeEvent)(VirtualQGraphicsView* self, QCloseEvent* event);
	void (*tabletEvent)(VirtualQGraphicsView* self, QTabletEvent* event);
	void (*actionEvent)(VirtualQGraphicsView* self, QActionEvent* event);
	void (*hideEvent)(VirtualQGraphicsView* self, QHideEvent* event);
	bool (*nativeEvent)(VirtualQGraphicsView* self, struct seaqt_string eventType, void* message, intptr_t* result);
	int (*metric)(const VirtualQGraphicsView* self, int param1);
	void (*initPainter)(const VirtualQGraphicsView* self, QPainter* painter);
	QPaintDevice* (*redirected)(const VirtualQGraphicsView* self, QPoint* offset);
	QPainter* (*sharedPainter)(const VirtualQGraphicsView* self);
	void (*timerEvent)(VirtualQGraphicsView* self, QTimerEvent* event);
	void (*childEvent)(VirtualQGraphicsView* self, QChildEvent* event);
	void (*customEvent)(VirtualQGraphicsView* self, QEvent* event);
	void (*connectNotify)(VirtualQGraphicsView* self, QMetaMethod* signal);
	void (*disconnectNotify)(VirtualQGraphicsView* self, QMetaMethod* signal);
}QGraphicsView_VTable;

void* QGraphicsView_vdata(VirtualQGraphicsView* self);
VirtualQGraphicsView* vdata_QGraphicsView(void* vdata);

VirtualQGraphicsView* QGraphicsView_new(const QGraphicsView_VTable* vtbl, size_t vdata);
VirtualQGraphicsView* QGraphicsView_new_scene(const QGraphicsView_VTable* vtbl, size_t vdata, QGraphicsScene* scene);
VirtualQGraphicsView* QGraphicsView_new_parent(const QGraphicsView_VTable* vtbl, size_t vdata, QWidget* parent);
VirtualQGraphicsView* QGraphicsView_new_scene_parent(const QGraphicsView_VTable* vtbl, size_t vdata, QGraphicsScene* scene, QWidget* parent);

void QGraphicsView_virtbase(QGraphicsView* src, QAbstractScrollArea** outptr_QAbstractScrollArea);
QMetaObject* QGraphicsView_metaObject(const QGraphicsView* self);
void* QGraphicsView_metacast(QGraphicsView* self, const char* param1);
int QGraphicsView_metacall(QGraphicsView* self, int param1, int param2, void** param3);
struct seaqt_string QGraphicsView_tr_s(const char* s);
QSize* QGraphicsView_sizeHint(const QGraphicsView* self);
int QGraphicsView_renderHints(const QGraphicsView* self);
void QGraphicsView_setRenderHint_hint(QGraphicsView* self, int hint);
void QGraphicsView_setRenderHints(QGraphicsView* self, int hints);
int QGraphicsView_alignment(const QGraphicsView* self);
void QGraphicsView_setAlignment(QGraphicsView* self, int alignment);
int QGraphicsView_transformationAnchor(const QGraphicsView* self);
void QGraphicsView_setTransformationAnchor(QGraphicsView* self, int anchor);
int QGraphicsView_resizeAnchor(const QGraphicsView* self);
void QGraphicsView_setResizeAnchor(QGraphicsView* self, int anchor);
int QGraphicsView_viewportUpdateMode(const QGraphicsView* self);
void QGraphicsView_setViewportUpdateMode(QGraphicsView* self, int mode);
int QGraphicsView_optimizationFlags(const QGraphicsView* self);
void QGraphicsView_setOptimizationFlag_flag(QGraphicsView* self, int flag);
void QGraphicsView_setOptimizationFlags(QGraphicsView* self, int flags);
int QGraphicsView_dragMode(const QGraphicsView* self);
void QGraphicsView_setDragMode(QGraphicsView* self, int mode);
int QGraphicsView_rubberBandSelectionMode(const QGraphicsView* self);
void QGraphicsView_setRubberBandSelectionMode(QGraphicsView* self, int mode);
QRect* QGraphicsView_rubberBandRect(const QGraphicsView* self);
int QGraphicsView_cacheMode(const QGraphicsView* self);
void QGraphicsView_setCacheMode(QGraphicsView* self, int mode);
void QGraphicsView_resetCachedContent(QGraphicsView* self);
bool QGraphicsView_isInteractive(const QGraphicsView* self);
void QGraphicsView_setInteractive(QGraphicsView* self, bool allowed);
QGraphicsScene* QGraphicsView_scene(const QGraphicsView* self);
void QGraphicsView_setScene(QGraphicsView* self, QGraphicsScene* scene);
QRectF* QGraphicsView_sceneRect(const QGraphicsView* self);
void QGraphicsView_setSceneRect_rect(QGraphicsView* self, QRectF* rect);
void QGraphicsView_setSceneRect_x_y_w_h(QGraphicsView* self, double x, double y, double w, double h);
QTransform* QGraphicsView_transform(const QGraphicsView* self);
QTransform* QGraphicsView_viewportTransform(const QGraphicsView* self);
bool QGraphicsView_isTransformed(const QGraphicsView* self);
void QGraphicsView_setTransform_matrix(QGraphicsView* self, QTransform* matrix);
void QGraphicsView_resetTransform(QGraphicsView* self);
void QGraphicsView_rotate(QGraphicsView* self, double angle);
void QGraphicsView_scale(QGraphicsView* self, double sx, double sy);
void QGraphicsView_shear(QGraphicsView* self, double sh, double sv);
void QGraphicsView_translate(QGraphicsView* self, double dx, double dy);
void QGraphicsView_centerOn_pos(QGraphicsView* self, QPointF* pos);
void QGraphicsView_centerOn_x_y(QGraphicsView* self, double x, double y);
void QGraphicsView_centerOn_item(QGraphicsView* self, QGraphicsItem* item);
void QGraphicsView_ensureVisible_rect(QGraphicsView* self, QRectF* rect);
void QGraphicsView_ensureVisible_x_y_w_h(QGraphicsView* self, double x, double y, double w, double h);
void QGraphicsView_ensureVisible_item(QGraphicsView* self, QGraphicsItem* item);
void QGraphicsView_fitInView_rect(QGraphicsView* self, QRectF* rect);
void QGraphicsView_fitInView_x_y_w_h(QGraphicsView* self, double x, double y, double w, double h);
void QGraphicsView_fitInView_item(QGraphicsView* self, QGraphicsItem* item);
void QGraphicsView_render_painter(QGraphicsView* self, QPainter* painter);
struct seaqt_array /* of QGraphicsItem* */  QGraphicsView_items(const QGraphicsView* self);
struct seaqt_array /* of QGraphicsItem* */  QGraphicsView_items_pos(const QGraphicsView* self, QPoint* pos);
struct seaqt_array /* of QGraphicsItem* */  QGraphicsView_items_x_y(const QGraphicsView* self, int x, int y);
struct seaqt_array /* of QGraphicsItem* */  QGraphicsView_items_rect(const QGraphicsView* self, QRect* rect);
struct seaqt_array /* of QGraphicsItem* */  QGraphicsView_items_x_y_w_h(const QGraphicsView* self, int x, int y, int w, int h);
struct seaqt_array /* of QGraphicsItem* */  QGraphicsView_items_path(const QGraphicsView* self, QPainterPath* path);
QGraphicsItem* QGraphicsView_itemAt_pos(const QGraphicsView* self, QPoint* pos);
QGraphicsItem* QGraphicsView_itemAt_x_y(const QGraphicsView* self, int x, int y);
QPointF* QGraphicsView_mapToScene_point(const QGraphicsView* self, QPoint* point);
QPainterPath* QGraphicsView_mapToScene_path(const QGraphicsView* self, QPainterPath* path);
QPoint* QGraphicsView_mapFromScene_point(const QGraphicsView* self, QPointF* point);
QPainterPath* QGraphicsView_mapFromScene_path(const QGraphicsView* self, QPainterPath* path);
QPointF* QGraphicsView_mapToScene_x_y(const QGraphicsView* self, int x, int y);
QPoint* QGraphicsView_mapFromScene_x_y(const QGraphicsView* self, double x, double y);
QVariant* QGraphicsView_inputMethodQuery(const QGraphicsView* self, int query);
QBrush* QGraphicsView_backgroundBrush(const QGraphicsView* self);
void QGraphicsView_setBackgroundBrush(QGraphicsView* self, QBrush* brush);
QBrush* QGraphicsView_foregroundBrush(const QGraphicsView* self);
void QGraphicsView_setForegroundBrush(QGraphicsView* self, QBrush* brush);
void QGraphicsView_updateScene(QGraphicsView* self, struct seaqt_array /* of QRectF* */  rects);
void QGraphicsView_invalidateScene(QGraphicsView* self);
void QGraphicsView_updateSceneRect(QGraphicsView* self, QRectF* rect);
void QGraphicsView_rubberBandChanged(QGraphicsView* self, QRect* viewportRect, QPointF* fromScenePoint, QPointF* toScenePoint);
void QGraphicsView_connect_rubberBandChanged(QGraphicsView* self, intptr_t slot, void (*callback)(intptr_t, QRect*, QPointF*, QPointF*), void (*release)(intptr_t));
void QGraphicsView_setupViewport(QGraphicsView* self, QWidget* widget);
bool QGraphicsView_event(QGraphicsView* self, QEvent* event);
bool QGraphicsView_viewportEvent(QGraphicsView* self, QEvent* event);
void QGraphicsView_contextMenuEvent(QGraphicsView* self, QContextMenuEvent* event);
void QGraphicsView_dragEnterEvent(QGraphicsView* self, QDragEnterEvent* event);
void QGraphicsView_dragLeaveEvent(QGraphicsView* self, QDragLeaveEvent* event);
void QGraphicsView_dragMoveEvent(QGraphicsView* self, QDragMoveEvent* event);
void QGraphicsView_dropEvent(QGraphicsView* self, QDropEvent* event);
void QGraphicsView_focusInEvent(QGraphicsView* self, QFocusEvent* event);
bool QGraphicsView_focusNextPrevChild(QGraphicsView* self, bool next);
void QGraphicsView_focusOutEvent(QGraphicsView* self, QFocusEvent* event);
void QGraphicsView_keyPressEvent(QGraphicsView* self, QKeyEvent* event);
void QGraphicsView_keyReleaseEvent(QGraphicsView* self, QKeyEvent* event);
void QGraphicsView_mouseDoubleClickEvent(QGraphicsView* self, QMouseEvent* event);
void QGraphicsView_mousePressEvent(QGraphicsView* self, QMouseEvent* event);
void QGraphicsView_mouseMoveEvent(QGraphicsView* self, QMouseEvent* event);
void QGraphicsView_mouseReleaseEvent(QGraphicsView* self, QMouseEvent* event);
void QGraphicsView_wheelEvent(QGraphicsView* self, QWheelEvent* event);
void QGraphicsView_paintEvent(QGraphicsView* self, QPaintEvent* event);
void QGraphicsView_resizeEvent(QGraphicsView* self, QResizeEvent* event);
void QGraphicsView_scrollContentsBy(QGraphicsView* self, int dx, int dy);
void QGraphicsView_showEvent(QGraphicsView* self, QShowEvent* event);
void QGraphicsView_inputMethodEvent(QGraphicsView* self, QInputMethodEvent* event);
void QGraphicsView_drawBackground(QGraphicsView* self, QPainter* painter, QRectF* rect);
void QGraphicsView_drawForeground(QGraphicsView* self, QPainter* painter, QRectF* rect);
struct seaqt_string QGraphicsView_tr_s_c(const char* s, const char* c);
struct seaqt_string QGraphicsView_tr_s_c_n(const char* s, const char* c, int n);
void QGraphicsView_setRenderHint_hint_enabled(QGraphicsView* self, int hint, bool enabled);
void QGraphicsView_setOptimizationFlag_flag_enabled(QGraphicsView* self, int flag, bool enabled);
void QGraphicsView_setTransform_matrix_combine(QGraphicsView* self, QTransform* matrix, bool combine);
void QGraphicsView_ensureVisible_rect_xmargin(QGraphicsView* self, QRectF* rect, int xmargin);
void QGraphicsView_ensureVisible_rect_xmargin_ymargin(QGraphicsView* self, QRectF* rect, int xmargin, int ymargin);
void QGraphicsView_ensureVisible_x_y_w_h_xmargin(QGraphicsView* self, double x, double y, double w, double h, int xmargin);
void QGraphicsView_ensureVisible_x_y_w_h_xmargin_ymargin(QGraphicsView* self, double x, double y, double w, double h, int xmargin, int ymargin);
void QGraphicsView_ensureVisible_item_xmargin(QGraphicsView* self, QGraphicsItem* item, int xmargin);
void QGraphicsView_ensureVisible_item_xmargin_ymargin(QGraphicsView* self, QGraphicsItem* item, int xmargin, int ymargin);
void QGraphicsView_fitInView_rect_aspectRadioMode(QGraphicsView* self, QRectF* rect, int aspectRadioMode);
void QGraphicsView_fitInView_x_y_w_h_aspectRadioMode(QGraphicsView* self, double x, double y, double w, double h, int aspectRadioMode);
void QGraphicsView_fitInView_item_aspectRadioMode(QGraphicsView* self, QGraphicsItem* item, int aspectRadioMode);
void QGraphicsView_render_painter_target(QGraphicsView* self, QPainter* painter, QRectF* target);
void QGraphicsView_render_painter_target_source(QGraphicsView* self, QPainter* painter, QRectF* target, QRect* source);
void QGraphicsView_render_painter_target_source_aspectRatioMode(QGraphicsView* self, QPainter* painter, QRectF* target, QRect* source, int aspectRatioMode);
struct seaqt_array /* of QGraphicsItem* */  QGraphicsView_items_rect_mode(const QGraphicsView* self, QRect* rect, int mode);
struct seaqt_array /* of QGraphicsItem* */  QGraphicsView_items_x_y_w_h_mode(const QGraphicsView* self, int x, int y, int w, int h, int mode);
struct seaqt_array /* of QGraphicsItem* */  QGraphicsView_items_path_mode(const QGraphicsView* self, QPainterPath* path, int mode);
void QGraphicsView_invalidateScene_rect(QGraphicsView* self, QRectF* rect);
void QGraphicsView_invalidateScene_rect_layers(QGraphicsView* self, QRectF* rect, int layers);

QMetaObject* QGraphicsView_virtualbase_metaObject(const VirtualQGraphicsView* self);
void* QGraphicsView_virtualbase_metacast(VirtualQGraphicsView* self, const char* param1);
int QGraphicsView_virtualbase_metacall(VirtualQGraphicsView* self, int param1, int param2, void** param3);
QSize* QGraphicsView_virtualbase_sizeHint(const VirtualQGraphicsView* self);
QVariant* QGraphicsView_virtualbase_inputMethodQuery(const VirtualQGraphicsView* self, int query);
void QGraphicsView_virtualbase_setupViewport(VirtualQGraphicsView* self, QWidget* widget);
bool QGraphicsView_virtualbase_event(VirtualQGraphicsView* self, QEvent* event);
bool QGraphicsView_virtualbase_viewportEvent(VirtualQGraphicsView* self, QEvent* event);
void QGraphicsView_virtualbase_contextMenuEvent(VirtualQGraphicsView* self, QContextMenuEvent* event);
void QGraphicsView_virtualbase_dragEnterEvent(VirtualQGraphicsView* self, QDragEnterEvent* event);
void QGraphicsView_virtualbase_dragLeaveEvent(VirtualQGraphicsView* self, QDragLeaveEvent* event);
void QGraphicsView_virtualbase_dragMoveEvent(VirtualQGraphicsView* self, QDragMoveEvent* event);
void QGraphicsView_virtualbase_dropEvent(VirtualQGraphicsView* self, QDropEvent* event);
void QGraphicsView_virtualbase_focusInEvent(VirtualQGraphicsView* self, QFocusEvent* event);
bool QGraphicsView_virtualbase_focusNextPrevChild(VirtualQGraphicsView* self, bool next);
void QGraphicsView_virtualbase_focusOutEvent(VirtualQGraphicsView* self, QFocusEvent* event);
void QGraphicsView_virtualbase_keyPressEvent(VirtualQGraphicsView* self, QKeyEvent* event);
void QGraphicsView_virtualbase_keyReleaseEvent(VirtualQGraphicsView* self, QKeyEvent* event);
void QGraphicsView_virtualbase_mouseDoubleClickEvent(VirtualQGraphicsView* self, QMouseEvent* event);
void QGraphicsView_virtualbase_mousePressEvent(VirtualQGraphicsView* self, QMouseEvent* event);
void QGraphicsView_virtualbase_mouseMoveEvent(VirtualQGraphicsView* self, QMouseEvent* event);
void QGraphicsView_virtualbase_mouseReleaseEvent(VirtualQGraphicsView* self, QMouseEvent* event);
void QGraphicsView_virtualbase_wheelEvent(VirtualQGraphicsView* self, QWheelEvent* event);
void QGraphicsView_virtualbase_paintEvent(VirtualQGraphicsView* self, QPaintEvent* event);
void QGraphicsView_virtualbase_resizeEvent(VirtualQGraphicsView* self, QResizeEvent* event);
void QGraphicsView_virtualbase_scrollContentsBy(VirtualQGraphicsView* self, int dx, int dy);
void QGraphicsView_virtualbase_showEvent(VirtualQGraphicsView* self, QShowEvent* event);
void QGraphicsView_virtualbase_inputMethodEvent(VirtualQGraphicsView* self, QInputMethodEvent* event);
void QGraphicsView_virtualbase_drawBackground(VirtualQGraphicsView* self, QPainter* painter, QRectF* rect);
void QGraphicsView_virtualbase_drawForeground(VirtualQGraphicsView* self, QPainter* painter, QRectF* rect);
QSize* QGraphicsView_virtualbase_minimumSizeHint(const VirtualQGraphicsView* self);
bool QGraphicsView_virtualbase_eventFilter(VirtualQGraphicsView* self, QObject* param1, QEvent* param2);
QSize* QGraphicsView_virtualbase_viewportSizeHint(const VirtualQGraphicsView* self);
void QGraphicsView_virtualbase_changeEvent(VirtualQGraphicsView* self, QEvent* param1);
void QGraphicsView_virtualbase_initStyleOption(const VirtualQGraphicsView* self, QStyleOptionFrame* option);
int QGraphicsView_virtualbase_devType(const VirtualQGraphicsView* self);
void QGraphicsView_virtualbase_setVisible(VirtualQGraphicsView* self, bool visible);
int QGraphicsView_virtualbase_heightForWidth(const VirtualQGraphicsView* self, int param1);
bool QGraphicsView_virtualbase_hasHeightForWidth(const VirtualQGraphicsView* self);
QPaintEngine* QGraphicsView_virtualbase_paintEngine(const VirtualQGraphicsView* self);
void QGraphicsView_virtualbase_enterEvent(VirtualQGraphicsView* self, QEnterEvent* event);
void QGraphicsView_virtualbase_leaveEvent(VirtualQGraphicsView* self, QEvent* event);
void QGraphicsView_virtualbase_moveEvent(VirtualQGraphicsView* self, QMoveEvent* event);
void QGraphicsView_virtualbase_closeEvent(VirtualQGraphicsView* self, QCloseEvent* event);
void QGraphicsView_virtualbase_tabletEvent(VirtualQGraphicsView* self, QTabletEvent* event);
void QGraphicsView_virtualbase_actionEvent(VirtualQGraphicsView* self, QActionEvent* event);
void QGraphicsView_virtualbase_hideEvent(VirtualQGraphicsView* self, QHideEvent* event);
bool QGraphicsView_virtualbase_nativeEvent(VirtualQGraphicsView* self, struct seaqt_string eventType, void* message, intptr_t* result);
int QGraphicsView_virtualbase_metric(const VirtualQGraphicsView* self, int param1);
void QGraphicsView_virtualbase_initPainter(const VirtualQGraphicsView* self, QPainter* painter);
QPaintDevice* QGraphicsView_virtualbase_redirected(const VirtualQGraphicsView* self, QPoint* offset);
QPainter* QGraphicsView_virtualbase_sharedPainter(const VirtualQGraphicsView* self);
void QGraphicsView_virtualbase_timerEvent(VirtualQGraphicsView* self, QTimerEvent* event);
void QGraphicsView_virtualbase_childEvent(VirtualQGraphicsView* self, QChildEvent* event);
void QGraphicsView_virtualbase_customEvent(VirtualQGraphicsView* self, QEvent* event);
void QGraphicsView_virtualbase_connectNotify(VirtualQGraphicsView* self, QMetaMethod* signal);
void QGraphicsView_virtualbase_disconnectNotify(VirtualQGraphicsView* self, QMetaMethod* signal);

void QGraphicsView_protectedbase_setViewportMargins_left_top_right_bottom(VirtualQGraphicsView* self, int left, int top, int right, int bottom);
QMargins* QGraphicsView_protectedbase_viewportMargins(const VirtualQGraphicsView* self);
void QGraphicsView_protectedbase_drawFrame(VirtualQGraphicsView* self, QPainter* param1);
void QGraphicsView_protectedbase_updateMicroFocus(VirtualQGraphicsView* self);
void QGraphicsView_protectedbase_create(VirtualQGraphicsView* self);
void QGraphicsView_protectedbase_destroy(VirtualQGraphicsView* self);
bool QGraphicsView_protectedbase_focusNextChild(VirtualQGraphicsView* self);
bool QGraphicsView_protectedbase_focusPreviousChild(VirtualQGraphicsView* self);
QObject* QGraphicsView_protectedbase_sender(const VirtualQGraphicsView* self);
int QGraphicsView_protectedbase_senderSignalIndex(const VirtualQGraphicsView* self);
int QGraphicsView_protectedbase_receivers(const VirtualQGraphicsView* self, const char* signal);
bool QGraphicsView_protectedbase_isSignalConnected(const VirtualQGraphicsView* self, QMetaMethod* signal);

void QGraphicsView_delete(QGraphicsView* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
