#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QMESSAGEBOX_H
#define SEAQT_QTWIDGETS_GEN_QMESSAGEBOX_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt-runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractButton;
class QActionEvent;
class QCheckBox;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDialog;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEnterEvent;
class QEvent;
class QFocusEvent;
class QHideEvent;
class QInputMethodEvent;
class QKeyEvent;
class QMessageBox;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPixmap;
class QPoint;
class QPushButton;
class QResizeEvent;
class QShowEvent;
class QSize;
class QTabletEvent;
class QTimerEvent;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractButton QAbstractButton;
typedef struct QActionEvent QActionEvent;
typedef struct QCheckBox QCheckBox;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMessageBox QMessageBox;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QPushButton QPushButton;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

typedef struct VirtualQMessageBox VirtualQMessageBox;
typedef struct QMessageBox_VTable{
	void (*destructor)(VirtualQMessageBox* self);
	QMetaObject* (*metaObject)(const VirtualQMessageBox* self);
	void* (*metacast)(VirtualQMessageBox* self, const char* param1);
	int (*metacall)(VirtualQMessageBox* self, int param1, int param2, void** param3);
	bool (*event)(VirtualQMessageBox* self, QEvent* e);
	void (*resizeEvent)(VirtualQMessageBox* self, QResizeEvent* event);
	void (*showEvent)(VirtualQMessageBox* self, QShowEvent* event);
	void (*closeEvent)(VirtualQMessageBox* self, QCloseEvent* event);
	void (*keyPressEvent)(VirtualQMessageBox* self, QKeyEvent* event);
	void (*changeEvent)(VirtualQMessageBox* self, QEvent* event);
	void (*setVisible)(VirtualQMessageBox* self, bool visible);
	QSize* (*sizeHint)(const VirtualQMessageBox* self);
	QSize* (*minimumSizeHint)(const VirtualQMessageBox* self);
	void (*open)(VirtualQMessageBox* self);
	int (*exec)(VirtualQMessageBox* self);
	void (*done)(VirtualQMessageBox* self, int param1);
	void (*accept)(VirtualQMessageBox* self);
	void (*reject)(VirtualQMessageBox* self);
	void (*contextMenuEvent)(VirtualQMessageBox* self, QContextMenuEvent* param1);
	bool (*eventFilter)(VirtualQMessageBox* self, QObject* param1, QEvent* param2);
	int (*devType)(const VirtualQMessageBox* self);
	int (*heightForWidth)(const VirtualQMessageBox* self, int param1);
	bool (*hasHeightForWidth)(const VirtualQMessageBox* self);
	QPaintEngine* (*paintEngine)(const VirtualQMessageBox* self);
	void (*mousePressEvent)(VirtualQMessageBox* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(VirtualQMessageBox* self, QMouseEvent* event);
	void (*mouseDoubleClickEvent)(VirtualQMessageBox* self, QMouseEvent* event);
	void (*mouseMoveEvent)(VirtualQMessageBox* self, QMouseEvent* event);
	void (*wheelEvent)(VirtualQMessageBox* self, QWheelEvent* event);
	void (*keyReleaseEvent)(VirtualQMessageBox* self, QKeyEvent* event);
	void (*focusInEvent)(VirtualQMessageBox* self, QFocusEvent* event);
	void (*focusOutEvent)(VirtualQMessageBox* self, QFocusEvent* event);
	void (*enterEvent)(VirtualQMessageBox* self, QEnterEvent* event);
	void (*leaveEvent)(VirtualQMessageBox* self, QEvent* event);
	void (*paintEvent)(VirtualQMessageBox* self, QPaintEvent* event);
	void (*moveEvent)(VirtualQMessageBox* self, QMoveEvent* event);
	void (*tabletEvent)(VirtualQMessageBox* self, QTabletEvent* event);
	void (*actionEvent)(VirtualQMessageBox* self, QActionEvent* event);
	void (*dragEnterEvent)(VirtualQMessageBox* self, QDragEnterEvent* event);
	void (*dragMoveEvent)(VirtualQMessageBox* self, QDragMoveEvent* event);
	void (*dragLeaveEvent)(VirtualQMessageBox* self, QDragLeaveEvent* event);
	void (*dropEvent)(VirtualQMessageBox* self, QDropEvent* event);
	void (*hideEvent)(VirtualQMessageBox* self, QHideEvent* event);
	bool (*nativeEvent)(VirtualQMessageBox* self, struct seaqt_string eventType, void* message, intptr_t* result);
	int (*metric)(const VirtualQMessageBox* self, int param1);
	void (*initPainter)(const VirtualQMessageBox* self, QPainter* painter);
	QPaintDevice* (*redirected)(const VirtualQMessageBox* self, QPoint* offset);
	QPainter* (*sharedPainter)(const VirtualQMessageBox* self);
	void (*inputMethodEvent)(VirtualQMessageBox* self, QInputMethodEvent* param1);
	QVariant* (*inputMethodQuery)(const VirtualQMessageBox* self, int param1);
	bool (*focusNextPrevChild)(VirtualQMessageBox* self, bool next);
	void (*timerEvent)(VirtualQMessageBox* self, QTimerEvent* event);
	void (*childEvent)(VirtualQMessageBox* self, QChildEvent* event);
	void (*customEvent)(VirtualQMessageBox* self, QEvent* event);
	void (*connectNotify)(VirtualQMessageBox* self, QMetaMethod* signal);
	void (*disconnectNotify)(VirtualQMessageBox* self, QMetaMethod* signal);
}QMessageBox_VTable;

void* QMessageBox_vdata(VirtualQMessageBox* self);
VirtualQMessageBox* vdata_QMessageBox(void* vdata);

VirtualQMessageBox* QMessageBox_new(const QMessageBox_VTable* vtbl, size_t vdata);
VirtualQMessageBox* QMessageBox_new_icon_title_text(const QMessageBox_VTable* vtbl, size_t vdata, int icon, struct seaqt_string title, struct seaqt_string text);
VirtualQMessageBox* QMessageBox_new_title_text_icon_button0_button1_button2(const QMessageBox_VTable* vtbl, size_t vdata, struct seaqt_string title, struct seaqt_string text, int icon, int button0, int button1, int button2);
VirtualQMessageBox* QMessageBox_new_parent(const QMessageBox_VTable* vtbl, size_t vdata, QWidget* parent);
VirtualQMessageBox* QMessageBox_new_icon_title_text_buttons(const QMessageBox_VTable* vtbl, size_t vdata, int icon, struct seaqt_string title, struct seaqt_string text, int buttons);
VirtualQMessageBox* QMessageBox_new_icon_title_text_buttons_parent(const QMessageBox_VTable* vtbl, size_t vdata, int icon, struct seaqt_string title, struct seaqt_string text, int buttons, QWidget* parent);
VirtualQMessageBox* QMessageBox_new_icon_title_text_buttons_parent_flags(const QMessageBox_VTable* vtbl, size_t vdata, int icon, struct seaqt_string title, struct seaqt_string text, int buttons, QWidget* parent, int flags);
VirtualQMessageBox* QMessageBox_new_title_text_icon_button0_button1_button2_parent(const QMessageBox_VTable* vtbl, size_t vdata, struct seaqt_string title, struct seaqt_string text, int icon, int button0, int button1, int button2, QWidget* parent);
VirtualQMessageBox* QMessageBox_new_title_text_icon_button0_button1_button2_parent_f(const QMessageBox_VTable* vtbl, size_t vdata, struct seaqt_string title, struct seaqt_string text, int icon, int button0, int button1, int button2, QWidget* parent, int f);

void QMessageBox_virtbase(QMessageBox* src, QDialog** outptr_QDialog);
QMetaObject* QMessageBox_metaObject(const QMessageBox* self);
void* QMessageBox_metacast(QMessageBox* self, const char* param1);
int QMessageBox_metacall(QMessageBox* self, int param1, int param2, void** param3);
struct seaqt_string QMessageBox_tr_s(const char* s);
void QMessageBox_addButton_button_role(QMessageBox* self, QAbstractButton* button, int role);
QPushButton* QMessageBox_addButton_text_role(QMessageBox* self, struct seaqt_string text, int role);
QPushButton* QMessageBox_addButton_button(QMessageBox* self, int button);
void QMessageBox_removeButton(QMessageBox* self, QAbstractButton* button);
struct seaqt_array /* of QAbstractButton* */  QMessageBox_buttons(const QMessageBox* self);
int QMessageBox_buttonRole(const QMessageBox* self, QAbstractButton* button);
void QMessageBox_setStandardButtons(QMessageBox* self, int buttons);
int QMessageBox_standardButtons(const QMessageBox* self);
int QMessageBox_standardButton(const QMessageBox* self, QAbstractButton* button);
QAbstractButton* QMessageBox_button(const QMessageBox* self, int which);
QPushButton* QMessageBox_defaultButton(const QMessageBox* self);
void QMessageBox_setDefaultButton_QPushButton(QMessageBox* self, QPushButton* button);
void QMessageBox_setDefaultButton_QMessageBox_StandardButton(QMessageBox* self, int button);
QAbstractButton* QMessageBox_escapeButton(const QMessageBox* self);
void QMessageBox_setEscapeButton_QAbstractButton(QMessageBox* self, QAbstractButton* button);
void QMessageBox_setEscapeButton_QMessageBox_StandardButton(QMessageBox* self, int button);
QAbstractButton* QMessageBox_clickedButton(const QMessageBox* self);
struct seaqt_string QMessageBox_text(const QMessageBox* self);
void QMessageBox_setText(QMessageBox* self, struct seaqt_string text);
int QMessageBox_icon(const QMessageBox* self);
void QMessageBox_setIcon(QMessageBox* self, int icon);
QPixmap* QMessageBox_iconPixmap(const QMessageBox* self);
void QMessageBox_setIconPixmap(QMessageBox* self, QPixmap* pixmap);
int QMessageBox_textFormat(const QMessageBox* self);
void QMessageBox_setTextFormat(QMessageBox* self, int format);
void QMessageBox_setTextInteractionFlags(QMessageBox* self, int flags);
int QMessageBox_textInteractionFlags(const QMessageBox* self);
void QMessageBox_setCheckBox(QMessageBox* self, QCheckBox* cb);
QCheckBox* QMessageBox_checkBox(const QMessageBox* self);
void QMessageBox_setOption_option(QMessageBox* self, int option);
bool QMessageBox_testOption(const QMessageBox* self, int option);
void QMessageBox_setOptions(QMessageBox* self, int options);
int QMessageBox_options(const QMessageBox* self);
int QMessageBox_information_QWidget_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text);
int QMessageBox_information_QWidget_QString_QString_QMessageBox_StandardButton(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0);
int QMessageBox_question_QWidget_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text);
int QMessageBox_question_QWidget_QString_QString_QMessageBox_StandardButton_QMessageBox_StandardButton(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0, int button1);
int QMessageBox_warning_QWidget_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text);
int QMessageBox_warning_QWidget_QString_QString_QMessageBox_StandardButton_QMessageBox_StandardButton(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0, int button1);
int QMessageBox_critical_QWidget_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text);
int QMessageBox_critical_QWidget_QString_QString_QMessageBox_StandardButton_QMessageBox_StandardButton(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0, int button1);
void QMessageBox_about(QWidget* parent, struct seaqt_string title, struct seaqt_string text);
void QMessageBox_aboutQt_parent(QWidget* parent);
int QMessageBox_information_QWidget_QString_QString_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0);
int QMessageBox_information_QWidget_QString_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text);
int QMessageBox_question_QWidget_QString_QString_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0);
int QMessageBox_question_QWidget_QString_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text);
int QMessageBox_warning_QWidget_QString_QString_int_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0, int button1);
int QMessageBox_warning_QWidget_QString_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text);
int QMessageBox_critical_QWidget_QString_QString_int_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0, int button1);
int QMessageBox_critical_QWidget_QString_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text);
struct seaqt_string QMessageBox_buttonText(const QMessageBox* self, int button);
void QMessageBox_setButtonText(QMessageBox* self, int button, struct seaqt_string text);
struct seaqt_string QMessageBox_informativeText(const QMessageBox* self);
void QMessageBox_setInformativeText(QMessageBox* self, struct seaqt_string text);
struct seaqt_string QMessageBox_detailedText(const QMessageBox* self);
void QMessageBox_setDetailedText(QMessageBox* self, struct seaqt_string text);
void QMessageBox_setWindowTitle(QMessageBox* self, struct seaqt_string title);
void QMessageBox_setWindowModality(QMessageBox* self, int windowModality);
QPixmap* QMessageBox_standardIcon(int icon);
void QMessageBox_buttonClicked(QMessageBox* self, QAbstractButton* button);
void QMessageBox_connect_buttonClicked(QMessageBox* self, intptr_t slot, void (*callback)(intptr_t, QAbstractButton*), void (*release)(intptr_t));
bool QMessageBox_event(QMessageBox* self, QEvent* e);
void QMessageBox_resizeEvent(QMessageBox* self, QResizeEvent* event);
void QMessageBox_showEvent(QMessageBox* self, QShowEvent* event);
void QMessageBox_closeEvent(QMessageBox* self, QCloseEvent* event);
void QMessageBox_keyPressEvent(QMessageBox* self, QKeyEvent* event);
void QMessageBox_changeEvent(QMessageBox* self, QEvent* event);
struct seaqt_string QMessageBox_tr_s_c(const char* s, const char* c);
struct seaqt_string QMessageBox_tr_s_c_n(const char* s, const char* c, int n);
void QMessageBox_setOption_option_on(QMessageBox* self, int option, bool on);
int QMessageBox_information_QWidget_QString_QString_QMessageBox_StandardButtons(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int buttons);
int QMessageBox_information_QWidget_QString_QString_QMessageBox_StandardButtons_QMessageBox_StandardButton(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int buttons, int defaultButton);
int QMessageBox_information_QWidget_QString_QString_QMessageBox_StandardButton_QMessageBox_StandardButton(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0, int button1);
int QMessageBox_question_QWidget_QString_QString_QMessageBox_StandardButtons(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int buttons);
int QMessageBox_question_QWidget_QString_QString_QMessageBox_StandardButtons_QMessageBox_StandardButton(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int buttons, int defaultButton);
int QMessageBox_warning_QWidget_QString_QString_QMessageBox_StandardButtons(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int buttons);
int QMessageBox_warning_QWidget_QString_QString_QMessageBox_StandardButtons_QMessageBox_StandardButton(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int buttons, int defaultButton);
int QMessageBox_critical_QWidget_QString_QString_QMessageBox_StandardButtons(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int buttons);
int QMessageBox_critical_QWidget_QString_QString_QMessageBox_StandardButtons_QMessageBox_StandardButton(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int buttons, int defaultButton);
void QMessageBox_aboutQt_parent_title(QWidget* parent, struct seaqt_string title);
int QMessageBox_information_QWidget_QString_QString_int_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0, int button1);
int QMessageBox_information_QWidget_QString_QString_int_int_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0, int button1, int button2);
int QMessageBox_information_QWidget_QString_QString_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text);
int QMessageBox_information_QWidget_QString_QString_QString_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text, struct seaqt_string button2Text);
int QMessageBox_information_QWidget_QString_QString_QString_QString_QString_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text, struct seaqt_string button2Text, int defaultButtonNumber);
int QMessageBox_information_QWidget_QString_QString_QString_QString_QString_int_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text, struct seaqt_string button2Text, int defaultButtonNumber, int escapeButtonNumber);
int QMessageBox_question_QWidget_QString_QString_int_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0, int button1);
int QMessageBox_question_QWidget_QString_QString_int_int_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0, int button1, int button2);
int QMessageBox_question_QWidget_QString_QString_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text);
int QMessageBox_question_QWidget_QString_QString_QString_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text, struct seaqt_string button2Text);
int QMessageBox_question_QWidget_QString_QString_QString_QString_QString_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text, struct seaqt_string button2Text, int defaultButtonNumber);
int QMessageBox_question_QWidget_QString_QString_QString_QString_QString_int_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text, struct seaqt_string button2Text, int defaultButtonNumber, int escapeButtonNumber);
int QMessageBox_warning_QWidget_QString_QString_int_int_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0, int button1, int button2);
int QMessageBox_warning_QWidget_QString_QString_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text);
int QMessageBox_warning_QWidget_QString_QString_QString_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text, struct seaqt_string button2Text);
int QMessageBox_warning_QWidget_QString_QString_QString_QString_QString_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text, struct seaqt_string button2Text, int defaultButtonNumber);
int QMessageBox_warning_QWidget_QString_QString_QString_QString_QString_int_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text, struct seaqt_string button2Text, int defaultButtonNumber, int escapeButtonNumber);
int QMessageBox_critical_QWidget_QString_QString_int_int_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, int button0, int button1, int button2);
int QMessageBox_critical_QWidget_QString_QString_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text);
int QMessageBox_critical_QWidget_QString_QString_QString_QString_QString(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text, struct seaqt_string button2Text);
int QMessageBox_critical_QWidget_QString_QString_QString_QString_QString_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text, struct seaqt_string button2Text, int defaultButtonNumber);
int QMessageBox_critical_QWidget_QString_QString_QString_QString_QString_int_int(QWidget* parent, struct seaqt_string title, struct seaqt_string text, struct seaqt_string button0Text, struct seaqt_string button1Text, struct seaqt_string button2Text, int defaultButtonNumber, int escapeButtonNumber);

QMetaObject* QMessageBox_virtualbase_metaObject(const VirtualQMessageBox* self);
void* QMessageBox_virtualbase_metacast(VirtualQMessageBox* self, const char* param1);
int QMessageBox_virtualbase_metacall(VirtualQMessageBox* self, int param1, int param2, void** param3);
bool QMessageBox_virtualbase_event(VirtualQMessageBox* self, QEvent* e);
void QMessageBox_virtualbase_resizeEvent(VirtualQMessageBox* self, QResizeEvent* event);
void QMessageBox_virtualbase_showEvent(VirtualQMessageBox* self, QShowEvent* event);
void QMessageBox_virtualbase_closeEvent(VirtualQMessageBox* self, QCloseEvent* event);
void QMessageBox_virtualbase_keyPressEvent(VirtualQMessageBox* self, QKeyEvent* event);
void QMessageBox_virtualbase_changeEvent(VirtualQMessageBox* self, QEvent* event);
void QMessageBox_virtualbase_setVisible(VirtualQMessageBox* self, bool visible);
QSize* QMessageBox_virtualbase_sizeHint(const VirtualQMessageBox* self);
QSize* QMessageBox_virtualbase_minimumSizeHint(const VirtualQMessageBox* self);
void QMessageBox_virtualbase_open(VirtualQMessageBox* self);
int QMessageBox_virtualbase_exec(VirtualQMessageBox* self);
void QMessageBox_virtualbase_done(VirtualQMessageBox* self, int param1);
void QMessageBox_virtualbase_accept(VirtualQMessageBox* self);
void QMessageBox_virtualbase_reject(VirtualQMessageBox* self);
void QMessageBox_virtualbase_contextMenuEvent(VirtualQMessageBox* self, QContextMenuEvent* param1);
bool QMessageBox_virtualbase_eventFilter(VirtualQMessageBox* self, QObject* param1, QEvent* param2);
int QMessageBox_virtualbase_devType(const VirtualQMessageBox* self);
int QMessageBox_virtualbase_heightForWidth(const VirtualQMessageBox* self, int param1);
bool QMessageBox_virtualbase_hasHeightForWidth(const VirtualQMessageBox* self);
QPaintEngine* QMessageBox_virtualbase_paintEngine(const VirtualQMessageBox* self);
void QMessageBox_virtualbase_mousePressEvent(VirtualQMessageBox* self, QMouseEvent* event);
void QMessageBox_virtualbase_mouseReleaseEvent(VirtualQMessageBox* self, QMouseEvent* event);
void QMessageBox_virtualbase_mouseDoubleClickEvent(VirtualQMessageBox* self, QMouseEvent* event);
void QMessageBox_virtualbase_mouseMoveEvent(VirtualQMessageBox* self, QMouseEvent* event);
void QMessageBox_virtualbase_wheelEvent(VirtualQMessageBox* self, QWheelEvent* event);
void QMessageBox_virtualbase_keyReleaseEvent(VirtualQMessageBox* self, QKeyEvent* event);
void QMessageBox_virtualbase_focusInEvent(VirtualQMessageBox* self, QFocusEvent* event);
void QMessageBox_virtualbase_focusOutEvent(VirtualQMessageBox* self, QFocusEvent* event);
void QMessageBox_virtualbase_enterEvent(VirtualQMessageBox* self, QEnterEvent* event);
void QMessageBox_virtualbase_leaveEvent(VirtualQMessageBox* self, QEvent* event);
void QMessageBox_virtualbase_paintEvent(VirtualQMessageBox* self, QPaintEvent* event);
void QMessageBox_virtualbase_moveEvent(VirtualQMessageBox* self, QMoveEvent* event);
void QMessageBox_virtualbase_tabletEvent(VirtualQMessageBox* self, QTabletEvent* event);
void QMessageBox_virtualbase_actionEvent(VirtualQMessageBox* self, QActionEvent* event);
void QMessageBox_virtualbase_dragEnterEvent(VirtualQMessageBox* self, QDragEnterEvent* event);
void QMessageBox_virtualbase_dragMoveEvent(VirtualQMessageBox* self, QDragMoveEvent* event);
void QMessageBox_virtualbase_dragLeaveEvent(VirtualQMessageBox* self, QDragLeaveEvent* event);
void QMessageBox_virtualbase_dropEvent(VirtualQMessageBox* self, QDropEvent* event);
void QMessageBox_virtualbase_hideEvent(VirtualQMessageBox* self, QHideEvent* event);
bool QMessageBox_virtualbase_nativeEvent(VirtualQMessageBox* self, struct seaqt_string eventType, void* message, intptr_t* result);
int QMessageBox_virtualbase_metric(const VirtualQMessageBox* self, int param1);
void QMessageBox_virtualbase_initPainter(const VirtualQMessageBox* self, QPainter* painter);
QPaintDevice* QMessageBox_virtualbase_redirected(const VirtualQMessageBox* self, QPoint* offset);
QPainter* QMessageBox_virtualbase_sharedPainter(const VirtualQMessageBox* self);
void QMessageBox_virtualbase_inputMethodEvent(VirtualQMessageBox* self, QInputMethodEvent* param1);
QVariant* QMessageBox_virtualbase_inputMethodQuery(const VirtualQMessageBox* self, int param1);
bool QMessageBox_virtualbase_focusNextPrevChild(VirtualQMessageBox* self, bool next);
void QMessageBox_virtualbase_timerEvent(VirtualQMessageBox* self, QTimerEvent* event);
void QMessageBox_virtualbase_childEvent(VirtualQMessageBox* self, QChildEvent* event);
void QMessageBox_virtualbase_customEvent(VirtualQMessageBox* self, QEvent* event);
void QMessageBox_virtualbase_connectNotify(VirtualQMessageBox* self, QMetaMethod* signal);
void QMessageBox_virtualbase_disconnectNotify(VirtualQMessageBox* self, QMetaMethod* signal);

void QMessageBox_protectedbase_adjustPosition(VirtualQMessageBox* self, QWidget* param1);
void QMessageBox_protectedbase_updateMicroFocus(VirtualQMessageBox* self);
void QMessageBox_protectedbase_create(VirtualQMessageBox* self);
void QMessageBox_protectedbase_destroy(VirtualQMessageBox* self);
bool QMessageBox_protectedbase_focusNextChild(VirtualQMessageBox* self);
bool QMessageBox_protectedbase_focusPreviousChild(VirtualQMessageBox* self);
QObject* QMessageBox_protectedbase_sender(const VirtualQMessageBox* self);
int QMessageBox_protectedbase_senderSignalIndex(const VirtualQMessageBox* self);
int QMessageBox_protectedbase_receivers(const VirtualQMessageBox* self, const char* signal);
bool QMessageBox_protectedbase_isSignalConnected(const VirtualQMessageBox* self, QMetaMethod* signal);
double QMessageBox_protectedbase_getDecodedMetricF(const VirtualQMessageBox* self, int metricA, int metricB);

const QMetaObject* QMessageBox_staticMetaObject();
void QMessageBox_delete(QMessageBox* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
