#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QBOXLAYOUT_H
#define SEAQT_QTWIDGETS_GEN_QBOXLAYOUT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt/libseaqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QBoxLayout;
class QChildEvent;
class QEvent;
class QHBoxLayout;
class QLayout;
class QLayoutItem;
class QMetaMethod;
class QMetaObject;
class QObject;
class QRect;
class QSize;
class QSpacerItem;
class QTimerEvent;
class QVBoxLayout;
class QWidget;
#else
typedef struct QBoxLayout QBoxLayout;
typedef struct QChildEvent QChildEvent;
typedef struct QEvent QEvent;
typedef struct QHBoxLayout QHBoxLayout;
typedef struct QLayout QLayout;
typedef struct QLayoutItem QLayoutItem;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QObject QObject;
typedef struct QRect QRect;
typedef struct QSize QSize;
typedef struct QSpacerItem QSpacerItem;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVBoxLayout QVBoxLayout;
typedef struct QWidget QWidget;
#endif

struct QBoxLayout_VTable {
	void (*destructor)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self);
	QMetaObject* (*metaObject)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self);
	void* (*metacast)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self, const char* param1);
	int (*metacall)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self, int param1, int param2, void** param3);
	void (*addItem)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self, QLayoutItem* param1);
	QSize* (*sizeHint)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self);
	QSize* (*minimumSize)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self);
	QSize* (*maximumSize)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self);
	bool (*hasHeightForWidth)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self);
	int (*heightForWidth)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self, int param1);
	int (*minimumHeightForWidth)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self, int param1);
	int (*expandingDirections)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self);
	void (*invalidate)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self);
	QLayoutItem* (*itemAt)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self, int param1);
	QLayoutItem* (*takeAt)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self, int param1);
	int (*count)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self);
	void (*setGeometry)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self, QRect* geometry);
	QRect* (*geometry)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self);
	int (*indexOf)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self, QWidget* param1);
	bool (*isEmpty)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self);
	int (*controlTypes)(struct QBoxLayout_VTable* vtbl, const QBoxLayout* self);
	QLayout* (*layout)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self);
	void (*childEvent)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self, QChildEvent* e);
	bool (*event)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self, QEvent* event);
	bool (*eventFilter)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self, QObject* watched, QEvent* event);
	void (*timerEvent)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self, QTimerEvent* event);
	void (*customEvent)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self, QEvent* event);
	void (*connectNotify)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self, QMetaMethod* signal);
	QWidget* (*widget)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self);
	QSpacerItem* (*spacerItem)(struct QBoxLayout_VTable* vtbl, QBoxLayout* self);
};
QBoxLayout* QBoxLayout_new(struct QBoxLayout_VTable* vtbl, int param1);
QBoxLayout* QBoxLayout_new2(struct QBoxLayout_VTable* vtbl, int param1, QWidget* parent);
void QBoxLayout_virtbase(QBoxLayout* src, QLayout** outptr_QLayout);
QMetaObject* QBoxLayout_metaObject(const QBoxLayout* self);
void* QBoxLayout_metacast(QBoxLayout* self, const char* param1);
int QBoxLayout_metacall(QBoxLayout* self, int param1, int param2, void** param3);
struct miqt_string QBoxLayout_tr(const char* s);
struct miqt_string QBoxLayout_trUtf8(const char* s);
int QBoxLayout_direction(const QBoxLayout* self);
void QBoxLayout_setDirection(QBoxLayout* self, int direction);
void QBoxLayout_addSpacing(QBoxLayout* self, int size);
void QBoxLayout_addStretch(QBoxLayout* self);
void QBoxLayout_addSpacerItem(QBoxLayout* self, QSpacerItem* spacerItem);
void QBoxLayout_addWidget(QBoxLayout* self, QWidget* param1);
void QBoxLayout_addLayout(QBoxLayout* self, QLayout* layout);
void QBoxLayout_addStrut(QBoxLayout* self, int param1);
void QBoxLayout_addItem(QBoxLayout* self, QLayoutItem* param1);
void QBoxLayout_insertSpacing(QBoxLayout* self, int index, int size);
void QBoxLayout_insertStretch(QBoxLayout* self, int index);
void QBoxLayout_insertSpacerItem(QBoxLayout* self, int index, QSpacerItem* spacerItem);
void QBoxLayout_insertWidget(QBoxLayout* self, int index, QWidget* widget);
void QBoxLayout_insertLayout(QBoxLayout* self, int index, QLayout* layout);
void QBoxLayout_insertItem(QBoxLayout* self, int index, QLayoutItem* param2);
int QBoxLayout_spacing(const QBoxLayout* self);
void QBoxLayout_setSpacing(QBoxLayout* self, int spacing);
bool QBoxLayout_setStretchFactor(QBoxLayout* self, QWidget* w, int stretch);
bool QBoxLayout_setStretchFactor2(QBoxLayout* self, QLayout* l, int stretch);
void QBoxLayout_setStretch(QBoxLayout* self, int index, int stretch);
int QBoxLayout_stretch(const QBoxLayout* self, int index);
QSize* QBoxLayout_sizeHint(const QBoxLayout* self);
QSize* QBoxLayout_minimumSize(const QBoxLayout* self);
QSize* QBoxLayout_maximumSize(const QBoxLayout* self);
bool QBoxLayout_hasHeightForWidth(const QBoxLayout* self);
int QBoxLayout_heightForWidth(const QBoxLayout* self, int param1);
int QBoxLayout_minimumHeightForWidth(const QBoxLayout* self, int param1);
int QBoxLayout_expandingDirections(const QBoxLayout* self);
void QBoxLayout_invalidate(QBoxLayout* self);
QLayoutItem* QBoxLayout_itemAt(const QBoxLayout* self, int param1);
QLayoutItem* QBoxLayout_takeAt(QBoxLayout* self, int param1);
int QBoxLayout_count(const QBoxLayout* self);
void QBoxLayout_setGeometry(QBoxLayout* self, QRect* geometry);
struct miqt_string QBoxLayout_tr2(const char* s, const char* c);
struct miqt_string QBoxLayout_tr3(const char* s, const char* c, int n);
struct miqt_string QBoxLayout_trUtf82(const char* s, const char* c);
struct miqt_string QBoxLayout_trUtf83(const char* s, const char* c, int n);
void QBoxLayout_addStretch1(QBoxLayout* self, int stretch);
void QBoxLayout_addWidget2(QBoxLayout* self, QWidget* param1, int stretch);
void QBoxLayout_addWidget3(QBoxLayout* self, QWidget* param1, int stretch, int alignment);
void QBoxLayout_addLayout2(QBoxLayout* self, QLayout* layout, int stretch);
void QBoxLayout_insertStretch2(QBoxLayout* self, int index, int stretch);
void QBoxLayout_insertWidget3(QBoxLayout* self, int index, QWidget* widget, int stretch);
void QBoxLayout_insertWidget4(QBoxLayout* self, int index, QWidget* widget, int stretch, int alignment);
void QBoxLayout_insertLayout3(QBoxLayout* self, int index, QLayout* layout, int stretch);
QMetaObject* QBoxLayout_virtualbase_metaObject(const void* self);
void* QBoxLayout_virtualbase_metacast(void* self, const char* param1);
int QBoxLayout_virtualbase_metacall(void* self, int param1, int param2, void** param3);
void QBoxLayout_virtualbase_addItem(void* self, QLayoutItem* param1);
QSize* QBoxLayout_virtualbase_sizeHint(const void* self);
QSize* QBoxLayout_virtualbase_minimumSize(const void* self);
QSize* QBoxLayout_virtualbase_maximumSize(const void* self);
bool QBoxLayout_virtualbase_hasHeightForWidth(const void* self);
int QBoxLayout_virtualbase_heightForWidth(const void* self, int param1);
int QBoxLayout_virtualbase_minimumHeightForWidth(const void* self, int param1);
int QBoxLayout_virtualbase_expandingDirections(const void* self);
void QBoxLayout_virtualbase_invalidate(void* self);
QLayoutItem* QBoxLayout_virtualbase_itemAt(const void* self, int param1);
QLayoutItem* QBoxLayout_virtualbase_takeAt(void* self, int param1);
int QBoxLayout_virtualbase_count(const void* self);
void QBoxLayout_virtualbase_setGeometry(void* self, QRect* geometry);
QRect* QBoxLayout_virtualbase_geometry(const void* self);
int QBoxLayout_virtualbase_indexOf(const void* self, QWidget* param1);
bool QBoxLayout_virtualbase_isEmpty(const void* self);
int QBoxLayout_virtualbase_controlTypes(const void* self);
QLayout* QBoxLayout_virtualbase_layout(void* self);
void QBoxLayout_virtualbase_childEvent(void* self, QChildEvent* e);
bool QBoxLayout_virtualbase_event(void* self, QEvent* event);
bool QBoxLayout_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
void QBoxLayout_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QBoxLayout_virtualbase_customEvent(void* self, QEvent* event);
void QBoxLayout_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QBoxLayout_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
QWidget* QBoxLayout_virtualbase_widget(void* self);
QSpacerItem* QBoxLayout_virtualbase_spacerItem(void* self);
void QBoxLayout_protectedbase_widgetEvent(bool* _dynamic_cast_ok, void* self, QEvent* param1);
void QBoxLayout_protectedbase_addChildLayout(bool* _dynamic_cast_ok, void* self, QLayout* l);
void QBoxLayout_protectedbase_addChildWidget(bool* _dynamic_cast_ok, void* self, QWidget* w);
bool QBoxLayout_protectedbase_adoptLayout(bool* _dynamic_cast_ok, void* self, QLayout* layout);
QRect* QBoxLayout_protectedbase_alignmentRect(bool* _dynamic_cast_ok, const void* self, QRect* param1);
QObject* QBoxLayout_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QBoxLayout_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QBoxLayout_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QBoxLayout_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
const QMetaObject* QBoxLayout_staticMetaObject();
void QBoxLayout_delete(QBoxLayout* self);

struct QHBoxLayout_VTable {
	void (*destructor)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self);
	QMetaObject* (*metaObject)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self);
	void* (*metacast)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self, const char* param1);
	int (*metacall)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self, int param1, int param2, void** param3);
	void (*addItem)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self, QLayoutItem* param1);
	QSize* (*sizeHint)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self);
	QSize* (*minimumSize)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self);
	QSize* (*maximumSize)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self);
	bool (*hasHeightForWidth)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self);
	int (*heightForWidth)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self, int param1);
	int (*minimumHeightForWidth)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self, int param1);
	int (*expandingDirections)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self);
	void (*invalidate)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self);
	QLayoutItem* (*itemAt)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self, int param1);
	QLayoutItem* (*takeAt)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self, int param1);
	int (*count)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self);
	void (*setGeometry)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self, QRect* geometry);
	QRect* (*geometry)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self);
	int (*indexOf)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self, QWidget* param1);
	bool (*isEmpty)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self);
	int (*controlTypes)(struct QHBoxLayout_VTable* vtbl, const QHBoxLayout* self);
	QLayout* (*layout)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self);
	void (*childEvent)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self, QChildEvent* e);
	bool (*event)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self, QEvent* event);
	bool (*eventFilter)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self, QObject* watched, QEvent* event);
	void (*timerEvent)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self, QTimerEvent* event);
	void (*customEvent)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self, QEvent* event);
	void (*connectNotify)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self, QMetaMethod* signal);
	QWidget* (*widget)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self);
	QSpacerItem* (*spacerItem)(struct QHBoxLayout_VTable* vtbl, QHBoxLayout* self);
};
QHBoxLayout* QHBoxLayout_new(struct QHBoxLayout_VTable* vtbl, QWidget* parent);
QHBoxLayout* QHBoxLayout_new2(struct QHBoxLayout_VTable* vtbl);
void QHBoxLayout_virtbase(QHBoxLayout* src, QBoxLayout** outptr_QBoxLayout);
QMetaObject* QHBoxLayout_metaObject(const QHBoxLayout* self);
void* QHBoxLayout_metacast(QHBoxLayout* self, const char* param1);
int QHBoxLayout_metacall(QHBoxLayout* self, int param1, int param2, void** param3);
struct miqt_string QHBoxLayout_tr(const char* s);
struct miqt_string QHBoxLayout_trUtf8(const char* s);
struct miqt_string QHBoxLayout_tr2(const char* s, const char* c);
struct miqt_string QHBoxLayout_tr3(const char* s, const char* c, int n);
struct miqt_string QHBoxLayout_trUtf82(const char* s, const char* c);
struct miqt_string QHBoxLayout_trUtf83(const char* s, const char* c, int n);
QMetaObject* QHBoxLayout_virtualbase_metaObject(const void* self);
void* QHBoxLayout_virtualbase_metacast(void* self, const char* param1);
int QHBoxLayout_virtualbase_metacall(void* self, int param1, int param2, void** param3);
void QHBoxLayout_virtualbase_addItem(void* self, QLayoutItem* param1);
QSize* QHBoxLayout_virtualbase_sizeHint(const void* self);
QSize* QHBoxLayout_virtualbase_minimumSize(const void* self);
QSize* QHBoxLayout_virtualbase_maximumSize(const void* self);
bool QHBoxLayout_virtualbase_hasHeightForWidth(const void* self);
int QHBoxLayout_virtualbase_heightForWidth(const void* self, int param1);
int QHBoxLayout_virtualbase_minimumHeightForWidth(const void* self, int param1);
int QHBoxLayout_virtualbase_expandingDirections(const void* self);
void QHBoxLayout_virtualbase_invalidate(void* self);
QLayoutItem* QHBoxLayout_virtualbase_itemAt(const void* self, int param1);
QLayoutItem* QHBoxLayout_virtualbase_takeAt(void* self, int param1);
int QHBoxLayout_virtualbase_count(const void* self);
void QHBoxLayout_virtualbase_setGeometry(void* self, QRect* geometry);
QRect* QHBoxLayout_virtualbase_geometry(const void* self);
int QHBoxLayout_virtualbase_indexOf(const void* self, QWidget* param1);
bool QHBoxLayout_virtualbase_isEmpty(const void* self);
int QHBoxLayout_virtualbase_controlTypes(const void* self);
QLayout* QHBoxLayout_virtualbase_layout(void* self);
void QHBoxLayout_virtualbase_childEvent(void* self, QChildEvent* e);
bool QHBoxLayout_virtualbase_event(void* self, QEvent* event);
bool QHBoxLayout_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
void QHBoxLayout_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QHBoxLayout_virtualbase_customEvent(void* self, QEvent* event);
void QHBoxLayout_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QHBoxLayout_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
QWidget* QHBoxLayout_virtualbase_widget(void* self);
QSpacerItem* QHBoxLayout_virtualbase_spacerItem(void* self);
void QHBoxLayout_protectedbase_widgetEvent(bool* _dynamic_cast_ok, void* self, QEvent* param1);
void QHBoxLayout_protectedbase_addChildLayout(bool* _dynamic_cast_ok, void* self, QLayout* l);
void QHBoxLayout_protectedbase_addChildWidget(bool* _dynamic_cast_ok, void* self, QWidget* w);
bool QHBoxLayout_protectedbase_adoptLayout(bool* _dynamic_cast_ok, void* self, QLayout* layout);
QRect* QHBoxLayout_protectedbase_alignmentRect(bool* _dynamic_cast_ok, const void* self, QRect* param1);
QObject* QHBoxLayout_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QHBoxLayout_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QHBoxLayout_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QHBoxLayout_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
const QMetaObject* QHBoxLayout_staticMetaObject();
void QHBoxLayout_delete(QHBoxLayout* self);

struct QVBoxLayout_VTable {
	void (*destructor)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self);
	QMetaObject* (*metaObject)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self);
	void* (*metacast)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self, const char* param1);
	int (*metacall)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self, int param1, int param2, void** param3);
	void (*addItem)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self, QLayoutItem* param1);
	QSize* (*sizeHint)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self);
	QSize* (*minimumSize)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self);
	QSize* (*maximumSize)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self);
	bool (*hasHeightForWidth)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self);
	int (*heightForWidth)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self, int param1);
	int (*minimumHeightForWidth)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self, int param1);
	int (*expandingDirections)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self);
	void (*invalidate)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self);
	QLayoutItem* (*itemAt)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self, int param1);
	QLayoutItem* (*takeAt)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self, int param1);
	int (*count)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self);
	void (*setGeometry)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self, QRect* geometry);
	QRect* (*geometry)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self);
	int (*indexOf)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self, QWidget* param1);
	bool (*isEmpty)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self);
	int (*controlTypes)(struct QVBoxLayout_VTable* vtbl, const QVBoxLayout* self);
	QLayout* (*layout)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self);
	void (*childEvent)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self, QChildEvent* e);
	bool (*event)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self, QEvent* event);
	bool (*eventFilter)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self, QObject* watched, QEvent* event);
	void (*timerEvent)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self, QTimerEvent* event);
	void (*customEvent)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self, QEvent* event);
	void (*connectNotify)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self, QMetaMethod* signal);
	QWidget* (*widget)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self);
	QSpacerItem* (*spacerItem)(struct QVBoxLayout_VTable* vtbl, QVBoxLayout* self);
};
QVBoxLayout* QVBoxLayout_new(struct QVBoxLayout_VTable* vtbl, QWidget* parent);
QVBoxLayout* QVBoxLayout_new2(struct QVBoxLayout_VTable* vtbl);
void QVBoxLayout_virtbase(QVBoxLayout* src, QBoxLayout** outptr_QBoxLayout);
QMetaObject* QVBoxLayout_metaObject(const QVBoxLayout* self);
void* QVBoxLayout_metacast(QVBoxLayout* self, const char* param1);
int QVBoxLayout_metacall(QVBoxLayout* self, int param1, int param2, void** param3);
struct miqt_string QVBoxLayout_tr(const char* s);
struct miqt_string QVBoxLayout_trUtf8(const char* s);
struct miqt_string QVBoxLayout_tr2(const char* s, const char* c);
struct miqt_string QVBoxLayout_tr3(const char* s, const char* c, int n);
struct miqt_string QVBoxLayout_trUtf82(const char* s, const char* c);
struct miqt_string QVBoxLayout_trUtf83(const char* s, const char* c, int n);
QMetaObject* QVBoxLayout_virtualbase_metaObject(const void* self);
void* QVBoxLayout_virtualbase_metacast(void* self, const char* param1);
int QVBoxLayout_virtualbase_metacall(void* self, int param1, int param2, void** param3);
void QVBoxLayout_virtualbase_addItem(void* self, QLayoutItem* param1);
QSize* QVBoxLayout_virtualbase_sizeHint(const void* self);
QSize* QVBoxLayout_virtualbase_minimumSize(const void* self);
QSize* QVBoxLayout_virtualbase_maximumSize(const void* self);
bool QVBoxLayout_virtualbase_hasHeightForWidth(const void* self);
int QVBoxLayout_virtualbase_heightForWidth(const void* self, int param1);
int QVBoxLayout_virtualbase_minimumHeightForWidth(const void* self, int param1);
int QVBoxLayout_virtualbase_expandingDirections(const void* self);
void QVBoxLayout_virtualbase_invalidate(void* self);
QLayoutItem* QVBoxLayout_virtualbase_itemAt(const void* self, int param1);
QLayoutItem* QVBoxLayout_virtualbase_takeAt(void* self, int param1);
int QVBoxLayout_virtualbase_count(const void* self);
void QVBoxLayout_virtualbase_setGeometry(void* self, QRect* geometry);
QRect* QVBoxLayout_virtualbase_geometry(const void* self);
int QVBoxLayout_virtualbase_indexOf(const void* self, QWidget* param1);
bool QVBoxLayout_virtualbase_isEmpty(const void* self);
int QVBoxLayout_virtualbase_controlTypes(const void* self);
QLayout* QVBoxLayout_virtualbase_layout(void* self);
void QVBoxLayout_virtualbase_childEvent(void* self, QChildEvent* e);
bool QVBoxLayout_virtualbase_event(void* self, QEvent* event);
bool QVBoxLayout_virtualbase_eventFilter(void* self, QObject* watched, QEvent* event);
void QVBoxLayout_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QVBoxLayout_virtualbase_customEvent(void* self, QEvent* event);
void QVBoxLayout_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QVBoxLayout_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
QWidget* QVBoxLayout_virtualbase_widget(void* self);
QSpacerItem* QVBoxLayout_virtualbase_spacerItem(void* self);
void QVBoxLayout_protectedbase_widgetEvent(bool* _dynamic_cast_ok, void* self, QEvent* param1);
void QVBoxLayout_protectedbase_addChildLayout(bool* _dynamic_cast_ok, void* self, QLayout* l);
void QVBoxLayout_protectedbase_addChildWidget(bool* _dynamic_cast_ok, void* self, QWidget* w);
bool QVBoxLayout_protectedbase_adoptLayout(bool* _dynamic_cast_ok, void* self, QLayout* layout);
QRect* QVBoxLayout_protectedbase_alignmentRect(bool* _dynamic_cast_ok, const void* self, QRect* param1);
QObject* QVBoxLayout_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QVBoxLayout_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QVBoxLayout_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QVBoxLayout_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
const QMetaObject* QVBoxLayout_staticMetaObject();
void QVBoxLayout_delete(QVBoxLayout* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
