#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QSPINBOX_H
#define SEAQT_QTWIDGETS_GEN_QSPINBOX_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt-runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractSpinBox;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDoubleSpinBox;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEnterEvent;
class QEvent;
class QFocusEvent;
class QHideEvent;
class QInputMethodEvent;
class QKeyEvent;
class QLineEdit;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QResizeEvent;
class QShowEvent;
class QSize;
class QSpinBox;
class QStyleOptionSpinBox;
class QTabletEvent;
class QTimerEvent;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractSpinBox QAbstractSpinBox;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDoubleSpinBox QDoubleSpinBox;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QLineEdit QLineEdit;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QSpinBox QSpinBox;
typedef struct QStyleOptionSpinBox QStyleOptionSpinBox;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

typedef struct VirtualQSpinBox VirtualQSpinBox;
typedef struct QSpinBox_VTable{
	void (*destructor)(VirtualQSpinBox* self);
	QMetaObject* (*metaObject)(const VirtualQSpinBox* self);
	void* (*metacast)(VirtualQSpinBox* self, const char* param1);
	int (*metacall)(VirtualQSpinBox* self, int param1, int param2, void** param3);
	bool (*event)(VirtualQSpinBox* self, QEvent* event);
	int (*validate)(const VirtualQSpinBox* self, struct seaqt_string input, int* pos);
	int (*valueFromText)(const VirtualQSpinBox* self, struct seaqt_string text);
	struct seaqt_string (*textFromValue)(const VirtualQSpinBox* self, int val);
	void (*fixup)(const VirtualQSpinBox* self, struct seaqt_string str);
	QSize* (*sizeHint)(const VirtualQSpinBox* self);
	QSize* (*minimumSizeHint)(const VirtualQSpinBox* self);
	QVariant* (*inputMethodQuery)(const VirtualQSpinBox* self, int param1);
	void (*stepBy)(VirtualQSpinBox* self, int steps);
	void (*clear)(VirtualQSpinBox* self);
	void (*resizeEvent)(VirtualQSpinBox* self, QResizeEvent* event);
	void (*keyPressEvent)(VirtualQSpinBox* self, QKeyEvent* event);
	void (*keyReleaseEvent)(VirtualQSpinBox* self, QKeyEvent* event);
	void (*wheelEvent)(VirtualQSpinBox* self, QWheelEvent* event);
	void (*focusInEvent)(VirtualQSpinBox* self, QFocusEvent* event);
	void (*focusOutEvent)(VirtualQSpinBox* self, QFocusEvent* event);
	void (*contextMenuEvent)(VirtualQSpinBox* self, QContextMenuEvent* event);
	void (*changeEvent)(VirtualQSpinBox* self, QEvent* event);
	void (*closeEvent)(VirtualQSpinBox* self, QCloseEvent* event);
	void (*hideEvent)(VirtualQSpinBox* self, QHideEvent* event);
	void (*mousePressEvent)(VirtualQSpinBox* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(VirtualQSpinBox* self, QMouseEvent* event);
	void (*mouseMoveEvent)(VirtualQSpinBox* self, QMouseEvent* event);
	void (*timerEvent)(VirtualQSpinBox* self, QTimerEvent* event);
	void (*paintEvent)(VirtualQSpinBox* self, QPaintEvent* event);
	void (*showEvent)(VirtualQSpinBox* self, QShowEvent* event);
	void (*initStyleOption)(const VirtualQSpinBox* self, QStyleOptionSpinBox* option);
	int (*stepEnabled)(const VirtualQSpinBox* self);
	int (*devType)(const VirtualQSpinBox* self);
	void (*setVisible)(VirtualQSpinBox* self, bool visible);
	int (*heightForWidth)(const VirtualQSpinBox* self, int param1);
	bool (*hasHeightForWidth)(const VirtualQSpinBox* self);
	QPaintEngine* (*paintEngine)(const VirtualQSpinBox* self);
	void (*mouseDoubleClickEvent)(VirtualQSpinBox* self, QMouseEvent* event);
	void (*enterEvent)(VirtualQSpinBox* self, QEnterEvent* event);
	void (*leaveEvent)(VirtualQSpinBox* self, QEvent* event);
	void (*moveEvent)(VirtualQSpinBox* self, QMoveEvent* event);
	void (*tabletEvent)(VirtualQSpinBox* self, QTabletEvent* event);
	void (*actionEvent)(VirtualQSpinBox* self, QActionEvent* event);
	void (*dragEnterEvent)(VirtualQSpinBox* self, QDragEnterEvent* event);
	void (*dragMoveEvent)(VirtualQSpinBox* self, QDragMoveEvent* event);
	void (*dragLeaveEvent)(VirtualQSpinBox* self, QDragLeaveEvent* event);
	void (*dropEvent)(VirtualQSpinBox* self, QDropEvent* event);
	bool (*nativeEvent)(VirtualQSpinBox* self, struct seaqt_string eventType, void* message, intptr_t* result);
	int (*metric)(const VirtualQSpinBox* self, int param1);
	void (*initPainter)(const VirtualQSpinBox* self, QPainter* painter);
	QPaintDevice* (*redirected)(const VirtualQSpinBox* self, QPoint* offset);
	QPainter* (*sharedPainter)(const VirtualQSpinBox* self);
	void (*inputMethodEvent)(VirtualQSpinBox* self, QInputMethodEvent* param1);
	bool (*focusNextPrevChild)(VirtualQSpinBox* self, bool next);
	bool (*eventFilter)(VirtualQSpinBox* self, QObject* watched, QEvent* event);
	void (*childEvent)(VirtualQSpinBox* self, QChildEvent* event);
	void (*customEvent)(VirtualQSpinBox* self, QEvent* event);
	void (*connectNotify)(VirtualQSpinBox* self, QMetaMethod* signal);
	void (*disconnectNotify)(VirtualQSpinBox* self, QMetaMethod* signal);
}QSpinBox_VTable;

void* QSpinBox_vdata(VirtualQSpinBox* self);
VirtualQSpinBox* vdata_QSpinBox(void* vdata);

VirtualQSpinBox* QSpinBox_new(const QSpinBox_VTable* vtbl, size_t vdata, QWidget* parent);
VirtualQSpinBox* QSpinBox_new2(const QSpinBox_VTable* vtbl, size_t vdata);

void QSpinBox_virtbase(QSpinBox* src, QAbstractSpinBox** outptr_QAbstractSpinBox);
QMetaObject* QSpinBox_metaObject(const QSpinBox* self);
void* QSpinBox_metacast(QSpinBox* self, const char* param1);
int QSpinBox_metacall(QSpinBox* self, int param1, int param2, void** param3);
struct seaqt_string QSpinBox_tr(const char* s);
int QSpinBox_value(const QSpinBox* self);
struct seaqt_string QSpinBox_prefix(const QSpinBox* self);
void QSpinBox_setPrefix(QSpinBox* self, struct seaqt_string prefix);
struct seaqt_string QSpinBox_suffix(const QSpinBox* self);
void QSpinBox_setSuffix(QSpinBox* self, struct seaqt_string suffix);
struct seaqt_string QSpinBox_cleanText(const QSpinBox* self);
int QSpinBox_singleStep(const QSpinBox* self);
void QSpinBox_setSingleStep(QSpinBox* self, int val);
int QSpinBox_minimum(const QSpinBox* self);
void QSpinBox_setMinimum(QSpinBox* self, int min);
int QSpinBox_maximum(const QSpinBox* self);
void QSpinBox_setMaximum(QSpinBox* self, int max);
void QSpinBox_setRange(QSpinBox* self, int min, int max);
int QSpinBox_stepType(const QSpinBox* self);
void QSpinBox_setStepType(QSpinBox* self, int stepType);
int QSpinBox_displayIntegerBase(const QSpinBox* self);
void QSpinBox_setDisplayIntegerBase(QSpinBox* self, int base);
bool QSpinBox_event(QSpinBox* self, QEvent* event);
int QSpinBox_validate(const QSpinBox* self, struct seaqt_string input, int* pos);
int QSpinBox_valueFromText(const QSpinBox* self, struct seaqt_string text);
struct seaqt_string QSpinBox_textFromValue(const QSpinBox* self, int val);
void QSpinBox_fixup(const QSpinBox* self, struct seaqt_string str);
void QSpinBox_setValue(QSpinBox* self, int val);
void QSpinBox_valueChanged(QSpinBox* self, int param1);
void QSpinBox_connect_valueChanged(QSpinBox* self, intptr_t slot);
void QSpinBox_textChanged(QSpinBox* self, struct seaqt_string param1);
void QSpinBox_connect_textChanged(QSpinBox* self, intptr_t slot);
struct seaqt_string QSpinBox_tr2(const char* s, const char* c);
struct seaqt_string QSpinBox_tr3(const char* s, const char* c, int n);

QMetaObject* QSpinBox_virtualbase_metaObject(const VirtualQSpinBox* self);
void* QSpinBox_virtualbase_metacast(VirtualQSpinBox* self, const char* param1);
int QSpinBox_virtualbase_metacall(VirtualQSpinBox* self, int param1, int param2, void** param3);
bool QSpinBox_virtualbase_event(VirtualQSpinBox* self, QEvent* event);
int QSpinBox_virtualbase_validate(const VirtualQSpinBox* self, struct seaqt_string input, int* pos);
int QSpinBox_virtualbase_valueFromText(const VirtualQSpinBox* self, struct seaqt_string text);
struct seaqt_string QSpinBox_virtualbase_textFromValue(const VirtualQSpinBox* self, int val);
void QSpinBox_virtualbase_fixup(const VirtualQSpinBox* self, struct seaqt_string str);
QSize* QSpinBox_virtualbase_sizeHint(const VirtualQSpinBox* self);
QSize* QSpinBox_virtualbase_minimumSizeHint(const VirtualQSpinBox* self);
QVariant* QSpinBox_virtualbase_inputMethodQuery(const VirtualQSpinBox* self, int param1);
void QSpinBox_virtualbase_stepBy(VirtualQSpinBox* self, int steps);
void QSpinBox_virtualbase_clear(VirtualQSpinBox* self);
void QSpinBox_virtualbase_resizeEvent(VirtualQSpinBox* self, QResizeEvent* event);
void QSpinBox_virtualbase_keyPressEvent(VirtualQSpinBox* self, QKeyEvent* event);
void QSpinBox_virtualbase_keyReleaseEvent(VirtualQSpinBox* self, QKeyEvent* event);
void QSpinBox_virtualbase_wheelEvent(VirtualQSpinBox* self, QWheelEvent* event);
void QSpinBox_virtualbase_focusInEvent(VirtualQSpinBox* self, QFocusEvent* event);
void QSpinBox_virtualbase_focusOutEvent(VirtualQSpinBox* self, QFocusEvent* event);
void QSpinBox_virtualbase_contextMenuEvent(VirtualQSpinBox* self, QContextMenuEvent* event);
void QSpinBox_virtualbase_changeEvent(VirtualQSpinBox* self, QEvent* event);
void QSpinBox_virtualbase_closeEvent(VirtualQSpinBox* self, QCloseEvent* event);
void QSpinBox_virtualbase_hideEvent(VirtualQSpinBox* self, QHideEvent* event);
void QSpinBox_virtualbase_mousePressEvent(VirtualQSpinBox* self, QMouseEvent* event);
void QSpinBox_virtualbase_mouseReleaseEvent(VirtualQSpinBox* self, QMouseEvent* event);
void QSpinBox_virtualbase_mouseMoveEvent(VirtualQSpinBox* self, QMouseEvent* event);
void QSpinBox_virtualbase_timerEvent(VirtualQSpinBox* self, QTimerEvent* event);
void QSpinBox_virtualbase_paintEvent(VirtualQSpinBox* self, QPaintEvent* event);
void QSpinBox_virtualbase_showEvent(VirtualQSpinBox* self, QShowEvent* event);
void QSpinBox_virtualbase_initStyleOption(const VirtualQSpinBox* self, QStyleOptionSpinBox* option);
int QSpinBox_virtualbase_stepEnabled(const VirtualQSpinBox* self);
int QSpinBox_virtualbase_devType(const VirtualQSpinBox* self);
void QSpinBox_virtualbase_setVisible(VirtualQSpinBox* self, bool visible);
int QSpinBox_virtualbase_heightForWidth(const VirtualQSpinBox* self, int param1);
bool QSpinBox_virtualbase_hasHeightForWidth(const VirtualQSpinBox* self);
QPaintEngine* QSpinBox_virtualbase_paintEngine(const VirtualQSpinBox* self);
void QSpinBox_virtualbase_mouseDoubleClickEvent(VirtualQSpinBox* self, QMouseEvent* event);
void QSpinBox_virtualbase_enterEvent(VirtualQSpinBox* self, QEnterEvent* event);
void QSpinBox_virtualbase_leaveEvent(VirtualQSpinBox* self, QEvent* event);
void QSpinBox_virtualbase_moveEvent(VirtualQSpinBox* self, QMoveEvent* event);
void QSpinBox_virtualbase_tabletEvent(VirtualQSpinBox* self, QTabletEvent* event);
void QSpinBox_virtualbase_actionEvent(VirtualQSpinBox* self, QActionEvent* event);
void QSpinBox_virtualbase_dragEnterEvent(VirtualQSpinBox* self, QDragEnterEvent* event);
void QSpinBox_virtualbase_dragMoveEvent(VirtualQSpinBox* self, QDragMoveEvent* event);
void QSpinBox_virtualbase_dragLeaveEvent(VirtualQSpinBox* self, QDragLeaveEvent* event);
void QSpinBox_virtualbase_dropEvent(VirtualQSpinBox* self, QDropEvent* event);
bool QSpinBox_virtualbase_nativeEvent(VirtualQSpinBox* self, struct seaqt_string eventType, void* message, intptr_t* result);
int QSpinBox_virtualbase_metric(const VirtualQSpinBox* self, int param1);
void QSpinBox_virtualbase_initPainter(const VirtualQSpinBox* self, QPainter* painter);
QPaintDevice* QSpinBox_virtualbase_redirected(const VirtualQSpinBox* self, QPoint* offset);
QPainter* QSpinBox_virtualbase_sharedPainter(const VirtualQSpinBox* self);
void QSpinBox_virtualbase_inputMethodEvent(VirtualQSpinBox* self, QInputMethodEvent* param1);
bool QSpinBox_virtualbase_focusNextPrevChild(VirtualQSpinBox* self, bool next);
bool QSpinBox_virtualbase_eventFilter(VirtualQSpinBox* self, QObject* watched, QEvent* event);
void QSpinBox_virtualbase_childEvent(VirtualQSpinBox* self, QChildEvent* event);
void QSpinBox_virtualbase_customEvent(VirtualQSpinBox* self, QEvent* event);
void QSpinBox_virtualbase_connectNotify(VirtualQSpinBox* self, QMetaMethod* signal);
void QSpinBox_virtualbase_disconnectNotify(VirtualQSpinBox* self, QMetaMethod* signal);

QLineEdit* QSpinBox_protectedbase_lineEdit(const VirtualQSpinBox* self);
void QSpinBox_protectedbase_setLineEdit(VirtualQSpinBox* self, QLineEdit* edit);
void QSpinBox_protectedbase_updateMicroFocus(VirtualQSpinBox* self);
void QSpinBox_protectedbase_create(VirtualQSpinBox* self);
void QSpinBox_protectedbase_destroy(VirtualQSpinBox* self);
bool QSpinBox_protectedbase_focusNextChild(VirtualQSpinBox* self);
bool QSpinBox_protectedbase_focusPreviousChild(VirtualQSpinBox* self);
QObject* QSpinBox_protectedbase_sender(const VirtualQSpinBox* self);
int QSpinBox_protectedbase_senderSignalIndex(const VirtualQSpinBox* self);
int QSpinBox_protectedbase_receivers(const VirtualQSpinBox* self, const char* signal);
bool QSpinBox_protectedbase_isSignalConnected(const VirtualQSpinBox* self, QMetaMethod* signal);

const QMetaObject* QSpinBox_staticMetaObject();
void QSpinBox_delete(QSpinBox* self);

typedef struct VirtualQDoubleSpinBox VirtualQDoubleSpinBox;
typedef struct QDoubleSpinBox_VTable{
	void (*destructor)(VirtualQDoubleSpinBox* self);
	QMetaObject* (*metaObject)(const VirtualQDoubleSpinBox* self);
	void* (*metacast)(VirtualQDoubleSpinBox* self, const char* param1);
	int (*metacall)(VirtualQDoubleSpinBox* self, int param1, int param2, void** param3);
	int (*validate)(const VirtualQDoubleSpinBox* self, struct seaqt_string input, int* pos);
	double (*valueFromText)(const VirtualQDoubleSpinBox* self, struct seaqt_string text);
	struct seaqt_string (*textFromValue)(const VirtualQDoubleSpinBox* self, double val);
	void (*fixup)(const VirtualQDoubleSpinBox* self, struct seaqt_string str);
	QSize* (*sizeHint)(const VirtualQDoubleSpinBox* self);
	QSize* (*minimumSizeHint)(const VirtualQDoubleSpinBox* self);
	bool (*event)(VirtualQDoubleSpinBox* self, QEvent* event);
	QVariant* (*inputMethodQuery)(const VirtualQDoubleSpinBox* self, int param1);
	void (*stepBy)(VirtualQDoubleSpinBox* self, int steps);
	void (*clear)(VirtualQDoubleSpinBox* self);
	void (*resizeEvent)(VirtualQDoubleSpinBox* self, QResizeEvent* event);
	void (*keyPressEvent)(VirtualQDoubleSpinBox* self, QKeyEvent* event);
	void (*keyReleaseEvent)(VirtualQDoubleSpinBox* self, QKeyEvent* event);
	void (*wheelEvent)(VirtualQDoubleSpinBox* self, QWheelEvent* event);
	void (*focusInEvent)(VirtualQDoubleSpinBox* self, QFocusEvent* event);
	void (*focusOutEvent)(VirtualQDoubleSpinBox* self, QFocusEvent* event);
	void (*contextMenuEvent)(VirtualQDoubleSpinBox* self, QContextMenuEvent* event);
	void (*changeEvent)(VirtualQDoubleSpinBox* self, QEvent* event);
	void (*closeEvent)(VirtualQDoubleSpinBox* self, QCloseEvent* event);
	void (*hideEvent)(VirtualQDoubleSpinBox* self, QHideEvent* event);
	void (*mousePressEvent)(VirtualQDoubleSpinBox* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(VirtualQDoubleSpinBox* self, QMouseEvent* event);
	void (*mouseMoveEvent)(VirtualQDoubleSpinBox* self, QMouseEvent* event);
	void (*timerEvent)(VirtualQDoubleSpinBox* self, QTimerEvent* event);
	void (*paintEvent)(VirtualQDoubleSpinBox* self, QPaintEvent* event);
	void (*showEvent)(VirtualQDoubleSpinBox* self, QShowEvent* event);
	void (*initStyleOption)(const VirtualQDoubleSpinBox* self, QStyleOptionSpinBox* option);
	int (*stepEnabled)(const VirtualQDoubleSpinBox* self);
	int (*devType)(const VirtualQDoubleSpinBox* self);
	void (*setVisible)(VirtualQDoubleSpinBox* self, bool visible);
	int (*heightForWidth)(const VirtualQDoubleSpinBox* self, int param1);
	bool (*hasHeightForWidth)(const VirtualQDoubleSpinBox* self);
	QPaintEngine* (*paintEngine)(const VirtualQDoubleSpinBox* self);
	void (*mouseDoubleClickEvent)(VirtualQDoubleSpinBox* self, QMouseEvent* event);
	void (*enterEvent)(VirtualQDoubleSpinBox* self, QEnterEvent* event);
	void (*leaveEvent)(VirtualQDoubleSpinBox* self, QEvent* event);
	void (*moveEvent)(VirtualQDoubleSpinBox* self, QMoveEvent* event);
	void (*tabletEvent)(VirtualQDoubleSpinBox* self, QTabletEvent* event);
	void (*actionEvent)(VirtualQDoubleSpinBox* self, QActionEvent* event);
	void (*dragEnterEvent)(VirtualQDoubleSpinBox* self, QDragEnterEvent* event);
	void (*dragMoveEvent)(VirtualQDoubleSpinBox* self, QDragMoveEvent* event);
	void (*dragLeaveEvent)(VirtualQDoubleSpinBox* self, QDragLeaveEvent* event);
	void (*dropEvent)(VirtualQDoubleSpinBox* self, QDropEvent* event);
	bool (*nativeEvent)(VirtualQDoubleSpinBox* self, struct seaqt_string eventType, void* message, intptr_t* result);
	int (*metric)(const VirtualQDoubleSpinBox* self, int param1);
	void (*initPainter)(const VirtualQDoubleSpinBox* self, QPainter* painter);
	QPaintDevice* (*redirected)(const VirtualQDoubleSpinBox* self, QPoint* offset);
	QPainter* (*sharedPainter)(const VirtualQDoubleSpinBox* self);
	void (*inputMethodEvent)(VirtualQDoubleSpinBox* self, QInputMethodEvent* param1);
	bool (*focusNextPrevChild)(VirtualQDoubleSpinBox* self, bool next);
	bool (*eventFilter)(VirtualQDoubleSpinBox* self, QObject* watched, QEvent* event);
	void (*childEvent)(VirtualQDoubleSpinBox* self, QChildEvent* event);
	void (*customEvent)(VirtualQDoubleSpinBox* self, QEvent* event);
	void (*connectNotify)(VirtualQDoubleSpinBox* self, QMetaMethod* signal);
	void (*disconnectNotify)(VirtualQDoubleSpinBox* self, QMetaMethod* signal);
}QDoubleSpinBox_VTable;

void* QDoubleSpinBox_vdata(VirtualQDoubleSpinBox* self);
VirtualQDoubleSpinBox* vdata_QDoubleSpinBox(void* vdata);

VirtualQDoubleSpinBox* QDoubleSpinBox_new(const QDoubleSpinBox_VTable* vtbl, size_t vdata, QWidget* parent);
VirtualQDoubleSpinBox* QDoubleSpinBox_new2(const QDoubleSpinBox_VTable* vtbl, size_t vdata);

void QDoubleSpinBox_virtbase(QDoubleSpinBox* src, QAbstractSpinBox** outptr_QAbstractSpinBox);
QMetaObject* QDoubleSpinBox_metaObject(const QDoubleSpinBox* self);
void* QDoubleSpinBox_metacast(QDoubleSpinBox* self, const char* param1);
int QDoubleSpinBox_metacall(QDoubleSpinBox* self, int param1, int param2, void** param3);
struct seaqt_string QDoubleSpinBox_tr(const char* s);
double QDoubleSpinBox_value(const QDoubleSpinBox* self);
struct seaqt_string QDoubleSpinBox_prefix(const QDoubleSpinBox* self);
void QDoubleSpinBox_setPrefix(QDoubleSpinBox* self, struct seaqt_string prefix);
struct seaqt_string QDoubleSpinBox_suffix(const QDoubleSpinBox* self);
void QDoubleSpinBox_setSuffix(QDoubleSpinBox* self, struct seaqt_string suffix);
struct seaqt_string QDoubleSpinBox_cleanText(const QDoubleSpinBox* self);
double QDoubleSpinBox_singleStep(const QDoubleSpinBox* self);
void QDoubleSpinBox_setSingleStep(QDoubleSpinBox* self, double val);
double QDoubleSpinBox_minimum(const QDoubleSpinBox* self);
void QDoubleSpinBox_setMinimum(QDoubleSpinBox* self, double min);
double QDoubleSpinBox_maximum(const QDoubleSpinBox* self);
void QDoubleSpinBox_setMaximum(QDoubleSpinBox* self, double max);
void QDoubleSpinBox_setRange(QDoubleSpinBox* self, double min, double max);
int QDoubleSpinBox_stepType(const QDoubleSpinBox* self);
void QDoubleSpinBox_setStepType(QDoubleSpinBox* self, int stepType);
int QDoubleSpinBox_decimals(const QDoubleSpinBox* self);
void QDoubleSpinBox_setDecimals(QDoubleSpinBox* self, int prec);
int QDoubleSpinBox_validate(const QDoubleSpinBox* self, struct seaqt_string input, int* pos);
double QDoubleSpinBox_valueFromText(const QDoubleSpinBox* self, struct seaqt_string text);
struct seaqt_string QDoubleSpinBox_textFromValue(const QDoubleSpinBox* self, double val);
void QDoubleSpinBox_fixup(const QDoubleSpinBox* self, struct seaqt_string str);
void QDoubleSpinBox_setValue(QDoubleSpinBox* self, double val);
void QDoubleSpinBox_valueChanged(QDoubleSpinBox* self, double param1);
void QDoubleSpinBox_connect_valueChanged(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_textChanged(QDoubleSpinBox* self, struct seaqt_string param1);
void QDoubleSpinBox_connect_textChanged(QDoubleSpinBox* self, intptr_t slot);
struct seaqt_string QDoubleSpinBox_tr2(const char* s, const char* c);
struct seaqt_string QDoubleSpinBox_tr3(const char* s, const char* c, int n);

QMetaObject* QDoubleSpinBox_virtualbase_metaObject(const VirtualQDoubleSpinBox* self);
void* QDoubleSpinBox_virtualbase_metacast(VirtualQDoubleSpinBox* self, const char* param1);
int QDoubleSpinBox_virtualbase_metacall(VirtualQDoubleSpinBox* self, int param1, int param2, void** param3);
int QDoubleSpinBox_virtualbase_validate(const VirtualQDoubleSpinBox* self, struct seaqt_string input, int* pos);
double QDoubleSpinBox_virtualbase_valueFromText(const VirtualQDoubleSpinBox* self, struct seaqt_string text);
struct seaqt_string QDoubleSpinBox_virtualbase_textFromValue(const VirtualQDoubleSpinBox* self, double val);
void QDoubleSpinBox_virtualbase_fixup(const VirtualQDoubleSpinBox* self, struct seaqt_string str);
QSize* QDoubleSpinBox_virtualbase_sizeHint(const VirtualQDoubleSpinBox* self);
QSize* QDoubleSpinBox_virtualbase_minimumSizeHint(const VirtualQDoubleSpinBox* self);
bool QDoubleSpinBox_virtualbase_event(VirtualQDoubleSpinBox* self, QEvent* event);
QVariant* QDoubleSpinBox_virtualbase_inputMethodQuery(const VirtualQDoubleSpinBox* self, int param1);
void QDoubleSpinBox_virtualbase_stepBy(VirtualQDoubleSpinBox* self, int steps);
void QDoubleSpinBox_virtualbase_clear(VirtualQDoubleSpinBox* self);
void QDoubleSpinBox_virtualbase_resizeEvent(VirtualQDoubleSpinBox* self, QResizeEvent* event);
void QDoubleSpinBox_virtualbase_keyPressEvent(VirtualQDoubleSpinBox* self, QKeyEvent* event);
void QDoubleSpinBox_virtualbase_keyReleaseEvent(VirtualQDoubleSpinBox* self, QKeyEvent* event);
void QDoubleSpinBox_virtualbase_wheelEvent(VirtualQDoubleSpinBox* self, QWheelEvent* event);
void QDoubleSpinBox_virtualbase_focusInEvent(VirtualQDoubleSpinBox* self, QFocusEvent* event);
void QDoubleSpinBox_virtualbase_focusOutEvent(VirtualQDoubleSpinBox* self, QFocusEvent* event);
void QDoubleSpinBox_virtualbase_contextMenuEvent(VirtualQDoubleSpinBox* self, QContextMenuEvent* event);
void QDoubleSpinBox_virtualbase_changeEvent(VirtualQDoubleSpinBox* self, QEvent* event);
void QDoubleSpinBox_virtualbase_closeEvent(VirtualQDoubleSpinBox* self, QCloseEvent* event);
void QDoubleSpinBox_virtualbase_hideEvent(VirtualQDoubleSpinBox* self, QHideEvent* event);
void QDoubleSpinBox_virtualbase_mousePressEvent(VirtualQDoubleSpinBox* self, QMouseEvent* event);
void QDoubleSpinBox_virtualbase_mouseReleaseEvent(VirtualQDoubleSpinBox* self, QMouseEvent* event);
void QDoubleSpinBox_virtualbase_mouseMoveEvent(VirtualQDoubleSpinBox* self, QMouseEvent* event);
void QDoubleSpinBox_virtualbase_timerEvent(VirtualQDoubleSpinBox* self, QTimerEvent* event);
void QDoubleSpinBox_virtualbase_paintEvent(VirtualQDoubleSpinBox* self, QPaintEvent* event);
void QDoubleSpinBox_virtualbase_showEvent(VirtualQDoubleSpinBox* self, QShowEvent* event);
void QDoubleSpinBox_virtualbase_initStyleOption(const VirtualQDoubleSpinBox* self, QStyleOptionSpinBox* option);
int QDoubleSpinBox_virtualbase_stepEnabled(const VirtualQDoubleSpinBox* self);
int QDoubleSpinBox_virtualbase_devType(const VirtualQDoubleSpinBox* self);
void QDoubleSpinBox_virtualbase_setVisible(VirtualQDoubleSpinBox* self, bool visible);
int QDoubleSpinBox_virtualbase_heightForWidth(const VirtualQDoubleSpinBox* self, int param1);
bool QDoubleSpinBox_virtualbase_hasHeightForWidth(const VirtualQDoubleSpinBox* self);
QPaintEngine* QDoubleSpinBox_virtualbase_paintEngine(const VirtualQDoubleSpinBox* self);
void QDoubleSpinBox_virtualbase_mouseDoubleClickEvent(VirtualQDoubleSpinBox* self, QMouseEvent* event);
void QDoubleSpinBox_virtualbase_enterEvent(VirtualQDoubleSpinBox* self, QEnterEvent* event);
void QDoubleSpinBox_virtualbase_leaveEvent(VirtualQDoubleSpinBox* self, QEvent* event);
void QDoubleSpinBox_virtualbase_moveEvent(VirtualQDoubleSpinBox* self, QMoveEvent* event);
void QDoubleSpinBox_virtualbase_tabletEvent(VirtualQDoubleSpinBox* self, QTabletEvent* event);
void QDoubleSpinBox_virtualbase_actionEvent(VirtualQDoubleSpinBox* self, QActionEvent* event);
void QDoubleSpinBox_virtualbase_dragEnterEvent(VirtualQDoubleSpinBox* self, QDragEnterEvent* event);
void QDoubleSpinBox_virtualbase_dragMoveEvent(VirtualQDoubleSpinBox* self, QDragMoveEvent* event);
void QDoubleSpinBox_virtualbase_dragLeaveEvent(VirtualQDoubleSpinBox* self, QDragLeaveEvent* event);
void QDoubleSpinBox_virtualbase_dropEvent(VirtualQDoubleSpinBox* self, QDropEvent* event);
bool QDoubleSpinBox_virtualbase_nativeEvent(VirtualQDoubleSpinBox* self, struct seaqt_string eventType, void* message, intptr_t* result);
int QDoubleSpinBox_virtualbase_metric(const VirtualQDoubleSpinBox* self, int param1);
void QDoubleSpinBox_virtualbase_initPainter(const VirtualQDoubleSpinBox* self, QPainter* painter);
QPaintDevice* QDoubleSpinBox_virtualbase_redirected(const VirtualQDoubleSpinBox* self, QPoint* offset);
QPainter* QDoubleSpinBox_virtualbase_sharedPainter(const VirtualQDoubleSpinBox* self);
void QDoubleSpinBox_virtualbase_inputMethodEvent(VirtualQDoubleSpinBox* self, QInputMethodEvent* param1);
bool QDoubleSpinBox_virtualbase_focusNextPrevChild(VirtualQDoubleSpinBox* self, bool next);
bool QDoubleSpinBox_virtualbase_eventFilter(VirtualQDoubleSpinBox* self, QObject* watched, QEvent* event);
void QDoubleSpinBox_virtualbase_childEvent(VirtualQDoubleSpinBox* self, QChildEvent* event);
void QDoubleSpinBox_virtualbase_customEvent(VirtualQDoubleSpinBox* self, QEvent* event);
void QDoubleSpinBox_virtualbase_connectNotify(VirtualQDoubleSpinBox* self, QMetaMethod* signal);
void QDoubleSpinBox_virtualbase_disconnectNotify(VirtualQDoubleSpinBox* self, QMetaMethod* signal);

QLineEdit* QDoubleSpinBox_protectedbase_lineEdit(const VirtualQDoubleSpinBox* self);
void QDoubleSpinBox_protectedbase_setLineEdit(VirtualQDoubleSpinBox* self, QLineEdit* edit);
void QDoubleSpinBox_protectedbase_updateMicroFocus(VirtualQDoubleSpinBox* self);
void QDoubleSpinBox_protectedbase_create(VirtualQDoubleSpinBox* self);
void QDoubleSpinBox_protectedbase_destroy(VirtualQDoubleSpinBox* self);
bool QDoubleSpinBox_protectedbase_focusNextChild(VirtualQDoubleSpinBox* self);
bool QDoubleSpinBox_protectedbase_focusPreviousChild(VirtualQDoubleSpinBox* self);
QObject* QDoubleSpinBox_protectedbase_sender(const VirtualQDoubleSpinBox* self);
int QDoubleSpinBox_protectedbase_senderSignalIndex(const VirtualQDoubleSpinBox* self);
int QDoubleSpinBox_protectedbase_receivers(const VirtualQDoubleSpinBox* self, const char* signal);
bool QDoubleSpinBox_protectedbase_isSignalConnected(const VirtualQDoubleSpinBox* self, QMetaMethod* signal);

const QMetaObject* QDoubleSpinBox_staticMetaObject();
void QDoubleSpinBox_delete(QDoubleSpinBox* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
