#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QINPUTDIALOG_H
#define SEAQT_QTWIDGETS_GEN_QINPUTDIALOG_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt/libseaqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDialog;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QHideEvent;
class QInputDialog;
class QInputMethodEvent;
class QKeyEvent;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QResizeEvent;
class QShowEvent;
class QSize;
class QTabletEvent;
class QTimerEvent;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputDialog QInputDialog;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

struct QInputDialog_VTable {
	void (*destructor)(struct QInputDialog_VTable* vtbl, QInputDialog* self);
	QMetaObject* (*metaObject)(struct QInputDialog_VTable* vtbl, const QInputDialog* self);
	void* (*metacast)(struct QInputDialog_VTable* vtbl, QInputDialog* self, const char* param1);
	int (*metacall)(struct QInputDialog_VTable* vtbl, QInputDialog* self, int param1, int param2, void** param3);
	QSize* (*minimumSizeHint)(struct QInputDialog_VTable* vtbl, const QInputDialog* self);
	QSize* (*sizeHint)(struct QInputDialog_VTable* vtbl, const QInputDialog* self);
	void (*setVisible)(struct QInputDialog_VTable* vtbl, QInputDialog* self, bool visible);
	void (*done)(struct QInputDialog_VTable* vtbl, QInputDialog* self, int result);
	void (*open)(struct QInputDialog_VTable* vtbl, QInputDialog* self);
	int (*exec)(struct QInputDialog_VTable* vtbl, QInputDialog* self);
	void (*accept)(struct QInputDialog_VTable* vtbl, QInputDialog* self);
	void (*reject)(struct QInputDialog_VTable* vtbl, QInputDialog* self);
	void (*keyPressEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QKeyEvent* param1);
	void (*closeEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QCloseEvent* param1);
	void (*showEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QShowEvent* param1);
	void (*resizeEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QResizeEvent* param1);
	void (*contextMenuEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QContextMenuEvent* param1);
	bool (*eventFilter)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QObject* param1, QEvent* param2);
	int (*devType)(struct QInputDialog_VTable* vtbl, const QInputDialog* self);
	int (*heightForWidth)(struct QInputDialog_VTable* vtbl, const QInputDialog* self, int param1);
	bool (*hasHeightForWidth)(struct QInputDialog_VTable* vtbl, const QInputDialog* self);
	QPaintEngine* (*paintEngine)(struct QInputDialog_VTable* vtbl, const QInputDialog* self);
	bool (*event)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QEvent* event);
	void (*mousePressEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QMouseEvent* event);
	void (*mouseDoubleClickEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QMouseEvent* event);
	void (*mouseMoveEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QMouseEvent* event);
	void (*wheelEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QWheelEvent* event);
	void (*keyReleaseEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QKeyEvent* event);
	void (*focusInEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QFocusEvent* event);
	void (*focusOutEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QFocusEvent* event);
	void (*enterEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QEvent* event);
	void (*leaveEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QEvent* event);
	void (*paintEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QPaintEvent* event);
	void (*moveEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QMoveEvent* event);
	void (*tabletEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QTabletEvent* event);
	void (*actionEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QActionEvent* event);
	void (*dragEnterEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QDragEnterEvent* event);
	void (*dragMoveEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QDragMoveEvent* event);
	void (*dragLeaveEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QDragLeaveEvent* event);
	void (*dropEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QDropEvent* event);
	void (*hideEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QHideEvent* event);
	bool (*nativeEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, struct miqt_string eventType, void* message, long* result);
	void (*changeEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QEvent* param1);
	int (*metric)(struct QInputDialog_VTable* vtbl, const QInputDialog* self, int param1);
	void (*initPainter)(struct QInputDialog_VTable* vtbl, const QInputDialog* self, QPainter* painter);
	QPaintDevice* (*redirected)(struct QInputDialog_VTable* vtbl, const QInputDialog* self, QPoint* offset);
	QPainter* (*sharedPainter)(struct QInputDialog_VTable* vtbl, const QInputDialog* self);
	void (*inputMethodEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QInputMethodEvent* param1);
	QVariant* (*inputMethodQuery)(struct QInputDialog_VTable* vtbl, const QInputDialog* self, int param1);
	bool (*focusNextPrevChild)(struct QInputDialog_VTable* vtbl, QInputDialog* self, bool next);
	void (*timerEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QTimerEvent* event);
	void (*childEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QChildEvent* event);
	void (*customEvent)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QEvent* event);
	void (*connectNotify)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QInputDialog_VTable* vtbl, QInputDialog* self, QMetaMethod* signal);
};
QInputDialog* QInputDialog_new(struct QInputDialog_VTable* vtbl, QWidget* parent);
QInputDialog* QInputDialog_new2(struct QInputDialog_VTable* vtbl);
QInputDialog* QInputDialog_new3(struct QInputDialog_VTable* vtbl, QWidget* parent, int flags);
void QInputDialog_virtbase(QInputDialog* src, QDialog** outptr_QDialog);
QMetaObject* QInputDialog_metaObject(const QInputDialog* self);
void* QInputDialog_metacast(QInputDialog* self, const char* param1);
int QInputDialog_metacall(QInputDialog* self, int param1, int param2, void** param3);
struct miqt_string QInputDialog_tr(const char* s);
struct miqt_string QInputDialog_trUtf8(const char* s);
void QInputDialog_setInputMode(QInputDialog* self, int mode);
int QInputDialog_inputMode(const QInputDialog* self);
void QInputDialog_setLabelText(QInputDialog* self, struct miqt_string text);
struct miqt_string QInputDialog_labelText(const QInputDialog* self);
void QInputDialog_setOption(QInputDialog* self, int option);
bool QInputDialog_testOption(const QInputDialog* self, int option);
void QInputDialog_setOptions(QInputDialog* self, int options);
int QInputDialog_options(const QInputDialog* self);
void QInputDialog_setTextValue(QInputDialog* self, struct miqt_string text);
struct miqt_string QInputDialog_textValue(const QInputDialog* self);
void QInputDialog_setTextEchoMode(QInputDialog* self, int mode);
int QInputDialog_textEchoMode(const QInputDialog* self);
void QInputDialog_setComboBoxEditable(QInputDialog* self, bool editable);
bool QInputDialog_isComboBoxEditable(const QInputDialog* self);
void QInputDialog_setComboBoxItems(QInputDialog* self, struct miqt_array /* of struct miqt_string */  items);
struct miqt_array /* of struct miqt_string */  QInputDialog_comboBoxItems(const QInputDialog* self);
void QInputDialog_setIntValue(QInputDialog* self, int value);
int QInputDialog_intValue(const QInputDialog* self);
void QInputDialog_setIntMinimum(QInputDialog* self, int min);
int QInputDialog_intMinimum(const QInputDialog* self);
void QInputDialog_setIntMaximum(QInputDialog* self, int max);
int QInputDialog_intMaximum(const QInputDialog* self);
void QInputDialog_setIntRange(QInputDialog* self, int min, int max);
void QInputDialog_setIntStep(QInputDialog* self, int step);
int QInputDialog_intStep(const QInputDialog* self);
void QInputDialog_setDoubleValue(QInputDialog* self, double value);
double QInputDialog_doubleValue(const QInputDialog* self);
void QInputDialog_setDoubleMinimum(QInputDialog* self, double min);
double QInputDialog_doubleMinimum(const QInputDialog* self);
void QInputDialog_setDoubleMaximum(QInputDialog* self, double max);
double QInputDialog_doubleMaximum(const QInputDialog* self);
void QInputDialog_setDoubleRange(QInputDialog* self, double min, double max);
void QInputDialog_setDoubleDecimals(QInputDialog* self, int decimals);
int QInputDialog_doubleDecimals(const QInputDialog* self);
void QInputDialog_setOkButtonText(QInputDialog* self, struct miqt_string text);
struct miqt_string QInputDialog_okButtonText(const QInputDialog* self);
void QInputDialog_setCancelButtonText(QInputDialog* self, struct miqt_string text);
struct miqt_string QInputDialog_cancelButtonText(const QInputDialog* self);
QSize* QInputDialog_minimumSizeHint(const QInputDialog* self);
QSize* QInputDialog_sizeHint(const QInputDialog* self);
void QInputDialog_setVisible(QInputDialog* self, bool visible);
struct miqt_string QInputDialog_getText(QWidget* parent, struct miqt_string title, struct miqt_string label);
struct miqt_string QInputDialog_getMultiLineText(QWidget* parent, struct miqt_string title, struct miqt_string label);
struct miqt_string QInputDialog_getItem(QWidget* parent, struct miqt_string title, struct miqt_string label, struct miqt_array /* of struct miqt_string */  items);
int QInputDialog_getInt(QWidget* parent, struct miqt_string title, struct miqt_string label);
double QInputDialog_getDouble(QWidget* parent, struct miqt_string title, struct miqt_string label);
double QInputDialog_getDouble2(QWidget* parent, struct miqt_string title, struct miqt_string label, double value, double minValue, double maxValue, int decimals, bool* ok, int flags, double step);
void QInputDialog_setDoubleStep(QInputDialog* self, double step);
double QInputDialog_doubleStep(const QInputDialog* self);
void QInputDialog_textValueChanged(QInputDialog* self, struct miqt_string text);
void QInputDialog_connect_textValueChanged(QInputDialog* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_string), void (*release)(intptr_t));
void QInputDialog_textValueSelected(QInputDialog* self, struct miqt_string text);
void QInputDialog_connect_textValueSelected(QInputDialog* self, intptr_t slot, void (*callback)(intptr_t, struct miqt_string), void (*release)(intptr_t));
void QInputDialog_intValueChanged(QInputDialog* self, int value);
void QInputDialog_connect_intValueChanged(QInputDialog* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QInputDialog_intValueSelected(QInputDialog* self, int value);
void QInputDialog_connect_intValueSelected(QInputDialog* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QInputDialog_doubleValueChanged(QInputDialog* self, double value);
void QInputDialog_connect_doubleValueChanged(QInputDialog* self, intptr_t slot, void (*callback)(intptr_t, double), void (*release)(intptr_t));
void QInputDialog_doubleValueSelected(QInputDialog* self, double value);
void QInputDialog_connect_doubleValueSelected(QInputDialog* self, intptr_t slot, void (*callback)(intptr_t, double), void (*release)(intptr_t));
void QInputDialog_done(QInputDialog* self, int result);
struct miqt_string QInputDialog_tr2(const char* s, const char* c);
struct miqt_string QInputDialog_tr3(const char* s, const char* c, int n);
struct miqt_string QInputDialog_trUtf82(const char* s, const char* c);
struct miqt_string QInputDialog_trUtf83(const char* s, const char* c, int n);
void QInputDialog_setOption2(QInputDialog* self, int option, bool on);
struct miqt_string QInputDialog_getText4(QWidget* parent, struct miqt_string title, struct miqt_string label, int echo);
struct miqt_string QInputDialog_getText5(QWidget* parent, struct miqt_string title, struct miqt_string label, int echo, struct miqt_string text);
struct miqt_string QInputDialog_getText6(QWidget* parent, struct miqt_string title, struct miqt_string label, int echo, struct miqt_string text, bool* ok);
struct miqt_string QInputDialog_getText7(QWidget* parent, struct miqt_string title, struct miqt_string label, int echo, struct miqt_string text, bool* ok, int flags);
struct miqt_string QInputDialog_getText8(QWidget* parent, struct miqt_string title, struct miqt_string label, int echo, struct miqt_string text, bool* ok, int flags, int inputMethodHints);
struct miqt_string QInputDialog_getMultiLineText4(QWidget* parent, struct miqt_string title, struct miqt_string label, struct miqt_string text);
struct miqt_string QInputDialog_getMultiLineText5(QWidget* parent, struct miqt_string title, struct miqt_string label, struct miqt_string text, bool* ok);
struct miqt_string QInputDialog_getMultiLineText6(QWidget* parent, struct miqt_string title, struct miqt_string label, struct miqt_string text, bool* ok, int flags);
struct miqt_string QInputDialog_getMultiLineText7(QWidget* parent, struct miqt_string title, struct miqt_string label, struct miqt_string text, bool* ok, int flags, int inputMethodHints);
struct miqt_string QInputDialog_getItem5(QWidget* parent, struct miqt_string title, struct miqt_string label, struct miqt_array /* of struct miqt_string */  items, int current);
struct miqt_string QInputDialog_getItem6(QWidget* parent, struct miqt_string title, struct miqt_string label, struct miqt_array /* of struct miqt_string */  items, int current, bool editable);
struct miqt_string QInputDialog_getItem7(QWidget* parent, struct miqt_string title, struct miqt_string label, struct miqt_array /* of struct miqt_string */  items, int current, bool editable, bool* ok);
struct miqt_string QInputDialog_getItem8(QWidget* parent, struct miqt_string title, struct miqt_string label, struct miqt_array /* of struct miqt_string */  items, int current, bool editable, bool* ok, int flags);
struct miqt_string QInputDialog_getItem9(QWidget* parent, struct miqt_string title, struct miqt_string label, struct miqt_array /* of struct miqt_string */  items, int current, bool editable, bool* ok, int flags, int inputMethodHints);
int QInputDialog_getInt4(QWidget* parent, struct miqt_string title, struct miqt_string label, int value);
int QInputDialog_getInt5(QWidget* parent, struct miqt_string title, struct miqt_string label, int value, int minValue);
int QInputDialog_getInt6(QWidget* parent, struct miqt_string title, struct miqt_string label, int value, int minValue, int maxValue);
int QInputDialog_getInt7(QWidget* parent, struct miqt_string title, struct miqt_string label, int value, int minValue, int maxValue, int step);
int QInputDialog_getInt8(QWidget* parent, struct miqt_string title, struct miqt_string label, int value, int minValue, int maxValue, int step, bool* ok);
int QInputDialog_getInt9(QWidget* parent, struct miqt_string title, struct miqt_string label, int value, int minValue, int maxValue, int step, bool* ok, int flags);
double QInputDialog_getDouble4(QWidget* parent, struct miqt_string title, struct miqt_string label, double value);
double QInputDialog_getDouble5(QWidget* parent, struct miqt_string title, struct miqt_string label, double value, double minValue);
double QInputDialog_getDouble6(QWidget* parent, struct miqt_string title, struct miqt_string label, double value, double minValue, double maxValue);
double QInputDialog_getDouble7(QWidget* parent, struct miqt_string title, struct miqt_string label, double value, double minValue, double maxValue, int decimals);
double QInputDialog_getDouble8(QWidget* parent, struct miqt_string title, struct miqt_string label, double value, double minValue, double maxValue, int decimals, bool* ok);
double QInputDialog_getDouble9(QWidget* parent, struct miqt_string title, struct miqt_string label, double value, double minValue, double maxValue, int decimals, bool* ok, int flags);
QMetaObject* QInputDialog_virtualbase_metaObject(const void* self);
void* QInputDialog_virtualbase_metacast(void* self, const char* param1);
int QInputDialog_virtualbase_metacall(void* self, int param1, int param2, void** param3);
QSize* QInputDialog_virtualbase_minimumSizeHint(const void* self);
QSize* QInputDialog_virtualbase_sizeHint(const void* self);
void QInputDialog_virtualbase_setVisible(void* self, bool visible);
void QInputDialog_virtualbase_done(void* self, int result);
void QInputDialog_virtualbase_open(void* self);
int QInputDialog_virtualbase_exec(void* self);
void QInputDialog_virtualbase_accept(void* self);
void QInputDialog_virtualbase_reject(void* self);
void QInputDialog_virtualbase_keyPressEvent(void* self, QKeyEvent* param1);
void QInputDialog_virtualbase_closeEvent(void* self, QCloseEvent* param1);
void QInputDialog_virtualbase_showEvent(void* self, QShowEvent* param1);
void QInputDialog_virtualbase_resizeEvent(void* self, QResizeEvent* param1);
void QInputDialog_virtualbase_contextMenuEvent(void* self, QContextMenuEvent* param1);
bool QInputDialog_virtualbase_eventFilter(void* self, QObject* param1, QEvent* param2);
int QInputDialog_virtualbase_devType(const void* self);
int QInputDialog_virtualbase_heightForWidth(const void* self, int param1);
bool QInputDialog_virtualbase_hasHeightForWidth(const void* self);
QPaintEngine* QInputDialog_virtualbase_paintEngine(const void* self);
bool QInputDialog_virtualbase_event(void* self, QEvent* event);
void QInputDialog_virtualbase_mousePressEvent(void* self, QMouseEvent* event);
void QInputDialog_virtualbase_mouseReleaseEvent(void* self, QMouseEvent* event);
void QInputDialog_virtualbase_mouseDoubleClickEvent(void* self, QMouseEvent* event);
void QInputDialog_virtualbase_mouseMoveEvent(void* self, QMouseEvent* event);
void QInputDialog_virtualbase_wheelEvent(void* self, QWheelEvent* event);
void QInputDialog_virtualbase_keyReleaseEvent(void* self, QKeyEvent* event);
void QInputDialog_virtualbase_focusInEvent(void* self, QFocusEvent* event);
void QInputDialog_virtualbase_focusOutEvent(void* self, QFocusEvent* event);
void QInputDialog_virtualbase_enterEvent(void* self, QEvent* event);
void QInputDialog_virtualbase_leaveEvent(void* self, QEvent* event);
void QInputDialog_virtualbase_paintEvent(void* self, QPaintEvent* event);
void QInputDialog_virtualbase_moveEvent(void* self, QMoveEvent* event);
void QInputDialog_virtualbase_tabletEvent(void* self, QTabletEvent* event);
void QInputDialog_virtualbase_actionEvent(void* self, QActionEvent* event);
void QInputDialog_virtualbase_dragEnterEvent(void* self, QDragEnterEvent* event);
void QInputDialog_virtualbase_dragMoveEvent(void* self, QDragMoveEvent* event);
void QInputDialog_virtualbase_dragLeaveEvent(void* self, QDragLeaveEvent* event);
void QInputDialog_virtualbase_dropEvent(void* self, QDropEvent* event);
void QInputDialog_virtualbase_hideEvent(void* self, QHideEvent* event);
bool QInputDialog_virtualbase_nativeEvent(void* self, struct miqt_string eventType, void* message, long* result);
void QInputDialog_virtualbase_changeEvent(void* self, QEvent* param1);
int QInputDialog_virtualbase_metric(const void* self, int param1);
void QInputDialog_virtualbase_initPainter(const void* self, QPainter* painter);
QPaintDevice* QInputDialog_virtualbase_redirected(const void* self, QPoint* offset);
QPainter* QInputDialog_virtualbase_sharedPainter(const void* self);
void QInputDialog_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* param1);
QVariant* QInputDialog_virtualbase_inputMethodQuery(const void* self, int param1);
bool QInputDialog_virtualbase_focusNextPrevChild(void* self, bool next);
void QInputDialog_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QInputDialog_virtualbase_childEvent(void* self, QChildEvent* event);
void QInputDialog_virtualbase_customEvent(void* self, QEvent* event);
void QInputDialog_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QInputDialog_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
void QInputDialog_protectedbase_adjustPosition(bool* _dynamic_cast_ok, void* self, QWidget* param1);
void QInputDialog_protectedbase_updateMicroFocus(bool* _dynamic_cast_ok, void* self);
void QInputDialog_protectedbase_create(bool* _dynamic_cast_ok, void* self);
void QInputDialog_protectedbase_destroy(bool* _dynamic_cast_ok, void* self);
bool QInputDialog_protectedbase_focusNextChild(bool* _dynamic_cast_ok, void* self);
bool QInputDialog_protectedbase_focusPreviousChild(bool* _dynamic_cast_ok, void* self);
QObject* QInputDialog_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QInputDialog_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QInputDialog_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QInputDialog_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
const QMetaObject* QInputDialog_staticMetaObject();
void QInputDialog_delete(QInputDialog* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
