#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QHEADERVIEW_H
#define SEAQT_QTWIDGETS_GEN_QHEADERVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt-runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemModel;
class QAbstractItemView;
class QAbstractScrollArea;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QFrame;
class QHeaderView;
class QHideEvent;
class QInputMethodEvent;
class QItemSelection;
class QItemSelectionModel;
class QKeyEvent;
class QMargins;
class QMetaMethod;
class QMetaObject;
class QModelIndex;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QRect;
class QRegion;
class QResizeEvent;
class QShowEvent;
class QSize;
class QStyleOptionHeader;
class QStyleOptionViewItem;
class QTabletEvent;
class QTimerEvent;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHeaderView QHeaderView;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionHeader QStyleOptionHeader;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

typedef struct VirtualQHeaderView VirtualQHeaderView;
typedef struct QHeaderView_VTable{
	void (*destructor)(VirtualQHeaderView* self);
	QMetaObject* (*metaObject)(const VirtualQHeaderView* self);
	void* (*metacast)(VirtualQHeaderView* self, const char* param1);
	int (*metacall)(VirtualQHeaderView* self, int param1, int param2, void** param3);
	void (*setModel)(VirtualQHeaderView* self, QAbstractItemModel* model);
	QSize* (*sizeHint)(const VirtualQHeaderView* self);
	void (*setVisible)(VirtualQHeaderView* self, bool v);
	void (*doItemsLayout)(VirtualQHeaderView* self);
	void (*reset)(VirtualQHeaderView* self);
	void (*currentChanged)(VirtualQHeaderView* self, QModelIndex* current, QModelIndex* old);
	bool (*event)(VirtualQHeaderView* self, QEvent* e);
	void (*paintEvent)(VirtualQHeaderView* self, QPaintEvent* e);
	void (*mousePressEvent)(VirtualQHeaderView* self, QMouseEvent* e);
	void (*mouseMoveEvent)(VirtualQHeaderView* self, QMouseEvent* e);
	void (*mouseReleaseEvent)(VirtualQHeaderView* self, QMouseEvent* e);
	void (*mouseDoubleClickEvent)(VirtualQHeaderView* self, QMouseEvent* e);
	bool (*viewportEvent)(VirtualQHeaderView* self, QEvent* e);
	void (*paintSection)(const VirtualQHeaderView* self, QPainter* painter, QRect* rect, int logicalIndex);
	QSize* (*sectionSizeFromContents)(const VirtualQHeaderView* self, int logicalIndex);
	int (*horizontalOffset)(const VirtualQHeaderView* self);
	int (*verticalOffset)(const VirtualQHeaderView* self);
	void (*updateGeometries)(VirtualQHeaderView* self);
	void (*scrollContentsBy)(VirtualQHeaderView* self, int dx, int dy);
	void (*dataChanged)(VirtualQHeaderView* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct seaqt_array /* of int */  roles);
	void (*rowsInserted)(VirtualQHeaderView* self, QModelIndex* parent, int start, int end);
	QRect* (*visualRect)(const VirtualQHeaderView* self, QModelIndex* index);
	void (*scrollTo)(VirtualQHeaderView* self, QModelIndex* index, int hint);
	QModelIndex* (*indexAt)(const VirtualQHeaderView* self, QPoint* p);
	bool (*isIndexHidden)(const VirtualQHeaderView* self, QModelIndex* index);
	QModelIndex* (*moveCursor)(VirtualQHeaderView* self, int param1, int param2);
	void (*setSelection)(VirtualQHeaderView* self, QRect* rect, int flags);
	QRegion* (*visualRegionForSelection)(const VirtualQHeaderView* self, QItemSelection* selection);
	void (*setSelectionModel)(VirtualQHeaderView* self, QItemSelectionModel* selectionModel);
	void (*keyboardSearch)(VirtualQHeaderView* self, struct seaqt_string search);
	int (*sizeHintForRow)(const VirtualQHeaderView* self, int row);
	int (*sizeHintForColumn)(const VirtualQHeaderView* self, int column);
	QVariant* (*inputMethodQuery)(const VirtualQHeaderView* self, int query);
	void (*setRootIndex)(VirtualQHeaderView* self, QModelIndex* index);
	void (*selectAll)(VirtualQHeaderView* self);
	void (*rowsAboutToBeRemoved)(VirtualQHeaderView* self, QModelIndex* parent, int start, int end);
	void (*selectionChanged)(VirtualQHeaderView* self, QItemSelection* selected, QItemSelection* deselected);
	void (*updateEditorData)(VirtualQHeaderView* self);
	void (*updateEditorGeometries)(VirtualQHeaderView* self);
	void (*verticalScrollbarAction)(VirtualQHeaderView* self, int action);
	void (*horizontalScrollbarAction)(VirtualQHeaderView* self, int action);
	void (*verticalScrollbarValueChanged)(VirtualQHeaderView* self, int value);
	void (*horizontalScrollbarValueChanged)(VirtualQHeaderView* self, int value);
	void (*closeEditor)(VirtualQHeaderView* self, QWidget* editor, int hint);
	void (*commitData)(VirtualQHeaderView* self, QWidget* editor);
	void (*editorDestroyed)(VirtualQHeaderView* self, QObject* editor);
	struct seaqt_array /* of QModelIndex* */  (*selectedIndexes)(const VirtualQHeaderView* self);
	bool (*edit_index_trigger_event)(VirtualQHeaderView* self, QModelIndex* index, int trigger, QEvent* event);
	int (*selectionCommand)(const VirtualQHeaderView* self, QModelIndex* index, QEvent* event);
	void (*startDrag)(VirtualQHeaderView* self, int supportedActions);
	QStyleOptionViewItem* (*viewOptions)(const VirtualQHeaderView* self);
	bool (*focusNextPrevChild)(VirtualQHeaderView* self, bool next);
	void (*dragEnterEvent)(VirtualQHeaderView* self, QDragEnterEvent* event);
	void (*dragMoveEvent)(VirtualQHeaderView* self, QDragMoveEvent* event);
	void (*dragLeaveEvent)(VirtualQHeaderView* self, QDragLeaveEvent* event);
	void (*dropEvent)(VirtualQHeaderView* self, QDropEvent* event);
	void (*focusInEvent)(VirtualQHeaderView* self, QFocusEvent* event);
	void (*focusOutEvent)(VirtualQHeaderView* self, QFocusEvent* event);
	void (*keyPressEvent)(VirtualQHeaderView* self, QKeyEvent* event);
	void (*resizeEvent)(VirtualQHeaderView* self, QResizeEvent* event);
	void (*timerEvent)(VirtualQHeaderView* self, QTimerEvent* event);
	void (*inputMethodEvent)(VirtualQHeaderView* self, QInputMethodEvent* event);
	bool (*eventFilter)(VirtualQHeaderView* self, QObject* object, QEvent* event);
	QSize* (*viewportSizeHint)(const VirtualQHeaderView* self);
	QSize* (*minimumSizeHint)(const VirtualQHeaderView* self);
	void (*setupViewport)(VirtualQHeaderView* self, QWidget* viewport);
	void (*wheelEvent)(VirtualQHeaderView* self, QWheelEvent* param1);
	void (*contextMenuEvent)(VirtualQHeaderView* self, QContextMenuEvent* param1);
	void (*changeEvent)(VirtualQHeaderView* self, QEvent* param1);
	int (*devType)(const VirtualQHeaderView* self);
	int (*heightForWidth)(const VirtualQHeaderView* self, int param1);
	bool (*hasHeightForWidth)(const VirtualQHeaderView* self);
	QPaintEngine* (*paintEngine)(const VirtualQHeaderView* self);
	void (*keyReleaseEvent)(VirtualQHeaderView* self, QKeyEvent* event);
	void (*enterEvent)(VirtualQHeaderView* self, QEvent* event);
	void (*leaveEvent)(VirtualQHeaderView* self, QEvent* event);
	void (*moveEvent)(VirtualQHeaderView* self, QMoveEvent* event);
	void (*closeEvent)(VirtualQHeaderView* self, QCloseEvent* event);
	void (*tabletEvent)(VirtualQHeaderView* self, QTabletEvent* event);
	void (*actionEvent)(VirtualQHeaderView* self, QActionEvent* event);
	void (*showEvent)(VirtualQHeaderView* self, QShowEvent* event);
	void (*hideEvent)(VirtualQHeaderView* self, QHideEvent* event);
	bool (*nativeEvent)(VirtualQHeaderView* self, struct seaqt_string eventType, void* message, long* result);
	int (*metric)(const VirtualQHeaderView* self, int param1);
	void (*initPainter)(const VirtualQHeaderView* self, QPainter* painter);
	QPaintDevice* (*redirected)(const VirtualQHeaderView* self, QPoint* offset);
	QPainter* (*sharedPainter)(const VirtualQHeaderView* self);
	void (*childEvent)(VirtualQHeaderView* self, QChildEvent* event);
	void (*customEvent)(VirtualQHeaderView* self, QEvent* event);
	void (*connectNotify)(VirtualQHeaderView* self, QMetaMethod* signal);
	void (*disconnectNotify)(VirtualQHeaderView* self, QMetaMethod* signal);
}QHeaderView_VTable;

void* QHeaderView_vdata(VirtualQHeaderView* self);
VirtualQHeaderView* vdata_QHeaderView(void* vdata);

VirtualQHeaderView* QHeaderView_new_orientation(const QHeaderView_VTable* vtbl, size_t vdata, int orientation);
VirtualQHeaderView* QHeaderView_new_orientation_parent(const QHeaderView_VTable* vtbl, size_t vdata, int orientation, QWidget* parent);

void QHeaderView_virtbase(QHeaderView* src, QAbstractItemView** outptr_QAbstractItemView);
QMetaObject* QHeaderView_metaObject(const QHeaderView* self);
void* QHeaderView_metacast(QHeaderView* self, const char* param1);
int QHeaderView_metacall(QHeaderView* self, int param1, int param2, void** param3);
struct seaqt_string QHeaderView_tr_s(const char* s);
struct seaqt_string QHeaderView_trUtf8_s(const char* s);
void QHeaderView_setModel(QHeaderView* self, QAbstractItemModel* model);
int QHeaderView_orientation(const QHeaderView* self);
int QHeaderView_offset(const QHeaderView* self);
int QHeaderView_length(const QHeaderView* self);
QSize* QHeaderView_sizeHint(const QHeaderView* self);
void QHeaderView_setVisible(QHeaderView* self, bool v);
int QHeaderView_sectionSizeHint(const QHeaderView* self, int logicalIndex);
int QHeaderView_visualIndexAt(const QHeaderView* self, int position);
int QHeaderView_logicalIndexAt_position(const QHeaderView* self, int position);
int QHeaderView_logicalIndexAt_x_y(const QHeaderView* self, int x, int y);
int QHeaderView_logicalIndexAt_pos(const QHeaderView* self, QPoint* pos);
int QHeaderView_sectionSize(const QHeaderView* self, int logicalIndex);
int QHeaderView_sectionPosition(const QHeaderView* self, int logicalIndex);
int QHeaderView_sectionViewportPosition(const QHeaderView* self, int logicalIndex);
void QHeaderView_moveSection(QHeaderView* self, int from, int to);
void QHeaderView_swapSections(QHeaderView* self, int first, int second);
void QHeaderView_resizeSection(QHeaderView* self, int logicalIndex, int size);
void QHeaderView_resizeSections_mode(QHeaderView* self, int mode);
bool QHeaderView_isSectionHidden(const QHeaderView* self, int logicalIndex);
void QHeaderView_setSectionHidden(QHeaderView* self, int logicalIndex, bool hide);
int QHeaderView_hiddenSectionCount(const QHeaderView* self);
void QHeaderView_hideSection(QHeaderView* self, int logicalIndex);
void QHeaderView_showSection(QHeaderView* self, int logicalIndex);
int QHeaderView_count(const QHeaderView* self);
int QHeaderView_visualIndex(const QHeaderView* self, int logicalIndex);
int QHeaderView_logicalIndex(const QHeaderView* self, int visualIndex);
void QHeaderView_setSectionsMovable(QHeaderView* self, bool movable);
bool QHeaderView_sectionsMovable(const QHeaderView* self);
void QHeaderView_setFirstSectionMovable(QHeaderView* self, bool movable);
bool QHeaderView_isFirstSectionMovable(const QHeaderView* self);
void QHeaderView_setSectionsClickable(QHeaderView* self, bool clickable);
bool QHeaderView_sectionsClickable(const QHeaderView* self);
void QHeaderView_setHighlightSections(QHeaderView* self, bool highlight);
bool QHeaderView_highlightSections(const QHeaderView* self);
int QHeaderView_sectionResizeMode(const QHeaderView* self, int logicalIndex);
void QHeaderView_setSectionResizeMode_mode(QHeaderView* self, int mode);
void QHeaderView_setSectionResizeMode_logicalIndex_mode(QHeaderView* self, int logicalIndex, int mode);
void QHeaderView_setResizeContentsPrecision(QHeaderView* self, int precision);
int QHeaderView_resizeContentsPrecision(const QHeaderView* self);
int QHeaderView_stretchSectionCount(const QHeaderView* self);
void QHeaderView_setSortIndicatorShown(QHeaderView* self, bool show);
bool QHeaderView_isSortIndicatorShown(const QHeaderView* self);
void QHeaderView_setSortIndicator(QHeaderView* self, int logicalIndex, int order);
int QHeaderView_sortIndicatorSection(const QHeaderView* self);
int QHeaderView_sortIndicatorOrder(const QHeaderView* self);
bool QHeaderView_stretchLastSection(const QHeaderView* self);
void QHeaderView_setStretchLastSection(QHeaderView* self, bool stretch);
bool QHeaderView_cascadingSectionResizes(const QHeaderView* self);
void QHeaderView_setCascadingSectionResizes(QHeaderView* self, bool enable);
int QHeaderView_defaultSectionSize(const QHeaderView* self);
void QHeaderView_setDefaultSectionSize(QHeaderView* self, int size);
void QHeaderView_resetDefaultSectionSize(QHeaderView* self);
int QHeaderView_minimumSectionSize(const QHeaderView* self);
void QHeaderView_setMinimumSectionSize(QHeaderView* self, int size);
int QHeaderView_maximumSectionSize(const QHeaderView* self);
void QHeaderView_setMaximumSectionSize(QHeaderView* self, int size);
int QHeaderView_defaultAlignment(const QHeaderView* self);
void QHeaderView_setDefaultAlignment(QHeaderView* self, int alignment);
void QHeaderView_doItemsLayout(QHeaderView* self);
bool QHeaderView_sectionsMoved(const QHeaderView* self);
bool QHeaderView_sectionsHidden(const QHeaderView* self);
struct seaqt_string QHeaderView_saveState(const QHeaderView* self);
bool QHeaderView_restoreState(QHeaderView* self, struct seaqt_string state);
void QHeaderView_reset(QHeaderView* self);
void QHeaderView_setOffset(QHeaderView* self, int offset);
void QHeaderView_setOffsetToSectionPosition(QHeaderView* self, int visualIndex);
void QHeaderView_setOffsetToLastSection(QHeaderView* self);
void QHeaderView_headerDataChanged(QHeaderView* self, int orientation, int logicalFirst, int logicalLast);
void QHeaderView_sectionMoved(QHeaderView* self, int logicalIndex, int oldVisualIndex, int newVisualIndex);
void QHeaderView_connect_sectionMoved(QHeaderView* self, intptr_t slot, void (*callback)(intptr_t, int, int, int), void (*release)(intptr_t));
void QHeaderView_sectionResized(QHeaderView* self, int logicalIndex, int oldSize, int newSize);
void QHeaderView_connect_sectionResized(QHeaderView* self, intptr_t slot, void (*callback)(intptr_t, int, int, int), void (*release)(intptr_t));
void QHeaderView_sectionPressed(QHeaderView* self, int logicalIndex);
void QHeaderView_connect_sectionPressed(QHeaderView* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QHeaderView_sectionClicked(QHeaderView* self, int logicalIndex);
void QHeaderView_connect_sectionClicked(QHeaderView* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QHeaderView_sectionEntered(QHeaderView* self, int logicalIndex);
void QHeaderView_connect_sectionEntered(QHeaderView* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QHeaderView_sectionDoubleClicked(QHeaderView* self, int logicalIndex);
void QHeaderView_connect_sectionDoubleClicked(QHeaderView* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QHeaderView_sectionCountChanged(QHeaderView* self, int oldCount, int newCount);
void QHeaderView_connect_sectionCountChanged(QHeaderView* self, intptr_t slot, void (*callback)(intptr_t, int, int), void (*release)(intptr_t));
void QHeaderView_sectionHandleDoubleClicked(QHeaderView* self, int logicalIndex);
void QHeaderView_connect_sectionHandleDoubleClicked(QHeaderView* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QHeaderView_geometriesChanged(QHeaderView* self);
void QHeaderView_connect_geometriesChanged(QHeaderView* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
void QHeaderView_sortIndicatorChanged(QHeaderView* self, int logicalIndex, int order);
void QHeaderView_connect_sortIndicatorChanged(QHeaderView* self, intptr_t slot, void (*callback)(intptr_t, int, int), void (*release)(intptr_t));
void QHeaderView_currentChanged(QHeaderView* self, QModelIndex* current, QModelIndex* old);
bool QHeaderView_event(QHeaderView* self, QEvent* e);
void QHeaderView_paintEvent(QHeaderView* self, QPaintEvent* e);
void QHeaderView_mousePressEvent(QHeaderView* self, QMouseEvent* e);
void QHeaderView_mouseMoveEvent(QHeaderView* self, QMouseEvent* e);
void QHeaderView_mouseReleaseEvent(QHeaderView* self, QMouseEvent* e);
void QHeaderView_mouseDoubleClickEvent(QHeaderView* self, QMouseEvent* e);
bool QHeaderView_viewportEvent(QHeaderView* self, QEvent* e);
void QHeaderView_paintSection(const QHeaderView* self, QPainter* painter, QRect* rect, int logicalIndex);
QSize* QHeaderView_sectionSizeFromContents(const QHeaderView* self, int logicalIndex);
int QHeaderView_horizontalOffset(const QHeaderView* self);
int QHeaderView_verticalOffset(const QHeaderView* self);
void QHeaderView_updateGeometries(QHeaderView* self);
void QHeaderView_scrollContentsBy(QHeaderView* self, int dx, int dy);
void QHeaderView_dataChanged(QHeaderView* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct seaqt_array /* of int */  roles);
void QHeaderView_rowsInserted(QHeaderView* self, QModelIndex* parent, int start, int end);
QRect* QHeaderView_visualRect(const QHeaderView* self, QModelIndex* index);
void QHeaderView_scrollTo(QHeaderView* self, QModelIndex* index, int hint);
QModelIndex* QHeaderView_indexAt(const QHeaderView* self, QPoint* p);
bool QHeaderView_isIndexHidden(const QHeaderView* self, QModelIndex* index);
QModelIndex* QHeaderView_moveCursor(QHeaderView* self, int param1, int param2);
void QHeaderView_setSelection(QHeaderView* self, QRect* rect, int flags);
QRegion* QHeaderView_visualRegionForSelection(const QHeaderView* self, QItemSelection* selection);
struct seaqt_string QHeaderView_tr_s_c(const char* s, const char* c);
struct seaqt_string QHeaderView_tr_s_c_n(const char* s, const char* c, int n);
struct seaqt_string QHeaderView_trUtf8_s_c(const char* s, const char* c);
struct seaqt_string QHeaderView_trUtf8_s_c_n(const char* s, const char* c, int n);

QMetaObject* QHeaderView_virtualbase_metaObject(const VirtualQHeaderView* self);
void* QHeaderView_virtualbase_metacast(VirtualQHeaderView* self, const char* param1);
int QHeaderView_virtualbase_metacall(VirtualQHeaderView* self, int param1, int param2, void** param3);
void QHeaderView_virtualbase_setModel(VirtualQHeaderView* self, QAbstractItemModel* model);
QSize* QHeaderView_virtualbase_sizeHint(const VirtualQHeaderView* self);
void QHeaderView_virtualbase_setVisible(VirtualQHeaderView* self, bool v);
void QHeaderView_virtualbase_doItemsLayout(VirtualQHeaderView* self);
void QHeaderView_virtualbase_reset(VirtualQHeaderView* self);
void QHeaderView_virtualbase_currentChanged(VirtualQHeaderView* self, QModelIndex* current, QModelIndex* old);
bool QHeaderView_virtualbase_event(VirtualQHeaderView* self, QEvent* e);
void QHeaderView_virtualbase_paintEvent(VirtualQHeaderView* self, QPaintEvent* e);
void QHeaderView_virtualbase_mousePressEvent(VirtualQHeaderView* self, QMouseEvent* e);
void QHeaderView_virtualbase_mouseMoveEvent(VirtualQHeaderView* self, QMouseEvent* e);
void QHeaderView_virtualbase_mouseReleaseEvent(VirtualQHeaderView* self, QMouseEvent* e);
void QHeaderView_virtualbase_mouseDoubleClickEvent(VirtualQHeaderView* self, QMouseEvent* e);
bool QHeaderView_virtualbase_viewportEvent(VirtualQHeaderView* self, QEvent* e);
void QHeaderView_virtualbase_paintSection(const VirtualQHeaderView* self, QPainter* painter, QRect* rect, int logicalIndex);
QSize* QHeaderView_virtualbase_sectionSizeFromContents(const VirtualQHeaderView* self, int logicalIndex);
int QHeaderView_virtualbase_horizontalOffset(const VirtualQHeaderView* self);
int QHeaderView_virtualbase_verticalOffset(const VirtualQHeaderView* self);
void QHeaderView_virtualbase_updateGeometries(VirtualQHeaderView* self);
void QHeaderView_virtualbase_scrollContentsBy(VirtualQHeaderView* self, int dx, int dy);
void QHeaderView_virtualbase_dataChanged(VirtualQHeaderView* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct seaqt_array /* of int */  roles);
void QHeaderView_virtualbase_rowsInserted(VirtualQHeaderView* self, QModelIndex* parent, int start, int end);
QRect* QHeaderView_virtualbase_visualRect(const VirtualQHeaderView* self, QModelIndex* index);
void QHeaderView_virtualbase_scrollTo(VirtualQHeaderView* self, QModelIndex* index, int hint);
QModelIndex* QHeaderView_virtualbase_indexAt(const VirtualQHeaderView* self, QPoint* p);
bool QHeaderView_virtualbase_isIndexHidden(const VirtualQHeaderView* self, QModelIndex* index);
QModelIndex* QHeaderView_virtualbase_moveCursor(VirtualQHeaderView* self, int param1, int param2);
void QHeaderView_virtualbase_setSelection(VirtualQHeaderView* self, QRect* rect, int flags);
QRegion* QHeaderView_virtualbase_visualRegionForSelection(const VirtualQHeaderView* self, QItemSelection* selection);
void QHeaderView_virtualbase_setSelectionModel(VirtualQHeaderView* self, QItemSelectionModel* selectionModel);
void QHeaderView_virtualbase_keyboardSearch(VirtualQHeaderView* self, struct seaqt_string search);
int QHeaderView_virtualbase_sizeHintForRow(const VirtualQHeaderView* self, int row);
int QHeaderView_virtualbase_sizeHintForColumn(const VirtualQHeaderView* self, int column);
QVariant* QHeaderView_virtualbase_inputMethodQuery(const VirtualQHeaderView* self, int query);
void QHeaderView_virtualbase_setRootIndex(VirtualQHeaderView* self, QModelIndex* index);
void QHeaderView_virtualbase_selectAll(VirtualQHeaderView* self);
void QHeaderView_virtualbase_rowsAboutToBeRemoved(VirtualQHeaderView* self, QModelIndex* parent, int start, int end);
void QHeaderView_virtualbase_selectionChanged(VirtualQHeaderView* self, QItemSelection* selected, QItemSelection* deselected);
void QHeaderView_virtualbase_updateEditorData(VirtualQHeaderView* self);
void QHeaderView_virtualbase_updateEditorGeometries(VirtualQHeaderView* self);
void QHeaderView_virtualbase_verticalScrollbarAction(VirtualQHeaderView* self, int action);
void QHeaderView_virtualbase_horizontalScrollbarAction(VirtualQHeaderView* self, int action);
void QHeaderView_virtualbase_verticalScrollbarValueChanged(VirtualQHeaderView* self, int value);
void QHeaderView_virtualbase_horizontalScrollbarValueChanged(VirtualQHeaderView* self, int value);
void QHeaderView_virtualbase_closeEditor(VirtualQHeaderView* self, QWidget* editor, int hint);
void QHeaderView_virtualbase_commitData(VirtualQHeaderView* self, QWidget* editor);
void QHeaderView_virtualbase_editorDestroyed(VirtualQHeaderView* self, QObject* editor);
struct seaqt_array /* of QModelIndex* */  QHeaderView_virtualbase_selectedIndexes(const VirtualQHeaderView* self);
bool QHeaderView_virtualbase_edit_index_trigger_event(VirtualQHeaderView* self, QModelIndex* index, int trigger, QEvent* event);
int QHeaderView_virtualbase_selectionCommand(const VirtualQHeaderView* self, QModelIndex* index, QEvent* event);
void QHeaderView_virtualbase_startDrag(VirtualQHeaderView* self, int supportedActions);
QStyleOptionViewItem* QHeaderView_virtualbase_viewOptions(const VirtualQHeaderView* self);
bool QHeaderView_virtualbase_focusNextPrevChild(VirtualQHeaderView* self, bool next);
void QHeaderView_virtualbase_dragEnterEvent(VirtualQHeaderView* self, QDragEnterEvent* event);
void QHeaderView_virtualbase_dragMoveEvent(VirtualQHeaderView* self, QDragMoveEvent* event);
void QHeaderView_virtualbase_dragLeaveEvent(VirtualQHeaderView* self, QDragLeaveEvent* event);
void QHeaderView_virtualbase_dropEvent(VirtualQHeaderView* self, QDropEvent* event);
void QHeaderView_virtualbase_focusInEvent(VirtualQHeaderView* self, QFocusEvent* event);
void QHeaderView_virtualbase_focusOutEvent(VirtualQHeaderView* self, QFocusEvent* event);
void QHeaderView_virtualbase_keyPressEvent(VirtualQHeaderView* self, QKeyEvent* event);
void QHeaderView_virtualbase_resizeEvent(VirtualQHeaderView* self, QResizeEvent* event);
void QHeaderView_virtualbase_timerEvent(VirtualQHeaderView* self, QTimerEvent* event);
void QHeaderView_virtualbase_inputMethodEvent(VirtualQHeaderView* self, QInputMethodEvent* event);
bool QHeaderView_virtualbase_eventFilter(VirtualQHeaderView* self, QObject* object, QEvent* event);
QSize* QHeaderView_virtualbase_viewportSizeHint(const VirtualQHeaderView* self);
QSize* QHeaderView_virtualbase_minimumSizeHint(const VirtualQHeaderView* self);
void QHeaderView_virtualbase_setupViewport(VirtualQHeaderView* self, QWidget* viewport);
void QHeaderView_virtualbase_wheelEvent(VirtualQHeaderView* self, QWheelEvent* param1);
void QHeaderView_virtualbase_contextMenuEvent(VirtualQHeaderView* self, QContextMenuEvent* param1);
void QHeaderView_virtualbase_changeEvent(VirtualQHeaderView* self, QEvent* param1);
int QHeaderView_virtualbase_devType(const VirtualQHeaderView* self);
int QHeaderView_virtualbase_heightForWidth(const VirtualQHeaderView* self, int param1);
bool QHeaderView_virtualbase_hasHeightForWidth(const VirtualQHeaderView* self);
QPaintEngine* QHeaderView_virtualbase_paintEngine(const VirtualQHeaderView* self);
void QHeaderView_virtualbase_keyReleaseEvent(VirtualQHeaderView* self, QKeyEvent* event);
void QHeaderView_virtualbase_enterEvent(VirtualQHeaderView* self, QEvent* event);
void QHeaderView_virtualbase_leaveEvent(VirtualQHeaderView* self, QEvent* event);
void QHeaderView_virtualbase_moveEvent(VirtualQHeaderView* self, QMoveEvent* event);
void QHeaderView_virtualbase_closeEvent(VirtualQHeaderView* self, QCloseEvent* event);
void QHeaderView_virtualbase_tabletEvent(VirtualQHeaderView* self, QTabletEvent* event);
void QHeaderView_virtualbase_actionEvent(VirtualQHeaderView* self, QActionEvent* event);
void QHeaderView_virtualbase_showEvent(VirtualQHeaderView* self, QShowEvent* event);
void QHeaderView_virtualbase_hideEvent(VirtualQHeaderView* self, QHideEvent* event);
bool QHeaderView_virtualbase_nativeEvent(VirtualQHeaderView* self, struct seaqt_string eventType, void* message, long* result);
int QHeaderView_virtualbase_metric(const VirtualQHeaderView* self, int param1);
void QHeaderView_virtualbase_initPainter(const VirtualQHeaderView* self, QPainter* painter);
QPaintDevice* QHeaderView_virtualbase_redirected(const VirtualQHeaderView* self, QPoint* offset);
QPainter* QHeaderView_virtualbase_sharedPainter(const VirtualQHeaderView* self);
void QHeaderView_virtualbase_childEvent(VirtualQHeaderView* self, QChildEvent* event);
void QHeaderView_virtualbase_customEvent(VirtualQHeaderView* self, QEvent* event);
void QHeaderView_virtualbase_connectNotify(VirtualQHeaderView* self, QMetaMethod* signal);
void QHeaderView_virtualbase_disconnectNotify(VirtualQHeaderView* self, QMetaMethod* signal);

void QHeaderView_protectedbase_updateSection(VirtualQHeaderView* self, int logicalIndex);
void QHeaderView_protectedbase_resizeSections(VirtualQHeaderView* self);
void QHeaderView_protectedbase_sectionsInserted(VirtualQHeaderView* self, QModelIndex* parent, int logicalFirst, int logicalLast);
void QHeaderView_protectedbase_sectionsAboutToBeRemoved(VirtualQHeaderView* self, QModelIndex* parent, int logicalFirst, int logicalLast);
void QHeaderView_protectedbase_initialize(VirtualQHeaderView* self);
void QHeaderView_protectedbase_initializeSections(VirtualQHeaderView* self);
void QHeaderView_protectedbase_initializeSections_start_end(VirtualQHeaderView* self, int start, int end);
void QHeaderView_protectedbase_initStyleOption(const VirtualQHeaderView* self, QStyleOptionHeader* option);
void QHeaderView_protectedbase_setHorizontalStepsPerItem(VirtualQHeaderView* self, int steps);
int QHeaderView_protectedbase_horizontalStepsPerItem(const VirtualQHeaderView* self);
void QHeaderView_protectedbase_setVerticalStepsPerItem(VirtualQHeaderView* self, int steps);
int QHeaderView_protectedbase_verticalStepsPerItem(const VirtualQHeaderView* self);
int QHeaderView_protectedbase_state(const VirtualQHeaderView* self);
void QHeaderView_protectedbase_setState(VirtualQHeaderView* self, int state);
void QHeaderView_protectedbase_scheduleDelayedItemsLayout(VirtualQHeaderView* self);
void QHeaderView_protectedbase_executeDelayedItemsLayout(VirtualQHeaderView* self);
void QHeaderView_protectedbase_setDirtyRegion(VirtualQHeaderView* self, QRegion* region);
void QHeaderView_protectedbase_scrollDirtyRegion(VirtualQHeaderView* self, int dx, int dy);
QPoint* QHeaderView_protectedbase_dirtyRegionOffset(const VirtualQHeaderView* self);
void QHeaderView_protectedbase_startAutoScroll(VirtualQHeaderView* self);
void QHeaderView_protectedbase_stopAutoScroll(VirtualQHeaderView* self);
void QHeaderView_protectedbase_doAutoScroll(VirtualQHeaderView* self);
int QHeaderView_protectedbase_dropIndicatorPosition(const VirtualQHeaderView* self);
void QHeaderView_protectedbase_setViewportMargins_left_top_right_bottom(VirtualQHeaderView* self, int left, int top, int right, int bottom);
QMargins* QHeaderView_protectedbase_viewportMargins(const VirtualQHeaderView* self);
void QHeaderView_protectedbase_drawFrame(VirtualQHeaderView* self, QPainter* param1);
void QHeaderView_protectedbase_updateMicroFocus(VirtualQHeaderView* self);
void QHeaderView_protectedbase_create(VirtualQHeaderView* self);
void QHeaderView_protectedbase_destroy(VirtualQHeaderView* self);
bool QHeaderView_protectedbase_focusNextChild(VirtualQHeaderView* self);
bool QHeaderView_protectedbase_focusPreviousChild(VirtualQHeaderView* self);
QObject* QHeaderView_protectedbase_sender(const VirtualQHeaderView* self);
int QHeaderView_protectedbase_senderSignalIndex(const VirtualQHeaderView* self);
int QHeaderView_protectedbase_receivers(const VirtualQHeaderView* self, const char* signal);
bool QHeaderView_protectedbase_isSignalConnected(const VirtualQHeaderView* self, QMetaMethod* signal);

void QHeaderView_delete(QHeaderView* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
