#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QTREEVIEW_H
#define SEAQT_QTWIDGETS_GEN_QTREEVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt-runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemModel;
class QAbstractItemView;
class QAbstractScrollArea;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QFrame;
class QHeaderView;
class QHideEvent;
class QInputMethodEvent;
class QItemSelection;
class QItemSelectionModel;
class QKeyEvent;
class QMargins;
class QMetaMethod;
class QMetaObject;
class QModelIndex;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QRect;
class QRegion;
class QResizeEvent;
class QShowEvent;
class QSize;
class QStyleOptionFrame;
class QStyleOptionViewItem;
class QTabletEvent;
class QTimerEvent;
class QTreeView;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHeaderView QHeaderView;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QTreeView QTreeView;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

typedef struct VirtualQTreeView VirtualQTreeView;
typedef struct QTreeView_VTable{
	void (*destructor)(VirtualQTreeView* self);
	QMetaObject* (*metaObject)(const VirtualQTreeView* self);
	void* (*metacast)(VirtualQTreeView* self, const char* param1);
	int (*metacall)(VirtualQTreeView* self, int param1, int param2, void** param3);
	void (*setModel)(VirtualQTreeView* self, QAbstractItemModel* model);
	void (*setRootIndex)(VirtualQTreeView* self, QModelIndex* index);
	void (*setSelectionModel)(VirtualQTreeView* self, QItemSelectionModel* selectionModel);
	void (*keyboardSearch)(VirtualQTreeView* self, struct seaqt_string search);
	QRect* (*visualRect)(const VirtualQTreeView* self, QModelIndex* index);
	void (*scrollTo)(VirtualQTreeView* self, QModelIndex* index, int hint);
	QModelIndex* (*indexAt)(const VirtualQTreeView* self, QPoint* p);
	void (*doItemsLayout)(VirtualQTreeView* self);
	void (*reset)(VirtualQTreeView* self);
	void (*dataChanged)(VirtualQTreeView* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct seaqt_array /* of int */  roles);
	void (*selectAll)(VirtualQTreeView* self);
	void (*verticalScrollbarValueChanged)(VirtualQTreeView* self, int value);
	void (*scrollContentsBy)(VirtualQTreeView* self, int dx, int dy);
	void (*rowsInserted)(VirtualQTreeView* self, QModelIndex* parent, int start, int end);
	void (*rowsAboutToBeRemoved)(VirtualQTreeView* self, QModelIndex* parent, int start, int end);
	QModelIndex* (*moveCursor)(VirtualQTreeView* self, int cursorAction, int modifiers);
	int (*horizontalOffset)(const VirtualQTreeView* self);
	int (*verticalOffset)(const VirtualQTreeView* self);
	void (*setSelection)(VirtualQTreeView* self, QRect* rect, int command);
	QRegion* (*visualRegionForSelection)(const VirtualQTreeView* self, QItemSelection* selection);
	struct seaqt_array /* of QModelIndex* */  (*selectedIndexes)(const VirtualQTreeView* self);
	void (*timerEvent)(VirtualQTreeView* self, QTimerEvent* event);
	void (*paintEvent)(VirtualQTreeView* self, QPaintEvent* event);
	void (*drawRow)(const VirtualQTreeView* self, QPainter* painter, QStyleOptionViewItem* options, QModelIndex* index);
	void (*drawBranches)(const VirtualQTreeView* self, QPainter* painter, QRect* rect, QModelIndex* index);
	void (*mousePressEvent)(VirtualQTreeView* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(VirtualQTreeView* self, QMouseEvent* event);
	void (*mouseDoubleClickEvent)(VirtualQTreeView* self, QMouseEvent* event);
	void (*mouseMoveEvent)(VirtualQTreeView* self, QMouseEvent* event);
	void (*keyPressEvent)(VirtualQTreeView* self, QKeyEvent* event);
	void (*dragMoveEvent)(VirtualQTreeView* self, QDragMoveEvent* event);
	bool (*viewportEvent)(VirtualQTreeView* self, QEvent* event);
	void (*updateGeometries)(VirtualQTreeView* self);
	QSize* (*viewportSizeHint)(const VirtualQTreeView* self);
	int (*sizeHintForColumn)(const VirtualQTreeView* self, int column);
	void (*horizontalScrollbarAction)(VirtualQTreeView* self, int action);
	bool (*isIndexHidden)(const VirtualQTreeView* self, QModelIndex* index);
	void (*selectionChanged)(VirtualQTreeView* self, QItemSelection* selected, QItemSelection* deselected);
	void (*currentChanged)(VirtualQTreeView* self, QModelIndex* current, QModelIndex* previous);
	int (*sizeHintForRow)(const VirtualQTreeView* self, int row);
	QVariant* (*inputMethodQuery)(const VirtualQTreeView* self, int query);
	void (*updateEditorData)(VirtualQTreeView* self);
	void (*updateEditorGeometries)(VirtualQTreeView* self);
	void (*verticalScrollbarAction)(VirtualQTreeView* self, int action);
	void (*horizontalScrollbarValueChanged)(VirtualQTreeView* self, int value);
	void (*closeEditor)(VirtualQTreeView* self, QWidget* editor, int hint);
	void (*commitData)(VirtualQTreeView* self, QWidget* editor);
	void (*editorDestroyed)(VirtualQTreeView* self, QObject* editor);
	bool (*edit_index_trigger_event)(VirtualQTreeView* self, QModelIndex* index, int trigger, QEvent* event);
	int (*selectionCommand)(const VirtualQTreeView* self, QModelIndex* index, QEvent* event);
	void (*startDrag)(VirtualQTreeView* self, int supportedActions);
	QStyleOptionViewItem* (*viewOptions)(const VirtualQTreeView* self);
	bool (*focusNextPrevChild)(VirtualQTreeView* self, bool next);
	bool (*event)(VirtualQTreeView* self, QEvent* event);
	void (*dragEnterEvent)(VirtualQTreeView* self, QDragEnterEvent* event);
	void (*dragLeaveEvent)(VirtualQTreeView* self, QDragLeaveEvent* event);
	void (*dropEvent)(VirtualQTreeView* self, QDropEvent* event);
	void (*focusInEvent)(VirtualQTreeView* self, QFocusEvent* event);
	void (*focusOutEvent)(VirtualQTreeView* self, QFocusEvent* event);
	void (*resizeEvent)(VirtualQTreeView* self, QResizeEvent* event);
	void (*inputMethodEvent)(VirtualQTreeView* self, QInputMethodEvent* event);
	bool (*eventFilter)(VirtualQTreeView* self, QObject* object, QEvent* event);
	QSize* (*minimumSizeHint)(const VirtualQTreeView* self);
	QSize* (*sizeHint)(const VirtualQTreeView* self);
	void (*setupViewport)(VirtualQTreeView* self, QWidget* viewport);
	void (*wheelEvent)(VirtualQTreeView* self, QWheelEvent* param1);
	void (*contextMenuEvent)(VirtualQTreeView* self, QContextMenuEvent* param1);
	void (*changeEvent)(VirtualQTreeView* self, QEvent* param1);
	int (*devType)(const VirtualQTreeView* self);
	void (*setVisible)(VirtualQTreeView* self, bool visible);
	int (*heightForWidth)(const VirtualQTreeView* self, int param1);
	bool (*hasHeightForWidth)(const VirtualQTreeView* self);
	QPaintEngine* (*paintEngine)(const VirtualQTreeView* self);
	void (*keyReleaseEvent)(VirtualQTreeView* self, QKeyEvent* event);
	void (*enterEvent)(VirtualQTreeView* self, QEvent* event);
	void (*leaveEvent)(VirtualQTreeView* self, QEvent* event);
	void (*moveEvent)(VirtualQTreeView* self, QMoveEvent* event);
	void (*closeEvent)(VirtualQTreeView* self, QCloseEvent* event);
	void (*tabletEvent)(VirtualQTreeView* self, QTabletEvent* event);
	void (*actionEvent)(VirtualQTreeView* self, QActionEvent* event);
	void (*showEvent)(VirtualQTreeView* self, QShowEvent* event);
	void (*hideEvent)(VirtualQTreeView* self, QHideEvent* event);
	bool (*nativeEvent)(VirtualQTreeView* self, struct seaqt_string eventType, void* message, long* result);
	int (*metric)(const VirtualQTreeView* self, int param1);
	void (*initPainter)(const VirtualQTreeView* self, QPainter* painter);
	QPaintDevice* (*redirected)(const VirtualQTreeView* self, QPoint* offset);
	QPainter* (*sharedPainter)(const VirtualQTreeView* self);
	void (*childEvent)(VirtualQTreeView* self, QChildEvent* event);
	void (*customEvent)(VirtualQTreeView* self, QEvent* event);
	void (*connectNotify)(VirtualQTreeView* self, QMetaMethod* signal);
	void (*disconnectNotify)(VirtualQTreeView* self, QMetaMethod* signal);
}QTreeView_VTable;

void* QTreeView_vdata(VirtualQTreeView* self);
VirtualQTreeView* vdata_QTreeView(void* vdata);

VirtualQTreeView* QTreeView_new(const QTreeView_VTable* vtbl, size_t vdata);
VirtualQTreeView* QTreeView_new_parent(const QTreeView_VTable* vtbl, size_t vdata, QWidget* parent);

void QTreeView_virtbase(QTreeView* src, QAbstractItemView** outptr_QAbstractItemView);
QMetaObject* QTreeView_metaObject(const QTreeView* self);
void* QTreeView_metacast(QTreeView* self, const char* param1);
int QTreeView_metacall(QTreeView* self, int param1, int param2, void** param3);
struct seaqt_string QTreeView_tr_s(const char* s);
struct seaqt_string QTreeView_trUtf8_s(const char* s);
void QTreeView_setModel(QTreeView* self, QAbstractItemModel* model);
void QTreeView_setRootIndex(QTreeView* self, QModelIndex* index);
void QTreeView_setSelectionModel(QTreeView* self, QItemSelectionModel* selectionModel);
QHeaderView* QTreeView_header(const QTreeView* self);
void QTreeView_setHeader(QTreeView* self, QHeaderView* header);
int QTreeView_autoExpandDelay(const QTreeView* self);
void QTreeView_setAutoExpandDelay(QTreeView* self, int delay);
int QTreeView_indentation(const QTreeView* self);
void QTreeView_setIndentation(QTreeView* self, int i);
void QTreeView_resetIndentation(QTreeView* self);
bool QTreeView_rootIsDecorated(const QTreeView* self);
void QTreeView_setRootIsDecorated(QTreeView* self, bool show);
bool QTreeView_uniformRowHeights(const QTreeView* self);
void QTreeView_setUniformRowHeights(QTreeView* self, bool uniform);
bool QTreeView_itemsExpandable(const QTreeView* self);
void QTreeView_setItemsExpandable(QTreeView* self, bool enable);
bool QTreeView_expandsOnDoubleClick(const QTreeView* self);
void QTreeView_setExpandsOnDoubleClick(QTreeView* self, bool enable);
int QTreeView_columnViewportPosition(const QTreeView* self, int column);
int QTreeView_columnWidth(const QTreeView* self, int column);
void QTreeView_setColumnWidth(QTreeView* self, int column, int width);
int QTreeView_columnAt(const QTreeView* self, int x);
bool QTreeView_isColumnHidden(const QTreeView* self, int column);
void QTreeView_setColumnHidden(QTreeView* self, int column, bool hide);
bool QTreeView_isHeaderHidden(const QTreeView* self);
void QTreeView_setHeaderHidden(QTreeView* self, bool hide);
bool QTreeView_isRowHidden(const QTreeView* self, int row, QModelIndex* parent);
void QTreeView_setRowHidden(QTreeView* self, int row, QModelIndex* parent, bool hide);
bool QTreeView_isFirstColumnSpanned(const QTreeView* self, int row, QModelIndex* parent);
void QTreeView_setFirstColumnSpanned(QTreeView* self, int row, QModelIndex* parent, bool span);
bool QTreeView_isExpanded(const QTreeView* self, QModelIndex* index);
void QTreeView_setExpanded(QTreeView* self, QModelIndex* index, bool expand);
void QTreeView_setSortingEnabled(QTreeView* self, bool enable);
bool QTreeView_isSortingEnabled(const QTreeView* self);
void QTreeView_setAnimated(QTreeView* self, bool enable);
bool QTreeView_isAnimated(const QTreeView* self);
void QTreeView_setAllColumnsShowFocus(QTreeView* self, bool enable);
bool QTreeView_allColumnsShowFocus(const QTreeView* self);
void QTreeView_setWordWrap(QTreeView* self, bool on);
bool QTreeView_wordWrap(const QTreeView* self);
void QTreeView_setTreePosition(QTreeView* self, int logicalIndex);
int QTreeView_treePosition(const QTreeView* self);
void QTreeView_keyboardSearch(QTreeView* self, struct seaqt_string search);
QRect* QTreeView_visualRect(const QTreeView* self, QModelIndex* index);
void QTreeView_scrollTo(QTreeView* self, QModelIndex* index, int hint);
QModelIndex* QTreeView_indexAt(const QTreeView* self, QPoint* p);
QModelIndex* QTreeView_indexAbove(const QTreeView* self, QModelIndex* index);
QModelIndex* QTreeView_indexBelow(const QTreeView* self, QModelIndex* index);
void QTreeView_doItemsLayout(QTreeView* self);
void QTreeView_reset(QTreeView* self);
void QTreeView_dataChanged(QTreeView* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct seaqt_array /* of int */  roles);
void QTreeView_selectAll(QTreeView* self);
void QTreeView_expanded(QTreeView* self, QModelIndex* index);
void QTreeView_connect_expanded(QTreeView* self, intptr_t slot, void (*callback)(intptr_t, QModelIndex*), void (*release)(intptr_t));
void QTreeView_collapsed(QTreeView* self, QModelIndex* index);
void QTreeView_connect_collapsed(QTreeView* self, intptr_t slot, void (*callback)(intptr_t, QModelIndex*), void (*release)(intptr_t));
void QTreeView_hideColumn(QTreeView* self, int column);
void QTreeView_showColumn(QTreeView* self, int column);
void QTreeView_expand(QTreeView* self, QModelIndex* index);
void QTreeView_collapse(QTreeView* self, QModelIndex* index);
void QTreeView_resizeColumnToContents(QTreeView* self, int column);
void QTreeView_sortByColumn_column(QTreeView* self, int column);
void QTreeView_sortByColumn_column_order(QTreeView* self, int column, int order);
void QTreeView_expandAll(QTreeView* self);
void QTreeView_expandRecursively_index(QTreeView* self, QModelIndex* index);
void QTreeView_collapseAll(QTreeView* self);
void QTreeView_expandToDepth(QTreeView* self, int depth);
void QTreeView_verticalScrollbarValueChanged(QTreeView* self, int value);
void QTreeView_scrollContentsBy(QTreeView* self, int dx, int dy);
void QTreeView_rowsInserted(QTreeView* self, QModelIndex* parent, int start, int end);
void QTreeView_rowsAboutToBeRemoved(QTreeView* self, QModelIndex* parent, int start, int end);
QModelIndex* QTreeView_moveCursor(QTreeView* self, int cursorAction, int modifiers);
int QTreeView_horizontalOffset(const QTreeView* self);
int QTreeView_verticalOffset(const QTreeView* self);
void QTreeView_setSelection(QTreeView* self, QRect* rect, int command);
QRegion* QTreeView_visualRegionForSelection(const QTreeView* self, QItemSelection* selection);
struct seaqt_array /* of QModelIndex* */  QTreeView_selectedIndexes(const QTreeView* self);
void QTreeView_timerEvent(QTreeView* self, QTimerEvent* event);
void QTreeView_paintEvent(QTreeView* self, QPaintEvent* event);
void QTreeView_drawRow(const QTreeView* self, QPainter* painter, QStyleOptionViewItem* options, QModelIndex* index);
void QTreeView_drawBranches(const QTreeView* self, QPainter* painter, QRect* rect, QModelIndex* index);
void QTreeView_mousePressEvent(QTreeView* self, QMouseEvent* event);
void QTreeView_mouseReleaseEvent(QTreeView* self, QMouseEvent* event);
void QTreeView_mouseDoubleClickEvent(QTreeView* self, QMouseEvent* event);
void QTreeView_mouseMoveEvent(QTreeView* self, QMouseEvent* event);
void QTreeView_keyPressEvent(QTreeView* self, QKeyEvent* event);
void QTreeView_dragMoveEvent(QTreeView* self, QDragMoveEvent* event);
bool QTreeView_viewportEvent(QTreeView* self, QEvent* event);
void QTreeView_updateGeometries(QTreeView* self);
QSize* QTreeView_viewportSizeHint(const QTreeView* self);
int QTreeView_sizeHintForColumn(const QTreeView* self, int column);
void QTreeView_horizontalScrollbarAction(QTreeView* self, int action);
bool QTreeView_isIndexHidden(const QTreeView* self, QModelIndex* index);
void QTreeView_selectionChanged(QTreeView* self, QItemSelection* selected, QItemSelection* deselected);
void QTreeView_currentChanged(QTreeView* self, QModelIndex* current, QModelIndex* previous);
struct seaqt_string QTreeView_tr_s_c(const char* s, const char* c);
struct seaqt_string QTreeView_tr_s_c_n(const char* s, const char* c, int n);
struct seaqt_string QTreeView_trUtf8_s_c(const char* s, const char* c);
struct seaqt_string QTreeView_trUtf8_s_c_n(const char* s, const char* c, int n);
void QTreeView_expandRecursively_index_depth(QTreeView* self, QModelIndex* index, int depth);

QMetaObject* QTreeView_virtualbase_metaObject(const VirtualQTreeView* self);
void* QTreeView_virtualbase_metacast(VirtualQTreeView* self, const char* param1);
int QTreeView_virtualbase_metacall(VirtualQTreeView* self, int param1, int param2, void** param3);
void QTreeView_virtualbase_setModel(VirtualQTreeView* self, QAbstractItemModel* model);
void QTreeView_virtualbase_setRootIndex(VirtualQTreeView* self, QModelIndex* index);
void QTreeView_virtualbase_setSelectionModel(VirtualQTreeView* self, QItemSelectionModel* selectionModel);
void QTreeView_virtualbase_keyboardSearch(VirtualQTreeView* self, struct seaqt_string search);
QRect* QTreeView_virtualbase_visualRect(const VirtualQTreeView* self, QModelIndex* index);
void QTreeView_virtualbase_scrollTo(VirtualQTreeView* self, QModelIndex* index, int hint);
QModelIndex* QTreeView_virtualbase_indexAt(const VirtualQTreeView* self, QPoint* p);
void QTreeView_virtualbase_doItemsLayout(VirtualQTreeView* self);
void QTreeView_virtualbase_reset(VirtualQTreeView* self);
void QTreeView_virtualbase_dataChanged(VirtualQTreeView* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct seaqt_array /* of int */  roles);
void QTreeView_virtualbase_selectAll(VirtualQTreeView* self);
void QTreeView_virtualbase_verticalScrollbarValueChanged(VirtualQTreeView* self, int value);
void QTreeView_virtualbase_scrollContentsBy(VirtualQTreeView* self, int dx, int dy);
void QTreeView_virtualbase_rowsInserted(VirtualQTreeView* self, QModelIndex* parent, int start, int end);
void QTreeView_virtualbase_rowsAboutToBeRemoved(VirtualQTreeView* self, QModelIndex* parent, int start, int end);
QModelIndex* QTreeView_virtualbase_moveCursor(VirtualQTreeView* self, int cursorAction, int modifiers);
int QTreeView_virtualbase_horizontalOffset(const VirtualQTreeView* self);
int QTreeView_virtualbase_verticalOffset(const VirtualQTreeView* self);
void QTreeView_virtualbase_setSelection(VirtualQTreeView* self, QRect* rect, int command);
QRegion* QTreeView_virtualbase_visualRegionForSelection(const VirtualQTreeView* self, QItemSelection* selection);
struct seaqt_array /* of QModelIndex* */  QTreeView_virtualbase_selectedIndexes(const VirtualQTreeView* self);
void QTreeView_virtualbase_timerEvent(VirtualQTreeView* self, QTimerEvent* event);
void QTreeView_virtualbase_paintEvent(VirtualQTreeView* self, QPaintEvent* event);
void QTreeView_virtualbase_drawRow(const VirtualQTreeView* self, QPainter* painter, QStyleOptionViewItem* options, QModelIndex* index);
void QTreeView_virtualbase_drawBranches(const VirtualQTreeView* self, QPainter* painter, QRect* rect, QModelIndex* index);
void QTreeView_virtualbase_mousePressEvent(VirtualQTreeView* self, QMouseEvent* event);
void QTreeView_virtualbase_mouseReleaseEvent(VirtualQTreeView* self, QMouseEvent* event);
void QTreeView_virtualbase_mouseDoubleClickEvent(VirtualQTreeView* self, QMouseEvent* event);
void QTreeView_virtualbase_mouseMoveEvent(VirtualQTreeView* self, QMouseEvent* event);
void QTreeView_virtualbase_keyPressEvent(VirtualQTreeView* self, QKeyEvent* event);
void QTreeView_virtualbase_dragMoveEvent(VirtualQTreeView* self, QDragMoveEvent* event);
bool QTreeView_virtualbase_viewportEvent(VirtualQTreeView* self, QEvent* event);
void QTreeView_virtualbase_updateGeometries(VirtualQTreeView* self);
QSize* QTreeView_virtualbase_viewportSizeHint(const VirtualQTreeView* self);
int QTreeView_virtualbase_sizeHintForColumn(const VirtualQTreeView* self, int column);
void QTreeView_virtualbase_horizontalScrollbarAction(VirtualQTreeView* self, int action);
bool QTreeView_virtualbase_isIndexHidden(const VirtualQTreeView* self, QModelIndex* index);
void QTreeView_virtualbase_selectionChanged(VirtualQTreeView* self, QItemSelection* selected, QItemSelection* deselected);
void QTreeView_virtualbase_currentChanged(VirtualQTreeView* self, QModelIndex* current, QModelIndex* previous);
int QTreeView_virtualbase_sizeHintForRow(const VirtualQTreeView* self, int row);
QVariant* QTreeView_virtualbase_inputMethodQuery(const VirtualQTreeView* self, int query);
void QTreeView_virtualbase_updateEditorData(VirtualQTreeView* self);
void QTreeView_virtualbase_updateEditorGeometries(VirtualQTreeView* self);
void QTreeView_virtualbase_verticalScrollbarAction(VirtualQTreeView* self, int action);
void QTreeView_virtualbase_horizontalScrollbarValueChanged(VirtualQTreeView* self, int value);
void QTreeView_virtualbase_closeEditor(VirtualQTreeView* self, QWidget* editor, int hint);
void QTreeView_virtualbase_commitData(VirtualQTreeView* self, QWidget* editor);
void QTreeView_virtualbase_editorDestroyed(VirtualQTreeView* self, QObject* editor);
bool QTreeView_virtualbase_edit_index_trigger_event(VirtualQTreeView* self, QModelIndex* index, int trigger, QEvent* event);
int QTreeView_virtualbase_selectionCommand(const VirtualQTreeView* self, QModelIndex* index, QEvent* event);
void QTreeView_virtualbase_startDrag(VirtualQTreeView* self, int supportedActions);
QStyleOptionViewItem* QTreeView_virtualbase_viewOptions(const VirtualQTreeView* self);
bool QTreeView_virtualbase_focusNextPrevChild(VirtualQTreeView* self, bool next);
bool QTreeView_virtualbase_event(VirtualQTreeView* self, QEvent* event);
void QTreeView_virtualbase_dragEnterEvent(VirtualQTreeView* self, QDragEnterEvent* event);
void QTreeView_virtualbase_dragLeaveEvent(VirtualQTreeView* self, QDragLeaveEvent* event);
void QTreeView_virtualbase_dropEvent(VirtualQTreeView* self, QDropEvent* event);
void QTreeView_virtualbase_focusInEvent(VirtualQTreeView* self, QFocusEvent* event);
void QTreeView_virtualbase_focusOutEvent(VirtualQTreeView* self, QFocusEvent* event);
void QTreeView_virtualbase_resizeEvent(VirtualQTreeView* self, QResizeEvent* event);
void QTreeView_virtualbase_inputMethodEvent(VirtualQTreeView* self, QInputMethodEvent* event);
bool QTreeView_virtualbase_eventFilter(VirtualQTreeView* self, QObject* object, QEvent* event);
QSize* QTreeView_virtualbase_minimumSizeHint(const VirtualQTreeView* self);
QSize* QTreeView_virtualbase_sizeHint(const VirtualQTreeView* self);
void QTreeView_virtualbase_setupViewport(VirtualQTreeView* self, QWidget* viewport);
void QTreeView_virtualbase_wheelEvent(VirtualQTreeView* self, QWheelEvent* param1);
void QTreeView_virtualbase_contextMenuEvent(VirtualQTreeView* self, QContextMenuEvent* param1);
void QTreeView_virtualbase_changeEvent(VirtualQTreeView* self, QEvent* param1);
int QTreeView_virtualbase_devType(const VirtualQTreeView* self);
void QTreeView_virtualbase_setVisible(VirtualQTreeView* self, bool visible);
int QTreeView_virtualbase_heightForWidth(const VirtualQTreeView* self, int param1);
bool QTreeView_virtualbase_hasHeightForWidth(const VirtualQTreeView* self);
QPaintEngine* QTreeView_virtualbase_paintEngine(const VirtualQTreeView* self);
void QTreeView_virtualbase_keyReleaseEvent(VirtualQTreeView* self, QKeyEvent* event);
void QTreeView_virtualbase_enterEvent(VirtualQTreeView* self, QEvent* event);
void QTreeView_virtualbase_leaveEvent(VirtualQTreeView* self, QEvent* event);
void QTreeView_virtualbase_moveEvent(VirtualQTreeView* self, QMoveEvent* event);
void QTreeView_virtualbase_closeEvent(VirtualQTreeView* self, QCloseEvent* event);
void QTreeView_virtualbase_tabletEvent(VirtualQTreeView* self, QTabletEvent* event);
void QTreeView_virtualbase_actionEvent(VirtualQTreeView* self, QActionEvent* event);
void QTreeView_virtualbase_showEvent(VirtualQTreeView* self, QShowEvent* event);
void QTreeView_virtualbase_hideEvent(VirtualQTreeView* self, QHideEvent* event);
bool QTreeView_virtualbase_nativeEvent(VirtualQTreeView* self, struct seaqt_string eventType, void* message, long* result);
int QTreeView_virtualbase_metric(const VirtualQTreeView* self, int param1);
void QTreeView_virtualbase_initPainter(const VirtualQTreeView* self, QPainter* painter);
QPaintDevice* QTreeView_virtualbase_redirected(const VirtualQTreeView* self, QPoint* offset);
QPainter* QTreeView_virtualbase_sharedPainter(const VirtualQTreeView* self);
void QTreeView_virtualbase_childEvent(VirtualQTreeView* self, QChildEvent* event);
void QTreeView_virtualbase_customEvent(VirtualQTreeView* self, QEvent* event);
void QTreeView_virtualbase_connectNotify(VirtualQTreeView* self, QMetaMethod* signal);
void QTreeView_virtualbase_disconnectNotify(VirtualQTreeView* self, QMetaMethod* signal);

void QTreeView_protectedbase_columnResized(VirtualQTreeView* self, int column, int oldSize, int newSize);
void QTreeView_protectedbase_columnCountChanged(VirtualQTreeView* self, int oldCount, int newCount);
void QTreeView_protectedbase_columnMoved(VirtualQTreeView* self);
void QTreeView_protectedbase_reexpand(VirtualQTreeView* self);
void QTreeView_protectedbase_rowsRemoved(VirtualQTreeView* self, QModelIndex* parent, int first, int last);
void QTreeView_protectedbase_drawTree(const VirtualQTreeView* self, QPainter* painter, QRegion* region);
int QTreeView_protectedbase_indexRowSizeHint(const VirtualQTreeView* self, QModelIndex* index);
int QTreeView_protectedbase_rowHeight(const VirtualQTreeView* self, QModelIndex* index);
void QTreeView_protectedbase_setHorizontalStepsPerItem(VirtualQTreeView* self, int steps);
int QTreeView_protectedbase_horizontalStepsPerItem(const VirtualQTreeView* self);
void QTreeView_protectedbase_setVerticalStepsPerItem(VirtualQTreeView* self, int steps);
int QTreeView_protectedbase_verticalStepsPerItem(const VirtualQTreeView* self);
int QTreeView_protectedbase_state(const VirtualQTreeView* self);
void QTreeView_protectedbase_setState(VirtualQTreeView* self, int state);
void QTreeView_protectedbase_scheduleDelayedItemsLayout(VirtualQTreeView* self);
void QTreeView_protectedbase_executeDelayedItemsLayout(VirtualQTreeView* self);
void QTreeView_protectedbase_setDirtyRegion(VirtualQTreeView* self, QRegion* region);
void QTreeView_protectedbase_scrollDirtyRegion(VirtualQTreeView* self, int dx, int dy);
QPoint* QTreeView_protectedbase_dirtyRegionOffset(const VirtualQTreeView* self);
void QTreeView_protectedbase_startAutoScroll(VirtualQTreeView* self);
void QTreeView_protectedbase_stopAutoScroll(VirtualQTreeView* self);
void QTreeView_protectedbase_doAutoScroll(VirtualQTreeView* self);
int QTreeView_protectedbase_dropIndicatorPosition(const VirtualQTreeView* self);
void QTreeView_protectedbase_setViewportMargins_left_top_right_bottom(VirtualQTreeView* self, int left, int top, int right, int bottom);
QMargins* QTreeView_protectedbase_viewportMargins(const VirtualQTreeView* self);
void QTreeView_protectedbase_drawFrame(VirtualQTreeView* self, QPainter* param1);
void QTreeView_protectedbase_initStyleOption(const VirtualQTreeView* self, QStyleOptionFrame* option);
void QTreeView_protectedbase_updateMicroFocus(VirtualQTreeView* self);
void QTreeView_protectedbase_create(VirtualQTreeView* self);
void QTreeView_protectedbase_destroy(VirtualQTreeView* self);
bool QTreeView_protectedbase_focusNextChild(VirtualQTreeView* self);
bool QTreeView_protectedbase_focusPreviousChild(VirtualQTreeView* self);
QObject* QTreeView_protectedbase_sender(const VirtualQTreeView* self);
int QTreeView_protectedbase_senderSignalIndex(const VirtualQTreeView* self);
int QTreeView_protectedbase_receivers(const VirtualQTreeView* self, const char* signal);
bool QTreeView_protectedbase_isSignalConnected(const VirtualQTreeView* self, QMetaMethod* signal);

const QMetaObject* QTreeView_staticMetaObject();
void QTreeView_delete(QTreeView* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
