#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QTREEVIEW_H
#define SEAQT_QTWIDGETS_GEN_QTREEVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt/libseaqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemDelegate;
class QAbstractItemModel;
class QAbstractItemView;
class QAbstractScrollArea;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEnterEvent;
class QEvent;
class QFocusEvent;
class QFrame;
class QHeaderView;
class QHideEvent;
class QInputMethodEvent;
class QItemSelection;
class QItemSelectionModel;
class QKeyEvent;
class QMargins;
class QMetaMethod;
class QMetaObject;
class QModelIndex;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QRect;
class QRegion;
class QResizeEvent;
class QShowEvent;
class QSize;
class QStyleOptionFrame;
class QStyleOptionViewItem;
class QTabletEvent;
class QTimerEvent;
class QTreeView;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHeaderView QHeaderView;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QTreeView QTreeView;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

struct QTreeView_VTable {
	void (*destructor)(struct QTreeView_VTable* vtbl, QTreeView* self);
	QMetaObject* (*metaObject)(struct QTreeView_VTable* vtbl, const QTreeView* self);
	void* (*metacast)(struct QTreeView_VTable* vtbl, QTreeView* self, const char* param1);
	int (*metacall)(struct QTreeView_VTable* vtbl, QTreeView* self, int param1, int param2, void** param3);
	void (*setModel)(struct QTreeView_VTable* vtbl, QTreeView* self, QAbstractItemModel* model);
	void (*setRootIndex)(struct QTreeView_VTable* vtbl, QTreeView* self, QModelIndex* index);
	void (*setSelectionModel)(struct QTreeView_VTable* vtbl, QTreeView* self, QItemSelectionModel* selectionModel);
	void (*keyboardSearch)(struct QTreeView_VTable* vtbl, QTreeView* self, struct miqt_string search);
	QRect* (*visualRect)(struct QTreeView_VTable* vtbl, const QTreeView* self, QModelIndex* index);
	void (*scrollTo)(struct QTreeView_VTable* vtbl, QTreeView* self, QModelIndex* index, int hint);
	QModelIndex* (*indexAt)(struct QTreeView_VTable* vtbl, const QTreeView* self, QPoint* p);
	void (*doItemsLayout)(struct QTreeView_VTable* vtbl, QTreeView* self);
	void (*reset)(struct QTreeView_VTable* vtbl, QTreeView* self);
	void (*dataChanged)(struct QTreeView_VTable* vtbl, QTreeView* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct miqt_array /* of int */  roles);
	void (*selectAll)(struct QTreeView_VTable* vtbl, QTreeView* self);
	void (*verticalScrollbarValueChanged)(struct QTreeView_VTable* vtbl, QTreeView* self, int value);
	void (*scrollContentsBy)(struct QTreeView_VTable* vtbl, QTreeView* self, int dx, int dy);
	void (*rowsInserted)(struct QTreeView_VTable* vtbl, QTreeView* self, QModelIndex* parent, int start, int end);
	void (*rowsAboutToBeRemoved)(struct QTreeView_VTable* vtbl, QTreeView* self, QModelIndex* parent, int start, int end);
	QModelIndex* (*moveCursor)(struct QTreeView_VTable* vtbl, QTreeView* self, int cursorAction, int modifiers);
	int (*horizontalOffset)(struct QTreeView_VTable* vtbl, const QTreeView* self);
	int (*verticalOffset)(struct QTreeView_VTable* vtbl, const QTreeView* self);
	void (*setSelection)(struct QTreeView_VTable* vtbl, QTreeView* self, QRect* rect, int command);
	QRegion* (*visualRegionForSelection)(struct QTreeView_VTable* vtbl, const QTreeView* self, QItemSelection* selection);
	struct miqt_array /* of QModelIndex* */  (*selectedIndexes)(struct QTreeView_VTable* vtbl, const QTreeView* self);
	void (*changeEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QEvent* event);
	void (*timerEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QTimerEvent* event);
	void (*paintEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QPaintEvent* event);
	void (*drawRow)(struct QTreeView_VTable* vtbl, const QTreeView* self, QPainter* painter, QStyleOptionViewItem* options, QModelIndex* index);
	void (*drawBranches)(struct QTreeView_VTable* vtbl, const QTreeView* self, QPainter* painter, QRect* rect, QModelIndex* index);
	void (*mousePressEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QMouseEvent* event);
	void (*mouseDoubleClickEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QMouseEvent* event);
	void (*mouseMoveEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QMouseEvent* event);
	void (*keyPressEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QKeyEvent* event);
	void (*dragMoveEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QDragMoveEvent* event);
	bool (*viewportEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QEvent* event);
	void (*updateGeometries)(struct QTreeView_VTable* vtbl, QTreeView* self);
	QSize* (*viewportSizeHint)(struct QTreeView_VTable* vtbl, const QTreeView* self);
	int (*sizeHintForColumn)(struct QTreeView_VTable* vtbl, const QTreeView* self, int column);
	void (*horizontalScrollbarAction)(struct QTreeView_VTable* vtbl, QTreeView* self, int action);
	bool (*isIndexHidden)(struct QTreeView_VTable* vtbl, const QTreeView* self, QModelIndex* index);
	void (*selectionChanged)(struct QTreeView_VTable* vtbl, QTreeView* self, QItemSelection* selected, QItemSelection* deselected);
	void (*currentChanged)(struct QTreeView_VTable* vtbl, QTreeView* self, QModelIndex* current, QModelIndex* previous);
	int (*sizeHintForRow)(struct QTreeView_VTable* vtbl, const QTreeView* self, int row);
	QAbstractItemDelegate* (*itemDelegateForIndex)(struct QTreeView_VTable* vtbl, const QTreeView* self, QModelIndex* index);
	QVariant* (*inputMethodQuery)(struct QTreeView_VTable* vtbl, const QTreeView* self, int query);
	void (*updateEditorData)(struct QTreeView_VTable* vtbl, QTreeView* self);
	void (*updateEditorGeometries)(struct QTreeView_VTable* vtbl, QTreeView* self);
	void (*verticalScrollbarAction)(struct QTreeView_VTable* vtbl, QTreeView* self, int action);
	void (*horizontalScrollbarValueChanged)(struct QTreeView_VTable* vtbl, QTreeView* self, int value);
	void (*closeEditor)(struct QTreeView_VTable* vtbl, QTreeView* self, QWidget* editor, int hint);
	void (*commitData)(struct QTreeView_VTable* vtbl, QTreeView* self, QWidget* editor);
	void (*editorDestroyed)(struct QTreeView_VTable* vtbl, QTreeView* self, QObject* editor);
	bool (*edit2)(struct QTreeView_VTable* vtbl, QTreeView* self, QModelIndex* index, int trigger, QEvent* event);
	int (*selectionCommand)(struct QTreeView_VTable* vtbl, const QTreeView* self, QModelIndex* index, QEvent* event);
	void (*startDrag)(struct QTreeView_VTable* vtbl, QTreeView* self, int supportedActions);
	void (*initViewItemOption)(struct QTreeView_VTable* vtbl, const QTreeView* self, QStyleOptionViewItem* option);
	bool (*focusNextPrevChild)(struct QTreeView_VTable* vtbl, QTreeView* self, bool next);
	bool (*event)(struct QTreeView_VTable* vtbl, QTreeView* self, QEvent* event);
	void (*dragEnterEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QDragEnterEvent* event);
	void (*dragLeaveEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QDragLeaveEvent* event);
	void (*dropEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QDropEvent* event);
	void (*focusInEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QFocusEvent* event);
	void (*focusOutEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QFocusEvent* event);
	void (*resizeEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QResizeEvent* event);
	void (*inputMethodEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QInputMethodEvent* event);
	bool (*eventFilter)(struct QTreeView_VTable* vtbl, QTreeView* self, QObject* object, QEvent* event);
	QSize* (*minimumSizeHint)(struct QTreeView_VTable* vtbl, const QTreeView* self);
	QSize* (*sizeHint)(struct QTreeView_VTable* vtbl, const QTreeView* self);
	void (*setupViewport)(struct QTreeView_VTable* vtbl, QTreeView* self, QWidget* viewport);
	void (*wheelEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QWheelEvent* param1);
	void (*contextMenuEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QContextMenuEvent* param1);
	void (*initStyleOption)(struct QTreeView_VTable* vtbl, const QTreeView* self, QStyleOptionFrame* option);
	int (*devType)(struct QTreeView_VTable* vtbl, const QTreeView* self);
	void (*setVisible)(struct QTreeView_VTable* vtbl, QTreeView* self, bool visible);
	int (*heightForWidth)(struct QTreeView_VTable* vtbl, const QTreeView* self, int param1);
	bool (*hasHeightForWidth)(struct QTreeView_VTable* vtbl, const QTreeView* self);
	QPaintEngine* (*paintEngine)(struct QTreeView_VTable* vtbl, const QTreeView* self);
	void (*keyReleaseEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QKeyEvent* event);
	void (*enterEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QEnterEvent* event);
	void (*leaveEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QEvent* event);
	void (*moveEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QMoveEvent* event);
	void (*closeEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QCloseEvent* event);
	void (*tabletEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QTabletEvent* event);
	void (*actionEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QActionEvent* event);
	void (*showEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QShowEvent* event);
	void (*hideEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QHideEvent* event);
	bool (*nativeEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, struct miqt_string eventType, void* message, intptr_t* result);
	int (*metric)(struct QTreeView_VTable* vtbl, const QTreeView* self, int param1);
	void (*initPainter)(struct QTreeView_VTable* vtbl, const QTreeView* self, QPainter* painter);
	QPaintDevice* (*redirected)(struct QTreeView_VTable* vtbl, const QTreeView* self, QPoint* offset);
	QPainter* (*sharedPainter)(struct QTreeView_VTable* vtbl, const QTreeView* self);
	void (*childEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QChildEvent* event);
	void (*customEvent)(struct QTreeView_VTable* vtbl, QTreeView* self, QEvent* event);
	void (*connectNotify)(struct QTreeView_VTable* vtbl, QTreeView* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QTreeView_VTable* vtbl, QTreeView* self, QMetaMethod* signal);
};
QTreeView* QTreeView_new(struct QTreeView_VTable* vtbl, QWidget* parent);
QTreeView* QTreeView_new2(struct QTreeView_VTable* vtbl);
void QTreeView_virtbase(QTreeView* src, QAbstractItemView** outptr_QAbstractItemView);
QMetaObject* QTreeView_metaObject(const QTreeView* self);
void* QTreeView_metacast(QTreeView* self, const char* param1);
int QTreeView_metacall(QTreeView* self, int param1, int param2, void** param3);
struct miqt_string QTreeView_tr(const char* s);
void QTreeView_setModel(QTreeView* self, QAbstractItemModel* model);
void QTreeView_setRootIndex(QTreeView* self, QModelIndex* index);
void QTreeView_setSelectionModel(QTreeView* self, QItemSelectionModel* selectionModel);
QHeaderView* QTreeView_header(const QTreeView* self);
void QTreeView_setHeader(QTreeView* self, QHeaderView* header);
int QTreeView_autoExpandDelay(const QTreeView* self);
void QTreeView_setAutoExpandDelay(QTreeView* self, int delay);
int QTreeView_indentation(const QTreeView* self);
void QTreeView_setIndentation(QTreeView* self, int i);
void QTreeView_resetIndentation(QTreeView* self);
bool QTreeView_rootIsDecorated(const QTreeView* self);
void QTreeView_setRootIsDecorated(QTreeView* self, bool show);
bool QTreeView_uniformRowHeights(const QTreeView* self);
void QTreeView_setUniformRowHeights(QTreeView* self, bool uniform);
bool QTreeView_itemsExpandable(const QTreeView* self);
void QTreeView_setItemsExpandable(QTreeView* self, bool enable);
bool QTreeView_expandsOnDoubleClick(const QTreeView* self);
void QTreeView_setExpandsOnDoubleClick(QTreeView* self, bool enable);
int QTreeView_columnViewportPosition(const QTreeView* self, int column);
int QTreeView_columnWidth(const QTreeView* self, int column);
void QTreeView_setColumnWidth(QTreeView* self, int column, int width);
int QTreeView_columnAt(const QTreeView* self, int x);
bool QTreeView_isColumnHidden(const QTreeView* self, int column);
void QTreeView_setColumnHidden(QTreeView* self, int column, bool hide);
bool QTreeView_isHeaderHidden(const QTreeView* self);
void QTreeView_setHeaderHidden(QTreeView* self, bool hide);
bool QTreeView_isRowHidden(const QTreeView* self, int row, QModelIndex* parent);
void QTreeView_setRowHidden(QTreeView* self, int row, QModelIndex* parent, bool hide);
bool QTreeView_isFirstColumnSpanned(const QTreeView* self, int row, QModelIndex* parent);
void QTreeView_setFirstColumnSpanned(QTreeView* self, int row, QModelIndex* parent, bool span);
bool QTreeView_isExpanded(const QTreeView* self, QModelIndex* index);
void QTreeView_setExpanded(QTreeView* self, QModelIndex* index, bool expand);
void QTreeView_setSortingEnabled(QTreeView* self, bool enable);
bool QTreeView_isSortingEnabled(const QTreeView* self);
void QTreeView_setAnimated(QTreeView* self, bool enable);
bool QTreeView_isAnimated(const QTreeView* self);
void QTreeView_setAllColumnsShowFocus(QTreeView* self, bool enable);
bool QTreeView_allColumnsShowFocus(const QTreeView* self);
void QTreeView_setWordWrap(QTreeView* self, bool on);
bool QTreeView_wordWrap(const QTreeView* self);
void QTreeView_setTreePosition(QTreeView* self, int logicalIndex);
int QTreeView_treePosition(const QTreeView* self);
void QTreeView_keyboardSearch(QTreeView* self, struct miqt_string search);
QRect* QTreeView_visualRect(const QTreeView* self, QModelIndex* index);
void QTreeView_scrollTo(QTreeView* self, QModelIndex* index, int hint);
QModelIndex* QTreeView_indexAt(const QTreeView* self, QPoint* p);
QModelIndex* QTreeView_indexAbove(const QTreeView* self, QModelIndex* index);
QModelIndex* QTreeView_indexBelow(const QTreeView* self, QModelIndex* index);
void QTreeView_doItemsLayout(QTreeView* self);
void QTreeView_reset(QTreeView* self);
void QTreeView_dataChanged(QTreeView* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct miqt_array /* of int */  roles);
void QTreeView_selectAll(QTreeView* self);
void QTreeView_expanded(QTreeView* self, QModelIndex* index);
void QTreeView_connect_expanded(QTreeView* self, intptr_t slot, void (*callback)(intptr_t, QModelIndex*), void (*release)(intptr_t));
void QTreeView_collapsed(QTreeView* self, QModelIndex* index);
void QTreeView_connect_collapsed(QTreeView* self, intptr_t slot, void (*callback)(intptr_t, QModelIndex*), void (*release)(intptr_t));
void QTreeView_hideColumn(QTreeView* self, int column);
void QTreeView_showColumn(QTreeView* self, int column);
void QTreeView_expand(QTreeView* self, QModelIndex* index);
void QTreeView_collapse(QTreeView* self, QModelIndex* index);
void QTreeView_resizeColumnToContents(QTreeView* self, int column);
void QTreeView_sortByColumn(QTreeView* self, int column, int order);
void QTreeView_expandAll(QTreeView* self);
void QTreeView_expandRecursively(QTreeView* self, QModelIndex* index);
void QTreeView_collapseAll(QTreeView* self);
void QTreeView_expandToDepth(QTreeView* self, int depth);
void QTreeView_verticalScrollbarValueChanged(QTreeView* self, int value);
void QTreeView_scrollContentsBy(QTreeView* self, int dx, int dy);
void QTreeView_rowsInserted(QTreeView* self, QModelIndex* parent, int start, int end);
void QTreeView_rowsAboutToBeRemoved(QTreeView* self, QModelIndex* parent, int start, int end);
QModelIndex* QTreeView_moveCursor(QTreeView* self, int cursorAction, int modifiers);
int QTreeView_horizontalOffset(const QTreeView* self);
int QTreeView_verticalOffset(const QTreeView* self);
void QTreeView_setSelection(QTreeView* self, QRect* rect, int command);
QRegion* QTreeView_visualRegionForSelection(const QTreeView* self, QItemSelection* selection);
struct miqt_array /* of QModelIndex* */  QTreeView_selectedIndexes(const QTreeView* self);
void QTreeView_changeEvent(QTreeView* self, QEvent* event);
void QTreeView_timerEvent(QTreeView* self, QTimerEvent* event);
void QTreeView_paintEvent(QTreeView* self, QPaintEvent* event);
void QTreeView_drawRow(const QTreeView* self, QPainter* painter, QStyleOptionViewItem* options, QModelIndex* index);
void QTreeView_drawBranches(const QTreeView* self, QPainter* painter, QRect* rect, QModelIndex* index);
void QTreeView_mousePressEvent(QTreeView* self, QMouseEvent* event);
void QTreeView_mouseReleaseEvent(QTreeView* self, QMouseEvent* event);
void QTreeView_mouseDoubleClickEvent(QTreeView* self, QMouseEvent* event);
void QTreeView_mouseMoveEvent(QTreeView* self, QMouseEvent* event);
void QTreeView_keyPressEvent(QTreeView* self, QKeyEvent* event);
void QTreeView_dragMoveEvent(QTreeView* self, QDragMoveEvent* event);
bool QTreeView_viewportEvent(QTreeView* self, QEvent* event);
void QTreeView_updateGeometries(QTreeView* self);
QSize* QTreeView_viewportSizeHint(const QTreeView* self);
int QTreeView_sizeHintForColumn(const QTreeView* self, int column);
void QTreeView_horizontalScrollbarAction(QTreeView* self, int action);
bool QTreeView_isIndexHidden(const QTreeView* self, QModelIndex* index);
void QTreeView_selectionChanged(QTreeView* self, QItemSelection* selected, QItemSelection* deselected);
void QTreeView_currentChanged(QTreeView* self, QModelIndex* current, QModelIndex* previous);
struct miqt_string QTreeView_tr2(const char* s, const char* c);
struct miqt_string QTreeView_tr3(const char* s, const char* c, int n);
void QTreeView_expandRecursively2(QTreeView* self, QModelIndex* index, int depth);
QMetaObject* QTreeView_virtualbase_metaObject(const void* self);
void* QTreeView_virtualbase_metacast(void* self, const char* param1);
int QTreeView_virtualbase_metacall(void* self, int param1, int param2, void** param3);
void QTreeView_virtualbase_setModel(void* self, QAbstractItemModel* model);
void QTreeView_virtualbase_setRootIndex(void* self, QModelIndex* index);
void QTreeView_virtualbase_setSelectionModel(void* self, QItemSelectionModel* selectionModel);
void QTreeView_virtualbase_keyboardSearch(void* self, struct miqt_string search);
QRect* QTreeView_virtualbase_visualRect(const void* self, QModelIndex* index);
void QTreeView_virtualbase_scrollTo(void* self, QModelIndex* index, int hint);
QModelIndex* QTreeView_virtualbase_indexAt(const void* self, QPoint* p);
void QTreeView_virtualbase_doItemsLayout(void* self);
void QTreeView_virtualbase_reset(void* self);
void QTreeView_virtualbase_dataChanged(void* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct miqt_array /* of int */  roles);
void QTreeView_virtualbase_selectAll(void* self);
void QTreeView_virtualbase_verticalScrollbarValueChanged(void* self, int value);
void QTreeView_virtualbase_scrollContentsBy(void* self, int dx, int dy);
void QTreeView_virtualbase_rowsInserted(void* self, QModelIndex* parent, int start, int end);
void QTreeView_virtualbase_rowsAboutToBeRemoved(void* self, QModelIndex* parent, int start, int end);
QModelIndex* QTreeView_virtualbase_moveCursor(void* self, int cursorAction, int modifiers);
int QTreeView_virtualbase_horizontalOffset(const void* self);
int QTreeView_virtualbase_verticalOffset(const void* self);
void QTreeView_virtualbase_setSelection(void* self, QRect* rect, int command);
QRegion* QTreeView_virtualbase_visualRegionForSelection(const void* self, QItemSelection* selection);
struct miqt_array /* of QModelIndex* */  QTreeView_virtualbase_selectedIndexes(const void* self);
void QTreeView_virtualbase_changeEvent(void* self, QEvent* event);
void QTreeView_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QTreeView_virtualbase_paintEvent(void* self, QPaintEvent* event);
void QTreeView_virtualbase_drawRow(const void* self, QPainter* painter, QStyleOptionViewItem* options, QModelIndex* index);
void QTreeView_virtualbase_drawBranches(const void* self, QPainter* painter, QRect* rect, QModelIndex* index);
void QTreeView_virtualbase_mousePressEvent(void* self, QMouseEvent* event);
void QTreeView_virtualbase_mouseReleaseEvent(void* self, QMouseEvent* event);
void QTreeView_virtualbase_mouseDoubleClickEvent(void* self, QMouseEvent* event);
void QTreeView_virtualbase_mouseMoveEvent(void* self, QMouseEvent* event);
void QTreeView_virtualbase_keyPressEvent(void* self, QKeyEvent* event);
void QTreeView_virtualbase_dragMoveEvent(void* self, QDragMoveEvent* event);
bool QTreeView_virtualbase_viewportEvent(void* self, QEvent* event);
void QTreeView_virtualbase_updateGeometries(void* self);
QSize* QTreeView_virtualbase_viewportSizeHint(const void* self);
int QTreeView_virtualbase_sizeHintForColumn(const void* self, int column);
void QTreeView_virtualbase_horizontalScrollbarAction(void* self, int action);
bool QTreeView_virtualbase_isIndexHidden(const void* self, QModelIndex* index);
void QTreeView_virtualbase_selectionChanged(void* self, QItemSelection* selected, QItemSelection* deselected);
void QTreeView_virtualbase_currentChanged(void* self, QModelIndex* current, QModelIndex* previous);
int QTreeView_virtualbase_sizeHintForRow(const void* self, int row);
QAbstractItemDelegate* QTreeView_virtualbase_itemDelegateForIndex(const void* self, QModelIndex* index);
QVariant* QTreeView_virtualbase_inputMethodQuery(const void* self, int query);
void QTreeView_virtualbase_updateEditorData(void* self);
void QTreeView_virtualbase_updateEditorGeometries(void* self);
void QTreeView_virtualbase_verticalScrollbarAction(void* self, int action);
void QTreeView_virtualbase_horizontalScrollbarValueChanged(void* self, int value);
void QTreeView_virtualbase_closeEditor(void* self, QWidget* editor, int hint);
void QTreeView_virtualbase_commitData(void* self, QWidget* editor);
void QTreeView_virtualbase_editorDestroyed(void* self, QObject* editor);
bool QTreeView_virtualbase_edit2(void* self, QModelIndex* index, int trigger, QEvent* event);
int QTreeView_virtualbase_selectionCommand(const void* self, QModelIndex* index, QEvent* event);
void QTreeView_virtualbase_startDrag(void* self, int supportedActions);
void QTreeView_virtualbase_initViewItemOption(const void* self, QStyleOptionViewItem* option);
bool QTreeView_virtualbase_focusNextPrevChild(void* self, bool next);
bool QTreeView_virtualbase_event(void* self, QEvent* event);
void QTreeView_virtualbase_dragEnterEvent(void* self, QDragEnterEvent* event);
void QTreeView_virtualbase_dragLeaveEvent(void* self, QDragLeaveEvent* event);
void QTreeView_virtualbase_dropEvent(void* self, QDropEvent* event);
void QTreeView_virtualbase_focusInEvent(void* self, QFocusEvent* event);
void QTreeView_virtualbase_focusOutEvent(void* self, QFocusEvent* event);
void QTreeView_virtualbase_resizeEvent(void* self, QResizeEvent* event);
void QTreeView_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* event);
bool QTreeView_virtualbase_eventFilter(void* self, QObject* object, QEvent* event);
QSize* QTreeView_virtualbase_minimumSizeHint(const void* self);
QSize* QTreeView_virtualbase_sizeHint(const void* self);
void QTreeView_virtualbase_setupViewport(void* self, QWidget* viewport);
void QTreeView_virtualbase_wheelEvent(void* self, QWheelEvent* param1);
void QTreeView_virtualbase_contextMenuEvent(void* self, QContextMenuEvent* param1);
void QTreeView_virtualbase_initStyleOption(const void* self, QStyleOptionFrame* option);
int QTreeView_virtualbase_devType(const void* self);
void QTreeView_virtualbase_setVisible(void* self, bool visible);
int QTreeView_virtualbase_heightForWidth(const void* self, int param1);
bool QTreeView_virtualbase_hasHeightForWidth(const void* self);
QPaintEngine* QTreeView_virtualbase_paintEngine(const void* self);
void QTreeView_virtualbase_keyReleaseEvent(void* self, QKeyEvent* event);
void QTreeView_virtualbase_enterEvent(void* self, QEnterEvent* event);
void QTreeView_virtualbase_leaveEvent(void* self, QEvent* event);
void QTreeView_virtualbase_moveEvent(void* self, QMoveEvent* event);
void QTreeView_virtualbase_closeEvent(void* self, QCloseEvent* event);
void QTreeView_virtualbase_tabletEvent(void* self, QTabletEvent* event);
void QTreeView_virtualbase_actionEvent(void* self, QActionEvent* event);
void QTreeView_virtualbase_showEvent(void* self, QShowEvent* event);
void QTreeView_virtualbase_hideEvent(void* self, QHideEvent* event);
bool QTreeView_virtualbase_nativeEvent(void* self, struct miqt_string eventType, void* message, intptr_t* result);
int QTreeView_virtualbase_metric(const void* self, int param1);
void QTreeView_virtualbase_initPainter(const void* self, QPainter* painter);
QPaintDevice* QTreeView_virtualbase_redirected(const void* self, QPoint* offset);
QPainter* QTreeView_virtualbase_sharedPainter(const void* self);
void QTreeView_virtualbase_childEvent(void* self, QChildEvent* event);
void QTreeView_virtualbase_customEvent(void* self, QEvent* event);
void QTreeView_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QTreeView_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
void QTreeView_protectedbase_columnResized(bool* _dynamic_cast_ok, void* self, int column, int oldSize, int newSize);
void QTreeView_protectedbase_columnCountChanged(bool* _dynamic_cast_ok, void* self, int oldCount, int newCount);
void QTreeView_protectedbase_columnMoved(bool* _dynamic_cast_ok, void* self);
void QTreeView_protectedbase_reexpand(bool* _dynamic_cast_ok, void* self);
void QTreeView_protectedbase_rowsRemoved(bool* _dynamic_cast_ok, void* self, QModelIndex* parent, int first, int last);
void QTreeView_protectedbase_drawTree(bool* _dynamic_cast_ok, const void* self, QPainter* painter, QRegion* region);
int QTreeView_protectedbase_indexRowSizeHint(bool* _dynamic_cast_ok, const void* self, QModelIndex* index);
int QTreeView_protectedbase_rowHeight(bool* _dynamic_cast_ok, const void* self, QModelIndex* index);
int QTreeView_protectedbase_state(bool* _dynamic_cast_ok, const void* self);
void QTreeView_protectedbase_setState(bool* _dynamic_cast_ok, void* self, int state);
void QTreeView_protectedbase_scheduleDelayedItemsLayout(bool* _dynamic_cast_ok, void* self);
void QTreeView_protectedbase_executeDelayedItemsLayout(bool* _dynamic_cast_ok, void* self);
void QTreeView_protectedbase_setDirtyRegion(bool* _dynamic_cast_ok, void* self, QRegion* region);
void QTreeView_protectedbase_scrollDirtyRegion(bool* _dynamic_cast_ok, void* self, int dx, int dy);
QPoint* QTreeView_protectedbase_dirtyRegionOffset(bool* _dynamic_cast_ok, const void* self);
void QTreeView_protectedbase_startAutoScroll(bool* _dynamic_cast_ok, void* self);
void QTreeView_protectedbase_stopAutoScroll(bool* _dynamic_cast_ok, void* self);
void QTreeView_protectedbase_doAutoScroll(bool* _dynamic_cast_ok, void* self);
int QTreeView_protectedbase_dropIndicatorPosition(bool* _dynamic_cast_ok, const void* self);
void QTreeView_protectedbase_setViewportMargins(bool* _dynamic_cast_ok, void* self, int left, int top, int right, int bottom);
QMargins* QTreeView_protectedbase_viewportMargins(bool* _dynamic_cast_ok, const void* self);
void QTreeView_protectedbase_drawFrame(bool* _dynamic_cast_ok, void* self, QPainter* param1);
void QTreeView_protectedbase_updateMicroFocus(bool* _dynamic_cast_ok, void* self);
void QTreeView_protectedbase_create(bool* _dynamic_cast_ok, void* self);
void QTreeView_protectedbase_destroy(bool* _dynamic_cast_ok, void* self);
bool QTreeView_protectedbase_focusNextChild(bool* _dynamic_cast_ok, void* self);
bool QTreeView_protectedbase_focusPreviousChild(bool* _dynamic_cast_ok, void* self);
QObject* QTreeView_protectedbase_sender(bool* _dynamic_cast_ok, const void* self);
int QTreeView_protectedbase_senderSignalIndex(bool* _dynamic_cast_ok, const void* self);
int QTreeView_protectedbase_receivers(bool* _dynamic_cast_ok, const void* self, const char* signal);
bool QTreeView_protectedbase_isSignalConnected(bool* _dynamic_cast_ok, const void* self, QMetaMethod* signal);
const QMetaObject* QTreeView_staticMetaObject();
void QTreeView_delete(QTreeView* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
