#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QCOMBOBOX_H
#define SEAQT_QTWIDGETS_GEN_QCOMBOBOX_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt-runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemDelegate;
class QAbstractItemModel;
class QAbstractItemView;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QComboBox;
class QCompleter;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEnterEvent;
class QEvent;
class QFocusEvent;
class QHideEvent;
class QIcon;
class QInputMethodEvent;
class QKeyEvent;
class QLineEdit;
class QMetaMethod;
class QMetaObject;
class QModelIndex;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QResizeEvent;
class QShowEvent;
class QSize;
class QStyleOptionComboBox;
class QTabletEvent;
class QTimerEvent;
class QValidator;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QComboBox QComboBox;
typedef struct QCompleter QCompleter;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QLineEdit QLineEdit;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionComboBox QStyleOptionComboBox;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QValidator QValidator;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

typedef struct VirtualQComboBox VirtualQComboBox;
typedef struct QComboBox_VTable{
	void (*destructor)(VirtualQComboBox* self);
	QMetaObject* (*metaObject)(const VirtualQComboBox* self);
	void* (*metacast)(VirtualQComboBox* self, const char* param1);
	int (*metacall)(VirtualQComboBox* self, int param1, int param2, void** param3);
	void (*setModel)(VirtualQComboBox* self, QAbstractItemModel* model);
	QSize* (*sizeHint)(const VirtualQComboBox* self);
	QSize* (*minimumSizeHint)(const VirtualQComboBox* self);
	void (*showPopup)(VirtualQComboBox* self);
	void (*hidePopup)(VirtualQComboBox* self);
	bool (*event)(VirtualQComboBox* self, QEvent* event);
	QVariant* (*inputMethodQuery_Qt_InputMethodQuery)(const VirtualQComboBox* self, int param1);
	void (*focusInEvent)(VirtualQComboBox* self, QFocusEvent* e);
	void (*focusOutEvent)(VirtualQComboBox* self, QFocusEvent* e);
	void (*changeEvent)(VirtualQComboBox* self, QEvent* e);
	void (*resizeEvent)(VirtualQComboBox* self, QResizeEvent* e);
	void (*paintEvent)(VirtualQComboBox* self, QPaintEvent* e);
	void (*showEvent)(VirtualQComboBox* self, QShowEvent* e);
	void (*hideEvent)(VirtualQComboBox* self, QHideEvent* e);
	void (*mousePressEvent)(VirtualQComboBox* self, QMouseEvent* e);
	void (*mouseReleaseEvent)(VirtualQComboBox* self, QMouseEvent* e);
	void (*keyPressEvent)(VirtualQComboBox* self, QKeyEvent* e);
	void (*keyReleaseEvent)(VirtualQComboBox* self, QKeyEvent* e);
	void (*wheelEvent)(VirtualQComboBox* self, QWheelEvent* e);
	void (*contextMenuEvent)(VirtualQComboBox* self, QContextMenuEvent* e);
	void (*inputMethodEvent)(VirtualQComboBox* self, QInputMethodEvent* param1);
	void (*initStyleOption)(const VirtualQComboBox* self, QStyleOptionComboBox* option);
	int (*devType)(const VirtualQComboBox* self);
	void (*setVisible)(VirtualQComboBox* self, bool visible);
	int (*heightForWidth)(const VirtualQComboBox* self, int param1);
	bool (*hasHeightForWidth)(const VirtualQComboBox* self);
	QPaintEngine* (*paintEngine)(const VirtualQComboBox* self);
	void (*mouseDoubleClickEvent)(VirtualQComboBox* self, QMouseEvent* event);
	void (*mouseMoveEvent)(VirtualQComboBox* self, QMouseEvent* event);
	void (*enterEvent)(VirtualQComboBox* self, QEnterEvent* event);
	void (*leaveEvent)(VirtualQComboBox* self, QEvent* event);
	void (*moveEvent)(VirtualQComboBox* self, QMoveEvent* event);
	void (*closeEvent)(VirtualQComboBox* self, QCloseEvent* event);
	void (*tabletEvent)(VirtualQComboBox* self, QTabletEvent* event);
	void (*actionEvent)(VirtualQComboBox* self, QActionEvent* event);
	void (*dragEnterEvent)(VirtualQComboBox* self, QDragEnterEvent* event);
	void (*dragMoveEvent)(VirtualQComboBox* self, QDragMoveEvent* event);
	void (*dragLeaveEvent)(VirtualQComboBox* self, QDragLeaveEvent* event);
	void (*dropEvent)(VirtualQComboBox* self, QDropEvent* event);
	bool (*nativeEvent)(VirtualQComboBox* self, struct seaqt_string eventType, void* message, intptr_t* result);
	int (*metric)(const VirtualQComboBox* self, int param1);
	void (*initPainter)(const VirtualQComboBox* self, QPainter* painter);
	QPaintDevice* (*redirected)(const VirtualQComboBox* self, QPoint* offset);
	QPainter* (*sharedPainter)(const VirtualQComboBox* self);
	bool (*focusNextPrevChild)(VirtualQComboBox* self, bool next);
	bool (*eventFilter)(VirtualQComboBox* self, QObject* watched, QEvent* event);
	void (*timerEvent)(VirtualQComboBox* self, QTimerEvent* event);
	void (*childEvent)(VirtualQComboBox* self, QChildEvent* event);
	void (*customEvent)(VirtualQComboBox* self, QEvent* event);
	void (*connectNotify)(VirtualQComboBox* self, QMetaMethod* signal);
	void (*disconnectNotify)(VirtualQComboBox* self, QMetaMethod* signal);
}QComboBox_VTable;

void* QComboBox_vdata(VirtualQComboBox* self);
VirtualQComboBox* vdata_QComboBox(void* vdata);

VirtualQComboBox* QComboBox_new_parent(const QComboBox_VTable* vtbl, size_t vdata, QWidget* parent);
VirtualQComboBox* QComboBox_new(const QComboBox_VTable* vtbl, size_t vdata);

void QComboBox_virtbase(QComboBox* src, QWidget** outptr_QWidget);
QMetaObject* QComboBox_metaObject(const QComboBox* self);
void* QComboBox_metacast(QComboBox* self, const char* param1);
int QComboBox_metacall(QComboBox* self, int param1, int param2, void** param3);
struct seaqt_string QComboBox_tr_s(const char* s);
int QComboBox_maxVisibleItems(const QComboBox* self);
void QComboBox_setMaxVisibleItems(QComboBox* self, int maxItems);
int QComboBox_count(const QComboBox* self);
void QComboBox_setMaxCount(QComboBox* self, int max);
int QComboBox_maxCount(const QComboBox* self);
bool QComboBox_duplicatesEnabled(const QComboBox* self);
void QComboBox_setDuplicatesEnabled(QComboBox* self, bool enable);
void QComboBox_setFrame(QComboBox* self, bool frame);
bool QComboBox_hasFrame(const QComboBox* self);
int QComboBox_findText_text(const QComboBox* self, struct seaqt_string text);
int QComboBox_findData_data(const QComboBox* self, QVariant* data);
int QComboBox_insertPolicy(const QComboBox* self);
void QComboBox_setInsertPolicy(QComboBox* self, int policy);
int QComboBox_sizeAdjustPolicy(const QComboBox* self);
void QComboBox_setSizeAdjustPolicy(QComboBox* self, int policy);
int QComboBox_minimumContentsLength(const QComboBox* self);
void QComboBox_setMinimumContentsLength(QComboBox* self, int characters);
QSize* QComboBox_iconSize(const QComboBox* self);
void QComboBox_setIconSize(QComboBox* self, QSize* size);
void QComboBox_setPlaceholderText(QComboBox* self, struct seaqt_string placeholderText);
struct seaqt_string QComboBox_placeholderText(const QComboBox* self);
bool QComboBox_isEditable(const QComboBox* self);
void QComboBox_setEditable(QComboBox* self, bool editable);
void QComboBox_setLineEdit(QComboBox* self, QLineEdit* edit);
QLineEdit* QComboBox_lineEdit(const QComboBox* self);
void QComboBox_setValidator(QComboBox* self, QValidator* v);
QValidator* QComboBox_validator(const QComboBox* self);
void QComboBox_setCompleter(QComboBox* self, QCompleter* c);
QCompleter* QComboBox_completer(const QComboBox* self);
QAbstractItemDelegate* QComboBox_itemDelegate(const QComboBox* self);
void QComboBox_setItemDelegate(QComboBox* self, QAbstractItemDelegate* delegate);
QAbstractItemModel* QComboBox_model(const QComboBox* self);
void QComboBox_setModel(QComboBox* self, QAbstractItemModel* model);
QModelIndex* QComboBox_rootModelIndex(const QComboBox* self);
void QComboBox_setRootModelIndex(QComboBox* self, QModelIndex* index);
int QComboBox_modelColumn(const QComboBox* self);
void QComboBox_setModelColumn(QComboBox* self, int visibleColumn);
int QComboBox_currentIndex(const QComboBox* self);
struct seaqt_string QComboBox_currentText(const QComboBox* self);
QVariant* QComboBox_currentData(const QComboBox* self);
struct seaqt_string QComboBox_itemText(const QComboBox* self, int index);
QIcon* QComboBox_itemIcon(const QComboBox* self, int index);
QVariant* QComboBox_itemData_index(const QComboBox* self, int index);
void QComboBox_addItem_text(QComboBox* self, struct seaqt_string text);
void QComboBox_addItem_icon_text(QComboBox* self, QIcon* icon, struct seaqt_string text);
void QComboBox_addItems(QComboBox* self, struct seaqt_array /* of struct seaqt_string */  texts);
void QComboBox_insertItem_index_text(QComboBox* self, int index, struct seaqt_string text);
void QComboBox_insertItem_index_icon_text(QComboBox* self, int index, QIcon* icon, struct seaqt_string text);
void QComboBox_insertItems(QComboBox* self, int index, struct seaqt_array /* of struct seaqt_string */  texts);
void QComboBox_insertSeparator(QComboBox* self, int index);
void QComboBox_removeItem(QComboBox* self, int index);
void QComboBox_setItemText(QComboBox* self, int index, struct seaqt_string text);
void QComboBox_setItemIcon(QComboBox* self, int index, QIcon* icon);
void QComboBox_setItemData_index_value(QComboBox* self, int index, QVariant* value);
QAbstractItemView* QComboBox_view(const QComboBox* self);
void QComboBox_setView(QComboBox* self, QAbstractItemView* itemView);
QSize* QComboBox_sizeHint(const QComboBox* self);
QSize* QComboBox_minimumSizeHint(const QComboBox* self);
void QComboBox_showPopup(QComboBox* self);
void QComboBox_hidePopup(QComboBox* self);
bool QComboBox_event(QComboBox* self, QEvent* event);
QVariant* QComboBox_inputMethodQuery_Qt_InputMethodQuery(const QComboBox* self, int param1);
QVariant* QComboBox_inputMethodQuery_Qt_InputMethodQuery_QVariant(const QComboBox* self, int query, QVariant* argument);
void QComboBox_clear(QComboBox* self);
void QComboBox_clearEditText(QComboBox* self);
void QComboBox_setEditText(QComboBox* self, struct seaqt_string text);
void QComboBox_setCurrentIndex(QComboBox* self, int index);
void QComboBox_setCurrentText(QComboBox* self, struct seaqt_string text);
void QComboBox_editTextChanged(QComboBox* self, struct seaqt_string param1);
void QComboBox_connect_editTextChanged(QComboBox* self, intptr_t slot, void (*callback)(intptr_t, struct seaqt_string), void (*release)(intptr_t));
void QComboBox_activated(QComboBox* self, int index);
void QComboBox_connect_activated(QComboBox* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QComboBox_textActivated(QComboBox* self, struct seaqt_string param1);
void QComboBox_connect_textActivated(QComboBox* self, intptr_t slot, void (*callback)(intptr_t, struct seaqt_string), void (*release)(intptr_t));
void QComboBox_highlighted(QComboBox* self, int index);
void QComboBox_connect_highlighted(QComboBox* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QComboBox_textHighlighted(QComboBox* self, struct seaqt_string param1);
void QComboBox_connect_textHighlighted(QComboBox* self, intptr_t slot, void (*callback)(intptr_t, struct seaqt_string), void (*release)(intptr_t));
void QComboBox_currentIndexChanged(QComboBox* self, int index);
void QComboBox_connect_currentIndexChanged(QComboBox* self, intptr_t slot, void (*callback)(intptr_t, int), void (*release)(intptr_t));
void QComboBox_currentTextChanged(QComboBox* self, struct seaqt_string param1);
void QComboBox_connect_currentTextChanged(QComboBox* self, intptr_t slot, void (*callback)(intptr_t, struct seaqt_string), void (*release)(intptr_t));
void QComboBox_focusInEvent(QComboBox* self, QFocusEvent* e);
void QComboBox_focusOutEvent(QComboBox* self, QFocusEvent* e);
void QComboBox_changeEvent(QComboBox* self, QEvent* e);
void QComboBox_resizeEvent(QComboBox* self, QResizeEvent* e);
void QComboBox_paintEvent(QComboBox* self, QPaintEvent* e);
void QComboBox_showEvent(QComboBox* self, QShowEvent* e);
void QComboBox_hideEvent(QComboBox* self, QHideEvent* e);
void QComboBox_mousePressEvent(QComboBox* self, QMouseEvent* e);
void QComboBox_mouseReleaseEvent(QComboBox* self, QMouseEvent* e);
void QComboBox_keyPressEvent(QComboBox* self, QKeyEvent* e);
void QComboBox_keyReleaseEvent(QComboBox* self, QKeyEvent* e);
void QComboBox_wheelEvent(QComboBox* self, QWheelEvent* e);
void QComboBox_contextMenuEvent(QComboBox* self, QContextMenuEvent* e);
void QComboBox_inputMethodEvent(QComboBox* self, QInputMethodEvent* param1);
void QComboBox_initStyleOption(const QComboBox* self, QStyleOptionComboBox* option);
struct seaqt_string QComboBox_tr_s_c(const char* s, const char* c);
struct seaqt_string QComboBox_tr_s_c_n(const char* s, const char* c, int n);
int QComboBox_findText_text_flags(const QComboBox* self, struct seaqt_string text, int flags);
int QComboBox_findData_data_role(const QComboBox* self, QVariant* data, int role);
int QComboBox_findData_data_role_flags(const QComboBox* self, QVariant* data, int role, int flags);
QVariant* QComboBox_currentData_role(const QComboBox* self, int role);
QVariant* QComboBox_itemData_index_role(const QComboBox* self, int index, int role);
void QComboBox_addItem_text_userData(QComboBox* self, struct seaqt_string text, QVariant* userData);
void QComboBox_addItem_icon_text_userData(QComboBox* self, QIcon* icon, struct seaqt_string text, QVariant* userData);
void QComboBox_insertItem_index_text_userData(QComboBox* self, int index, struct seaqt_string text, QVariant* userData);
void QComboBox_insertItem_index_icon_text_userData(QComboBox* self, int index, QIcon* icon, struct seaqt_string text, QVariant* userData);
void QComboBox_setItemData_index_value_role(QComboBox* self, int index, QVariant* value, int role);

QMetaObject* QComboBox_virtualbase_metaObject(const VirtualQComboBox* self);
void* QComboBox_virtualbase_metacast(VirtualQComboBox* self, const char* param1);
int QComboBox_virtualbase_metacall(VirtualQComboBox* self, int param1, int param2, void** param3);
void QComboBox_virtualbase_setModel(VirtualQComboBox* self, QAbstractItemModel* model);
QSize* QComboBox_virtualbase_sizeHint(const VirtualQComboBox* self);
QSize* QComboBox_virtualbase_minimumSizeHint(const VirtualQComboBox* self);
void QComboBox_virtualbase_showPopup(VirtualQComboBox* self);
void QComboBox_virtualbase_hidePopup(VirtualQComboBox* self);
bool QComboBox_virtualbase_event(VirtualQComboBox* self, QEvent* event);
QVariant* QComboBox_virtualbase_inputMethodQuery_Qt_InputMethodQuery(const VirtualQComboBox* self, int param1);
void QComboBox_virtualbase_focusInEvent(VirtualQComboBox* self, QFocusEvent* e);
void QComboBox_virtualbase_focusOutEvent(VirtualQComboBox* self, QFocusEvent* e);
void QComboBox_virtualbase_changeEvent(VirtualQComboBox* self, QEvent* e);
void QComboBox_virtualbase_resizeEvent(VirtualQComboBox* self, QResizeEvent* e);
void QComboBox_virtualbase_paintEvent(VirtualQComboBox* self, QPaintEvent* e);
void QComboBox_virtualbase_showEvent(VirtualQComboBox* self, QShowEvent* e);
void QComboBox_virtualbase_hideEvent(VirtualQComboBox* self, QHideEvent* e);
void QComboBox_virtualbase_mousePressEvent(VirtualQComboBox* self, QMouseEvent* e);
void QComboBox_virtualbase_mouseReleaseEvent(VirtualQComboBox* self, QMouseEvent* e);
void QComboBox_virtualbase_keyPressEvent(VirtualQComboBox* self, QKeyEvent* e);
void QComboBox_virtualbase_keyReleaseEvent(VirtualQComboBox* self, QKeyEvent* e);
void QComboBox_virtualbase_wheelEvent(VirtualQComboBox* self, QWheelEvent* e);
void QComboBox_virtualbase_contextMenuEvent(VirtualQComboBox* self, QContextMenuEvent* e);
void QComboBox_virtualbase_inputMethodEvent(VirtualQComboBox* self, QInputMethodEvent* param1);
void QComboBox_virtualbase_initStyleOption(const VirtualQComboBox* self, QStyleOptionComboBox* option);
int QComboBox_virtualbase_devType(const VirtualQComboBox* self);
void QComboBox_virtualbase_setVisible(VirtualQComboBox* self, bool visible);
int QComboBox_virtualbase_heightForWidth(const VirtualQComboBox* self, int param1);
bool QComboBox_virtualbase_hasHeightForWidth(const VirtualQComboBox* self);
QPaintEngine* QComboBox_virtualbase_paintEngine(const VirtualQComboBox* self);
void QComboBox_virtualbase_mouseDoubleClickEvent(VirtualQComboBox* self, QMouseEvent* event);
void QComboBox_virtualbase_mouseMoveEvent(VirtualQComboBox* self, QMouseEvent* event);
void QComboBox_virtualbase_enterEvent(VirtualQComboBox* self, QEnterEvent* event);
void QComboBox_virtualbase_leaveEvent(VirtualQComboBox* self, QEvent* event);
void QComboBox_virtualbase_moveEvent(VirtualQComboBox* self, QMoveEvent* event);
void QComboBox_virtualbase_closeEvent(VirtualQComboBox* self, QCloseEvent* event);
void QComboBox_virtualbase_tabletEvent(VirtualQComboBox* self, QTabletEvent* event);
void QComboBox_virtualbase_actionEvent(VirtualQComboBox* self, QActionEvent* event);
void QComboBox_virtualbase_dragEnterEvent(VirtualQComboBox* self, QDragEnterEvent* event);
void QComboBox_virtualbase_dragMoveEvent(VirtualQComboBox* self, QDragMoveEvent* event);
void QComboBox_virtualbase_dragLeaveEvent(VirtualQComboBox* self, QDragLeaveEvent* event);
void QComboBox_virtualbase_dropEvent(VirtualQComboBox* self, QDropEvent* event);
bool QComboBox_virtualbase_nativeEvent(VirtualQComboBox* self, struct seaqt_string eventType, void* message, intptr_t* result);
int QComboBox_virtualbase_metric(const VirtualQComboBox* self, int param1);
void QComboBox_virtualbase_initPainter(const VirtualQComboBox* self, QPainter* painter);
QPaintDevice* QComboBox_virtualbase_redirected(const VirtualQComboBox* self, QPoint* offset);
QPainter* QComboBox_virtualbase_sharedPainter(const VirtualQComboBox* self);
bool QComboBox_virtualbase_focusNextPrevChild(VirtualQComboBox* self, bool next);
bool QComboBox_virtualbase_eventFilter(VirtualQComboBox* self, QObject* watched, QEvent* event);
void QComboBox_virtualbase_timerEvent(VirtualQComboBox* self, QTimerEvent* event);
void QComboBox_virtualbase_childEvent(VirtualQComboBox* self, QChildEvent* event);
void QComboBox_virtualbase_customEvent(VirtualQComboBox* self, QEvent* event);
void QComboBox_virtualbase_connectNotify(VirtualQComboBox* self, QMetaMethod* signal);
void QComboBox_virtualbase_disconnectNotify(VirtualQComboBox* self, QMetaMethod* signal);

void QComboBox_protectedbase_updateMicroFocus(VirtualQComboBox* self);
void QComboBox_protectedbase_create(VirtualQComboBox* self);
void QComboBox_protectedbase_destroy(VirtualQComboBox* self);
bool QComboBox_protectedbase_focusNextChild(VirtualQComboBox* self);
bool QComboBox_protectedbase_focusPreviousChild(VirtualQComboBox* self);
QObject* QComboBox_protectedbase_sender(const VirtualQComboBox* self);
int QComboBox_protectedbase_senderSignalIndex(const VirtualQComboBox* self);
int QComboBox_protectedbase_receivers(const VirtualQComboBox* self, const char* signal);
bool QComboBox_protectedbase_isSignalConnected(const VirtualQComboBox* self, QMetaMethod* signal);

void QComboBox_delete(QComboBox* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
