#pragma once
#ifndef SEAQT_QTWIDGETS_GEN_QTREEWIDGET_H
#define SEAQT_QTWIDGETS_GEN_QTREEWIDGET_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt-runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractItemDelegate;
class QAbstractItemView;
class QAbstractScrollArea;
class QActionEvent;
class QBrush;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QDataStream;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEnterEvent;
class QEvent;
class QFocusEvent;
class QFont;
class QFrame;
class QHideEvent;
class QIcon;
class QInputMethodEvent;
class QItemSelection;
class QItemSelectionModel;
class QKeyEvent;
class QMargins;
class QMetaMethod;
class QMetaObject;
class QMimeData;
class QModelIndex;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPoint;
class QRect;
class QRegion;
class QResizeEvent;
class QShowEvent;
class QSize;
class QStyleOptionFrame;
class QStyleOptionViewItem;
class QTabletEvent;
class QTimerEvent;
class QTreeView;
class QTreeWidget;
class QTreeWidgetItem;
class QVariant;
class QWheelEvent;
class QWidget;
#else
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QBrush QBrush;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDataStream QDataStream;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QTreeView QTreeView;
typedef struct QTreeWidget QTreeWidget;
typedef struct QTreeWidgetItem QTreeWidgetItem;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

typedef struct VirtualQTreeWidgetItem VirtualQTreeWidgetItem;
typedef struct QTreeWidgetItem_VTable{
	void (*destructor)(VirtualQTreeWidgetItem* self);
	QTreeWidgetItem* (*clone)(const VirtualQTreeWidgetItem* self);
	QVariant* (*data)(const VirtualQTreeWidgetItem* self, int column, int role);
	void (*setData)(VirtualQTreeWidgetItem* self, int column, int role, QVariant* value);
	bool (*operatorLesser)(const VirtualQTreeWidgetItem* self, QTreeWidgetItem* other);
	void (*read)(VirtualQTreeWidgetItem* self, QDataStream* in);
	void (*write)(const VirtualQTreeWidgetItem* self, QDataStream* out);
}QTreeWidgetItem_VTable;

void* QTreeWidgetItem_vdata(VirtualQTreeWidgetItem* self);
VirtualQTreeWidgetItem* vdata_QTreeWidgetItem(void* vdata);

VirtualQTreeWidgetItem* QTreeWidgetItem_new(const QTreeWidgetItem_VTable* vtbl, size_t vdata);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_strings(const QTreeWidgetItem_VTable* vtbl, size_t vdata, struct seaqt_array /* of struct seaqt_string */  strings);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_treeview(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidget* treeview);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_treeview_strings(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidget* treeview, struct seaqt_array /* of struct seaqt_string */  strings);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_treeview_after(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidget* treeview, QTreeWidgetItem* after);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_parent(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidgetItem* parent);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_parent_strings(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidgetItem* parent, struct seaqt_array /* of struct seaqt_string */  strings);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_parent_after(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidgetItem* parent, QTreeWidgetItem* after);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_from(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidgetItem* from);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_type(const QTreeWidgetItem_VTable* vtbl, size_t vdata, int type);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_strings_type(const QTreeWidgetItem_VTable* vtbl, size_t vdata, struct seaqt_array /* of struct seaqt_string */  strings, int type);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_treeview_type(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidget* treeview, int type);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_treeview_strings_type(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidget* treeview, struct seaqt_array /* of struct seaqt_string */  strings, int type);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_treeview_after_type(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidget* treeview, QTreeWidgetItem* after, int type);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_parent_type(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidgetItem* parent, int type);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_parent_strings_type(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidgetItem* parent, struct seaqt_array /* of struct seaqt_string */  strings, int type);
VirtualQTreeWidgetItem* QTreeWidgetItem_new_parent_after_type(const QTreeWidgetItem_VTable* vtbl, size_t vdata, QTreeWidgetItem* parent, QTreeWidgetItem* after, int type);

QTreeWidgetItem* QTreeWidgetItem_clone(const QTreeWidgetItem* self);
QTreeWidget* QTreeWidgetItem_treeWidget(const QTreeWidgetItem* self);
void QTreeWidgetItem_setSelected(QTreeWidgetItem* self, bool select);
bool QTreeWidgetItem_isSelected(const QTreeWidgetItem* self);
void QTreeWidgetItem_setHidden(QTreeWidgetItem* self, bool hide);
bool QTreeWidgetItem_isHidden(const QTreeWidgetItem* self);
void QTreeWidgetItem_setExpanded(QTreeWidgetItem* self, bool expand);
bool QTreeWidgetItem_isExpanded(const QTreeWidgetItem* self);
void QTreeWidgetItem_setFirstColumnSpanned(QTreeWidgetItem* self, bool span);
bool QTreeWidgetItem_isFirstColumnSpanned(const QTreeWidgetItem* self);
void QTreeWidgetItem_setDisabled(QTreeWidgetItem* self, bool disabled);
bool QTreeWidgetItem_isDisabled(const QTreeWidgetItem* self);
void QTreeWidgetItem_setChildIndicatorPolicy(QTreeWidgetItem* self, int policy);
int QTreeWidgetItem_childIndicatorPolicy(const QTreeWidgetItem* self);
int QTreeWidgetItem_flags(const QTreeWidgetItem* self);
void QTreeWidgetItem_setFlags(QTreeWidgetItem* self, int flags);
struct seaqt_string QTreeWidgetItem_text(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_setText(QTreeWidgetItem* self, int column, struct seaqt_string text);
QIcon* QTreeWidgetItem_icon(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_setIcon(QTreeWidgetItem* self, int column, QIcon* icon);
struct seaqt_string QTreeWidgetItem_statusTip(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_setStatusTip(QTreeWidgetItem* self, int column, struct seaqt_string statusTip);
struct seaqt_string QTreeWidgetItem_toolTip(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_setToolTip(QTreeWidgetItem* self, int column, struct seaqt_string toolTip);
struct seaqt_string QTreeWidgetItem_whatsThis(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_setWhatsThis(QTreeWidgetItem* self, int column, struct seaqt_string whatsThis);
QFont* QTreeWidgetItem_font(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_setFont(QTreeWidgetItem* self, int column, QFont* font);
int QTreeWidgetItem_textAlignment(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_setTextAlignment_int_int(QTreeWidgetItem* self, int column, int alignment);
void QTreeWidgetItem_setTextAlignment_int_Qt_AlignmentFlag(QTreeWidgetItem* self, int column, int alignment);
void QTreeWidgetItem_setTextAlignment_int_Qt_Alignment(QTreeWidgetItem* self, int column, int alignment);
QBrush* QTreeWidgetItem_background(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_setBackground(QTreeWidgetItem* self, int column, QBrush* brush);
QBrush* QTreeWidgetItem_foreground(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_setForeground(QTreeWidgetItem* self, int column, QBrush* brush);
int QTreeWidgetItem_checkState(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_setCheckState(QTreeWidgetItem* self, int column, int state);
QSize* QTreeWidgetItem_sizeHint(const QTreeWidgetItem* self, int column);
void QTreeWidgetItem_setSizeHint(QTreeWidgetItem* self, int column, QSize* size);
QVariant* QTreeWidgetItem_data(const QTreeWidgetItem* self, int column, int role);
void QTreeWidgetItem_setData(QTreeWidgetItem* self, int column, int role, QVariant* value);
bool QTreeWidgetItem_operatorLesser(const QTreeWidgetItem* self, QTreeWidgetItem* other);
void QTreeWidgetItem_read(QTreeWidgetItem* self, QDataStream* in);
void QTreeWidgetItem_write(const QTreeWidgetItem* self, QDataStream* out);
void QTreeWidgetItem_operatorAssign(QTreeWidgetItem* self, QTreeWidgetItem* from);
QTreeWidgetItem* QTreeWidgetItem_parent(const QTreeWidgetItem* self);
QTreeWidgetItem* QTreeWidgetItem_child(const QTreeWidgetItem* self, int index);
int QTreeWidgetItem_childCount(const QTreeWidgetItem* self);
int QTreeWidgetItem_columnCount(const QTreeWidgetItem* self);
int QTreeWidgetItem_indexOfChild(const QTreeWidgetItem* self, QTreeWidgetItem* child);
void QTreeWidgetItem_addChild(QTreeWidgetItem* self, QTreeWidgetItem* child);
void QTreeWidgetItem_insertChild(QTreeWidgetItem* self, int index, QTreeWidgetItem* child);
void QTreeWidgetItem_removeChild(QTreeWidgetItem* self, QTreeWidgetItem* child);
QTreeWidgetItem* QTreeWidgetItem_takeChild(QTreeWidgetItem* self, int index);
void QTreeWidgetItem_addChildren(QTreeWidgetItem* self, struct seaqt_array /* of QTreeWidgetItem* */  children);
void QTreeWidgetItem_insertChildren(QTreeWidgetItem* self, int index, struct seaqt_array /* of QTreeWidgetItem* */  children);
struct seaqt_array /* of QTreeWidgetItem* */  QTreeWidgetItem_takeChildren(QTreeWidgetItem* self);
int QTreeWidgetItem_type(const QTreeWidgetItem* self);
void QTreeWidgetItem_sortChildren(QTreeWidgetItem* self, int column, int order);

QTreeWidgetItem* QTreeWidgetItem_virtualbase_clone(const VirtualQTreeWidgetItem* self);
QVariant* QTreeWidgetItem_virtualbase_data(const VirtualQTreeWidgetItem* self, int column, int role);
void QTreeWidgetItem_virtualbase_setData(VirtualQTreeWidgetItem* self, int column, int role, QVariant* value);
bool QTreeWidgetItem_virtualbase_operatorLesser(const VirtualQTreeWidgetItem* self, QTreeWidgetItem* other);
void QTreeWidgetItem_virtualbase_read(VirtualQTreeWidgetItem* self, QDataStream* in);
void QTreeWidgetItem_virtualbase_write(const VirtualQTreeWidgetItem* self, QDataStream* out);

void QTreeWidgetItem_protectedbase_emitDataChanged(VirtualQTreeWidgetItem* self);

void QTreeWidgetItem_delete(QTreeWidgetItem* self);

typedef struct VirtualQTreeWidget VirtualQTreeWidget;
typedef struct QTreeWidget_VTable{
	void (*destructor)(VirtualQTreeWidget* self);
	QMetaObject* (*metaObject)(const VirtualQTreeWidget* self);
	void* (*metacast)(VirtualQTreeWidget* self, const char* param1);
	int (*metacall)(VirtualQTreeWidget* self, int param1, int param2, void** param3);
	void (*setSelectionModel)(VirtualQTreeWidget* self, QItemSelectionModel* selectionModel);
	bool (*event)(VirtualQTreeWidget* self, QEvent* e);
	struct seaqt_array /* of struct seaqt_string */  (*mimeTypes)(const VirtualQTreeWidget* self);
	QMimeData* (*mimeData)(const VirtualQTreeWidget* self, struct seaqt_array /* of QTreeWidgetItem* */  items);
	bool (*dropMimeData)(VirtualQTreeWidget* self, QTreeWidgetItem* parent, int index, QMimeData* data, int action);
	int (*supportedDropActions)(const VirtualQTreeWidget* self);
	void (*dropEvent)(VirtualQTreeWidget* self, QDropEvent* event);
	void (*setRootIndex)(VirtualQTreeWidget* self, QModelIndex* index);
	void (*keyboardSearch)(VirtualQTreeWidget* self, struct seaqt_string search);
	QRect* (*visualRect)(const VirtualQTreeWidget* self, QModelIndex* index);
	void (*scrollTo)(VirtualQTreeWidget* self, QModelIndex* index, int hint);
	QModelIndex* (*indexAt)(const VirtualQTreeWidget* self, QPoint* p);
	void (*doItemsLayout)(VirtualQTreeWidget* self);
	void (*reset)(VirtualQTreeWidget* self);
	void (*dataChanged)(VirtualQTreeWidget* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct seaqt_array /* of int */  roles);
	void (*selectAll)(VirtualQTreeWidget* self);
	void (*verticalScrollbarValueChanged)(VirtualQTreeWidget* self, int value);
	void (*scrollContentsBy)(VirtualQTreeWidget* self, int dx, int dy);
	void (*rowsInserted)(VirtualQTreeWidget* self, QModelIndex* parent, int start, int end);
	void (*rowsAboutToBeRemoved)(VirtualQTreeWidget* self, QModelIndex* parent, int start, int end);
	QModelIndex* (*moveCursor)(VirtualQTreeWidget* self, int cursorAction, int modifiers);
	int (*horizontalOffset)(const VirtualQTreeWidget* self);
	int (*verticalOffset)(const VirtualQTreeWidget* self);
	void (*setSelection)(VirtualQTreeWidget* self, QRect* rect, int command);
	QRegion* (*visualRegionForSelection)(const VirtualQTreeWidget* self, QItemSelection* selection);
	struct seaqt_array /* of QModelIndex* */  (*selectedIndexes)(const VirtualQTreeWidget* self);
	void (*changeEvent)(VirtualQTreeWidget* self, QEvent* event);
	void (*timerEvent)(VirtualQTreeWidget* self, QTimerEvent* event);
	void (*paintEvent)(VirtualQTreeWidget* self, QPaintEvent* event);
	void (*drawRow)(const VirtualQTreeWidget* self, QPainter* painter, QStyleOptionViewItem* options, QModelIndex* index);
	void (*drawBranches)(const VirtualQTreeWidget* self, QPainter* painter, QRect* rect, QModelIndex* index);
	void (*mousePressEvent)(VirtualQTreeWidget* self, QMouseEvent* event);
	void (*mouseReleaseEvent)(VirtualQTreeWidget* self, QMouseEvent* event);
	void (*mouseDoubleClickEvent)(VirtualQTreeWidget* self, QMouseEvent* event);
	void (*mouseMoveEvent)(VirtualQTreeWidget* self, QMouseEvent* event);
	void (*keyPressEvent)(VirtualQTreeWidget* self, QKeyEvent* event);
	void (*dragMoveEvent)(VirtualQTreeWidget* self, QDragMoveEvent* event);
	bool (*viewportEvent)(VirtualQTreeWidget* self, QEvent* event);
	void (*updateGeometries)(VirtualQTreeWidget* self);
	QSize* (*viewportSizeHint)(const VirtualQTreeWidget* self);
	int (*sizeHintForColumn)(const VirtualQTreeWidget* self, int column);
	void (*horizontalScrollbarAction)(VirtualQTreeWidget* self, int action);
	bool (*isIndexHidden)(const VirtualQTreeWidget* self, QModelIndex* index);
	void (*selectionChanged)(VirtualQTreeWidget* self, QItemSelection* selected, QItemSelection* deselected);
	void (*currentChanged)(VirtualQTreeWidget* self, QModelIndex* current, QModelIndex* previous);
	int (*sizeHintForRow)(const VirtualQTreeWidget* self, int row);
	QAbstractItemDelegate* (*itemDelegateForIndex)(const VirtualQTreeWidget* self, QModelIndex* index);
	QVariant* (*inputMethodQuery)(const VirtualQTreeWidget* self, int query);
	void (*updateEditorData)(VirtualQTreeWidget* self);
	void (*updateEditorGeometries)(VirtualQTreeWidget* self);
	void (*verticalScrollbarAction)(VirtualQTreeWidget* self, int action);
	void (*horizontalScrollbarValueChanged)(VirtualQTreeWidget* self, int value);
	void (*closeEditor)(VirtualQTreeWidget* self, QWidget* editor, int hint);
	void (*commitData)(VirtualQTreeWidget* self, QWidget* editor);
	void (*editorDestroyed)(VirtualQTreeWidget* self, QObject* editor);
	bool (*edit_index_trigger_event)(VirtualQTreeWidget* self, QModelIndex* index, int trigger, QEvent* event);
	int (*selectionCommand)(const VirtualQTreeWidget* self, QModelIndex* index, QEvent* event);
	void (*startDrag)(VirtualQTreeWidget* self, int supportedActions);
	void (*initViewItemOption)(const VirtualQTreeWidget* self, QStyleOptionViewItem* option);
	bool (*focusNextPrevChild)(VirtualQTreeWidget* self, bool next);
	void (*dragEnterEvent)(VirtualQTreeWidget* self, QDragEnterEvent* event);
	void (*dragLeaveEvent)(VirtualQTreeWidget* self, QDragLeaveEvent* event);
	void (*focusInEvent)(VirtualQTreeWidget* self, QFocusEvent* event);
	void (*focusOutEvent)(VirtualQTreeWidget* self, QFocusEvent* event);
	void (*resizeEvent)(VirtualQTreeWidget* self, QResizeEvent* event);
	void (*inputMethodEvent)(VirtualQTreeWidget* self, QInputMethodEvent* event);
	bool (*eventFilter)(VirtualQTreeWidget* self, QObject* object, QEvent* event);
	QSize* (*minimumSizeHint)(const VirtualQTreeWidget* self);
	QSize* (*sizeHint)(const VirtualQTreeWidget* self);
	void (*setupViewport)(VirtualQTreeWidget* self, QWidget* viewport);
	void (*wheelEvent)(VirtualQTreeWidget* self, QWheelEvent* param1);
	void (*contextMenuEvent)(VirtualQTreeWidget* self, QContextMenuEvent* param1);
	void (*initStyleOption)(const VirtualQTreeWidget* self, QStyleOptionFrame* option);
	int (*devType)(const VirtualQTreeWidget* self);
	void (*setVisible)(VirtualQTreeWidget* self, bool visible);
	int (*heightForWidth)(const VirtualQTreeWidget* self, int param1);
	bool (*hasHeightForWidth)(const VirtualQTreeWidget* self);
	QPaintEngine* (*paintEngine)(const VirtualQTreeWidget* self);
	void (*keyReleaseEvent)(VirtualQTreeWidget* self, QKeyEvent* event);
	void (*enterEvent)(VirtualQTreeWidget* self, QEnterEvent* event);
	void (*leaveEvent)(VirtualQTreeWidget* self, QEvent* event);
	void (*moveEvent)(VirtualQTreeWidget* self, QMoveEvent* event);
	void (*closeEvent)(VirtualQTreeWidget* self, QCloseEvent* event);
	void (*tabletEvent)(VirtualQTreeWidget* self, QTabletEvent* event);
	void (*actionEvent)(VirtualQTreeWidget* self, QActionEvent* event);
	void (*showEvent)(VirtualQTreeWidget* self, QShowEvent* event);
	void (*hideEvent)(VirtualQTreeWidget* self, QHideEvent* event);
	bool (*nativeEvent)(VirtualQTreeWidget* self, struct seaqt_string eventType, void* message, intptr_t* result);
	int (*metric)(const VirtualQTreeWidget* self, int param1);
	void (*initPainter)(const VirtualQTreeWidget* self, QPainter* painter);
	QPaintDevice* (*redirected)(const VirtualQTreeWidget* self, QPoint* offset);
	QPainter* (*sharedPainter)(const VirtualQTreeWidget* self);
	void (*childEvent)(VirtualQTreeWidget* self, QChildEvent* event);
	void (*customEvent)(VirtualQTreeWidget* self, QEvent* event);
	void (*connectNotify)(VirtualQTreeWidget* self, QMetaMethod* signal);
	void (*disconnectNotify)(VirtualQTreeWidget* self, QMetaMethod* signal);
}QTreeWidget_VTable;

void* QTreeWidget_vdata(VirtualQTreeWidget* self);
VirtualQTreeWidget* vdata_QTreeWidget(void* vdata);

VirtualQTreeWidget* QTreeWidget_new(const QTreeWidget_VTable* vtbl, size_t vdata);
VirtualQTreeWidget* QTreeWidget_new_parent(const QTreeWidget_VTable* vtbl, size_t vdata, QWidget* parent);

void QTreeWidget_virtbase(QTreeWidget* src, QTreeView** outptr_QTreeView);
QMetaObject* QTreeWidget_metaObject(const QTreeWidget* self);
void* QTreeWidget_metacast(QTreeWidget* self, const char* param1);
int QTreeWidget_metacall(QTreeWidget* self, int param1, int param2, void** param3);
struct seaqt_string QTreeWidget_tr_s(const char* s);
int QTreeWidget_columnCount(const QTreeWidget* self);
void QTreeWidget_setColumnCount(QTreeWidget* self, int columns);
QTreeWidgetItem* QTreeWidget_invisibleRootItem(const QTreeWidget* self);
QTreeWidgetItem* QTreeWidget_topLevelItem(const QTreeWidget* self, int index);
int QTreeWidget_topLevelItemCount(const QTreeWidget* self);
void QTreeWidget_insertTopLevelItem(QTreeWidget* self, int index, QTreeWidgetItem* item);
void QTreeWidget_addTopLevelItem(QTreeWidget* self, QTreeWidgetItem* item);
QTreeWidgetItem* QTreeWidget_takeTopLevelItem(QTreeWidget* self, int index);
int QTreeWidget_indexOfTopLevelItem(const QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_insertTopLevelItems(QTreeWidget* self, int index, struct seaqt_array /* of QTreeWidgetItem* */  items);
void QTreeWidget_addTopLevelItems(QTreeWidget* self, struct seaqt_array /* of QTreeWidgetItem* */  items);
QTreeWidgetItem* QTreeWidget_headerItem(const QTreeWidget* self);
void QTreeWidget_setHeaderItem(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_setHeaderLabels(QTreeWidget* self, struct seaqt_array /* of struct seaqt_string */  labels);
void QTreeWidget_setHeaderLabel(QTreeWidget* self, struct seaqt_string label);
QTreeWidgetItem* QTreeWidget_currentItem(const QTreeWidget* self);
int QTreeWidget_currentColumn(const QTreeWidget* self);
void QTreeWidget_setCurrentItem_item(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_setCurrentItem_item_column(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_setCurrentItem_item_column_command(QTreeWidget* self, QTreeWidgetItem* item, int column, int command);
QTreeWidgetItem* QTreeWidget_itemAt_p(const QTreeWidget* self, QPoint* p);
QTreeWidgetItem* QTreeWidget_itemAt_x_y(const QTreeWidget* self, int x, int y);
QRect* QTreeWidget_visualItemRect(const QTreeWidget* self, QTreeWidgetItem* item);
int QTreeWidget_sortColumn(const QTreeWidget* self);
void QTreeWidget_sortItems(QTreeWidget* self, int column, int order);
void QTreeWidget_editItem_item(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_openPersistentEditor_item(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_closePersistentEditor_item(QTreeWidget* self, QTreeWidgetItem* item);
bool QTreeWidget_isPersistentEditorOpen_item(const QTreeWidget* self, QTreeWidgetItem* item);
QWidget* QTreeWidget_itemWidget(const QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_setItemWidget(QTreeWidget* self, QTreeWidgetItem* item, int column, QWidget* widget);
void QTreeWidget_removeItemWidget(QTreeWidget* self, QTreeWidgetItem* item, int column);
struct seaqt_array /* of QTreeWidgetItem* */  QTreeWidget_selectedItems(const QTreeWidget* self);
struct seaqt_array /* of QTreeWidgetItem* */  QTreeWidget_findItems_text_flags(const QTreeWidget* self, struct seaqt_string text, int flags);
QTreeWidgetItem* QTreeWidget_itemAbove(const QTreeWidget* self, QTreeWidgetItem* item);
QTreeWidgetItem* QTreeWidget_itemBelow(const QTreeWidget* self, QTreeWidgetItem* item);
QModelIndex* QTreeWidget_indexFromItem_item(const QTreeWidget* self, QTreeWidgetItem* item);
QTreeWidgetItem* QTreeWidget_itemFromIndex(const QTreeWidget* self, QModelIndex* index);
void QTreeWidget_setSelectionModel(QTreeWidget* self, QItemSelectionModel* selectionModel);
void QTreeWidget_scrollToItem_item(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_expandItem(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_collapseItem(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_clear(QTreeWidget* self);
void QTreeWidget_itemPressed(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_connect_itemPressed(QTreeWidget* self, intptr_t slot, void (*callback)(intptr_t, QTreeWidgetItem*, int), void (*release)(intptr_t));
void QTreeWidget_itemClicked(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_connect_itemClicked(QTreeWidget* self, intptr_t slot, void (*callback)(intptr_t, QTreeWidgetItem*, int), void (*release)(intptr_t));
void QTreeWidget_itemDoubleClicked(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_connect_itemDoubleClicked(QTreeWidget* self, intptr_t slot, void (*callback)(intptr_t, QTreeWidgetItem*, int), void (*release)(intptr_t));
void QTreeWidget_itemActivated(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_connect_itemActivated(QTreeWidget* self, intptr_t slot, void (*callback)(intptr_t, QTreeWidgetItem*, int), void (*release)(intptr_t));
void QTreeWidget_itemEntered(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_connect_itemEntered(QTreeWidget* self, intptr_t slot, void (*callback)(intptr_t, QTreeWidgetItem*, int), void (*release)(intptr_t));
void QTreeWidget_itemChanged(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_connect_itemChanged(QTreeWidget* self, intptr_t slot, void (*callback)(intptr_t, QTreeWidgetItem*, int), void (*release)(intptr_t));
void QTreeWidget_itemExpanded(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_connect_itemExpanded(QTreeWidget* self, intptr_t slot, void (*callback)(intptr_t, QTreeWidgetItem*), void (*release)(intptr_t));
void QTreeWidget_itemCollapsed(QTreeWidget* self, QTreeWidgetItem* item);
void QTreeWidget_connect_itemCollapsed(QTreeWidget* self, intptr_t slot, void (*callback)(intptr_t, QTreeWidgetItem*), void (*release)(intptr_t));
void QTreeWidget_currentItemChanged(QTreeWidget* self, QTreeWidgetItem* current, QTreeWidgetItem* previous);
void QTreeWidget_connect_currentItemChanged(QTreeWidget* self, intptr_t slot, void (*callback)(intptr_t, QTreeWidgetItem*, QTreeWidgetItem*), void (*release)(intptr_t));
void QTreeWidget_itemSelectionChanged(QTreeWidget* self);
void QTreeWidget_connect_itemSelectionChanged(QTreeWidget* self, intptr_t slot, void (*callback)(intptr_t), void (*release)(intptr_t));
bool QTreeWidget_event(QTreeWidget* self, QEvent* e);
struct seaqt_array /* of struct seaqt_string */  QTreeWidget_mimeTypes(const QTreeWidget* self);
QMimeData* QTreeWidget_mimeData(const QTreeWidget* self, struct seaqt_array /* of QTreeWidgetItem* */  items);
bool QTreeWidget_dropMimeData(QTreeWidget* self, QTreeWidgetItem* parent, int index, QMimeData* data, int action);
int QTreeWidget_supportedDropActions(const QTreeWidget* self);
void QTreeWidget_dropEvent(QTreeWidget* self, QDropEvent* event);
struct seaqt_string QTreeWidget_tr_s_c(const char* s, const char* c);
struct seaqt_string QTreeWidget_tr_s_c_n(const char* s, const char* c, int n);
void QTreeWidget_editItem_item_column(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_openPersistentEditor_item_column(QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_closePersistentEditor_item_column(QTreeWidget* self, QTreeWidgetItem* item, int column);
bool QTreeWidget_isPersistentEditorOpen_item_column(const QTreeWidget* self, QTreeWidgetItem* item, int column);
struct seaqt_array /* of QTreeWidgetItem* */  QTreeWidget_findItems_text_flags_column(const QTreeWidget* self, struct seaqt_string text, int flags, int column);
QModelIndex* QTreeWidget_indexFromItem_item_column(const QTreeWidget* self, QTreeWidgetItem* item, int column);
void QTreeWidget_scrollToItem_item_hint(QTreeWidget* self, QTreeWidgetItem* item, int hint);

QMetaObject* QTreeWidget_virtualbase_metaObject(const VirtualQTreeWidget* self);
void* QTreeWidget_virtualbase_metacast(VirtualQTreeWidget* self, const char* param1);
int QTreeWidget_virtualbase_metacall(VirtualQTreeWidget* self, int param1, int param2, void** param3);
void QTreeWidget_virtualbase_setSelectionModel(VirtualQTreeWidget* self, QItemSelectionModel* selectionModel);
bool QTreeWidget_virtualbase_event(VirtualQTreeWidget* self, QEvent* e);
struct seaqt_array /* of struct seaqt_string */  QTreeWidget_virtualbase_mimeTypes(const VirtualQTreeWidget* self);
QMimeData* QTreeWidget_virtualbase_mimeData(const VirtualQTreeWidget* self, struct seaqt_array /* of QTreeWidgetItem* */  items);
bool QTreeWidget_virtualbase_dropMimeData(VirtualQTreeWidget* self, QTreeWidgetItem* parent, int index, QMimeData* data, int action);
int QTreeWidget_virtualbase_supportedDropActions(const VirtualQTreeWidget* self);
void QTreeWidget_virtualbase_dropEvent(VirtualQTreeWidget* self, QDropEvent* event);
void QTreeWidget_virtualbase_setRootIndex(VirtualQTreeWidget* self, QModelIndex* index);
void QTreeWidget_virtualbase_keyboardSearch(VirtualQTreeWidget* self, struct seaqt_string search);
QRect* QTreeWidget_virtualbase_visualRect(const VirtualQTreeWidget* self, QModelIndex* index);
void QTreeWidget_virtualbase_scrollTo(VirtualQTreeWidget* self, QModelIndex* index, int hint);
QModelIndex* QTreeWidget_virtualbase_indexAt(const VirtualQTreeWidget* self, QPoint* p);
void QTreeWidget_virtualbase_doItemsLayout(VirtualQTreeWidget* self);
void QTreeWidget_virtualbase_reset(VirtualQTreeWidget* self);
void QTreeWidget_virtualbase_dataChanged(VirtualQTreeWidget* self, QModelIndex* topLeft, QModelIndex* bottomRight, struct seaqt_array /* of int */  roles);
void QTreeWidget_virtualbase_selectAll(VirtualQTreeWidget* self);
void QTreeWidget_virtualbase_verticalScrollbarValueChanged(VirtualQTreeWidget* self, int value);
void QTreeWidget_virtualbase_scrollContentsBy(VirtualQTreeWidget* self, int dx, int dy);
void QTreeWidget_virtualbase_rowsInserted(VirtualQTreeWidget* self, QModelIndex* parent, int start, int end);
void QTreeWidget_virtualbase_rowsAboutToBeRemoved(VirtualQTreeWidget* self, QModelIndex* parent, int start, int end);
QModelIndex* QTreeWidget_virtualbase_moveCursor(VirtualQTreeWidget* self, int cursorAction, int modifiers);
int QTreeWidget_virtualbase_horizontalOffset(const VirtualQTreeWidget* self);
int QTreeWidget_virtualbase_verticalOffset(const VirtualQTreeWidget* self);
void QTreeWidget_virtualbase_setSelection(VirtualQTreeWidget* self, QRect* rect, int command);
QRegion* QTreeWidget_virtualbase_visualRegionForSelection(const VirtualQTreeWidget* self, QItemSelection* selection);
struct seaqt_array /* of QModelIndex* */  QTreeWidget_virtualbase_selectedIndexes(const VirtualQTreeWidget* self);
void QTreeWidget_virtualbase_changeEvent(VirtualQTreeWidget* self, QEvent* event);
void QTreeWidget_virtualbase_timerEvent(VirtualQTreeWidget* self, QTimerEvent* event);
void QTreeWidget_virtualbase_paintEvent(VirtualQTreeWidget* self, QPaintEvent* event);
void QTreeWidget_virtualbase_drawRow(const VirtualQTreeWidget* self, QPainter* painter, QStyleOptionViewItem* options, QModelIndex* index);
void QTreeWidget_virtualbase_drawBranches(const VirtualQTreeWidget* self, QPainter* painter, QRect* rect, QModelIndex* index);
void QTreeWidget_virtualbase_mousePressEvent(VirtualQTreeWidget* self, QMouseEvent* event);
void QTreeWidget_virtualbase_mouseReleaseEvent(VirtualQTreeWidget* self, QMouseEvent* event);
void QTreeWidget_virtualbase_mouseDoubleClickEvent(VirtualQTreeWidget* self, QMouseEvent* event);
void QTreeWidget_virtualbase_mouseMoveEvent(VirtualQTreeWidget* self, QMouseEvent* event);
void QTreeWidget_virtualbase_keyPressEvent(VirtualQTreeWidget* self, QKeyEvent* event);
void QTreeWidget_virtualbase_dragMoveEvent(VirtualQTreeWidget* self, QDragMoveEvent* event);
bool QTreeWidget_virtualbase_viewportEvent(VirtualQTreeWidget* self, QEvent* event);
void QTreeWidget_virtualbase_updateGeometries(VirtualQTreeWidget* self);
QSize* QTreeWidget_virtualbase_viewportSizeHint(const VirtualQTreeWidget* self);
int QTreeWidget_virtualbase_sizeHintForColumn(const VirtualQTreeWidget* self, int column);
void QTreeWidget_virtualbase_horizontalScrollbarAction(VirtualQTreeWidget* self, int action);
bool QTreeWidget_virtualbase_isIndexHidden(const VirtualQTreeWidget* self, QModelIndex* index);
void QTreeWidget_virtualbase_selectionChanged(VirtualQTreeWidget* self, QItemSelection* selected, QItemSelection* deselected);
void QTreeWidget_virtualbase_currentChanged(VirtualQTreeWidget* self, QModelIndex* current, QModelIndex* previous);
int QTreeWidget_virtualbase_sizeHintForRow(const VirtualQTreeWidget* self, int row);
QAbstractItemDelegate* QTreeWidget_virtualbase_itemDelegateForIndex(const VirtualQTreeWidget* self, QModelIndex* index);
QVariant* QTreeWidget_virtualbase_inputMethodQuery(const VirtualQTreeWidget* self, int query);
void QTreeWidget_virtualbase_updateEditorData(VirtualQTreeWidget* self);
void QTreeWidget_virtualbase_updateEditorGeometries(VirtualQTreeWidget* self);
void QTreeWidget_virtualbase_verticalScrollbarAction(VirtualQTreeWidget* self, int action);
void QTreeWidget_virtualbase_horizontalScrollbarValueChanged(VirtualQTreeWidget* self, int value);
void QTreeWidget_virtualbase_closeEditor(VirtualQTreeWidget* self, QWidget* editor, int hint);
void QTreeWidget_virtualbase_commitData(VirtualQTreeWidget* self, QWidget* editor);
void QTreeWidget_virtualbase_editorDestroyed(VirtualQTreeWidget* self, QObject* editor);
bool QTreeWidget_virtualbase_edit_index_trigger_event(VirtualQTreeWidget* self, QModelIndex* index, int trigger, QEvent* event);
int QTreeWidget_virtualbase_selectionCommand(const VirtualQTreeWidget* self, QModelIndex* index, QEvent* event);
void QTreeWidget_virtualbase_startDrag(VirtualQTreeWidget* self, int supportedActions);
void QTreeWidget_virtualbase_initViewItemOption(const VirtualQTreeWidget* self, QStyleOptionViewItem* option);
bool QTreeWidget_virtualbase_focusNextPrevChild(VirtualQTreeWidget* self, bool next);
void QTreeWidget_virtualbase_dragEnterEvent(VirtualQTreeWidget* self, QDragEnterEvent* event);
void QTreeWidget_virtualbase_dragLeaveEvent(VirtualQTreeWidget* self, QDragLeaveEvent* event);
void QTreeWidget_virtualbase_focusInEvent(VirtualQTreeWidget* self, QFocusEvent* event);
void QTreeWidget_virtualbase_focusOutEvent(VirtualQTreeWidget* self, QFocusEvent* event);
void QTreeWidget_virtualbase_resizeEvent(VirtualQTreeWidget* self, QResizeEvent* event);
void QTreeWidget_virtualbase_inputMethodEvent(VirtualQTreeWidget* self, QInputMethodEvent* event);
bool QTreeWidget_virtualbase_eventFilter(VirtualQTreeWidget* self, QObject* object, QEvent* event);
QSize* QTreeWidget_virtualbase_minimumSizeHint(const VirtualQTreeWidget* self);
QSize* QTreeWidget_virtualbase_sizeHint(const VirtualQTreeWidget* self);
void QTreeWidget_virtualbase_setupViewport(VirtualQTreeWidget* self, QWidget* viewport);
void QTreeWidget_virtualbase_wheelEvent(VirtualQTreeWidget* self, QWheelEvent* param1);
void QTreeWidget_virtualbase_contextMenuEvent(VirtualQTreeWidget* self, QContextMenuEvent* param1);
void QTreeWidget_virtualbase_initStyleOption(const VirtualQTreeWidget* self, QStyleOptionFrame* option);
int QTreeWidget_virtualbase_devType(const VirtualQTreeWidget* self);
void QTreeWidget_virtualbase_setVisible(VirtualQTreeWidget* self, bool visible);
int QTreeWidget_virtualbase_heightForWidth(const VirtualQTreeWidget* self, int param1);
bool QTreeWidget_virtualbase_hasHeightForWidth(const VirtualQTreeWidget* self);
QPaintEngine* QTreeWidget_virtualbase_paintEngine(const VirtualQTreeWidget* self);
void QTreeWidget_virtualbase_keyReleaseEvent(VirtualQTreeWidget* self, QKeyEvent* event);
void QTreeWidget_virtualbase_enterEvent(VirtualQTreeWidget* self, QEnterEvent* event);
void QTreeWidget_virtualbase_leaveEvent(VirtualQTreeWidget* self, QEvent* event);
void QTreeWidget_virtualbase_moveEvent(VirtualQTreeWidget* self, QMoveEvent* event);
void QTreeWidget_virtualbase_closeEvent(VirtualQTreeWidget* self, QCloseEvent* event);
void QTreeWidget_virtualbase_tabletEvent(VirtualQTreeWidget* self, QTabletEvent* event);
void QTreeWidget_virtualbase_actionEvent(VirtualQTreeWidget* self, QActionEvent* event);
void QTreeWidget_virtualbase_showEvent(VirtualQTreeWidget* self, QShowEvent* event);
void QTreeWidget_virtualbase_hideEvent(VirtualQTreeWidget* self, QHideEvent* event);
bool QTreeWidget_virtualbase_nativeEvent(VirtualQTreeWidget* self, struct seaqt_string eventType, void* message, intptr_t* result);
int QTreeWidget_virtualbase_metric(const VirtualQTreeWidget* self, int param1);
void QTreeWidget_virtualbase_initPainter(const VirtualQTreeWidget* self, QPainter* painter);
QPaintDevice* QTreeWidget_virtualbase_redirected(const VirtualQTreeWidget* self, QPoint* offset);
QPainter* QTreeWidget_virtualbase_sharedPainter(const VirtualQTreeWidget* self);
void QTreeWidget_virtualbase_childEvent(VirtualQTreeWidget* self, QChildEvent* event);
void QTreeWidget_virtualbase_customEvent(VirtualQTreeWidget* self, QEvent* event);
void QTreeWidget_virtualbase_connectNotify(VirtualQTreeWidget* self, QMetaMethod* signal);
void QTreeWidget_virtualbase_disconnectNotify(VirtualQTreeWidget* self, QMetaMethod* signal);

void QTreeWidget_protectedbase_columnResized(VirtualQTreeWidget* self, int column, int oldSize, int newSize);
void QTreeWidget_protectedbase_columnCountChanged(VirtualQTreeWidget* self, int oldCount, int newCount);
void QTreeWidget_protectedbase_columnMoved(VirtualQTreeWidget* self);
void QTreeWidget_protectedbase_reexpand(VirtualQTreeWidget* self);
void QTreeWidget_protectedbase_rowsRemoved(VirtualQTreeWidget* self, QModelIndex* parent, int first, int last);
void QTreeWidget_protectedbase_drawTree(const VirtualQTreeWidget* self, QPainter* painter, QRegion* region);
int QTreeWidget_protectedbase_indexRowSizeHint(const VirtualQTreeWidget* self, QModelIndex* index);
int QTreeWidget_protectedbase_rowHeight(const VirtualQTreeWidget* self, QModelIndex* index);
int QTreeWidget_protectedbase_state(const VirtualQTreeWidget* self);
void QTreeWidget_protectedbase_setState(VirtualQTreeWidget* self, int state);
void QTreeWidget_protectedbase_scheduleDelayedItemsLayout(VirtualQTreeWidget* self);
void QTreeWidget_protectedbase_executeDelayedItemsLayout(VirtualQTreeWidget* self);
void QTreeWidget_protectedbase_setDirtyRegion(VirtualQTreeWidget* self, QRegion* region);
void QTreeWidget_protectedbase_scrollDirtyRegion(VirtualQTreeWidget* self, int dx, int dy);
QPoint* QTreeWidget_protectedbase_dirtyRegionOffset(const VirtualQTreeWidget* self);
void QTreeWidget_protectedbase_startAutoScroll(VirtualQTreeWidget* self);
void QTreeWidget_protectedbase_stopAutoScroll(VirtualQTreeWidget* self);
void QTreeWidget_protectedbase_doAutoScroll(VirtualQTreeWidget* self);
int QTreeWidget_protectedbase_dropIndicatorPosition(const VirtualQTreeWidget* self);
void QTreeWidget_protectedbase_setViewportMargins_left_top_right_bottom(VirtualQTreeWidget* self, int left, int top, int right, int bottom);
QMargins* QTreeWidget_protectedbase_viewportMargins(const VirtualQTreeWidget* self);
void QTreeWidget_protectedbase_drawFrame(VirtualQTreeWidget* self, QPainter* param1);
void QTreeWidget_protectedbase_updateMicroFocus(VirtualQTreeWidget* self);
void QTreeWidget_protectedbase_create(VirtualQTreeWidget* self);
void QTreeWidget_protectedbase_destroy(VirtualQTreeWidget* self);
bool QTreeWidget_protectedbase_focusNextChild(VirtualQTreeWidget* self);
bool QTreeWidget_protectedbase_focusPreviousChild(VirtualQTreeWidget* self);
QObject* QTreeWidget_protectedbase_sender(const VirtualQTreeWidget* self);
int QTreeWidget_protectedbase_senderSignalIndex(const VirtualQTreeWidget* self);
int QTreeWidget_protectedbase_receivers(const VirtualQTreeWidget* self, const char* signal);
bool QTreeWidget_protectedbase_isSignalConnected(const VirtualQTreeWidget* self, QMetaMethod* signal);

void QTreeWidget_delete(QTreeWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
