#pragma once
#ifndef SEAQT_QTGUI_GEN_QPAINTER_H
#define SEAQT_QTGUI_GEN_QPAINTER_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../libseaqt-runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QBrush;
class QColor;
class QFont;
class QFontInfo;
class QFontMetrics;
class QGlyphRun;
class QImage;
class QLine;
class QLineF;
class QMatrix;
class QMetaObject;
class QPaintDevice;
class QPaintEngine;
class QPainter;
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QPainter__PixmapFragment)
typedef QPainter::PixmapFragment QPainter__PixmapFragment;
#else
class QPainter__PixmapFragment;
#endif
class QPainterPath;
class QPen;
class QPicture;
class QPixmap;
class QPoint;
class QPointF;
class QRect;
class QRectF;
class QRegion;
class QStaticText;
class QTextItem;
class QTextOption;
class QTransform;
#else
typedef struct QBrush QBrush;
typedef struct QColor QColor;
typedef struct QFont QFont;
typedef struct QFontInfo QFontInfo;
typedef struct QFontMetrics QFontMetrics;
typedef struct QGlyphRun QGlyphRun;
typedef struct QImage QImage;
typedef struct QLine QLine;
typedef struct QLineF QLineF;
typedef struct QMatrix QMatrix;
typedef struct QMetaObject QMetaObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPainter QPainter;
typedef struct QPainter__PixmapFragment QPainter__PixmapFragment;
typedef struct QPainterPath QPainterPath;
typedef struct QPen QPen;
typedef struct QPicture QPicture;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QPointF QPointF;
typedef struct QRect QRect;
typedef struct QRectF QRectF;
typedef struct QRegion QRegion;
typedef struct QStaticText QStaticText;
typedef struct QTextItem QTextItem;
typedef struct QTextOption QTextOption;
typedef struct QTransform QTransform;
#endif

QPainter* QPainter_new();
QPainter* QPainter_new_QPaintDevice(QPaintDevice* param1);

QPaintDevice* QPainter_device(const QPainter* self);
bool QPainter_begin(QPainter* self, QPaintDevice* param1);
bool QPainter_end(QPainter* self);
bool QPainter_isActive(const QPainter* self);
void QPainter_initFrom(QPainter* self, QPaintDevice* device);
void QPainter_setCompositionMode(QPainter* self, int mode);
int QPainter_compositionMode(const QPainter* self);
QFont* QPainter_font(const QPainter* self);
void QPainter_setFont(QPainter* self, QFont* f);
QFontMetrics* QPainter_fontMetrics(const QPainter* self);
QFontInfo* QPainter_fontInfo(const QPainter* self);
void QPainter_setPen_color(QPainter* self, QColor* color);
void QPainter_setPen_pen(QPainter* self, QPen* pen);
void QPainter_setPen_style(QPainter* self, int style);
QPen* QPainter_pen(const QPainter* self);
void QPainter_setBrush_brush(QPainter* self, QBrush* brush);
void QPainter_setBrush_style(QPainter* self, int style);
QBrush* QPainter_brush(const QPainter* self);
void QPainter_setBackgroundMode(QPainter* self, int mode);
int QPainter_backgroundMode(const QPainter* self);
QPoint* QPainter_brushOrigin(const QPainter* self);
void QPainter_setBrushOrigin_int_int(QPainter* self, int x, int y);
void QPainter_setBrushOrigin_QPoint(QPainter* self, QPoint* brushOrigin);
void QPainter_setBrushOrigin_QPointF(QPainter* self, QPointF* brushOrigin);
void QPainter_setBackground(QPainter* self, QBrush* bg);
QBrush* QPainter_background(const QPainter* self);
double QPainter_opacity(const QPainter* self);
void QPainter_setOpacity(QPainter* self, double opacity);
QRegion* QPainter_clipRegion(const QPainter* self);
QPainterPath* QPainter_clipPath(const QPainter* self);
void QPainter_setClipRect_QRectF(QPainter* self, QRectF* param1);
void QPainter_setClipRect_QRect(QPainter* self, QRect* param1);
void QPainter_setClipRect_int_int_int_int(QPainter* self, int x, int y, int w, int h);
void QPainter_setClipRegion_QRegion(QPainter* self, QRegion* param1);
void QPainter_setClipPath_path(QPainter* self, QPainterPath* path);
void QPainter_setClipping(QPainter* self, bool enable);
bool QPainter_hasClipping(const QPainter* self);
QRectF* QPainter_clipBoundingRect(const QPainter* self);
void QPainter_save(QPainter* self);
void QPainter_restore(QPainter* self);
void QPainter_setMatrix_matrix(QPainter* self, QMatrix* matrix);
QMatrix* QPainter_matrix(const QPainter* self);
QMatrix* QPainter_deviceMatrix(const QPainter* self);
void QPainter_resetMatrix(QPainter* self);
void QPainter_setTransform_transform(QPainter* self, QTransform* transform);
QTransform* QPainter_transform(const QPainter* self);
QTransform* QPainter_deviceTransform(const QPainter* self);
void QPainter_resetTransform(QPainter* self);
void QPainter_setWorldMatrix_matrix(QPainter* self, QMatrix* matrix);
QMatrix* QPainter_worldMatrix(const QPainter* self);
QMatrix* QPainter_combinedMatrix(const QPainter* self);
void QPainter_setMatrixEnabled(QPainter* self, bool enabled);
bool QPainter_matrixEnabled(const QPainter* self);
void QPainter_setWorldTransform_matrix(QPainter* self, QTransform* matrix);
QTransform* QPainter_worldTransform(const QPainter* self);
QTransform* QPainter_combinedTransform(const QPainter* self);
void QPainter_setWorldMatrixEnabled(QPainter* self, bool enabled);
bool QPainter_worldMatrixEnabled(const QPainter* self);
void QPainter_scale(QPainter* self, double sx, double sy);
void QPainter_shear(QPainter* self, double sh, double sv);
void QPainter_rotate(QPainter* self, double a);
void QPainter_translate_QPointF(QPainter* self, QPointF* offset);
void QPainter_translate_QPoint(QPainter* self, QPoint* offset);
void QPainter_translate_qreal_qreal(QPainter* self, double dx, double dy);
QRect* QPainter_window(const QPainter* self);
void QPainter_setWindow_window(QPainter* self, QRect* window);
void QPainter_setWindow_x_y_w_h(QPainter* self, int x, int y, int w, int h);
QRect* QPainter_viewport(const QPainter* self);
void QPainter_setViewport_viewport(QPainter* self, QRect* viewport);
void QPainter_setViewport_x_y_w_h(QPainter* self, int x, int y, int w, int h);
void QPainter_setViewTransformEnabled(QPainter* self, bool enable);
bool QPainter_viewTransformEnabled(const QPainter* self);
void QPainter_strokePath(QPainter* self, QPainterPath* path, QPen* pen);
void QPainter_fillPath(QPainter* self, QPainterPath* path, QBrush* brush);
void QPainter_drawPath(QPainter* self, QPainterPath* path);
void QPainter_drawPoint_pt(QPainter* self, QPointF* pt);
void QPainter_drawPoint_p(QPainter* self, QPoint* p);
void QPainter_drawPoint_x_y(QPainter* self, int x, int y);
void QPainter_drawPoints_QPointF_int(QPainter* self, QPointF* points, int pointCount);
void QPainter_drawPoints_QPoint_int(QPainter* self, QPoint* points, int pointCount);
void QPainter_drawLine_QLineF(QPainter* self, QLineF* line);
void QPainter_drawLine_QLine(QPainter* self, QLine* line);
void QPainter_drawLine_int_int_int_int(QPainter* self, int x1, int y1, int x2, int y2);
void QPainter_drawLine_QPoint_QPoint(QPainter* self, QPoint* p1, QPoint* p2);
void QPainter_drawLine_QPointF_QPointF(QPainter* self, QPointF* p1, QPointF* p2);
void QPainter_drawLines_QLineF_int(QPainter* self, QLineF* lines, int lineCount);
void QPainter_drawLines_QVectorOfQLineF(QPainter* self, struct seaqt_array /* of QLineF* */  lines);
void QPainter_drawLines_QPointF_int(QPainter* self, QPointF* pointPairs, int lineCount);
void QPainter_drawLines_QVectorOfQPointF(QPainter* self, struct seaqt_array /* of QPointF* */  pointPairs);
void QPainter_drawLines_QLine_int(QPainter* self, QLine* lines, int lineCount);
void QPainter_drawLines_QVectorOfQLine(QPainter* self, struct seaqt_array /* of QLine* */  lines);
void QPainter_drawLines_QPoint_int(QPainter* self, QPoint* pointPairs, int lineCount);
void QPainter_drawLines_QVectorOfQPoint(QPainter* self, struct seaqt_array /* of QPoint* */  pointPairs);
void QPainter_drawRect_QRectF(QPainter* self, QRectF* rect);
void QPainter_drawRect_int_int_int_int(QPainter* self, int x1, int y1, int w, int h);
void QPainter_drawRect_QRect(QPainter* self, QRect* rect);
void QPainter_drawRects_QRectF_int(QPainter* self, QRectF* rects, int rectCount);
void QPainter_drawRects_QVectorOfQRectF(QPainter* self, struct seaqt_array /* of QRectF* */  rectangles);
void QPainter_drawRects_QRect_int(QPainter* self, QRect* rects, int rectCount);
void QPainter_drawRects_QVectorOfQRect(QPainter* self, struct seaqt_array /* of QRect* */  rectangles);
void QPainter_drawEllipse_QRectF(QPainter* self, QRectF* r);
void QPainter_drawEllipse_QRect(QPainter* self, QRect* r);
void QPainter_drawEllipse_int_int_int_int(QPainter* self, int x, int y, int w, int h);
void QPainter_drawEllipse_QPointF_qreal_qreal(QPainter* self, QPointF* center, double rx, double ry);
void QPainter_drawEllipse_QPoint_int_int(QPainter* self, QPoint* center, int rx, int ry);
void QPainter_drawPolyline_QPointF_int(QPainter* self, QPointF* points, int pointCount);
void QPainter_drawPolyline_QPoint_int(QPainter* self, QPoint* points, int pointCount);
void QPainter_drawPolygon_QPointF_int(QPainter* self, QPointF* points, int pointCount);
void QPainter_drawPolygon_QPoint_int(QPainter* self, QPoint* points, int pointCount);
void QPainter_drawConvexPolygon_QPointF_int(QPainter* self, QPointF* points, int pointCount);
void QPainter_drawConvexPolygon_QPoint_int(QPainter* self, QPoint* points, int pointCount);
void QPainter_drawArc_QRectF_int_int(QPainter* self, QRectF* rect, int a, int alen);
void QPainter_drawArc_QRect_int_int(QPainter* self, QRect* param1, int a, int alen);
void QPainter_drawArc_int_int_int_int_int_int(QPainter* self, int x, int y, int w, int h, int a, int alen);
void QPainter_drawPie_QRectF_int_int(QPainter* self, QRectF* rect, int a, int alen);
void QPainter_drawPie_int_int_int_int_int_int(QPainter* self, int x, int y, int w, int h, int a, int alen);
void QPainter_drawPie_QRect_int_int(QPainter* self, QRect* param1, int a, int alen);
void QPainter_drawChord_QRectF_int_int(QPainter* self, QRectF* rect, int a, int alen);
void QPainter_drawChord_int_int_int_int_int_int(QPainter* self, int x, int y, int w, int h, int a, int alen);
void QPainter_drawChord_QRect_int_int(QPainter* self, QRect* param1, int a, int alen);
void QPainter_drawRoundedRect_QRectF_qreal_qreal(QPainter* self, QRectF* rect, double xRadius, double yRadius);
void QPainter_drawRoundedRect_int_int_int_int_qreal_qreal(QPainter* self, int x, int y, int w, int h, double xRadius, double yRadius);
void QPainter_drawRoundedRect_QRect_qreal_qreal(QPainter* self, QRect* rect, double xRadius, double yRadius);
void QPainter_drawRoundRect_QRectF(QPainter* self, QRectF* r);
void QPainter_drawRoundRect_int_int_int_int(QPainter* self, int x, int y, int w, int h);
void QPainter_drawRoundRect_QRect(QPainter* self, QRect* r);
void QPainter_drawTiledPixmap_QRectF_QPixmap(QPainter* self, QRectF* rect, QPixmap* pm);
void QPainter_drawTiledPixmap_int_int_int_int_QPixmap(QPainter* self, int x, int y, int w, int h, QPixmap* param5);
void QPainter_drawTiledPixmap_QRect_QPixmap(QPainter* self, QRect* param1, QPixmap* param2);
void QPainter_drawPicture_QPointF_QPicture(QPainter* self, QPointF* p, QPicture* picture);
void QPainter_drawPicture_int_int_QPicture(QPainter* self, int x, int y, QPicture* picture);
void QPainter_drawPicture_QPoint_QPicture(QPainter* self, QPoint* p, QPicture* picture);
void QPainter_drawPixmap_QRectF_QPixmap_QRectF(QPainter* self, QRectF* targetRect, QPixmap* pixmap, QRectF* sourceRect);
void QPainter_drawPixmap_QRect_QPixmap_QRect(QPainter* self, QRect* targetRect, QPixmap* pixmap, QRect* sourceRect);
void QPainter_drawPixmap_int_int_int_int_QPixmap_int_int_int_int(QPainter* self, int x, int y, int w, int h, QPixmap* pm, int sx, int sy, int sw, int sh);
void QPainter_drawPixmap_int_int_QPixmap_int_int_int_int(QPainter* self, int x, int y, QPixmap* pm, int sx, int sy, int sw, int sh);
void QPainter_drawPixmap_QPointF_QPixmap_QRectF(QPainter* self, QPointF* p, QPixmap* pm, QRectF* sr);
void QPainter_drawPixmap_QPoint_QPixmap_QRect(QPainter* self, QPoint* p, QPixmap* pm, QRect* sr);
void QPainter_drawPixmap_QPointF_QPixmap(QPainter* self, QPointF* p, QPixmap* pm);
void QPainter_drawPixmap_QPoint_QPixmap(QPainter* self, QPoint* p, QPixmap* pm);
void QPainter_drawPixmap_int_int_QPixmap(QPainter* self, int x, int y, QPixmap* pm);
void QPainter_drawPixmap_QRect_QPixmap(QPainter* self, QRect* r, QPixmap* pm);
void QPainter_drawPixmap_int_int_int_int_QPixmap(QPainter* self, int x, int y, int w, int h, QPixmap* pm);
void QPainter_drawPixmapFragments_fragments_fragmentCount_pixmap(QPainter* self, QPainter__PixmapFragment* fragments, int fragmentCount, QPixmap* pixmap);
void QPainter_drawImage_QRectF_QImage_QRectF(QPainter* self, QRectF* targetRect, QImage* image, QRectF* sourceRect);
void QPainter_drawImage_QRect_QImage_QRect(QPainter* self, QRect* targetRect, QImage* image, QRect* sourceRect);
void QPainter_drawImage_QPointF_QImage_QRectF(QPainter* self, QPointF* p, QImage* image, QRectF* sr);
void QPainter_drawImage_QPoint_QImage_QRect(QPainter* self, QPoint* p, QImage* image, QRect* sr);
void QPainter_drawImage_QRectF_QImage(QPainter* self, QRectF* r, QImage* image);
void QPainter_drawImage_QRect_QImage(QPainter* self, QRect* r, QImage* image);
void QPainter_drawImage_QPointF_QImage(QPainter* self, QPointF* p, QImage* image);
void QPainter_drawImage_QPoint_QImage(QPainter* self, QPoint* p, QImage* image);
void QPainter_drawImage_int_int_QImage(QPainter* self, int x, int y, QImage* image);
void QPainter_setLayoutDirection(QPainter* self, int direction);
int QPainter_layoutDirection(const QPainter* self);
void QPainter_drawGlyphRun(QPainter* self, QPointF* position, QGlyphRun* glyphRun);
void QPainter_drawStaticText_QPointF_QStaticText(QPainter* self, QPointF* topLeftPosition, QStaticText* staticText);
void QPainter_drawStaticText_QPoint_QStaticText(QPainter* self, QPoint* topLeftPosition, QStaticText* staticText);
void QPainter_drawStaticText_int_int_QStaticText(QPainter* self, int left, int top, QStaticText* staticText);
void QPainter_drawText_QPointF_QString(QPainter* self, QPointF* p, struct seaqt_string s);
void QPainter_drawText_QPoint_QString(QPainter* self, QPoint* p, struct seaqt_string s);
void QPainter_drawText_int_int_QString(QPainter* self, int x, int y, struct seaqt_string s);
void QPainter_drawText_QPointF_QString_int_int(QPainter* self, QPointF* p, struct seaqt_string str, int tf, int justificationPadding);
void QPainter_drawText_QRectF_int_QString(QPainter* self, QRectF* r, int flags, struct seaqt_string text);
void QPainter_drawText_QRect_int_QString(QPainter* self, QRect* r, int flags, struct seaqt_string text);
void QPainter_drawText_int_int_int_int_int_QString(QPainter* self, int x, int y, int w, int h, int flags, struct seaqt_string text);
void QPainter_drawText_QRectF_QString(QPainter* self, QRectF* r, struct seaqt_string text);
QRectF* QPainter_boundingRect_QRectF_int_QString(QPainter* self, QRectF* rect, int flags, struct seaqt_string text);
QRect* QPainter_boundingRect_QRect_int_QString(QPainter* self, QRect* rect, int flags, struct seaqt_string text);
QRect* QPainter_boundingRect_int_int_int_int_int_QString(QPainter* self, int x, int y, int w, int h, int flags, struct seaqt_string text);
QRectF* QPainter_boundingRect_QRectF_QString(QPainter* self, QRectF* rect, struct seaqt_string text);
void QPainter_drawTextItem_QPointF_QTextItem(QPainter* self, QPointF* p, QTextItem* ti);
void QPainter_drawTextItem_int_int_QTextItem(QPainter* self, int x, int y, QTextItem* ti);
void QPainter_drawTextItem_QPoint_QTextItem(QPainter* self, QPoint* p, QTextItem* ti);
void QPainter_fillRect_QRectF_QBrush(QPainter* self, QRectF* param1, QBrush* param2);
void QPainter_fillRect_int_int_int_int_QBrush(QPainter* self, int x, int y, int w, int h, QBrush* param5);
void QPainter_fillRect_QRect_QBrush(QPainter* self, QRect* param1, QBrush* param2);
void QPainter_fillRect_QRectF_QColor(QPainter* self, QRectF* param1, QColor* color);
void QPainter_fillRect_int_int_int_int_QColor(QPainter* self, int x, int y, int w, int h, QColor* color);
void QPainter_fillRect_QRect_QColor(QPainter* self, QRect* param1, QColor* color);
void QPainter_fillRect_int_int_int_int_Qt_GlobalColor(QPainter* self, int x, int y, int w, int h, int c);
void QPainter_fillRect_QRect_Qt_GlobalColor(QPainter* self, QRect* r, int c);
void QPainter_fillRect_QRectF_Qt_GlobalColor(QPainter* self, QRectF* r, int c);
void QPainter_fillRect_int_int_int_int_Qt_BrushStyle(QPainter* self, int x, int y, int w, int h, int style);
void QPainter_fillRect_QRect_Qt_BrushStyle(QPainter* self, QRect* r, int style);
void QPainter_fillRect_QRectF_Qt_BrushStyle(QPainter* self, QRectF* r, int style);
void QPainter_fillRect_int_int_int_int_QGradient_Preset(QPainter* self, int x, int y, int w, int h, int preset);
void QPainter_fillRect_QRect_QGradient_Preset(QPainter* self, QRect* r, int preset);
void QPainter_fillRect_QRectF_QGradient_Preset(QPainter* self, QRectF* r, int preset);
void QPainter_eraseRect_QRectF(QPainter* self, QRectF* param1);
void QPainter_eraseRect_int_int_int_int(QPainter* self, int x, int y, int w, int h);
void QPainter_eraseRect_QRect(QPainter* self, QRect* param1);
void QPainter_setRenderHint_hint(QPainter* self, int hint);
void QPainter_setRenderHints_hints(QPainter* self, int hints);
int QPainter_renderHints(const QPainter* self);
bool QPainter_testRenderHint(const QPainter* self, int hint);
QPaintEngine* QPainter_paintEngine(const QPainter* self);
void QPainter_setRedirected_device_replacement(QPaintDevice* device, QPaintDevice* replacement);
QPaintDevice* QPainter_redirected_device(QPaintDevice* device);
void QPainter_restoreRedirected(QPaintDevice* device);
void QPainter_beginNativePainting(QPainter* self);
void QPainter_endNativePainting(QPainter* self);
void QPainter_setClipRect_QRectF_Qt_ClipOperation(QPainter* self, QRectF* param1, int op);
void QPainter_setClipRect_QRect_Qt_ClipOperation(QPainter* self, QRect* param1, int op);
void QPainter_setClipRect_int_int_int_int_Qt_ClipOperation(QPainter* self, int x, int y, int w, int h, int op);
void QPainter_setClipRegion_QRegion_Qt_ClipOperation(QPainter* self, QRegion* param1, int op);
void QPainter_setClipPath_path_op(QPainter* self, QPainterPath* path, int op);
void QPainter_setMatrix_matrix_combine(QPainter* self, QMatrix* matrix, bool combine);
void QPainter_setTransform_transform_combine(QPainter* self, QTransform* transform, bool combine);
void QPainter_setWorldMatrix_matrix_combine(QPainter* self, QMatrix* matrix, bool combine);
void QPainter_setWorldTransform_matrix_combine(QPainter* self, QTransform* matrix, bool combine);
void QPainter_drawPolygon_QPointF_int_Qt_FillRule(QPainter* self, QPointF* points, int pointCount, int fillRule);
void QPainter_drawPolygon_QPoint_int_Qt_FillRule(QPainter* self, QPoint* points, int pointCount, int fillRule);
void QPainter_drawRoundedRect_QRectF_qreal_qreal_Qt_SizeMode(QPainter* self, QRectF* rect, double xRadius, double yRadius, int mode);
void QPainter_drawRoundedRect_int_int_int_int_qreal_qreal_Qt_SizeMode(QPainter* self, int x, int y, int w, int h, double xRadius, double yRadius, int mode);
void QPainter_drawRoundedRect_QRect_qreal_qreal_Qt_SizeMode(QPainter* self, QRect* rect, double xRadius, double yRadius, int mode);
void QPainter_drawRoundRect_QRectF_int(QPainter* self, QRectF* r, int xround);
void QPainter_drawRoundRect_QRectF_int_int(QPainter* self, QRectF* r, int xround, int yround);
void QPainter_drawRoundRect_int_int_int_int_int(QPainter* self, int x, int y, int w, int h, int param5);
void QPainter_drawRoundRect_int_int_int_int_int_int(QPainter* self, int x, int y, int w, int h, int param5, int param6);
void QPainter_drawRoundRect_QRect_int(QPainter* self, QRect* r, int xround);
void QPainter_drawRoundRect_QRect_int_int(QPainter* self, QRect* r, int xround, int yround);
void QPainter_drawTiledPixmap_QRectF_QPixmap_QPointF(QPainter* self, QRectF* rect, QPixmap* pm, QPointF* offset);
void QPainter_drawTiledPixmap_int_int_int_int_QPixmap_int(QPainter* self, int x, int y, int w, int h, QPixmap* param5, int sx);
void QPainter_drawTiledPixmap_int_int_int_int_QPixmap_int_int(QPainter* self, int x, int y, int w, int h, QPixmap* param5, int sx, int sy);
void QPainter_drawTiledPixmap_QRect_QPixmap_QPoint(QPainter* self, QRect* param1, QPixmap* param2, QPoint* param3);
void QPainter_drawPixmapFragments_fragments_fragmentCount_pixmap_hints(QPainter* self, QPainter__PixmapFragment* fragments, int fragmentCount, QPixmap* pixmap, int hints);
void QPainter_drawImage_QRectF_QImage_QRectF_Qt_ImageConversionFlags(QPainter* self, QRectF* targetRect, QImage* image, QRectF* sourceRect, int flags);
void QPainter_drawImage_QRect_QImage_QRect_Qt_ImageConversionFlags(QPainter* self, QRect* targetRect, QImage* image, QRect* sourceRect, int flags);
void QPainter_drawImage_QPointF_QImage_QRectF_Qt_ImageConversionFlags(QPainter* self, QPointF* p, QImage* image, QRectF* sr, int flags);
void QPainter_drawImage_QPoint_QImage_QRect_Qt_ImageConversionFlags(QPainter* self, QPoint* p, QImage* image, QRect* sr, int flags);
void QPainter_drawImage_int_int_QImage_int(QPainter* self, int x, int y, QImage* image, int sx);
void QPainter_drawImage_int_int_QImage_int_int(QPainter* self, int x, int y, QImage* image, int sx, int sy);
void QPainter_drawImage_int_int_QImage_int_int_int(QPainter* self, int x, int y, QImage* image, int sx, int sy, int sw);
void QPainter_drawImage_int_int_QImage_int_int_int_int(QPainter* self, int x, int y, QImage* image, int sx, int sy, int sw, int sh);
void QPainter_drawImage_int_int_QImage_int_int_int_int_Qt_ImageConversionFlags(QPainter* self, int x, int y, QImage* image, int sx, int sy, int sw, int sh, int flags);
void QPainter_drawText_QRectF_int_QString_QRectF(QPainter* self, QRectF* r, int flags, struct seaqt_string text, QRectF* br);
void QPainter_drawText_QRect_int_QString_QRect(QPainter* self, QRect* r, int flags, struct seaqt_string text, QRect* br);
void QPainter_drawText_int_int_int_int_int_QString_QRect(QPainter* self, int x, int y, int w, int h, int flags, struct seaqt_string text, QRect* br);
void QPainter_drawText_QRectF_QString_QTextOption(QPainter* self, QRectF* r, struct seaqt_string text, QTextOption* o);
QRectF* QPainter_boundingRect_QRectF_QString_QTextOption(QPainter* self, QRectF* rect, struct seaqt_string text, QTextOption* o);
void QPainter_setRenderHint_hint_on(QPainter* self, int hint, bool on);
void QPainter_setRenderHints_hints_on(QPainter* self, int hints, bool on);
void QPainter_setRedirected_device_replacement_offset(QPaintDevice* device, QPaintDevice* replacement, QPoint* offset);
QPaintDevice* QPainter_redirected_device_offset(QPaintDevice* device, QPoint* offset);

const QMetaObject* QPainter_staticMetaObject();
void QPainter_delete(QPainter* self);

double QPainter__PixmapFragment_x(const QPainter__PixmapFragment* self);
void QPainter__PixmapFragment_setX(QPainter__PixmapFragment* self, double x);
double QPainter__PixmapFragment_y(const QPainter__PixmapFragment* self);
void QPainter__PixmapFragment_setY(QPainter__PixmapFragment* self, double y);
double QPainter__PixmapFragment_sourceLeft(const QPainter__PixmapFragment* self);
void QPainter__PixmapFragment_setSourceLeft(QPainter__PixmapFragment* self, double sourceLeft);
double QPainter__PixmapFragment_sourceTop(const QPainter__PixmapFragment* self);
void QPainter__PixmapFragment_setSourceTop(QPainter__PixmapFragment* self, double sourceTop);
double QPainter__PixmapFragment_width(const QPainter__PixmapFragment* self);
void QPainter__PixmapFragment_setWidth(QPainter__PixmapFragment* self, double width);
double QPainter__PixmapFragment_height(const QPainter__PixmapFragment* self);
void QPainter__PixmapFragment_setHeight(QPainter__PixmapFragment* self, double height);
double QPainter__PixmapFragment_scaleX(const QPainter__PixmapFragment* self);
void QPainter__PixmapFragment_setScaleX(QPainter__PixmapFragment* self, double scaleX);
double QPainter__PixmapFragment_scaleY(const QPainter__PixmapFragment* self);
void QPainter__PixmapFragment_setScaleY(QPainter__PixmapFragment* self, double scaleY);
double QPainter__PixmapFragment_rotation(const QPainter__PixmapFragment* self);
void QPainter__PixmapFragment_setRotation(QPainter__PixmapFragment* self, double rotation);
double QPainter__PixmapFragment_opacity(const QPainter__PixmapFragment* self);
void QPainter__PixmapFragment_setOpacity(QPainter__PixmapFragment* self, double opacity);
QPainter__PixmapFragment* QPainter__PixmapFragment_create_pos_sourceRect(QPointF* pos, QRectF* sourceRect);
QPainter__PixmapFragment* QPainter__PixmapFragment_create_pos_sourceRect_scaleX(QPointF* pos, QRectF* sourceRect, double scaleX);
QPainter__PixmapFragment* QPainter__PixmapFragment_create_pos_sourceRect_scaleX_scaleY(QPointF* pos, QRectF* sourceRect, double scaleX, double scaleY);
QPainter__PixmapFragment* QPainter__PixmapFragment_create_pos_sourceRect_scaleX_scaleY_rotation(QPointF* pos, QRectF* sourceRect, double scaleX, double scaleY, double rotation);
QPainter__PixmapFragment* QPainter__PixmapFragment_create_pos_sourceRect_scaleX_scaleY_rotation_opacity(QPointF* pos, QRectF* sourceRect, double scaleX, double scaleY, double rotation, double opacity);

void QPainter__PixmapFragment_delete(QPainter__PixmapFragment* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
